### ISSUE TITLE
Visibility of the new Package property page need to controlled via a capability

### ISSUE THREAD

**Issue by RaulPerez1** [dotnet/roslyn-project-system#1001]
Currently the page will always be visible regardless of the project type. It should be controlled via a capability (PackagePage was suggested on a different thread).

src\microsoft.visualstudio.projectsystem.csharp.vs\projectsystem\vs\properties\csharpprojectdesignerpageprovider.cs

        public Task<IReadOnlyCollection<IPageMetadata>> GetPagesAsync()
        {
            return Task.FromResult<IReadOnlyCollection<IPageMetadata>>(
                new IPageMetadata[] {
                    CSharpProjectDesignerPage.Application,
                    CSharpProjectDesignerPage.Build,
                    CSharpProjectDesignerPage.BuildEvents,
                    CSharpProjectDesignerPage.Package,
                    CSharpProjectDesignerPage.Debug,
                    CSharpProjectDesignerPage.ReferencePaths,
                    CSharpProjectDesignerPage.Signing,
            });
        }

**Comment by srivatsn** [comment]
Currently only netcore projects will show this page since the project system is only for NetCore. This bug is needed when we bring up desktop proejcts.

**Comment by mavasani** [comment]
Already have a PR out for this: https://github.com/dotnet/roslyn-project-system/pull/1023

**Comment by mavasani** [comment]
Fixed now.
