### ISSUE TITLE
Cannot modify item property after editing .csproj file, closing, and re-opening project

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/roslyn-project-system#1015]
- File \ New Project \ Console App (.NET Core)
- Right click on project, select "Edit .csproj"
- Close project, then re-open it (in the same instance of Visual Studio)
- Select Program.cs in solution explorer
- In Properties window, change "Copy to Output Directory" to "Copy if newer"

EXPECTED: Property change is applied
ACTUAL: Property value is not valid error

![image](https://cloud.githubusercontent.com/assets/145043/21377542/2ae7e0f0-c6f4-11e6-9733-53b07005cd0f.png)

Clicking on details shows:

> An error has occurred while saving the edited properties listed below:
	Copy to Output Directory
One or more values are invalid. Could not find a part of the path 'C:\Users\daplaist\AppData\Local\Temp\5qetm5lf.0xp\ConsoleApp13.csproj'.

@333fred Perhaps this is caused because the path to the temp file changes when the project is reloaded, but the old path is still cached somewhere in VS or MSBuild.  If so, this might get fixed as part of switching to an in-memory editor.

**Comment by 333fred** [comment]
This is caused by the fact that the csproj editor is still open, but the project closed so it removed the temp file. This will be going away in a pull that I'll be submitting shortly that will close the csproj editor when the project is unloaded.
