### ISSUE TITLE
[loc][Query][dotNet] Possible error in the English source

### ISSUE THREAD

**Issue by mkyjakova** [dotnet/roslyn-project-system#1016]
Hi, we have a question from our translator. Can you help please? Thanks!

Source:
&Bro&wse...

File Name:
DebugPropPage.ko.xlf

Query:
It seems that one of the ampersands is redundant and should be removed. Can you please confirm? Thanks!

**Comment by srivatsn** [comment]
Sounds like an error to me - the second & should be there since there's a different Browse button on the same with ampersand on the 'B'.
