### ISSUE TITLE
Build Events in project lose line separators making them very hard to read and maintain 

### ISSUE THREAD

**Issue by srivatsn** [dotnet/roslyn-project-system#1031]
Using Dev15 d15rel 15.0.25831.1
File->New->Project->C# WpfApp
Project->Properties->BuildEvents->Edit Post Build event:
paste in these 2 lines 
@echo hi
@echo there
They look fine.
Examine the .CSPROJ with a binary editor 
Confirm that there are Cr/Lf between the lines
Close the solution,
Reopen the solution
Project->Properties->BuildEvents
Observe that the 2 lines are together now with no cr/lf between them 
![image](https://cloud.githubusercontent.com/assets/20570/21439479/2a58bcfe-c843-11e6-9d69-c1e12e1c6b7e.png)

**Comment by davkean** [comment]
Is this the page or the project system? Does the same thing happen for .NET Core?

**Comment by srivatsn** [comment]
Don't know. This was reported through VSFeedback multiple times - [Link1](https://developercommunity.visualstudio.com/content/problem/2615/vs-2017-rc1-project-properties-box-prepost-build-e.html) [Link2](https://developercommunity.visualstudio.com/content/problem/2588/problem-during-opening-project-with-build-events-v.html) [Link3](https://developercommunity.visualstudio.com/content/problem/4730/csproj-postpre-build-event-command-lines-editor-do.html)

**Comment by srivatsn** [comment]
[One more VSFeedback report](https://developercommunity.visualstudio.com/content/problem/6649/events-assembly-when-you-save-a-project-closing-op.html)

**Comment by sujaysarma** [comment]
Why are we tracking this bug under Roslyn? This is a .csproj bug (old project system). Also, as of Build VisualStudio/public.d15rel/15.0.26009.0 this is no longer an issue. It is working correctly now.

**Comment by davkean** [comment]
Because the page lives in this repo.

**Comment by srivatsn** [comment]
I can't repro this in RC3 and as @sujaysarma mentions that this is fixed for him as well.
