### ISSUE TITLE
In item properties, "<reset to default>" does not appear in dropdown until item has been deselected and reselected

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/roslyn-project-system#1039]
- Create a new Console App (.NET Core)
- Select Program.cs in Solution Explorer
- In Properties window, change "Copy to Output Directory" from "Do not copy" to "Copy if newer"
- Open dropdown for "Copy to Output Directory" properties

EXPECTED: Dropdown includes "<reset to default>"
ACTUAL: Dropdown does not include "<reset to default>", until you deselect and reselect the item in Solution Explorer

**Comment by mavasani** [comment]
I believe this is due to the same CPS issue mentioned here: https://github.com/dotnet/roslyn-project-system/issues/1040#issuecomment-270220877
