### ISSUE TITLE
In item properties, property value for "Copy to Output Directory" should be displayed after selecting "<reset to default>"

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/roslyn-project-system#1040]
- Create a new Console App (.NET Core)
- Select Program.cs in Solution Explorer
- In Properties window, change "Copy to Output Directory" from "Do not copy" to "Copy if newer"
- Deselect and reselect Program.cs in Solution Explorer (workaround for #1039)
- Open dropdown for "Copy to Output Directory", and select "<reset to default>"

EXPECTED: Property value shows "Do not copy" unbolded, to indicate that it is the default value
ACTUAL: Property value shows "<Reset to default>" bolded, until item is deselected and selected in Solution Explorer

This may be the same bug as #1039, and may be in CPS as opposed to the Roslyn Project System.

**Comment by jviau** [comment]
@dsplaisted this is a known issue in CPS, we do not refresh the properties window until the item is deselected then re-selected. We would like to fix this, but it was moved out of RTM. It is on our backlog though and will be revisited later.
