### ISSUE TITLE
Debug property page font size regressed

### ISSUE THREAD

**Issue by basoundr** [dotnet/roslyn-project-system#1067]
![image](https://cloud.githubusercontent.com/assets/10550513/21628241/c9d3b462-d1d2-11e6-9b4f-30c5cef8d599.png)

d15prerel 26102.3

**Comment by davkean** [comment]
This is just: https://github.com/dotnet/roslyn-project-system/issues/646.

**Comment by davkean** [comment]
You can tell it's a dup - look at the size of your tabs and their font, that's not the default DPI/font size.
