### ISSUE TITLE
Reference Paths properties page relevance to .NET Core projects

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn-project-system#1071]
![image](https://cloud.githubusercontent.com/assets/12449387/21653915/4047f85c-d268-11e6-9cf5-a5a296ac6d19.png)

o	What does this do? Does it make sense in a .NET Core/.NET Standard project to have it?

Reported by @DamianEdwards

**Comment by davkean** [comment]
Yeah, it's not that relevant, it's basically used to supplement the directories where we look for "Bar" in `<Reference Include="Bar"/>`. 

I'd argue that we should probably remove this page in general for all projects - it burns a set of paths in the .user file - so a team member doesn't see it, or a 'git clean' and you've lost the settings.

**Comment by RaulPerez1** [comment]
Removing this for RTM, opened #1397 to track improvements here.

**Comment by RaulPerez1** [comment]
Fixed via #1402
