### ISSUE TITLE
Richer support for manipulating NuGet dependencies in solution explorer

### ISSUE THREAD

**Issue by rrelyea** [dotnet/roslyn-project-system#1072]
internal feedback item: 732977 (resolved dupe to this new item)
From Daniel Roth, asp.net core team - When you right click on the NuGet node under Dependencies in a .NET Core project you don't get the option to Manage NuGet Packages. This is inconsistent with the experience for Bower packages - you can right click on Bower and manage your Bower packages. The work around is to right click on the Dependencies node.

**Comment by abpiskunov** [comment]
@srivatsn i assign it to myself, however not sure what milestone it will be go to.

**Comment by srivatsn** [comment]
Dupe o f #914
