### ISSUE TITLE
Fails to add a new resource file , Works fine if the file already exists

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn-project-system#1078]
![image](https://cloud.githubusercontent.com/assets/12449387/21664581/4846deb8-d29c-11e6-9689-57a3d97aa54a.png)

**Comment by davkean** [comment]
Yeah, this will be fixed by https://github.com/dotnet/roslyn-project-system/pull/1060.

**Comment by srivatsn** [comment]
Should be fixed by #1060
