### ISSUE TITLE
Output type for ASP.NET Core web application shows up as 'Windows application' in the property page

### ISSUE THREAD

**Issue by balachir** [dotnet/roslyn-project-system#1087]
Dev15 RC.3 build d15prerel.26105.02

1. New ASP.NET Core Web Application (.NET Core) > Empty 
2. View Property Pages

ACTUAL
Output type shows "Windows Application"

![image](https://cloud.githubusercontent.com/assets/8246794/21697603/03888978-d348-11e6-9733-71024f97ce68.png)

EXPECTED
Output type shows "Console Application"

**Comment by davkean** [comment]
@RaulPerez1 You marked this as fixed over here: https://github.com/dotnet/roslyn-project-system/issues/813, but if I'm debugging I still run into the same thing.

**Comment by srivatsn** [comment]
Are you using the updated rules? I think he added a rule in his fix

**Comment by davkean** [comment]
This still looks broken in 26102.0 D15PreRel.

**Comment by srivatsn** [comment]
The change just got inserted today

**Comment by davkean** [comment]
Installed 26107.1 and confirmed this has been resolved.
