### ISSUE TITLE
Project files should include the xml prolog by default

### ISSUE THREAD

**Issue by tannergooding** [dotnet/roslyn-project-system#1093]
While the XML prolog (`<?xml version="1.0" encoding="utf-8"?>`) is optional (according to the xml spec), it should be included by default in our project files.

Almost all external editors with syntax highlighting will recognize the XML prolog and do the appropriate thing. However, very few will recognize the various extensions (*.csproj, *.vbproj, etc) out of the box.

We currently add the XML prolog to our project templates in the legacy project system and should continue doing so here.

**Comment by davkean** [comment]
To simplify the project file format, it was deliberate that the prolog was removed. We're not going to add it back without significant feedback. Some editors, such as Sublime, make it very easy to associate an extension with a format - wondering if we put up with that.

**Comment by tannergooding** [comment]
I feel like everything else removed, was actually just simplification, and the overall file is treated the same (in practically all editors) regardless of whether the information was there or removed.

However, the removal of the prolog in particular means that the out of box editing experience in practically all other editors has now regressed.

The workaround is to just associate *.csproj and *.vbproj files to be treated as xml, which is possible and generally fairly simple in most editors. However, I feel like this is something users should not need to do, and it should continue to just work.

**Comment by srivatsn** [comment]
We made this decision to prioritize editing. We'll reconsider this if there's more feedback about adding needing the header.
