### ISSUE TITLE
Enable Access Modifier on .resx files

### ISSUE THREAD

**Issue by sayedihashimi** [dotnet/roslyn-project-system#1097]
In a core project if I add a .resx file I cannot change the Access Modifier. See image below.
I was hoping that this would come "for free" when we moved to the roslyn project system, but it looks like there may be some pending work here. Is this on the radar?

<img width="308" alt="access-mod" src="https://cloud.githubusercontent.com/assets/1283154/21731769/e5327574-d40a-11e6-8240-27baf5b9e9d3.png">

Note: related issue https://github.com/aspnet/Tooling/issues/339

**Comment by srivatsn** [comment]
@333fred didn't you fix this? Or does this require @davkean's DTAR changes?

**Comment by 333fred** [comment]
It appears to be working for me, tested on both the latest public bits and d15prerel/26105.09. I tested using asp.net empty web applications with both 1.0.3 and 1.1. @sayedihashimi, what project type are you using?

**Comment by sayedihashimi** [comment]
I just tested on another machine and it's working fine for me too. I must have had a bad build on my other machine. Closing this now. Sorry for the bad report.
