### ISSUE TITLE
Visual Studio deadlocks if you attempt to close a project before NuGet restore has finished

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn-project-system#1104]
26107.1.d15prel

1. Create new Empty Web Application
2. Close Solution and VS
3. Open Solution
4. File -> Close Solution *before* NuGet restore has started/finish

--Deadlock--

If I did this quickly, was I able to deadlock VS 100% of the time.

Dump: [internalMLshare]\public\davkean\project-system\1104

**Comment by davkean** [comment]
tag @natidea @alpaix @rrelyea - who owns registering the async task with CPS, it looks like the deadlock is when CPS is draining the async tasks on close.

**Comment by srivatsn** [comment]
Tracking using https://github.com/NuGet/Home/issues/4257
