### ISSUE TITLE
Building VSSDK projects with the new project system

### ISSUE THREAD

**Issue by twsouthwick** [dotnet/roslyn-project-system#1121]
I have a project with a few libraries that is currently building with the new project system and we want to add a VS extension to it. However, it doesn't seem to run any of the SDK targets. I've created a repro here: https://github.com/twsouthwick/vs17sdk. It builds fine, but no package is created. Is there a way to support this or is it not expected to work at the moment?

**Comment by davkean** [comment]
@mavasani Were you running into the same thing in the SDK repo?

**Comment by srivatsn** [comment]
I don't see why it wouldn't work. I've converted some VSIX projects in this repo to use the SDK and it seems to work fine. Can you do a msbuild /pp on this project and check if the VSSDK targets are getting pulled in?

**Comment by twsouthwick** [comment]
@Srivatsn Can you point me at one? When I run the `msbuild /pp` command it looks like the targets are being included. The issue seems to be in the `CreateMenuPkgDef` target.

```
4>Target CreateMenuPkgDef:
4>  Skipping target "CreateMenuPkgDef" because it has no outputs.
```

**Comment by srivatsn** [comment]
https://github.com/srivatsn/roslyn-project-system/tree/dogfood is the branch. The VSIX projects (ProjectsystemSetup for eg) include some repo-specific targets and I added the SDK attribute there.

**Comment by twsouthwick** [comment]
Looks like those projects are still including some items that are not required in the new version, such as the namespace, ToolsVersion="12.0", project guids, etc. Will that make a difference?

**Comment by davkean** [comment]
This issue was moved to dotnet/sdk#1008
