### ISSUE TITLE
With NetCore workload, AspNetCoreWebApp_NoAuth_1 : open with VS, prompts to install Web workload

### ISSUE THREAD

**Issue by balachir** [dotnet/roslyn-project-system#1123]
## Steps to reproduce
Using VS 2017 RC.3 (Build d15rel 26109.02)
Install .NET Core workload
git clone https://github.com/balaTest/ProjectKTestProjects
Open solution under Dev14_K101/Tooling202/AspNetCoreWebApp_NoAuth_1

## Actual behavior
Prompts to install web workload

![image](https://cloud.githubusercontent.com/assets/8246794/21829118/2d6b84a2-d749-11e6-9d6a-b4de9fec5666.png)

## Expected behavior
Project should open and migrate without needing the web workload

**Comment by natidea** [comment]
@basoundr ported to [367212](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/367212). Please review and fill out the "Ask Mode" tab and send to Matt to approve

**Comment by basoundr** [comment]
Fixed in the [VS Side](https://devdiv.visualstudio.com/DevDiv/_workitems?id=367212&_a=edit)
