### ISSUE TITLE
Open Dev14 solution with xproj AspNetCoreWebApp_NoAuth_1 using VS, global.json shows up twice in Solution Explorer

### ISSUE THREAD

**Issue by balachir** [dotnet/roslyn-project-system#1124]
## Steps to reproduce
Using VS 2017 RC.3 (Build d15rel 26109.02) with Web workload
git clone https://github.com/balaTest/ProjectKTestProjects
Open solution under Dev14_K101/Tooling202/AspNetCoreWebApp_NoAuth_1

## Actual behavior
global.json shows up twice in Solution Explorer

![image](https://cloud.githubusercontent.com/assets/8246794/21829235/d4bf5d3c-d749-11e6-9bc9-43b0785f59f1.png)

## Expected behavior
global.json shows up only once in Solution Explorer

**Comment by srivatsn** [comment]
And the sln file doesn't list it twice? We don't add the global.json at all. Tagging @mlorbetske

**Comment by balachir** [comment]
I just checked the sln file and there does seem to be 2 entries there

```
Project("{2150E333-8FDC-42A3-9474-1A3956D46DE8}") = "Solution Items", "Solution Items", "{23CBDAA2-0C75-456E-91D4-EE16A435FB82}"
	ProjectSection(SolutionItems) = preProject
		..\AspNetCoreWeb_IndAuth_WithAI_1\global.json = ..\AspNetCoreWeb_IndAuth_WithAI_1\global.json
		global.json = global.json
	EndProjectSection
EndProject
```

**Comment by srivatsn** [comment]
The global.json is added by the web tooling and is planned to be removed.
