### ISSUE TITLE
Hide items with 'Visible=false' metadata

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/roslyn-project-system#1126]
In VS 2015, items marked with metadata 'Visible' set to false did not appear in the solution explorer.
cref https://msdn.microsoft.com/en-us/library/ms171468.aspx

In VS2017, these items appear.

Repo:
1. Add a file 'somehiddenfile.txt' to a project folder.
2.  Add to csproj
  ```xml
  <Project ToolsVersion="15.0" Sdk="Microsoft.NET.Sdk">
    <ItemGroup>
       <None Include="somehiddenfile.txt" Visible="false" />
    </ItemGroup>
  </Project>
  ```

![image](https://cloud.githubusercontent.com/assets/2696087/21830014/bd6bbeb4-d74e-11e6-943f-6f3464004dc1.png)

Using 15.0.26109.1

**Comment by davkean** [comment]
Hmm, `<Visible>false</Visible>` is respected - I think what's probably happening here is that the implicit globs are re-adding the file with different metadata. @dsplaisted

**Comment by natemcmaster** [comment]
Yeah, that's probably what is happening. It seems to go away when opting-out of default items.
```xml
<EnableDefaultNoneItems>false</EnableDefaultNoneItems>
```

**Comment by rainersigwald** [comment]
You could keep the default items if you change to

```xml
     <None Update="somehiddenfile.txt" Visible="false" />
```

Where `Update` means "change metadata on existing item" rather than "add a new item to the list".

**Comment by srivatsn** [comment]
This should now be fixed with https://github.com/dotnet/sdk/pull/624. Please reopen if you are still seeing this.
