### ISSUE TITLE
Certain capabilities should be a fixed set of capabilities

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn-project-system#1127]
We have a set of capabilities that if "dynamically" changed by adding or removing fundamentally breaks CPS.

Anything that affects the project tree via IProjectTreeSettingsProvider, is COM aggregation cannot be a dynamic capability (ie cannot come from targets):

HandlesOwnReload
AppDesigner
EditAndContinue

**Comment by davkean** [comment]
This is the cause of the second issue in https://github.com/dotnet/roslyn-project-system/issues/1103.

**Comment by 333fred** [comment]
I'm going to add OpenProjectFile to this list. It's really a capability of the project system, not of the project type, and to move to the in-memory editor we'll need to use COM aggregation anyway.

**Comment by 333fred** [comment]
Fixed in #1141.

**Comment by davkean** [comment]
I think we need another bug to track removing the default capabilities provider - that currently will cause us to load for all projects.

**Comment by 333fred** [comment]
@davkean that exists, https://github.com/dotnet/roslyn-project-system/issues/559
