### ISSUE TITLE
Add PackageVersion and Version properties to NuGet restore rules

### ISSUE THREAD

**Issue by alpaix** [dotnet/roslyn-project-system#1132]
Roslyn project system should track changes of `PackageVersion`/`Version` properties and pass their respective values to the Nominate API.

This is needed to determine a package version for P2P dependencies.

Correlates to NuGet/Home#3901.

**Comment by rrelyea** [comment]
We're targeting the nuget side of the fix for RTM, but soon.

**Comment by alpaix** [comment]
@natidea What's the ETA for this issue?

**Comment by natidea** [comment]
I'll take a look at this today.

**Comment by alpaix** [comment]
The package version family of properties shouldn't be evaluated per tfm. Therefore the nominate API in its current shape won't fit to accommodate them. 

I have two proposals then.
First, introduce `IVsPackageVersionInfo` defined as following:
```c#
    public interface IVsPackageVersionInfo
    {
        string VersionPrefix { get; }
        string VersionSuffix { get; }
        string Version { get; }
        string PackageVersion { get; }
    }
```

-or-

Add a property bag in `IVsProjectRestoreInfo`.

**Comment by natidea** [comment]
We will add a property bag to `IVsProjectRestoreInfo` to capture these and other future "Project Properties"
