### ISSUE TITLE
Output path and various other build properties are empty 

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn-project-system#1135]
1. File -> New -> C# .NET Core app
2. Right-click on project, choose Properties
3. Choose Build tab

- Output path is empty
- Checking XML documentation file, gives the wrong path
- Conditional compilation symbols is empty - despite us automatically defining some.

**Comment by srivatsn** [comment]
Caused by https://github.com/Microsoft/msbuild/issues/1570

**Comment by srivatsn** [comment]
This issue still repros after the fix for https://github.com/Microsoft/msbuild/issues/1570
