### ISSUE TITLE
CustomTool rule not available on .cs files

### ISSUE THREAD

**Issue by madskristensen** [dotnet/roslyn-project-system#1136]
Before the CPS based project system, a _CustomTool_ rule property was available on all project items in the project. In the new it seems only .resx files has the support.

My use case for it is to use a _SingleFileGenerator_ to generate a TypeScript definition file (.d.ts) based on a C# model for use in ASP.NET projects. Without _CustomTools_ I don't get file nesting and SCC support if I did the generation without _CustomTool_.

From looking at the source code, it seems like the fix is isolated to [this XAML file](https://github.com/dotnet/roslyn-project-system/blob/ef16880b0329cf833668657e86397e0a57e8b7fb/src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/CSharp.BrowseObject.xaml) which is missing the _CustomTool_ rule..

**Comment by sayedihashimi** [comment]
+1

**Comment by iwhp** [comment]
+1

**Comment by basoundr** [comment]
Fixed by #1289
