### ISSUE TITLE
Switching debug profiles causes a build failure with no further information

### ISSUE THREAD

**Issue by BillHiebert** [dotnet/roslyn-project-system#1144]
Latest D15Rel build.
1. New .net core console application
2. r-click on project node and open properties
3. navigate to the Debug tab and create a new profile
4. Change the launch from executable to Project
5. Save
6. Build - builds fine
7. In the debug dropdown change profiles to the new one
8. Build - builds fine
9. Switch the profile to the original one
10. Build - It fails with no further information.
1>------ Build started: Project: ConsoleApp4, Configuration: Debug Any CPU ------
========== Build: 0 succeeded or up-to-date, **1 failed,** 0 skipped ==========

The diagnostic output shows nothing of interest from msbuild.

[BuildFailureOutput.txt](https://github.com/dotnet/roslyn-project-system/files/700033/BuildFailureOutput.txt)

**Comment by srivatsn** [comment]
Likely the same as https://github.com/Microsoft/msbuild/issues/1526

**Comment by srivatsn** [comment]
@rainersigwald - does this look similar?

**Comment by rainersigwald** [comment]
Yes it does. Trying with my fix from https://github.com/Microsoft/msbuild/pull/1547.

**Comment by rainersigwald** [comment]
I can walk through all of those steps using that fix successfully.

**Comment by srivatsn** [comment]
Thanks for verifying @rainersigwald - closing as a dupe of https://github.com/Microsoft/msbuild/issues/1526
