### ISSUE TITLE
Migrated project fails to debug

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn-project-system#1146]
**Repro Steps**

- Copy \\mlangfs1\public\Jinuj\TestCases\MigrationIssue1\EFGetStarted.AspNetCore.NewDb
- Double click the .sln file
- Select for migration 
- Once migrated , build 
I get build warning 

![image](https://cloud.githubusercontent.com/assets/12449387/21866776/63357752-d800-11e6-9149-c337c6bf8273.png)

- Once Build, click debug from the tool menu (keep IIS Express selected) 

**Expected**
Debugs successfully 

**Actual**
image
![image](https://cloud.githubusercontent.com/assets/12449387/21866834/9c3d3fd0-d800-11e6-9e8c-c75f9a9cb392.png)

Note:
 I have "Cross Platform and Desktop Workload Installed.
o VS : VisualStudio/15.0.0-RC.3+26110.0.d15rel
o CLI : 1.0.0-preview5-004460

**Comment by srivatsn** [comment]
Is this still reproing?

**Comment by jinujoseph** [comment]
Verified it's working on 26118.0.d15rel
