### ISSUE TITLE
Build Properties Page broken with .Net Core Project 

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn-project-system#1147]
**Repro Steps**
- Create console application 
- Right click properties 
- Click "Build"

**Expected** 
![image](https://cloud.githubusercontent.com/assets/12449387/21868930/f36d113c-d809-11e6-9d40-5fc2f8fd3851.png)

**Actual**
![image](https://cloud.githubusercontent.com/assets/12449387/21868944/ffa11f2a-d809-11e6-8b3f-4cc3d45ac16f.png)

Note : 
This works fine in VisualStudio/15.0.0-RC.3+26110.0.d15rel 
Fails in VisualStudio/15.0.0-**RC.3+26110.1.d15rel**

Looks like a regression

**Comment by jinujoseph** [comment]
@RaulPerez1 any thing changed here , remember you fixing this.

**Comment by rainersigwald** [comment]
This is because of https://github.com/Microsoft/msbuild/issues/1570
