### ISSUE TITLE
Project System: Project references should have a different icon to binary references

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn-project-system#115]
It's hard to tell in the References tree, which is a project reference vs a binary reference:

![image](https://cloud.githubusercontent.com/assets/1103906/14004581/64b2ad54-f118-11e5-9989-b4a58f5882fa.png)

We should choose a better icon, similar to what we did with NuGet, to better differentiate. 

_Copied from original issue: dotnet/roslyn#10039_

**Comment by davkean** [comment]
_From @ErikSchierboom on March 24, 2016 8:36_

Great suggestion!

**Comment by svick** [comment]
Would it make sense to also sort project references separately, i.e. first list all project references and then list all binary references?

**Comment by srivatsn** [comment]
This is now done with the new dependencies node.

**Comment by ErikSchierboom** [comment]
🎉
