### ISSUE TITLE
Debug Launch option "IIS Express" disappears once switched to any other option.

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn-project-system#1151]
- Create a Web Application (.Net Core )
- Right click properties 
- Switch to Debug option 
- Change the "launch" setting from "IIS Express" to "project"
- Save  and close 
- Reopen the debug properties, now you don't have "IIS Express" option.

![image](https://cloud.githubusercontent.com/assets/12449387/21905220/891e9bfe-d8bb-11e6-8279-8dd0de0063b2.png)

**Build Info** 
VS : VisualStudio/15.0.0-RC.3+26111.0.d15rel

**Comment by jinujoseph** [comment]
cc / @BillHiebert

**Comment by BillHiebert** [comment]
This is fixed with the web tooling extensions to the dialog added to RTW.
