### ISSUE TITLE
Saving the edited project properties page brings "Output-PackageManager.txt"

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn-project-system#1165]
- Create a new console application
- Right click properties 
- Make an edit 
- Ctrl+S or save from the tool menu 

**Expected**
The file is saved 

**Actual**
![image](https://cloud.githubusercontent.com/assets/12449387/21945424/0e3bbbbc-d990-11e6-96cd-5b4b95af67b9.png)

****Build Info**
26112.1.d15rel

**Comment by srivatsn** [comment]
Are you sure the focus wasn't on the output window when you hit ctrl+s?

**Comment by srivatsn** [comment]
I think you likely changed the TF which kicks off a restore which changes the focus to the output window

**Comment by jinujoseph** [comment]
you might be right , retesting

**Comment by jinujoseph** [comment]
thatz right , closing this phew
