### ISSUE TITLE
Edit open project file converts to UTF-16

### ISSUE THREAD

**Issue by nguerrera** [dotnet/roslyn-project-system#1168]
Repro steps:

* File -> New Project -> Console App (.NET Core)
* Right click, Edit ConsoleApp1.csproj

Make a change, save. The file is encoded in UTF-16. UTF-16 files are evil. Silently changing the encoding of user data is even more evil.

**Comment by nguerrera** [comment]
@333fred

**Comment by nguerrera** [comment]
And if I try to change it to UTF8 in the xml header (which it added btw), it switches back to UTF-16 every time I hit save. :trollface:

**Comment by nguerrera** [comment]
Also, if I make changes, git diff just says "binary files differ"

This is pretty bad.

**Comment by davkean** [comment]
The encoding should match exactly what file opened with - I was pretty sure there was specially handling for this. Can we make sure that we leave the bom if one exists, or don't remove it if it doesn't.

**Comment by davkean** [comment]
What I mean, is that that's the behavior we should have, not that thats' the current behavior.

**Comment by nguerrera** [comment]
Agree. I was a bit harsh saying we should use UTF-8, but really everyone should. UTF-16 files are for people who like being broken by just about everything.

**Comment by nguerrera** [comment]
Our templates are valid UTF-8 and have no BOM or xml declaration. This is valid and XML spec says to detect the encoding as UTf-8 in this case. We should leave it that way but I'd tolerate adding BOM and explicit xml declaration with encoding=UTF-8.

It turns out that even if I add a BOM and/or xml declaration with encoding=utf-8, it still gets converted to UTF-16!

**Comment by davkean** [comment]
Do we add the XML declaration?

**Comment by nguerrera** [comment]
We (edit project file) do.

**Comment by davkean** [comment]
Okay, that's not supposed to happen, that's a bug.

**Comment by nguerrera** [comment]
Given that we're breaking `git diff`, I'd like us to consider getting a fix for RC3. I can live with adding the declaration until RTW if we at least preserve the original encoding.

**Comment by nguerrera** [comment]
Just had a thought: maybe this is only happening because my OS and VS are French? I'm surprised nobody else spotted this yet...

**Comment by 333fred** [comment]
The only time we write to the file system for this, we specifically write with the existing project file encoding.

* Overwriting the project file: https://github.com/dotnet/roslyn-project-system/blob/2fe39a1106da2bfe346a2166b501dadd70d86f8e/src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Editor/MsBuildXmlAccessor.cs#L41-L42
* Initializing the temp file: https://github.com/dotnet/roslyn-project-system/blob/2fe39a1106da2bfe346a2166b501dadd70d86f8e/src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Editor/TempFileTextBufferManager.cs#L76
* Updating the temp file: https://github.com/dotnet/roslyn-project-system/blob/2fe39a1106da2bfe346a2166b501dadd70d86f8e/src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Editor/TempFileTextBufferManager.cs#L105

In all cases, we're specifying the encoding received from `_unconfiguredProject.GetFileEncodingAsync()`, which is the same behavior that CPS has when saving the project file. I've confirmed the following:
1. When we write out both the temp file and overwrite the main file, we set the file encoding to be UTF-8. 
2. However, it appears that the XML returned from `ProjectLockReleaser.GetProjectXmlAsync()` has the UTF-16 header `<?xml version="1.0" encoding="utf-16"?>`.
3. After we save the file once, future calls to `GetFileEncodingAsync` return UTF-16, so I'd guess that the MSBuild parsing sees the header and decides the file should be in UTF-16 format, even though it's saved as UTF-8.

@jviau and @rainersigwald, does this look like a plausible explanation? We really need to have a correct way of getting the actual XML that will be written to disk if the user saves the project. This is causing a number of bugs, mostly around whitespace. Will this be resolved by @jviau's CPS change to use the new reloading mechanism, or does this require more work?

**Comment by AArnott** [comment]
I'm seeing it too on d15rel 26114.00. It makes git treat it as a binary file. ☹️

**Comment by 333fred** [comment]
I've worked around this as part of #1197. We need to revert that workaround when the appropriate MSBuild/CPS fix is made.

**Comment by 333fred** [comment]
I opened https://github.com/Microsoft/msbuild/issues/1573 for the return having a UTF-16 header.

**Comment by jviau** [comment]
I did some investigation and found that the UTF-16 header is added by MSBuild when calling `Save(StringWriter writer)` - it is added to just the `StringWriter` and the project itself is not affected (until we reload that is). Even if the project raw xml already has a UTF-8 header, it is replaced with a UTF-16 header.

When saving directly to disk ( `Save()` or `Save(string path)` ) it is not added.

**Comment by rainersigwald** [comment]
Per @andygerlicher in https://github.com/Microsoft/msbuild/issues/1573#issuecomment-273029418, it sounds like this will have to be worked around outside of MSBuild. `StringWriter` itself implies UTF-16 👎

**Comment by AArnott** [comment]
Is it as easy as passing in a different `TextWriter` that claims to be UTF8?

**Comment by jviau** [comment]
@AArnott that would still add a header with UTF-8 if there wasn't one before. If the user has no header at all we should not be adding one.

**Comment by AArnott** [comment]
IMO adding a UTF 8 header is far less of a problem. So if we could fix it this way fast and fix it the right way later (assuming it's harder to fix the right way)  then I'd be in favor.

**Comment by srivatsn** [comment]
Temporary fix to strip the header outi in the project system has been checked in. Keeping this open to track the real fix.

**Comment by 333fred** [comment]
@jviau, I tested that locally, and it actually doesn't appear to add a header in the UTF-8 case. I'll submit a pull for that shortly
