### ISSUE TITLE
AssemblyInfo dialog in the Application property page

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn-project-system#117]
_From @davkean on March 23, 2016 21:25_

PSFFILEID_AssemblyInfo

_Copied from original issue: dotnet/roslyn#10032_

**Comment by srivatsn** [comment]
Repurposing this issue to include the work to get the AssemblyInfo dialog functional in the application prop page.

**Comment by srivatsn** [comment]
Completed by https://github.com/dotnet/roslyn-project-system/pull/280
