### ISSUE TITLE
Slow solution loading when changing branches

### ISSUE THREAD

**Issue by alrz** [dotnet/roslyn-project-system#1171]
I usually need to close/reopen the entire solution (Roslyn.sln in my case) before checkout another branch.

**Comment by davkean** [comment]
Yes, this is know issue with legacy project system. It performs a bunch of [design-time builds](https://github.com/dotnet/roslyn-project-system/blob/master/docs/design-time-builds.md) on the UI thread, which exponentially increase as the graph increases. The new project-system does not do this (it smartly groups design-time builds and waits for them on a background thread and runs them out-of-proc). Until the new project system supports existing desktop projects in a future release, workarounds include:

1. Use the Git tools within VS to switch branches, it will automatically reload the solution in that case.

2. VS itself now lets you reload the solution when it detects that a project file has changed outside of Visual Studio, click Reload Solution in those cases.

**Comment by alrz** [comment]
Unfortunately I cannot use git extension because it couldn't find the repo on ramdisk. I've filed a bug but they said it's on VS side (https://github.com/github/VisualStudio/issues/729).


>Until the new project system supports existing desktop projects in a future release

So it's post-dev15 I suppose.

**Comment by davkean** [comment]
@alrz Did you "report a problem" on the RAM disk issue?

**Comment by alrz** [comment]
@davkean Forgot at that time, but I did it now. Thanks!

**Comment by davkean** [comment]
If you can point me the feedback item - I'll make sure we get a bug on it and route to the right team.

**Comment by alrz** [comment]
I couldn't find any particular link for the issue from VS,

![screenshot](https://cloud.githubusercontent.com/assets/3105979/22006226/8dc2af26-dc7e-11e6-9138-c87b1d261c95.jpg)


Apparently there is no web version of feedback items either, but that's the title anyways. Hope that helps.

**Comment by davkean** [comment]
Thanks - I found it, routed and it will show up as bug against the right team.

**Comment by srivatsn** [comment]
Closing this issue as external.
