### ISSUE TITLE
Adding a framework to <TargetFrameworks> and building causes VS to hang.

### ISSUE THREAD

**Issue by NickCraver** [dotnet/roslyn-project-system#1174]
If you change a `.csproj` and build by adding a target framework then *immediately* build, VS hangs indefinitely.  I've committed a current repo to reproduce easily here: https://github.com/MiniProfiler/dotnet/tree/6e2ccc233da4f9d8614a57573857c885292e1881

As an example, edit  `/samples/Samples.Console/Samples.Console.csproj`, specifically:
```xml
<TargetFrameworks>net45</TargetFrameworks>
```
to this:
```xml
<TargetFrameworks>net45;netstandard1.5</TargetFrameworks>
```
And then build *immediately* (if you change tabs, it doesn't repro). Hitting build will cause VS to hang.

**Comment by srivatsn** [comment]
Tracking this using https://github.com/NuGet/Home/issues/4295
