### ISSUE TITLE
VS 2017 RC project migration doesn't delete project.json and XPROJ files

### ISSUE THREAD

**Issue by scottaddie** [dotnet/roslyn-project-system#1178]
@333fred When migrating my ASP.NET Core project via the CLI, everything goes as expected. When migrating via VS 2017 RC, the `project.json` and `.csproj` files aren't deleted from the `src` folder. To reproduce, follow these steps:

1. `git clone https://github.com/scottaddie/DotNetCoreSampleApp`
2. Open solution in VS 2017 RC, and click the OK button on the "One-way upgrade" dialog:
![xproj_migration_dialog](https://cloud.githubusercontent.com/assets/10702007/21995528/063f1456-dbeb-11e6-8225-7cb8e163a6ee.png)
3. Right-click the project in Solution Explorer, and choose **Open Folder in File Explorer**

When Windows Explorer opens, notice that the `project.json` and `WebApplication1.xproj` files remain. I would've expected them to be deleted, especially since they exist in the `Backup\src\WebApplication1` folder.

**Comment by 333fred** [comment]
We've confirmed that this is because the project system bits weren't updated. Once updated, the issue doesn't repro.
