### ISSUE TITLE
Edit csproj and remove PackageReference and save, it prompts you to reload the project file

### ISSUE THREAD

**Issue by balachir** [dotnet/roslyn-project-system#1179]
## Steps to reproduce
Using VS 2017 RC.3 (Build d15rel 26114.02), installed Web workload

1. New ASP.NET Core 1.0 > Empty web application
2. Build
3. Right-click > Edit csproj
4. Remove the line
    <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.0.0-beta1" />
5. Save

## Actual behavior
You get the prompt to reload the project file
![image](https://cloud.githubusercontent.com/assets/8246794/21995595/992cd818-dbda-11e6-95a8-9f87e42b11dd.png)

## Expected behavior
It should not prompt to reload the project file

**Comment by basoundr** [comment]
I tried for a repro and it does not happen all the time. Keep saving and editing, going back and forth and eventually we will hit this

**Comment by balachir** [comment]
@basoundr fyi, I did this 3 times today and have seen it repro every time on my machine.

**Comment by srivatsn** [comment]
This is because of the RC2->RC3 upgrade issue.
