### ISSUE TITLE
Saving an sdk style file adds xml header (utf-16)

### ISSUE THREAD

**Issue by onovotny** [dotnet/roslyn-project-system#1180]
Right clicking and editing a project file adds a utf-16 header even if the file is utf-8. The header shouldn't be there. Worse, after being read as UTF-16, the save changes the encoding of the file creating massive conflicts in Git/Version control.

**Comment by 333fred** [comment]
Same as https://github.com/dotnet/roslyn-project-system/issues/1168

**Comment by davkean** [comment]
Dup of #1168.
