### ISSUE TITLE
VS 2017 RC ASP.NET Core project "Default namespace" not populated

### ISSUE THREAD

**Issue by scottaddie** [dotnet/roslyn-project-system#1183]
Follow these steps to reproduce:

1. `git clone https://github.com/scottaddie/DotNetCoreSampleApp`
2. Open solution in VS 2017 RC
3. Right-click project in Solution Explorer, and choose **Properties** option from context menu
4. Click the **Application** tab, and notice that the **Default namespace** textbox is empty:
![empty_default_namespace_vs2017](https://cloud.githubusercontent.com/assets/10702007/21996178/8ce2ccac-dbee-11e6-805f-7c3ef1fdf0a7.png)

I would've expected this namespace textbox to be populated, as it looked like this in VS 2015 Update 3:
![empty_default_namespace_vs2015](https://cloud.githubusercontent.com/assets/10702007/21996224/c350b75e-dbee-11e6-8b9b-b88e0726d262.png)

**Comment by mavasani** [comment]
I verified this works fine on a clean install of d15rel.26114.02. This is most likely due to older packages due to https://github.com/dotnet/roslyn-project-system/issues/1187
