### ISSUE TITLE
Project type Guid  is updated during migration after fail

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn-project-system#1186]
The project type guid is updated to the new project system guid after migration, even if an error occurs. This means the solution will not attempt migration any more and open with errors. /cc @MarkMichaelis

**Comment by MarkMichaelis** [comment]
The project with this issue can be found https://github.com/IntelliTect/Coalesce.  The update I made to the project.json file can be found in the vs2017Rc3.pre branch (https://github.com/IntelliTect/Coalesce/tree/vs2017Rc3.pre).
To reproduce the issue, clone the Master branch and open with VS2017RC3(pre).

**Comment by 333fred** [comment]
This isn't repro'ing any more. A combination of fixes from the CLI guys and https://github.com/dotnet/roslyn-project-system/pull/1227, where I changed the migration to explicitly set the upgraded project GUID on migration failure back to Xproj, fixed it.
