### ISSUE TITLE
One occurrence of build never showing up completed in VS

### ISSUE THREAD

**Issue by nguerrera** [dotnet/roslyn-project-system#1188]
No repro steps for this as it did not re-occur on closing and reopening VS.

devenv.exe dumps are saved to `[internal file share]\public\nicholg\roslyn-project-system_1189`

The build appeared to have completed but VS never handled that and left the solution in a state where the build had to be cancelled. Attaching to msbuild.exe showed it doing nothing and waiting for reuse. There was no output in the output window. VS remained responsive throughout but considered the build to still be in progress. This is `build_of_two_test_projects_never_completing.dmp`

From this state, shutting down VS led to an actual "Not responding" hang" This is `hanging_on_shutdown.dmp`.

**Comment by nguerrera** [comment]
cc @ovotny

**Comment by nguerrera** [comment]
cc @onovotny

**Comment by srivatsn** [comment]
Maybe related to https://github.com/dotnet/roslyn-project-system/issues/1222?

**Comment by davkean** [comment]
This looks different from #1222.

**Comment by davkean** [comment]
I looked at the hang on shutdown and it looks like this: https://github.com/NuGet/Home/issues/4257.

The build never completing I have no idea, nothing interesting is occurring in the background and the UI thread is just pumping. We're/NuGet are nowhere to be seen, I think I'm going to move this to CPS.

**Comment by davkean** [comment]
Build also, doesn't appear to be blocked on NuGet restore like this hang one: https://github.com/dotnet/roslyn-project-system/issues/1273

**Comment by davkean** [comment]
Moved this internally to: https://devdiv.visualstudio.com/DevDiv/VS%20IDE/_workitems?id=372928&fullScreen=false&_a=edit.
