### ISSUE TITLE
Install: The product failed to install the listed workloads and components due to one or more package failures.

### ISSUE THREAD

**Issue by MarkMichaelis** [dotnet/roslyn-project-system#1191]
During an upgrade from VS2017 RC2 to RC3 (Version 15.0.26114.2 D15REL) the following error occurred: 
The product failed to install the listed workloads and components due to one or more package failures.

Incomplete workloads
    Game development with Unity (Microsoft.VisualStudio.Workload.ManagedGame,version=15.0.26109.1)
    Mobile development with .NET (Preview) (Microsoft.VisualStudio.Workload.NetCrossPlat,version=15.0.26114.2)

Incomplete components
    Unity editor (Component.UnityEngine,version=15.0.26109.1)
    Xamarin (Component.Xamarin,version=15.0.26114.2)

You can search for solutions using the information below, modify your selections for the above workloads and components and retry the installation, or remove the product from your machine.

Following is a collection of individual package failures that led to the incomplete workloads and components above. To search for existing reports of these specific problems, please copy and paste the URL from each package failure into a web browser. If the issue has already been reported, you can find solutions or workarounds there. If the issue has not been reported, you can create a new issue where other people will be able to find solutions or workarounds.

Package 'Xamarin_Preparation_Tool,version=4.0.2.1,chip=neutral' failed to download from 'https://go.microsoft.com/fwlink/?LinkId=734997'.
    Search URL: https://aka.ms/VSSetupErrorReports?q=PackageId=Xamarin_Preparation_Tool;PackageAction=DownloadPackage;ReturnCode=0x80131500
    Impacted workloads
        Mobile development with .NET (Preview) (Microsoft.VisualStudio.Workload.NetCrossPlat,version=15.0.26114.2)
    Impacted components
        Xamarin (Component.Xamarin,version=15.0.26114.2)
    Details
        WebClient download failed: The remote server returned an error: (403) Forbidden.
        Bits download failed: Error context: BG_ERROR_CONTEXT_REMOTE_FILE, Error code: -2145844845
        WinInet download failed: Url 'http://download.xamarin.com/XamarinforVisualStudio/XamarinCleanup.exe' returned HTTP status code: 403

Package 'Unity3dV1,version=1.0,chip=x64' failed to download from 'https://go.microsoft.com/fwlink/?linkid=823167'.
    Search URL: https://aka.ms/VSSetupErrorReports?q=PackageId=Unity3dV1;PackageAction=DownloadPackage;ReturnCode=0x80131500
    Impacted workloads
        Game development with Unity (Microsoft.VisualStudio.Workload.ManagedGame,version=15.0.26109.1)
    Impacted components
        Unity editor (Component.UnityEngine,version=15.0.26109.1)
    Details
        WebClient download failed: The remote server returned an error: (403) Forbidden.
        Bits download failed: Error context: BG_ERROR_CONTEXT_REMOTE_FILE, Error code: -2145844845
        WinInet download failed: Url 'http://download.unity3d.com/download_unity/a6d8d714de6f/Windows64EditorInstaller/UnitySetup64-5.4.0f3.exe' returned HTTP status code: 403

@GrantErickson, @jinujoseph @morrisjoe

**Comment by srivatsn** [comment]
I believe this has been resolved. Closing as external.
