### ISSUE TITLE
MSTest: Constructor runs for every test (rather than once for the class) during Debug

### ISSUE THREAD

**Issue by MarkMichaelis** [dotnet/roslyn-project-system#1192]
If you Debug an MSTest with one or more test methods, the constructor runs once for every test (rather than once for the entire class).  This does not seem to occur when running (not debugging).  The following code demonstrates the issue - failing when debugging (successful when not debugging):

`using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace UnitTestProject1
{
    [TestClass]
    public class TestBase
    {

    }

    [TestClass]
    public class UnitTestSample
    {
        static public int ConstructorCount { get; set; }

        public UnitTestSample()
        {
            ConstructorCount++;
        }

        [TestMethod]
        public void TestMethod1()
        {
        }

        [TestMethod]
        public void TestMethod2()
        {
        }

        [ClassCleanup]
        static public void ClassCleanup()
        {
            Assert.AreEqual<int>(1, ConstructorCount);
        }
    }
}
`
@jinujoseph @GrantErickson @morrisjoe

**Comment by srivatsn** [comment]
@dotnet/vstest can you take a look?

**Comment by davkean** [comment]
This issue was moved to Microsoft/vstest#360
