### ISSUE TITLE
NuGet Package Manager Always Returns to Installed Tab Rather than Last Tab

### ISSUE THREAD

**Issue by MarkMichaelis** [dotnet/roslyn-project-system#1193]
Each time you open up NuGet Package manager it returns to the Installed Tab rather than the last used tab, as the (for example) Browse tab which, at least for me, is far more common.
cc: @GrantErickson

**Comment by scottaddie** [comment]
Related issue that I logged a while back [here](https://github.com/NuGet/Home/issues/2353). Would be nice to make this behavior configurable.

**Comment by srivatsn** [comment]
This issue was moved to NuGet/Home#4299
