### ISSUE TITLE
Enter key doesn't work at the end of an @taghelper line in _ViewImports file.

### ISSUE THREAD

**Issue by MarkMichaelis** [dotnet/roslyn-project-system#1194]
When working in a _ViewImports file, the ENTER key doesn't work at the end of the `@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers` line.

cc: @GrantErickson, @jinujoseph

**Comment by srivatsn** [comment]
This issue was moved to aspnet/Tooling#945
