### ISSUE TITLE
Installation issue upgrading from VS 2017 RC2 to RC3

### ISSUE THREAD

**Issue by scottaddie** [dotnet/roslyn-project-system#1195]
The product failed to install the listed workloads and components due to one or more package failures.

Incomplete workloads
    Universal Windows Platform development (Microsoft.VisualStudio.Workload.Universal,version=15.0.26109.1)

Incomplete components
    .NET Native (Microsoft.Component.NetFX.Native,version=15.0.26004.1)
    Universal Windows Platform tools (2.0) (Microsoft.VisualStudio.Component.UWP.Support,version=15.0.26114.2)
    Universal Windows Platform tools for Cordova (2.0) (Microsoft.VisualStudio.ComponentGroup.UWP.Cordova,version=15.0.26109.1)
    Universal Windows Platform tools for Xamarin (2.0) (Microsoft.VisualStudio.ComponentGroup.UWP.Xamarin,version=15.0.26109.1)

You can search for solutions using the information below, modify your selections for the above workloads and components and retry the installation, or remove the product from your machine.

Following is a collection of individual package failures that led to the incomplete workloads and components above. To search for existing reports of these specific problems, please copy and paste the URL from each package failure into a web browser. If the issue has already been reported, you can find solutions or workarounds there. If the issue has not been reported, you can create a new issue where other people will be able to find solutions or workarounds.

Package 'Microsoft.VisualStudio.DotNetNative.ILC,version=15.0.26114.2' failed to repair.
    Search URL: https://aka.ms/VSSetupErrorReports?q=PackageId=Microsoft.VisualStudio.DotNetNative.ILC;PackageAction=Repair;ReturnCode=1638
    Impacted workloads
        Universal Windows Platform development (Microsoft.VisualStudio.Workload.Universal,version=15.0.26109.1)
    Impacted components
        .NET Native (Microsoft.Component.NetFX.Native,version=15.0.26004.1)
        Universal Windows Platform tools (2.0) (Microsoft.VisualStudio.Component.UWP.Support,version=15.0.26114.2)
        Universal Windows Platform tools for Cordova (2.0) (Microsoft.VisualStudio.ComponentGroup.UWP.Cordova,version=15.0.26109.1)
        Universal Windows Platform tools for Xamarin (2.0) (Microsoft.VisualStudio.ComponentGroup.UWP.Xamarin,version=15.0.26109.1)
    Log
        C:\Users\Scott Addie\AppData\Local\Temp\dd_setup_20170116132229_093_Microsoft.VisualStudio.DotNetNative.ILC.log
    Details
        MSI: C:\ProgramData\Microsoft\VisualStudio\Packages\Microsoft.VisualStudio.DotNetNative.ILC,version=15.0.26114.2\netfx_NativeCompilationBuild.15.0.msi, Properties:  REBOOT=ReallySuppress ARPSYSTEMCOMPONENT=1  MSIFASTINSTALL="7"  VSEXTUI="1"  REINSTALL=ALL  REINSTALLMODE="cmuse" IGNOREDEPENDENCIES=ALL 
        Return code: 1638
        Return code details: Another version of this product is already installed. Installation of this version cannot continue. To configure or remove the existing version of this product, use Add/Remove Programs on the Control Panel.

**Comment by jinujoseph** [comment]
filed new bug under VS repo : 368787
