### ISSUE TITLE
Need to visually differentiate when VS2015 is open or VS2017 is open

### ISSUE THREAD

**Issue by julielerman** [dotnet/roslyn-project-system#1196]
if you have the same color schemes for VS2015 & VS2017, you can't tell which version you have open without doing some exploration. Here is the same project opened in both IDEs:

VS2015
![vs2015](https://cloud.githubusercontent.com/assets/5007120/22000103/6300c304-dc0b-11e6-9d9c-39c93f9cf2b8.jpg)
VS2017
![vs2017](https://cloud.githubusercontent.com/assets/5007120/22000105/655d271e-dc0b-11e6-8293-7f964f6c7f54.jpg)

**Comment by khellang** [comment]
At the very least, the icon in the title bar could match the one in the task bar :smile:

**Comment by srivatsn** [comment]
JoC mentioned that there is different iconography coming for RTM to distinguish. Closing this since this is tracked internally in a different repo.
