### ISSUE TITLE
Properties Page for Web Application seems to be broken

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn-project-system#1198]
**Repro Steps** 
Create a New -> new Core Web Application 
View  properties 

![image](https://cloud.githubusercontent.com/assets/12449387/22000983/2718e466-dbf7-11e6-9b56-adb484f4378f.png)

This is same issue as https://github.com/dotnet/roslyn-project-system/issues/1147 
Build : 26114.2

**Comment by davkean** [comment]
We should make our properties provider sensitive to and handle converting from a empty string to something, instead of failing regardless of any MSBuild bug that prevents us from reading the properties correctly.

**Comment by srivatsn** [comment]
The web properties should now work - the issue was that the web rules had Label=Configuration in their datasource.
