### ISSUE TITLE
Edit CSPROJ context menu option shouldn't appear if XML content already open

### ISSUE THREAD

**Issue by scottaddie** [dotnet/roslyn-project-system#1200]
The "Edit CSPROJ" context menu option which appears when right-clicking an ASP.NET Core project shouldn't appear if I've already selected it and have the CSPROJ XML open. Here are the steps to reproduce in VS 2017 RC:

1. Create a new project using the ASP.NET Core 1.1 / .NET Core project template
2. Right-click the project in Solution Explorer, and select "Edit _<project_name_here>_.csproj"
3. Repeat step 2, and notice that you can still select this option from the context menu. The option shouldn't appear, since the XML content of the CSPROJ file is already open in the IDE.

![edit_csproj_file](https://cloud.githubusercontent.com/assets/10702007/22001989/4cd404f0-dbfd-11e6-80df-78b738a6aac8.png)

**Comment by davkean** [comment]
Why do you think that's the correct behavior? 

This is exactly the same behavor as "editing" (open) a source file. If it's not already open, open it, otherwise, make it the current editor.

**Comment by 333fred** [comment]
Scott and I talked a bit offline. The design of this feature is that we want to open the editor if it's not open, and switch to it if it's already open. The editor itself reloads in the background as necessary, so it can be open for a long period of time.
