### ISSUE TITLE
Project Properties "Assembly name" textbox empty

### ISSUE THREAD

**Issue by scottaddie** [dotnet/roslyn-project-system#1201]
Create a new ASP.NET Core 1.1/.NET Core project in VS 2017 RC3 via the project template, right-click the project in Solution Explorer, choose Properties, and notice that the Application tab's "Assembly name" textbox is empty.

![empty_assembly_name](https://cloud.githubusercontent.com/assets/10702007/22002197/bfb297ce-dbfe-11e6-9ae4-27eff49a8d5f.png)

**Comment by davkean** [comment]
@333fred Can you make sure that @scottaddie install got correctly upgraded from RC2 -> RC3?

**Comment by davkean** [comment]
@scottaddie As a side note, what resolution/DPI are you running?

**Comment by scottaddie** [comment]
@davkean 3200 x 1800

**Comment by jinujoseph** [comment]
This is most probably same as : #1198 
@scottaddie can you confirm this is webapplication.

**Comment by scottaddie** [comment]
@jinujoseph Yes, this is a web application. I used this project template:
![web_app_project_template](https://cloud.githubusercontent.com/assets/10702007/22002969/f68771ec-dc04-11e6-8a92-7aef88bee3d0.png)

**Comment by srivatsn** [comment]
This should now fixed in today's build.
