### ISSUE TITLE
Hide 'Pack' option for Unit Test Project (.Net Core)” / "ASP.Net Core Web Application (.Net Core) project"

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn-project-system#1204]

**Comment by mavasani** [comment]
Is the suggestion here even to hide the Package property page? Both the command and the page are currently based on "Pack" capability which is pulled in by NuGet Pack target.

Tagging @srivatsn

**Comment by srivatsn** [comment]
Ya we should have the pack capability only for class libraries then.

**Comment by srivatsn** [comment]
This issue was moved to NuGet/Home#4323
