### ISSUE TITLE
Downgrade warning message does not indicate project or file

### ISSUE THREAD

**Issue by NickCraver** [dotnet/roslyn-project-system#1209]
## Steps to reproduce
1. Grab the Dapper repo here: https://github.com/StackExchange/dapper-dot-net/tree/5f2b81f0edf1ada009806a852a0749081980ac85
2. Open `Dapper.sln` in VS 2017 RC
4. Open the error window

This is what a user sees, note that Project and File columns are empty, so the user doesn't know which project is having an issue:
<img width="1125" alt="screen shot 2017-01-16 at 19 23 16" src="https://cloud.githubusercontent.com/assets/454813/22003427/705d3a3a-dc21-11e6-9f99-7860a2bb995c.png">

Ideally, click these errors would also navigate to those `<PackageReference />` elements. I realize that's far less trivial, but it should be the end goal if possible.

**Comment by srivatsn** [comment]
This issue was moved to NuGet/Home#4322
