### ISSUE TITLE
Provide full path of projects/files when hovering over file/open/recent

### ISSUE THREAD

**Issue by julielerman** [dotnet/roslyn-project-system#1210]
When opening a recent project/solution, if they have similar names but are in different paths, it's impossible to tell which one to open. This may be because of my current resolution but either way, it would be much more helpful if I could see the full paths when hovering over a particular option.

![image](https://cloud.githubusercontent.com/assets/5007120/22028254/a0a0c760-dca4-11e6-9cc7-6f62343057e7.png)

**Comment by srivatsn** [comment]
Filed an internal TFS bug on the shell team.
