### ISSUE TITLE
legacy project that depends on a CPS project, old NuGet built dlls can get loaded into msbuild or devenv process, causing restore erros

### ISSUE THREAD

**Issue by rrelyea** [dotnet/roslyn-project-system#1211]
If you use a legacy project that depends on a CPS project, old NuGet built dlls can get loaded into msbuild or devenv process, causing restore errors.

NuGet VSIX and Microsoft.NET.Build.Tasks must have identical NuGet build numbers for their dependencies.

ways to repro:
1) load that type of solution into VS 2017, kick off a restore. 
result: method missing error

or

1) msbuild /t:restore from vs2017 dev command prompt.
result: method missing error

Sri's proposed logistics for a fix:
1.	The myget feed is updated with the new nuget (please make sure that the SDK and CLI repos build fine). CLI is still making changes for RC3 and if they do another insertion it’ll carry the new bits.
2.	We kick off a build of SDK and insert that into VS.
3.	A WTE insertion is needed to update the pack tasks in VS.
4.	We don’t need a CLI insertion but if there’s a new one it’ll carry the bits.

**Comment by tmat** [comment]
Is this gonna make it to RTM? I see the error in a project I'm converting to the new project system now. This is blocking since i need to have a project in the solution that targets Desktop FX.

**Comment by srivatsn** [comment]
This is fixed.
