### ISSUE TITLE
FindAllReferences should be simpler for multiple target frameworks.

### ISSUE THREAD

**Issue by NickCraver** [dotnet/roslyn-project-system#1212]
First, kudos on this dialog in 2017. Find All References is a huge improvement. I think we can do even better with some hopefully relatively simple changes.

This is a general issue, but here are repro specs for the specific screenshot used in this example:

## Steps to reproduce
1. Grab the MiniProfiler repo here: https://github.com/MiniProfiler/dotnet/tree/261d3d1bdaf4047d59f0a1eba4b3b779f26a6e84
2. Open `src\MiniProfiler.Shared\MiniProfiler.cs`
3. Go to [Line #75 for `DurationMilliseconds`](https://github.com/MiniProfiler/dotnet/blob/v4/src/MiniProfiler.Shared/MiniProfiler.cs#L75)
4. Right click > Find All References

The "Find All References" dialog looks like this:
<img width="1056" alt="screen shot 2017-01-17 at 11 29 18" src="https://cloud.githubusercontent.com/assets/454813/22029804/a0c9b436-dca9-11e6-9c05-f6bdf40049a7.png">

This is quite cluttered, and that's fo a simple project with only 2 target frameworks. Imagine more. Every framework added is effectively a multiplier for volume in the results window (adjusting for `#ifdef`s of course). 

But there are not `n` copies of this code, there are 1. It should be a single result, which would be far more usable. I propose instead it groups by the existing lines/columns of code there, with target framework being a comma-delimited list. In the screenshot above, picture *one* set of lines of code (no changes), but instead of the headers saying this:
```
MiniProfiler.Shared(net45) (3)
MiniProfiler.Shared(netstandard1.5) (3)
```
To a single header, like this:
```
MiniProfiler.Shared(net45, netstandard1.5) (3)
```
When you click the lines of code, they all go to the same place and do the same thing. We shouldn't show them many times, it's a developer experience that could be much better.

cc @CyrusNajmabadi

**Comment by CyrusNajmabadi** [comment]
For cases where there truly is 100% overlap I totally agree we should do something like this. But sure what the best thing is when the overlap is not 1:1 though.  

This is also tricky to pull off due to the streaming nature of the feature. 

However, I totally agree that these types of projects lead to a poor experience, and that we should do something about that.

**Comment by NickCraver** [comment]
On the < 100% case: I'd say the groups are by the lines below. If a line if inside a `#ifdef NET45` for example, another group showing only "(net45)" would show, with that 1 result inside.

FWIW, I'd readily trade the streaming nature of the feature for the more usable UI in the multi-targeting case.

**Comment by srivatsn** [comment]
This issue was moved to dotnet/roslyn#16587
