### ISSUE TITLE
Null reference exception when Ctrl+Z after "Generate Type" fix.

### ISSUE THREAD

**Issue by NickCraver** [dotnet/roslyn-project-system#1216]
## Steps to repro
1. Create a new project, class contents:
```c#
public class Class1
{
    public MyType Thing { get; }
}
```
2. `MyType` is an unknown type, `Ctrl+.` and select **"Generate type 'MyType'"**
3. Observe the MyFile.cs is added to the project
4. Hit Ctrl+Z to undo the refactoring

This works correctly on the old project system, removing the file. An exception is thrown in the roslyn system:
> Object reference not set to an instance of an object.

Picture path:
<img width="692" alt="screen shot 2017-01-17 at 13 34 14" src="https://cloud.githubusercontent.com/assets/454813/22034476/6eb00ffc-dcba-11e6-8f34-aa6b773dd70c.png">
<img width="792" alt="screen shot 2017-01-17 at 13 34 27" src="https://cloud.githubusercontent.com/assets/454813/22034492/77ecd488-dcba-11e6-85cd-6bd99bf33759.png">

**Comment by davkean** [comment]
This looks similar to: https://github.com/dotnet/roslyn/issues/16546.

**Comment by davkean** [comment]
I have a fix for this in #1246.
