### ISSUE TITLE
NuGet restore in Visual Studio doesn't recognize that additional target frameworks have been added to a project

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/roslyn-project-system#1226]
- New Project -> Class Library (.NET Standard)
- Edit .csproj, change `TargetFramework` property to `TargetFrameworks`
- Change value of `TargetFrameworks` property from `netstandard1.4` to `netstandard1.4;netstandard1.3`
- Build

**EXPECTED:** Build succeeds
**ACTUAL:** Build fails.  There are lots of compilation errors that various APIs from the Framework can't be found, but the relevant one is this: 

> 1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.Sdk.targets(76,5): error : Assets file 'c:\users\daplaist\documents\visual studio 2017\Projects\AddTargetFrameworkRepro\AddTargetFrameworkRepro\obj\project.assets.json' doesn't have a target for '.NETStandard,Version=v1.3'. Ensure you have restored this project for TargetFramework='netstandard1.3' and RuntimeIdentifier=''.

Closing and reopening the solution fixes the issue.  Manually invoking restore in VS does **not** fix the issue, it says "All packages are already installed and there is nothing to restore."  It appears that the NuGet restore in VS is not recognizing that the project restore is out of date due to an additional TFM having been added.

@rrelyea

**Comment by natidea** [comment]
This sounds like a known issue where our subscriptions are not firing appropriately when you make certain TF -> TFS changes. Bug #614 tracks changing the way we subscribe to active configured projects, and that may fix this.

**Comment by mavasani** [comment]
Isn't the issue here specific to explicit build? Nat, the issue you mentioned is specific to design time build/background restore - it won't fix this issue.

**Comment by srivatsn** [comment]
Closing in favor of #1321
