### ISSUE TITLE
Test Explorer Should Show Test Durations in ms by default

### ISSUE THREAD

**Issue by ardalis** [dotnet/roslyn-project-system#1232]
The new format of 0:00:00.000 for test times takes up way too much space for most unit tests which run in under 10ms. See the screenshot below, showing VS2017 above and VS2015 below:

![image](https://cloud.githubusercontent.com/assets/782127/22045773/4a7e1400-dcea-11e6-8d23-68453f268ccd.png)

I'd much rather see 3 ms than 0:00:00.003 for test duration, and I'd much rather see more of the name of my test than a bunch of useless 0s.

This is rejected as "by design" in [user voice](https://visualstudio.uservoice.com/forums/121579-visual-studio-ide/suggestions/17049103-report-unit-test-duration-in-test-explorer-in-mill), but I'd like to see this reconsidered. The reasoning behind this change is "consistency with the summary" but I don't see how that's valuable. The format used to display the duration should match the context, not necessarily be a one-size-fits-all decision.

**Comment by sbaid** [comment]
Thanks for feedback. We are looking at it. + @pvlakshm

**Comment by davkean** [comment]
This issue was moved to Microsoft/vstest#359
