### ISSUE TITLE
[Performance] .NET Core project takes 4 times longer to build than a .NET Framework project

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn-project-system#1243]
I tested a Console App (.NET Framework) vs Console App (.NET Core), and from the command-line the project takes 4 times longer to build (if MSBuild is hot):

```
msbuild /t:rebuild
```

Average time to build .NET Framework: 220 Milliseconds
Average time to build .NET Core: 800 Millseconds

In Visual Studio, via right-click Rebuild:

Average time to build .NET Framework: 50 Milliseconds
Average time to build .NET Core: 230 Millseconds

**Comment by srivatsn** [comment]
This issue was moved to dotnet/sdk#754
