### ISSUE TITLE
"Generate NuGet package on build" indeterminate for web applications

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn-project-system#1244]
1. File -> New Web Application (.NET Core)

![image](https://cloud.githubusercontent.com/assets/1103906/22093011/2f5c0110-de56-11e6-9c46-7771d8b8690c.png)

**Comment by srivatsn** [comment]
Verified that this is fixed in 26118.00:

![image](https://cloud.githubusercontent.com/assets/20570/22095233/1195e274-ddc8-11e6-9763-defd876efd55.png)
