### ISSUE TITLE
intellisense for the NuGet package versions in csproj file

### ISSUE THREAD

**Issue by damienbod** [dotnet/roslyn-project-system#1249]
I really miss the intellisense for the NuGet package versions in the project file. Would be great to have this again in the csproj file.

**Comment by damienbod** [comment]
https://github.com/dotnet/roslyn-project-system/issues/1224

**Comment by NickCraver** [comment]
I think there are 2 sets of Intellisense in play here. One is the NuGet packages, and the other is overall (NuGet metadata element names, etc.). **I agree the most critical for RTM is this one.** If we don't have this in by VS 2017 RTM, and we don't have `project.json` support, then we have exactly what many (including me) feared: a major step backwards from `project.json`.

I'd happily test this as soon as it's ready, I think the NuGet versions intellisense is a must. The other bits for Metadata *should* mostly be there via schema additions already. Autocomplete for things like the variables, e.g. `$(Tar` yielding `$(TargetFramework)` is another item, but I'm guessing that's already tracked somewhere I can't find. That certainly *should* work, but it's not a hard blocker to the new system being usable for all.

**Comment by davkean** [comment]
I've filed the MSBuild metadata one here: https://github.com/dotnet/roslyn-project-system/issues/1253, but I'm sure we're already tracking it somewhere else as we've been talking about it for a while.

**Comment by NickCraver** [comment]
For others: schema intellisense issue (e.g. `<PackageReference>` itself) is here: https://github.com/Microsoft/msbuild/issues/1488

**Comment by srivatsn** [comment]
Schema intellisense is fixed. We've added [these entries](https://gist.github.com/srivatsn/09c6eb4128bbe3da6404d87dce1baa01) to the schema for RTM. 

For version IntelliSense I believe somone in @mlorbetske's group was working on an extension that enables it

**Comment by srivatsn** [comment]
Closing this in favor of tracking with #766
