### ISSUE TITLE
Project Properties tool window shows "Output Type" twice

### ISSUE THREAD

**Issue by AArnott** [dotnet/roslyn-project-system#1261]
The .NET Core project system's properties tool window shows Output Type twice when the project node is selected in Solution Explorer:

![image](https://cloud.githubusercontent.com/assets/3548/22121757/0b2f1168-de3a-11e6-96b4-ba1552b1828d.png)

The BrowseObject .xaml file probably lists the property twice.

**Comment by AArnott** [comment]
Indeed, [two properties are defined](https://github.com/dotnet/roslyn-project-system/blob/f0070bceed62c1f6335457bd3ca496c9b8efb05e/src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/GeneralBrowseObject.xaml#L44) with the same display name.

Also, why are integers used as the display text for these property values? That's worse than even the msbuild level property values.

**Comment by jinujoseph** [comment]
Context on why it was added twice and int #261. This should be fixed as we resolve #389

**Comment by jinujoseph** [comment]
This should be fixed with #1472
