### ISSUE TITLE
Adding a new profile on debug tab doesn't work correctly

### ISSUE THREAD

**Issue by BillHiebert** [dotnet/roslyn-project-system#1263]
1. Create a new .Net Core console application
2. R-click and bring up properties
3. Select the debug tab
4. Click the New profile button, press OK
5. New profile appears in the text box of the dropdown, but does not appear in the list when the dropdown is expanded. 
6. Select another Profile.
Now try to select the one from step 4, you can't because it is not in the list.

**Comment by BillHiebert** [comment]
The problem is the ItemsSource for the combobox is bound to a List instead of an observable collection so it doesn't refresh its contents.

**Comment by srivatsn** [comment]
Fixed now.
