### ISSUE TITLE
Launch URL does nothing in Console applications or in web projects where the user has added an Executable profile

### ISSUE THREAD

**Issue by balachir** [dotnet/roslyn-project-system#1264]
## Steps to reproduce

1. Using VS 2017 RC.3 (d15rel.26118.01)
2. New ASP.NET Core web app, open property pages
3. Add new profile, set the 'Launch' setting to Executable
4. Provide a Launch URL
![image](https://cloud.githubusercontent.com/assets/8246794/22130228/b0c257f0-de5f-11e6-92c5-5128f57cd899.png)
5. F5 or Ctrl-F5

## Actual behavior
The executable gets launched but the URL does not get opened in the browser

## Expected  behavior
The executable gets launched _**AND**_ the URL does not get opened in the browser

**Comment by BillHiebert** [comment]
The fix for RCW is to hide this field for executable and project  launch types for console applications

**Comment by BillHiebert** [comment]
Closed in error

**Comment by srivatsn** [comment]
Fixed now.
