### ISSUE TITLE
When using TargetFrameworks the dropdown is disabled in the property pages

### ISSUE THREAD

**Issue by RaulPerez1** [dotnet/roslyn-project-system#1268]
1) Create a new .NET Core App
2) Change TargetFramework to TargetFrameworks
3) Open the Application property page

Expected: Default (first) value is selected in the dropdown
Actual: Dropdown is not populated and the control is disabled

![image](https://cloud.githubusercontent.com/assets/19919028/22131485/9637054e-de68-11e6-865f-e4b1c3ffec28.png)

**Comment by davkean** [comment]
The behavior is currently by design, as we haven't updated to support multiple.

Why would you expect the first TFM to show?

**Comment by RaulPerez1** [comment]
Because we're returning the first one as the default in the provider. Thinking about it though you're right this would get confusing fast. I think the right (post RTW) fix is to turn that into a checked listbox to support both single and multiple entries.

**Comment by davkean** [comment]
Yep, agreed.

**Comment by srivatsn** [comment]
Yes and that's tracked by https://github.com/dotnet/roslyn-project-system/issues/800
