### ISSUE TITLE
Cannot install extensions because some small instance of VS2017RC is still in memory

### ISSUE THREAD

**Issue by julielerman** [dotnet/roslyn-project-system#1269]
I've seen this twice now. Once when attempting to install an extension from a downloaded VSIX after closing VS2017RC and just now when trying to install a different extension via the Visual Studio Installer App.

# STEPS TO REPRODUCE
THIS IS NOT 100% REPRODUCIBLE. I cannot figure out what causes the extra 1.2MB VS2017 process. But I have seen it a few times now and am trying to figure out where it's coming from. Maybe *that* is the problem and not the installer.

This will be what I just experienced -- attempting to install an extension via the Installer Desktop App.
The other experience I had as installing the SQLCe/SQLite ToolBox from its VSIX file.

Open VS2017RC.
Close VS2017 RC.

Open VS2017 Installer App. 
Select the the Enterprise Box and click Modify.
Scroll down to the Visual Studio Extension Development  and select that.
In the summary section, scroll down to the bottom and select Modeling SDK (or possiby any other option that is not installed yet).

Notice that after the app calculates the the install size, the Modify button remains inactive.

That's when you might notice the itty bitty warning at the bottom of the screen that  says "Please close all instances of Visual Studio 2017 RC before preceding with this operation".

I have no running instances of VS2017RC.

Close the installer app.

Open task manager.

There is an instance of VS2017RC (devenv.exe) running that is taking a very small amount of memory.

![image](https://cloud.githubusercontent.com/assets/5007120/22131537/b6c04dc8-de79-11e6-80cb-7ecf8e6e7ee9.png)

click on that listing and choose end task. Nothing happens.

Right click the lsiting and choose Details.
![image](https://cloud.githubusercontent.com/assets/5007120/22131577/fc07afb6-de79-11e6-9c14-43242b2593bd.png)

Select the devenv.exe process on the details page and then click the End Task button.

Confirmation window ...don you want to end this task?
Click on End Process.

Error pops up that says Unable to Terminate Process.  The operation could not be completed. Access denied.

# WORKAROUND

The only way Im able to install is by restarting the machine and running the installation BEFORE ever starting up VS2017RC.

**Comment by ErikEJ** [comment]
I Think this is a known issue, check th RC Release notes. For the Toolbox, only the Daily build Works, I Think

**Comment by julielerman** [comment]
Hey @ErikEJ it's not your VSIX, I promise. That was one of the things I happened to be installing. Also, I installed it and mentioned it on @ch9 VS Toolbox bragging about how it already works with VS2017 :)  I do believe my problem was related to something NOT directly related to installing but maybe a prior crash that is not cleaning up a process. I think I'll close this and open a new issue.

**Comment by ErikEJ** [comment]
Also, I think there is a special web site for VS 2017 feedback
