### ISSUE TITLE
[Data loss] Editing an unsaved project loses data

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn-project-system#1270]
1. Create a new .NET Core project
2. Create a Shared Project
3. Add a reference from .NET Core project to Shared Project
4. Right-click project and choose Edit Project
5. Close the solution

Expected: Get prompted to save project
Actual: Only get prompted to save solution, reopening the project you can see the reference never gets saved.

The same occurs for any change that results in the project changing, such as setting a property, excluding a folder, etc.

**Comment by davkean** [comment]
tag @srivatsn @333fred

**Comment by 333fred** [comment]
Tag @lifengl, this sounds like an issue with the project itself not being considered dirty?

**Comment by 333fred** [comment]
This is because `ProjectRootElement.Save()` clears the dirty flag, which we're using to get the content of the project xml.

**Comment by 333fred** [comment]
@cdmihai @rainersigwald, would it be possible to get a `SaveAs` that does does the same thing as `Save`, except that it doesn't increment the version?
