### ISSUE TITLE
Suggestion: Reference HintPaths that go through program files should be absolute

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn-project-system#1274]
I'm not sure what the benefit of this HintPath is:

```
..\..\..\..\..\..\..\Program Files (x86)\DevExpress 16.2\Components\Bin\Framework\DevExpress.Utils.v16.2.dll
```

Over this:

```
C:\Program Files (x86)\DevExpress 16.2\Components\Bin\Framework\DevExpress.Utils.v16.2.dll
```

If it goes through %programfiles% or %programfiles(x86)%, seems logical that it should never be a relative path.

**Comment by davkean** [comment]
It's a bug that we're burning them in the first plcae: https://github.com/dotnet/roslyn-project-system/issues/235.
