### ISSUE TITLE
Project properties causes error by inserting "winexe" instead of "WinExe"

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn-project-system#1276]
To repro (15.0.26014.0), csproj:

```xml
<Project Sdk="Microsoft.NET.Sdk" ToolsVersion="15.0">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net452</TargetFramework>
    <RuntimeIdentifier>win</RuntimeIdentifier>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="**\*.cs" />
    <EmbeddedResource Include="**\*.resx" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="System.Windows.Forms" />
  </ItemGroup>
</Project>
```

Program.cs:
```cs
using System.Windows.Forms;

namespace TestWinFormsLicx
{
    public static class Program
    {
        public static void Main()
        {
            Application.EnableVisualStyles();
            Application.SetCompatibleTextRenderingDefault(false);
            Application.Run(new Form());
        }
    }
}
```

 * Go project properties > Application, change "Output type" from its erroneous current value of "Windows Application" to "Console Application" and then back to "Windows Application."
 * Start debugging and get an error message box:
   > Unable to run your project. The "RunCommand" property is not defined.

 * See `<OutputType>winexe</OutputType>` in the .csproj, change to `<OutputType>WinExe</OutputType>`
 * Start debugging and everything works as expected

**Comment by jnm2** [comment]
For some reason, `WinExe`, running worked the first time I tried it but then it gives the same error as `winexe` for subsequent runs. I unloaded and reloaded the project and the first run worked again and subsequent runs failed. I unloaded and reloaded a few more times and it's failing every time now. I see that the .csproj contents are still `WinExe`.

**Comment by davkean** [comment]
Looks like WinExe isn't the only case: https://github.com/dotnet/roslyn-project-system/issues/1276

Dup'ing this against 1276 which contains more cases.

**Comment by jnm2** [comment]
Do you mean #1309? I almost linked it earlier when I saw it come up.

**Comment by davkean** [comment]
Sorry, I meant: https://github.com/dotnet/roslyn-project-system/issues/1299, but #1309 could also be related.

**Comment by davidmatson** [comment]
I'm currently hitting the same bug and am glad to hear it's fixed. How do I install the fix ? Is this fix for this bug fix already in a production version of VS 2017?

**Comment by davkean** [comment]
No this fix is not yet available in a public version of Visual Studio, in particular, this will end up in our 15.3 release: https://github.com/dotnet/roslyn-project-system/blob/master/docs/repo/roadmap.md
