### ISSUE TITLE
Project System: Setup authoring

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn-project-system#128]
_From @davkean on December 1, 2015 19:24_

_Copied from original issue: dotnet/roslyn#7153_

**Comment by davkean** [comment]
New files that we need to setup:

# Extension directory:
Microsoft.VisualStudio.AppDesigner.dll
Microsoft.VisualStudio.Editors.dll
Microsoft.VisualStudio.Editors.pkgdef
Microsoft.VisualStudio.ProjectSystem.Managed
Microsoft.VisualStudio.ProjectSystem.Managed.VS
Microsoft.VisualStudio.ProjectSystem.CSharp
Microsoft.VisualStudio.ProjectSystem.VisualBasic
Microsoft.VisualStudio.ProjectSystem.CSharp.VS.dll
Microsoft.VisualStudio.ProjectSystem.CSharp.VS.pkgdef
Microsoft.VisualStudio.ProjectSystem.VisualBasic.VS.dll
Microsoft.VisualStudio.ProjectSystem.VisualBasic.VS.pkgdef
ProjectSystem.pkgdef
extension.vsixmanifest

MSBuild directory:
Microsoft.CSharp.Designer.targets
Microsoft.VisualBasic.Designer.targets
[lang]\AppDesigner.xaml

**Comment by natidea** [comment]
Design Targets and Common File Work Items
- [x] Author design time targets and XAML files into Modern VSIX
- [x] Update MSBuild Current Version targets to call design time targets (https://github.com/Microsoft/msbuild/pull/789)
- [ ] Move XAML files into language specific folders
- [ ] Move all unused XAML files

**Comment by srivatsn** [comment]
Split out the remaining issues to #348.
