### ISSUE TITLE
Xml Documentation file path not computed properly

### ISSUE THREAD

**Issue by basoundr** [dotnet/roslyn-project-system#1280]
Enabling XML Documentation File in Property pages Build Tab, shows this

![image](https://cloud.githubusercontent.com/assets/10550513/22160988/0cf871ec-defd-11e6-9af6-0527c21892bb.png)

**Comment by jnm2** [comment]
For me in 26127.3, with a class library targeting `net20;netstandard1.3`, when I first check the box it inserts `\AssemblyName.xml`. Then the build fails because it doesn't have write access to `C:\AssemblyName.xml`.

**Comment by jnm2** [comment]
I removed the beginning slash and all is well.

**Comment by jnm2** [comment]
Not all is well- I spoke too soon. I removed the trailing slash and it does appear correctly at `bin\{config}\{tfm}\{AssemblyName}.xml`, but it also shows up beside the .csproj on each build and of course source control picks it up because it's not in  build output folder.

**Comment by jnm2** [comment]
`bin\Debug\netstandard1.3\{AssemblyName}.xml` is the current workaround. Hopefully this is reduced to `{AssemblyName}.xml` eventually without that extra out-of-place output.

**Comment by basoundr** [comment]
Fixed with #1842

**Comment by jnm2** [comment]
@basoundr I don't want to have to specify a path. Is that ability included in the fix?

**Comment by srivatsn** [comment]
No that's tracked by https://github.com/dotnet/roslyn-project-system/issues/368
