### ISSUE TITLE
Microsoft.DotNet.ProjectModel.ProjectContextBuilder Replacement for CSProj

### ISSUE THREAD

**Issue by MarkMichaelis** [dotnet/roslyn-project-system#1284]
Currently, we use Microsoft.DotNet.ProjectModel.ProjectContextBuilder to build a Microsoft.DotNet.ProjectModel.ProjectContext. Currently, this fails on a 2017 project with the following error: Could not resolve project at: D:\Work\Coalesce.VS2017RC3.15.0.26116.0.D15REL\src\Coalesce.Web\. This could happen when project.lock.json was moved after restore.
What is the planned upgrade path to get this working with .csproj based projects?

/cc @granterickson, @morrisjoe, @breaman, @ascott18

**Comment by srivatsn** [comment]
I don't know what ProjectContextBuilder used to do @piotrpMSFT @davidfowl any thoughts here?

**Comment by Sharpiro** [comment]
@davidfowl @filipw 

Static methods on ```Microsoft.DotNet.ProjectModel.ProjectContext``` seem to be incompatible with the new .csproj, and fail looking for a project.json file.

Ex:

```
Microsoft.DotNet.ProjectModel.ProjectContext.CreateContextForEachTarget
Microsoft.DotNet.ProjectModel.ProjectContext.Create
```

Is there a new way to get a project context w/ .csproj?

**Comment by davidfowl** [comment]
You need to use the msbuild APIs. Omnisharp is your best bet at figuring out the equivalent APIs to use (these are no longer first class):

https://github.com/OmniSharp/omnisharp-roslyn/blob/cf41430ccded50d36cafd81ced578e29770c5daa/src/OmniSharp.MSBuild/ProjectFile/ProjectFileInfo.cs

**Comment by Sharpiro** [comment]
is omnisharp-roslyn and those msbuild APIs available as a nuget package?

**Comment by davkean** [comment]
Going to close this in lieu of MSBuild APIs, this is what OmniSharp a few other projects are using.

**Comment by giggio** [comment]
I know this is an old question, but I just want to point out the nice project Buildalyzer, which makes all this work really simple, for future reference. It might help other people as it has helped me.
https://github.com/daveaglick/Buildalyzer
