### ISSUE TITLE
Replacement for Microsoft.CodeAnalysis.MSBuild.MSBuildWorkspace?

### ISSUE THREAD

**Issue by MarkMichaelis** [dotnet/roslyn-project-system#1285]
In migrating from VS2015 to VS2017, is Microsoft.CodeAnalysis.MSBuild.MSBuildWorkspace the intended replacement for Microsoft.DotNet.ProjectModel.Workspaces.ProjectJsonWorkspace? Or is there some other implementation of Microsoft.CodeAnalysis.Workspace that we should be using?

/cc @granterickson, @morrisjoe, @breaman, @ascott18

**Comment by srivatsn** [comment]
Yes MSBuildWorkspace should work for these projects. Now I know @mattwar was looking into MSBuildWorkspace being broken due to MSBuild moving elsewhere. Matt, does MSBuildWorkspace work with MSBuild 15 (which is needed for it to understand .NET core projects).

**Comment by mattwar** [comment]
Msbuild should work in RC3.  Though you'll need to upgrade the app's redirects to include the newest msbuild's redirects found in msbuild.exe.config.

**Comment by JosephWoodward** [comment]
Does MSBuildWorkspace support the .NET Standard? IE, can it be used for loading .NET Core projects on Mac and Linux?

**Comment by mattwar** [comment]
MSBuildWorkspace only supports desktop clr currently.

**Comment by JosephWoodward** [comment]
Ok, thank you for the prompt reply!

**Comment by JosephWoodward** [comment]
@mattwar Do you have any suggestions as where to look or what to do for anyone that wants to load the new MsBuild .csproj proj format on Mac and Linux?

**Comment by davkean** [comment]
This issue was moved to dotnet/roslyn#17974

**Comment by davkean** [comment]
Move this over to Roslyn, as they own MSBuildWorkspace.
