### ISSUE TITLE
For a web application targeting ASP.NET Core 1.0, the version of Microsoft.NETCore.App in dependencies tree is 1.1.0 instead of 1.0.3

### ISSUE THREAD

**Issue by balachir** [dotnet/roslyn-project-system#1288]
## Steps to reproduce

1. Using VS 2017 RC.3 (d15rel.26118.01)
2. New ASP.NET Core web app (ASP.NET Core 1.0 on Core)
3. View dependencies tree

## Actual behavior
Microsoft.NetCore.App package shows up as 1.1.0
![image](https://cloud.githubusercontent.com/assets/8246794/22170003/c7568c92-df2d-11e6-9f65-83cf9c9fd064.png)

## Expected  behavior
Microsoft.NetCore.App package shows up as 1.0.3

**Comment by davkean** [comment]
This issue was moved to dotnet/sdk#701
