### ISSUE TITLE
Renaming .NET Core Project breaks Restore and Build

### ISSUE THREAD

**Issue by natidea** [dotnet/roslyn-project-system#1293]
Ported from https://github.com/NuGet/Home/issues/4287

VS 2017 26114.00 (rc3 not final)

Repro Steps
1. Create a NetStandard project named ClassLibraryNetStandard
2. Rename the project ClassLibraryNetStandard14
3. Build

Expected: no error, restore works

Actual: In build output window, see a message: Error occurred while restoring NuGet packages: The operation failed as details for project ClassLibraryNetStandard14 could not be loaded.

Workaround: unload + reload project or close solution/open solution.
or: hand edit the project file and add/remove or change a package reference, and the Project and NuGet will be in sync again enabling NuGet package operations

**Comment by natidea** [comment]
Adding the `MSBuildProjectFile` property to NuGetRestore subscription rules fixes this.

**Comment by devinvisible** [comment]
@natidea Where exactly can I find the NuGetRestore subscription rules? I'd like to try this for https://github.com/NuGet/Home/issues/8456

**Comment by drewnoakes** [comment]
@devinvisible the linked PR https://github.com/dotnet/project-system/pull/1318 shows what @natidea was referring to.
