### ISSUE TITLE
Nuget Dependency Tree is lost after you close and reopen the project

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn-project-system#1295]
**Repro steps**
- Create a new .Net core Console application.
- Restore and build 
- Notice the dependency Tree load fine 
![image](https://cloud.githubusercontent.com/assets/12449387/22187524/02bd0654-e0bd-11e6-8fcf-097a8bbdcf0f.png)

- Close the solution and reopen again 
- Notice the dependency tree again .
![image](https://cloud.githubusercontent.com/assets/12449387/22187537/3b8f9082-e0bd-11e6-97ca-97de4ca9709c.png)

Build : 26121.5.d15prerel

**Comment by jinujoseph** [comment]
cc/ @abpiskunov is this related to #1320 ?

**Comment by abpiskunov** [comment]
no, doe snot look like that. Can you consistently repro that? If yes, could we look at your machine?
