### ISSUE TITLE
Cannot check "Check for arithmetic overflow/underflow"

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn-project-system#1304]
1. Choose Project Properties -> Build -> Advanced
2. Check "Check for arithmetic overflow/underflow"
3. Click OK

Expected: For the property to be saved and take affect
Actual: Nothing, the dialog does not close and stays open

**Comment by davkean** [comment]
Once you've changed it's value, you cannot close the dialog with "OK".

**Comment by basoundr** [comment]
This does not repro any more. 26216.1.d15rel build.

 Please reopen this issue if you still seeing this somehow.

**Comment by basoundr** [comment]
@davkean fyi
