### ISSUE TITLE
Get an error when you attempt to choose a strong name key

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn-project-system#1306]
1. File -> New Class Library (.NET Standard)
2. Choose **Properties** -> **Signing** 
3. Check **Sign the assembly**
4. Under "choose a strong name key file", drop the drop down

```
---------------------------
Microsoft Visual Studio
---------------------------
AssemblyOriginatorKeyFile:

Value cannot be null.

Parameter name: value
---------------------------
OK   
---------------------------
```

**Comment by davkean** [comment]
After you get this in state, you can't get out of it or close Visual Studio. It continues to display the error.

**Comment by mavasani** [comment]
Dupe of VSO 364884

**Comment by mavasani** [comment]
https://devdiv.visualstudio.com/DevDiv/_workitems?id=364884&_a=edit
