### ISSUE TITLE
Open properties for a file in Solution Explorer, opens a non-modal dialog with duplicate categories

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn-project-system#1313]
1. Right-click on a file and choose Properties

![image](https://cloud.githubusercontent.com/assets/1103906/22192994/b13fcae8-e18c-11e6-9ede-75ad3e0832d1.png)

![image](https://cloud.githubusercontent.com/assets/1103906/22192988/a9d123ce-e18c-11e6-9ad0-3271706a3162.png)

**Comment by abpiskunov** [comment]
Might be related to this https://github.com/dotnet/roslyn-project-system/issues/397 , since it seems that CPS by some reason opens that dialog in most cases instead of Browse Properties tool window.

**Comment by davkean** [comment]
Dupe of #397
