### ISSUE TITLE
Changing the build action of a C# file from "C# compiler" -> "None" fails

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn-project-system#1315]
1. Select a C# file
2. In Properties, change Build Action from "C# compiler" -> "None"

Expected: For this succeed
Actual: 

```
An error has occurred while saving the edited properties listed below:
	Build Action
One or more values are invalid. An internal error occurred. Please contact Microsoft Product Support Services.

```

**Comment by davkean** [comment]
Here's other strange repro's:

1. Select a C# file
2. Create a new folder called "Foo"
3. Change Build Action from "C# compiler" -> "Context"

Fails with the same thing. If you don't create a folder in 2, it doesn't fail.

**Comment by davkean** [comment]
https://github.com/dotnet/roslyn-project-system/issues/1044

**Comment by davkean** [comment]
Changing my mind about this being a dup - two different errors.

**Comment by RaulPerez1** [comment]
I can't repro this with the latest build.

**Comment by davkean** [comment]
Which build? This is prerel.

**Comment by RaulPerez1** [comment]
D15Rel 26124.0. I'll grab a machine with latest Prerel as well to double check.

**Comment by davkean** [comment]
I'm doing it now.
