### ISSUE TITLE
CodeLens does not see references from .NET Framework project to .NET Core project

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn-project-system#1323]
**Repro Steps**
•	create a framework console app (FrameworkConsoleApp3_2:   4.6.1);
•	Add a new standard class library project (StandardCL3_2: [netstandard1.4]), write the method to the class;
•	Add the reference from FrameworkConsoleApp3_2 to StandardCL3_2 successfully;
•	Call the class library method from FrameworkConsoleApp3_2 and save the program.cs;
•	Build the solution succeeded;

Notice the reference count is wrong.

![image](https://cloud.githubusercontent.com/assets/12449387/22229582/715ba0b8-e18d-11e6-962f-da86e46ba355.png)

**Comment by MiaomiaoHuangfu** [comment]
The issue is still repro on d15prerel.26125.4.

**Comment by mavasani** [comment]
I did some more testing around this:

1. This is not specific to CodeLens. For the above repro, even Find All References doesn't show these references.
2. This is not related to references across CPS based project and legacy project system based project. If I change the target framework for the CPS based project to be net45, everything works fine for FAR and CodeLens.

**Comment by mavasani** [comment]
On a clean box with today's d15prerel I see that this is indeed specific to methods - CodeLens and FAR both find the reference to the Class in legacy project system based netfx project, but doesn't find reference to method. Everything works fine if netfx project is CPS based.

**Comment by mavasani** [comment]
Tagging @CyrusNajmabadi 

Roslyn FindReferences functionaly is failing [here](http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces/FindSymbols/FindReferences/Finders/AbstractReferenceFinder.cs,190) when attempting to match method symbol from referenced and referencing project. I am going to move this issue to Roslyn and provide a repro project.

**Comment by mavasani** [comment]
Now tracked by https://github.com/dotnet/roslyn/issues/16827.
