### ISSUE TITLE
Duplicate and missing accelerators in localization

### ISSUE THREAD

**Issue by nguerrera** [dotnet/roslyn-project-system#1331]
This is a tracking issue for the following related issues filed internally on VSO

It seems that the accelerators were not preserved from previous releases in the translation recycling process.

* [368010](https://devdiv.visualstudio.com/DevDiv/_workitems?id=368010) [CHS] The ‘Default namespace’ & ‘Output type’ items have the same hot-key 'Alt + I' in Application page
* [368022](https://devdiv.visualstudio.com/DevDiv/_workitems?id=368022) [KOR] The ‘Neutral language’ option have no hot-key just have ‘(_)’ in Assembly Information dialog
* [368870](https://devdiv.visualstudio.com/DevDiv/_workitems?id=368870) [ESN] The ‘Output type’ & ‘Resource file’ items have the same hot-key: <Alt + S> in application page
* [368872](https://devdiv.visualstudio.com/DevDiv/_workitems?id=368872) [FRA] The ‘Output type’ & ‘Startup object’ items have the same hot-key: <Alt + O> in Application page
* [368875](https://devdiv.visualstudio.com/DevDiv/_workitems?id=368875) [ITA] The ‘Description’ and ‘Company’ option have the same hot-key: <ALT + S> in Assembly Information dialog
* [368881](https://devdiv.visualstudio.com/DevDiv/_workitems?id=368881) [PLK] The ‘Assembly version’ and ‘File version’ option have the same hot-key: <ALT + W> in Assembly Information dialog

@janbaltus

**Comment by lukaschal** [comment]
All HKs issue fixed.

**Comment by janbaltus** [comment]
fixed with PR https://github.com/dotnet/roslyn-project-system/pull/1336
