### ISSUE TITLE
"RuntimeIdentiifer must be set for .NETFramework executables"

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn-project-system#1333]
- Target net45 from a SDK-based Console App.

Get:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error		RuntimeIdentifier must be set for .NETFramework executables. Consider RuntimeIdentifier=win7-x86 or RuntimeIdentifier=win7-x64.	ConsoleApp95	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.RuntimeIdentifierInference.targets	49	
```

Why? I can target .NET Framework from a legacy project without needing anything here - why do I need one in this case?

**Comment by dsplaisted** [comment]
Closing this one in favor of dotnet/sdk#730, as this error is coming from the SDK

**Comment by srivatsn** [comment]
Which in turn was closed in favour of https://github.com/dotnet/sdk/issues/357
