### ISSUE TITLE
Broken integration test ProjectSystem_NetCore.xml

### ISSUE THREAD

**Issue by piotroko** [dotnet/roslyn-project-system#1344]
The test is reporting the following exception:

`System.IO.FileNotFoundException: The system cannot find the file specified. (Exception from HRESULT: 0x80070002)
14:07:00    at EnvDTE80.Solution2.GetProjectTemplate(String TemplateName, String Language)
14:07:00    at Roslyn.VSHosting.Test.AddProjectAction.GetProjectTemplatePath(Solution2 solution, String templateName, String language) in D:\j\workspace\vsie85c1a07\roslyn-internal\Closed\Hosting\Test\Actions\VisualStudio\AddProjectAction.cs:line 279
14:07:00    at Roslyn.VSHosting.Test.AddProjectAction.AddProject(TaoEngine engine) in D:\j\workspace\vsie85c1a07\roslyn-internal\Closed\Hosting\Test\Actions\VisualStudio\AddProjectAction.cs:line 186
14:07:00    at Roslyn.VSHosting.Test.AddProjectAction.Execute(TaoEngine engine) in D:\j\workspace\vsie85c1a07\roslyn-internal\Closed\Hosting\Test\Actions\VisualStudio\AddProjectAction.cs:line 92
14:07:00    at Tao.Engine.DebuggableActionExecutor.Execute()
14:07:00    at `Tao.Engine.DefaultActionExecutor.Execute()`

**Comment by johnbeisner** [comment]
Merge pull request #1614 from johnbeisner/master

**Comment by johnbeisner** [comment]
Merge pull request 1596 from johnbeisner/VSI-Issue1344 to dotnet/Roslyn-Internal
