### ISSUE TITLE
Property Page resets values of settings after being opened once

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn-project-system#1347]
Repro Steps:
1. Create a new project
2. Open the Project Properties, check optimize on the build settings page. Save.
3. Close the properties page.
4. Open the csproj and remove the optimize line. Save.

**Expected**:
Optimize is reset to false in both the project properties and properties page, project is not considered dirty.

**Actual**:
Optimize box is still checked in the project properties, and still set to true in the properties page. Project is considered dirty. If you close and reopen the solution, optimize is false as expected.

Related to https://github.com/dotnet/roslyn-project-system/issues/1245. /cc @davkean

**Comment by 333fred** [comment]
When you do close the solution, the dirty popup will appear. As far as I can tell, saving does nothing, and the removal of the optimize line is correctly handled.

**Comment by 333fred** [comment]
Also, this is written about the optimize property, but it applies generally.

**Comment by davkean** [comment]
Ugh, I can't imagine what this is.

**Comment by davkean** [comment]
This smells similar: https://github.com/dotnet/roslyn-project-system/issues/1348, but I have to have the editor open for the repro to occur.

**Comment by 333fred** [comment]
@adrianvmsft, this does seem very similar to #1348. I've debugged through the property pages, and it does appear that the underlying property page is returning `true` as the value of the property I've been testing with (Optimize), even though the project file does not have the value set, and the default is false.

**Comment by davkean** [comment]
Where did we land with this? I've confirmed that #1348 is fixed, but I'm still running into this.

**Comment by 333fred** [comment]
@davkean, it does look like a different issue. What I'm seeing is that the value of the property the page is retrieving really is incorrect, but I've been looking at a few other issues and haven't followed up more on this one.
