### ISSUE TITLE
Certain changes to the project are not getting represented in the editor

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn-project-system#1348]
1. Create new Console App
2. Right-click Edit
3. Select Program.cs, change Build Action -> Content

Expected: For the content in the Editor to be updated with:

``` XML
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp1.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Program.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Program.cs" />
  </ItemGroup>

</Project>
``` 
Actual: Contents in the editor don't change and stay as:

``` XML
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp1.0</TargetFramework>
  </PropertyGroup>

</Project>
```

If I save the project file within the actual editor, the contents of the edited file update to reflect the "Expected" and I get the following prompt. Clicking Overwrite or Ignore doesn't cause the editor content's to change.

![image](https://cloud.githubusercontent.com/assets/1103906/22358979/7d3015ce-e497-11e6-9cf4-d97d4a527924.png)

**Comment by 333fred** [comment]
Interesting wrinkle to the repro: if I click on the project node and save, the csproj is updated as expected with no prompt. If I then change the content type back to `C# Compiler`, the project file is updated with no prompt, without having to save anything. @jviau @adrianvmsft, it seems like `UnconfiguredProjectAdvanced.ChangingProjectFile` isn't triggered for some property changes? And when the project is reloading, some seem overwrite the content of the project file? For the original repro scenario, I'd expect the reloaded project's properties to override the `Content` setting, but that doesn't seem to be what's happening here.

**Comment by 333fred** [comment]
Instead, the `Content` setting seems be delayed in being written back out to the project file.

**Comment by 333fred** [comment]
This is a CPS bug, converting this to tracking. https://devdiv.visualstudio.com/DevDiv/_workitems?id=376669&fullScreen=false&_a=edit

**Comment by 333fred** [comment]
CPS has committed a fix, insertion PR here: https://devdiv.visualstudio.com/DevDiv/VS%20IDE%20CPS/_git/VS/pullrequest/55285?_a=overview.

**Comment by davkean** [comment]
This looks fixed, but I'm seeing other weirdness that I'm filing.
