### ISSUE TITLE
Test projects do not get the test project icon

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn-project-system#1361]
I've been used to scanning along the row of icons to pick out the test projects in a long list of similarly-named projects. With the new .csproj format there is nothing marking the project as a test project.

Could you either:

 * Change the icon when tests are first discovered and cache the fact that it's a test project so that on subsequent opening of the project it's immediately assumed to still be a test project. When dependencies change it could be invalidated. It could also be driven off dependencies to testing frameworks maybe.

Or

 * Provide some attribute to specify which projects are intended to be run as tests.
  I strongly prefer this option because it's possible to have a project that references a testing framework or even contains tests which should not be treated as a test assembly and tests (if any) should not be discovered.

   For example, if I'm building an extension or utility library to extend a testing framework, I'll need to reference the testing framework but it's still not a test library and shouldn't get the icon.

   For another example, if you're developing a testing framework or an extension or a utility library, it's common to have a mock test assembly which references the testing framework and contains discoverable tests, but which the IDE should not discover because those mock tests are intended to fail and timeout, etc. The mock tests are used when some real tests (in an _actual_ test project which the IDE _should_ discover) point the testing framework at the mock tests to verify that certain failures are reported and certain successes are reported, timeouts are handled, and so on.

**Comment by davkean** [comment]
This issue was moved to Microsoft/vstest#394
