### ISSUE TITLE
Project Migration in RC3 results in build errors depending on win versions of net core app

### ISSUE THREAD

**Issue by julielerman** [dotnet/roslyn-project-system#1363]
I have a solution from VS2015 with 4 projects in it. These targetted .net core and had project.json files

I have tested VS2017 RC migrating this solution in previous version of the RC. This problem never showed before.

# The solution to test with
I've pushed the VS2015 version of the solution to github here: [https://github.com/julielerman/NetCoreSolutionToMigrateToVS2017](url)

# My environment

Visual Studio Enterprise 2017 RC version 15.0.26127.0

dotnet
  Version  : 1.1.0
  Build    : 928f77c4bc3f49d892459992fb6e1d5542cb5e86

dotnet --version
1.0.0-rc3-004530

This is on an Azure VM.
Windows 10 Enterprise N
Version 1607
OS Build 14393.693

# Description of the problem
Two of the projects are class libraries that targeted net standard 1.6.1.
One project was an ASP.NET Core Web API targetting .NET Core App 1.0
The last project is a test project also targeting .NET Core App 1.0

After the migration (successful) in VS, there were 4 errors for each of those two projects. The erros themselves did not indicate which project was throwing the error.

-----------------------------------------
# Update
After a lot of experiments, I've narrowed the problem down to this test project. Here is the csproj

```XML
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp1.0</TargetFramework>
    <AssemblyName>SamuraiTests</AssemblyName>
    <PackageId>SamuraiTests</PackageId>
    <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
    <PackageTargetFallback>$(PackageTargetFallback);dnxcore50</PackageTargetFallback>
    <GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
    <GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
    <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.0.0-preview-20170106-08" />
    <PackageReference Include="MSTest.TestAdapter" Version="1.1.8-rc" />
    <!--<PackageReference Include="Microsoft.NETCore.App" Version="1.1.0" />-->
    <PackageReference Include="SamuraiAppCore.Data" Version="2.0.0-*" />
    <PackageReference Include="SamuraiAppCore.Domain" Version="2.0.0-*" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="1.1.0" />
    <PackageReference Include="MSTest.TestFramework" Version="1.0.8-rc" />
  </ItemGroup>
</Project>
```

If I remove the package refs to my class libraries (Data & Domain) the errors go away. But note that in my ASP.NET Core Web API project, the references to the Data and Domain are still in place. So it's something about the test project. I did not have this problem migrating this exact same solution with earlier version of VS2017 RC.
# End of Update

Unable to resolve [project name & version] for .NETCoreApp, Version=v.1.0 (win-x64)
Unable to resolve [project name & version] for .NETCoreApp, Version=v.1.0 (win)
Unable to resolve [project name & version] for .NETCoreApp, Version=v.1.0 (win-x86)
Unable to resolve [project name & version] for .NETCoreApp, Version=v.1.0 

Here is the project.json for one of those projects:

```JSON
{
    "version": "2.0.0-*",

    "dependencies": {
        "Microsoft.EntityFrameworkCore.SqlServer": "1.1.0",
        "NETStandard.Library": "1.6.1",
        "SamuraiAppCore.Domain": "2.0.0-*"
    },

    "frameworks": {
        "netstandard1.6": {
            "imports": "dnxcore50"
        }
    },
    "tools": {
        "Microsoft.EntityFrameworkCore.Tools.DotNet": "1.1.0-preview4"
    }

}
```

Here is the csproj for that project after it was migrated:

```XML
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <VersionPrefix>2.0.0</VersionPrefix>
    <TargetFramework>netstandard1.6</TargetFramework>
    <AssemblyName>SamuraiAppCore.Data</AssemblyName>
    <PackageId>SamuraiAppCore.Data</PackageId>
    <PackageTargetFallback>$(PackageTargetFallback);dnxcore50</PackageTargetFallback>
    <GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
    <GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
    <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\SamuraiAppCore.Domain\SamuraiAppCore.Domain.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="1.1.0" />
    <PackageReference Include="NETStandard.Library" Version="1.6.1" />
  </ItemGroup>
  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="1.1.0-preview4" />
  </ItemGroup>
</Project>
```

The other two projects both have references to the netstandard projects. These project both originally had refs to Microsoft.NETCoreApp. 

I've done a variety of experiments to see if I can make this problem go away. I also added a new web application to the solution and had it reference one of my netstandard class libraries. It did not add any more of the "unable to resolve" errors. I noticed that its target framework was netcoreapp1.1. I changed my original web api project from netcoreapp1.0 to netcoreapp1.1 but there was no change.

**Comment by livarcocc** [comment]
@julielerman you must have permissions set in the repo, because I can't access it. I get a 404. Also, I suspect that this happens because you have NETStandard.Library 1.6.1, which is the equivalent on Microsoft.NETCore.App 1.1.

I imagine that if you have a library targeting netstandard.library 1.6.1, your consuming app needs to be netcoreapp1.1, or you need a packagetargetfallback.

If you can give me persmissions to the repo, I can try some of these things out and report back.

**Comment by julielerman** [comment]
oh ... I guess a typo. I don't have an private repos.
Go to my github.com/julielerman account. It's the newest repo. Here's another attempt at a direct link: https://github.com/julielerman/NetCoreSolutionToMigrateToVS2017

changing the test project to 1.1
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp1.1</TargetFramework>

didn't have an impact. And the sad part is that I migrated this solution a number of times in earlier versions of VS2017RC with no issues so defiitely confused. Thanks for looking!

**Comment by livarcocc** [comment]
Everything seems to be working for me. I omitted the restore output because it is big.

```
 14:39:55  ~/Documents/git/NetCoreSolutionToMigrateToVS2017   master ✘ ✖ ✹ ✭ 
$ cd SamuraiTests

 14:40:00  ~/Documents/git/NetCoreSolutionToMigrateToVS2017/SamuraiTests   master ✘ ✖ ✹ ✭ 
$ dotnet build
Microsoft (R) Build Engine version 15.1.539.38876
Copyright (C) Microsoft Corporation. All rights reserved.

  SamuraiAppCore.Domain -> /Documents/git/NetCoreSolutionToMigrateToVS2017/src/SamuraiAppCore.Domain/bin/Debug/netstandard1.6/SamuraiAppCore.Domain.dll
  SamuraiAppCore.Data -> /Documents/git/NetCoreSolutionToMigrateToVS2017/src/SamuraiAppCore.Data/bin/Debug/netstandard1.6/SamuraiAppCore.Data.dll
  SamuraiTests -> /Documents/git/NetCoreSolutionToMigrateToVS2017/SamuraiTests/bin/Debug/netcoreapp1.0/SamuraiTests.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:07.20

 14:40:11  ~/Documents/git/NetCoreSolutionToMigrateToVS2017/SamuraiTests   master ✘ ✖ ✹ ✭ 
$ dotnet test
Build started, please wait...
Build completed.

Test run for /Documents/git/NetCoreSolutionToMigrateToVS2017/SamuraiTests/bin/Debug/netcoreapp1.0/SamuraiTests.dll(.NETCoreApp,Version=v1.0)
Microsoft (R) Test Execution Command Line Tool Version 15.0.0.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
Passed   SamuraiTests.SamuraiModelTests.TwoPlusTwoEqualsFour
Passed   SamuraiTests.SamuraiModelTests.CanRetrieveListOfSamuraiValues
Passed   SamuraiTests.SamuraiModelTests.CanRetrieveAllSamuraiValuePairs
Passed   SamuraiTests.SamuraiModelTests.CanLoadQuotesAndIdentityForASamurai

Total tests: 4. Passed: 4. Failed: 0. Skipped: 0.
Test Run Successful.
Test execution time: 2.8638 Seconds
```

**Comment by livarcocc** [comment]
All I did was run dotnet migrate at the root of the repo, followed by dotnet restore. Then cd into SamuraiTests. Dotnet build and then dotnet test.

**Comment by julielerman** [comment]
what the .... ?? ;)
Okay but I did not run dotnet migrate.
I opened VS2017RC3 and opened the solution.
Do you get the same results? I will start from scratch ...again.

**Comment by julielerman** [comment]
downloaded the zip from my repo. Extracted it. Opened VS2017RC3. File open solution...same results as before:
![image](https://cloud.githubusercontent.com/assets/5007120/22408681/cc491c82-e64a-11e6-8a64-770263102f4d.png)

**Comment by livarcocc** [comment]
It is possible that you are hitting some issue that has already been fixed in the CLI but the version of VS2017 that you are using does not have that new CLI yet.

Would you mind downloading the CLI from github.com/dotnet/cli and running dotnet migrate from the command line?

**Comment by julielerman** [comment]
I wanted to compare apples to apples so I started with the CLI currently installed which is rc3-004530.
Migrate was fine.
Everything restored and built.
dotnet test passed
So that was the same solution, the same CLI but the problem is only showing up in VS2017.

I'm now downloading 004707 and will see if that makes a difference in VS2017. Might not get back to you until later.

**Comment by julielerman** [comment]
oh, this isn't going well! :) I tried to install the latest sdk installer (windows 64 bit). It kept failing saying that .net core was alerady installed and I had to uninstall via "remove programs". I've never had that happen before. There were 3 different versions. I installed the latest, and tried the instlaler. Same. Ended up uninstalling all versions of .net core and still the installer says "it's already instealleld"  Pretty sure it's all gone now since dotnet --version just returns dotnet help. It's just a VM I created for this test so I'm not worried...but ...uggh. I can't verify that the latest sdk fixes the problem that seems to be particular to VS2017RC3.

**Comment by 333fred** [comment]
@livarcocc, migrating just the `SamuraiTests` project is producing different output when migrated separately. If I migrate from opening VS, and then fix up the SamuraiTests csproj, everything appears to work correctly. In the single migration scenario, the references to `SamuraiAppCore.*` are added as package references, and in solution migration from CLI, they're added as project references. Here's the diff:
```
+  <ItemGroup>
+    <ProjectReference Include="..\src\SamuraiAppCore.Data\SamuraiAppCore.Data.csproj" />
+    <ProjectReference Include="..\src\SamuraiAppCore.Domain\SamuraiAppCore.Domain.csproj" />
+  </ItemGroup>
   <ItemGroup>
     <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.0.0-preview-20170106-08" />
     <PackageReference Include="MSTest.TestAdapter" Version="1.1.8-rc" />
     <PackageReference Include="Microsoft.NETCore.App" Version="1.1.0" />
-    <PackageReference Include="SamuraiAppCore.Data" Version="2.0.0-*" />
-    <PackageReference Include="SamuraiAppCore.Domain" Version="2.0.0-*" />
     <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="1.1.0" />
     <PackageReference Include="MSTest.TestFramework" Version="1.0.8-rc" />
   </ItemGroup>
```

**Comment by livarcocc** [comment]
Which version of the CLI did you use. I tried it with `dotnet migrate -s` on the SamuraiTests project and this is what I got:

```
cat SamuraiTests.csproj
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp1.0</TargetFramework>
    <AssemblyName>SamuraiTests</AssemblyName>
    <PackageId>SamuraiTests</PackageId>
    <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
    <RuntimeFrameworkVersion>1.1.0</RuntimeFrameworkVersion>
    <PackageTargetFallback>$(PackageTargetFallback);dnxcore50</PackageTargetFallback>
    <GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
    <GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
    <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../src/SamuraiAppCore.Data/SamuraiAppCore.Data.csproj" />
    <ProjectReference Include="../src/SamuraiAppCore.Domain/SamuraiAppCore.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.0.0-preview-20170106-08" />
    <PackageReference Include="MSTest.TestAdapter" Version="1.1.8-rc" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="1.1.0" />
    <PackageReference Include="MSTest.TestFramework" Version="1.0.8-rc" />
  </ItemGroup>

</Project>
```

My version of the CLI is 
```
dotnet --info
.NET Command Line Tools (1.0.0-rc4-004721)

Product Information:
 Version:            1.0.0-rc4-004721
 Commit SHA-1 hash:  d499639b14
```

**Comment by 333fred** [comment]
On my home computer, with the official RC3 build.

```
 dotnet --info
.NET Command Line Tools (1.0.0-rc3-004530)

Product Information:
 Version:            1.0.0-rc3-004530
 Commit SHA-1 hash:  0de3338607

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0-rc3-004530
```

**Comment by 333fred** [comment]
So this issue might already be fixed in master.

**Comment by julielerman** [comment]
oh! I didn't catch that I was getting my project refs as package refs! (rolls eyes). You can see it in the update  I made to the original posting. Also, curious why as a project ref it doesn't have the version. Is that intentional?

Thanks so much for pursuing it.

Also, I was never able to install the sdk package I downloaded even after uninstalling every other version of the SDK. This might be something to test with new bits (install VS2017RC, then try to install the latest sdk package on top of it). I literally have no tools on my machine now. Id this known or should I create a new issue?

**Comment by srivatsn** [comment]
For the CLI installer issue, please log a new issue in https://github.com/dotnet/cli

Closing this bug as fixed

**Comment by julielerman** [comment]
@srivatsn filed the issue: https://github.com/dotnet/cli/issues/5531
