### ISSUE TITLE
VS 2017 RC3 Solution Explorer file nesting not persisting

### ISSUE THREAD

**Issue by scottaddie** [dotnet/roslyn-project-system#1366]
Here are the steps to reproduce in VS 2017 RC3 (15.0.26127.0 D15REL):
1. Clone the following repo: https://github.com/scottaddie/TagHelpersDemo. This is an ASP.NET Core MVC project targeting .NET Core.
2. Open the solution in VS, right-click the project in Solution Explorer, and choose **Edit TagHelpersDemo.csproj** from the context menu.
3. Remove the **Compile** node (provided below) from the project file's **ItemGroup**, and save the f
```xml
<Compile Update="Views\Shared\Partials\CardViewModel.cs" DependentUpon="Views\Shared\Partials\_Card.cshtml" />
```
4. Add this **Compile** node back into the **ItemGroup**, and save the file. Notice that the **CardViewModel.cs** file is properly nested beneath **_Card.cshtml** in Solution Explorer.
5. Close the solution, and then reopen it in VS. Notice that the file nesting is no longer present in Solution Explorer.

**Comment by abpiskunov** [comment]
@lifengl

**Comment by srivatsn** [comment]
The file nesting is implemented in the web tools extension. So moving to the web tools repo.

**Comment by srivatsn** [comment]
This issue was moved to aspnet/Tooling#981

**Comment by abpiskunov** [comment]
No no - @srivatsn  that is not the case here :), thats i added Lifeng here - this is what creates a proble, <Compile Update="Views\Shared\Partials\CardViewModel.cs" DependentUpon="Views\Shared\Partials\_Card.cshtml" /> , this is either something new in CPS or again same issue with circular nestings , which CPS needs to handle.

**Comment by abpiskunov** [comment]
`<Compile Update="Views\Shared\Partials\CardViewModel.cs" DependentUpon="Views\Shared\Partials\_Card.cshtml" />`
