### ISSUE TITLE
"Cannot access a disposed object." Object name: 'Microsoft.VisualStudio.ProjectSystem.ProjectCapabilitiesScope

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn-project-system#1373]
From: https://developercommunity.visualstudio.com/content/problem/13674/cannot-access-disposed-object.html.

1. Created a new ASP .Net Core Application (version 1.1)
a. Decide on some data you want your app to track in a database and create a class that represents the data
a. Note: the class must have an Id attribute
b. Add a " MVC Controller with view, using Entity Framework" that will represent the view for working with this data collection to the project. In the creation dialog:
a. For the "Model class:" field choose the class you defined in step 1 from the dropdown
b. For the "Data context class:" field, choose the only entry in the list
c. Go to Tools -> Package Manager Console and type
a. add-migration <name of your class> [Enter]
b. update-database [Enter]
2. Then added a unit test project ( .NET Core | Unit Test Project (.NET Core) )
3. Built the solution.
4. Closed the soltion and got the below error

Then added a unit test project ( .NET Core | Unit Test Project (.NET Core) )

Built the solution.

Closed the soltion and got the below error:
"Cannot access a disposed object. Object name: 'Microsoft.VisualStudio.ProjectSystem.ProjectCapabilitiesScope'"

**Comment by davkean** [comment]
I ran into a similar thing while debugging, though this did not bring down VS, it was handled somewhere down the stack, repro (you need to be attached with first-change exceptions turned on):

1. Create a new .NET Core app
2. Right-click Edit ConsoleApp1.csproj
3. Delete the Sdk attribute and it's contents
4. Save

ObjectDisposedException:

```
 	Microsoft.VisualStudio.Validation.dll!Microsoft.Verify.NotDisposed(Microsoft.IDisposableObservable disposedValue, string message)	Unknown
 	Microsoft.VisualStudio.ProjectSystem.dll!Microsoft.VisualStudio.ProjectSystem.OnceInitializedOnceDisposed.EnsureInitialized(bool allowInitializing)	Unknown
 	Microsoft.VisualStudio.ProjectSystem.dll!Microsoft.VisualStudio.ProjectSystem.ProjectCapabilitiesScopeBase.Current.get()	Unknown
 	Microsoft.VisualStudio.ProjectSystem.dll!Microsoft.VisualStudio.ProjectSystem.CapabilitiesExtensions.GetEffectiveCapabilitiesSnapshot(Microsoft.VisualStudio.ProjectSystem.IProjectCapabilitiesScope capabilitiesScope)	Unknown
 	Microsoft.VisualStudio.ProjectSystem.dll!Microsoft.VisualStudio.ProjectSystem.OrderPrecedenceImportCollection<Microsoft.VisualStudio.ProjectSystem.VS.Tree.Dependencies.IProjectDependenciesSubTreeProvider, Microsoft.VisualStudio.ProjectSystem.IOrderPrecedenceMetadataView>.GetFilteredSnapshot()	Unknown
 	Microsoft.VisualStudio.ProjectSystem.dll!Microsoft.VisualStudio.ProjectSystem.OrderPrecedenceImportCollection<Microsoft.VisualStudio.ProjectSystem.VS.Tree.Dependencies.IProjectDependenciesSubTreeProvider, Microsoft.VisualStudio.ProjectSystem.IOrderPrecedenceMetadataView>.GetEnumerator()	Unknown
>	Microsoft.VisualStudio.ProjectSystem.Managed.VS.dll!Microsoft.VisualStudio.ProjectSystem.VS.Tree.Dependencies.DependenciesProjectTreeProvider.Dispose(bool disposing) Line 319	C#
 	Microsoft.VisualStudio.ProjectSystem.dll!Microsoft.VisualStudio.ProjectSystem.OnceInitializedOnceDisposed.DisposeAsync.AnonymousMethod__17_0()	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task.InnerInvoke()	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task.Execute()	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task.ExecutionContextCallback(object obj)	Unknown
 	mscorlib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)	Unknown
 	mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task.ExecuteWithThreadLocal(ref System.Threading.Tasks.Task currentTaskSlot)	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task.ExecuteEntry(bool bPreventDoubleExecution)	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()	Unknown
 	mscorlib.dll!System.Threading.ThreadPoolWorkQueue.Dispatch()	Unknown
 	mscorlib.dll!System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()	Unknown
 	[Native to Managed Transition]	
 	kernel32.dll!759962c4()	Unknown
 	[Frames below may be incorrect and/or missing, no symbols loaded for kernel32.dll]	
 	ntdll.dll!77d20fd9()	Unknown
 	ntdll.dll!77d20fa4()	Unknown

```

in this line:
``` C#
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                foreach (var provider in SubTreeProviders) <-- ObjectDisposedException
                {
                    provider.Value.DependenciesChanged -= OnDependenciesChanged;
                }

                ProjectContextUnloaded?.Invoke(this, new ProjectContextEventArgs(this));
            }

            base.Dispose(disposing);
        }
```

I'm unsure if this related.

**Comment by davkean** [comment]
It looks like @abpiskunov added a catch block here in a unrelated chagne - but instead we should avoid touching these components in Dispose, there's no guarantee around MEF dispose order (this is not a CPS thing).

**Comment by abpiskunov** [comment]
There is related TFS bug 393230

**Comment by abpiskunov** [comment]
@davkean i am fixing dependencies excpetion in the attached PR , however original issue opened here was not for dependencies, so i will keep it open for you to close when you ready...

**Comment by davkean** [comment]
How do you know this wasn't for dependencies?

**Comment by abpiskunov** [comment]
i don't know , there no stack trace, thats why i can not say if it is in Dependencies. We could close it when PR complete and reopen if someone see ObjectDisposed again somewhere else if you like that.

**Comment by davkean** [comment]
Yeah, I would dupe it for now.

**Comment by davkean** [comment]
This has been resolved.
