### ISSUE TITLE
VS2017 RC3 not compiling netstandard1.2;netcoreapp1.0

### ISSUE THREAD

**Issue by roryprimrose** [dotnet/roslyn-project-system#1385]
I have updated to VS2017 RC3 26127.0, created a new .core library project and set the following configuration:
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>netstandard1.2;netcoreapp1.0</TargetFrameworks>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
</Project>
```
The project shows a warning on the NetStandard.Library (1.6.1) reference and compiling this project fails.

![image](https://cloud.githubusercontent.com/assets/2044291/22454196/4c269694-e7d8-11e6-8c9e-a7c2919d6f34.png)

Project is at 
[ClassLibrary1.zip](https://github.com/dotnet/roslyn-project-system/files/741221/ClassLibrary1.zip)

**Comment by niemyjski** [comment]
Any reason why you'd be targetting your app as both netstandard and netcoreapp1.0? I have a test project that has tests but is also a reference and I'm running into issues where my tests aren't discovered. Which makes me think I need to do something like this but it doesn't make sense to build both.

**Comment by roryprimrose** [comment]
I was wanting to cover netstandard1.2 to include support for 4.5.2 and then netcoreapp1.0 to cover 4.6.2 and netcore. I was using the table at http://andrewlock.net/understanding-net-core-netstandard-and-asp-net-core/#netstandardanevolutionofpcls as the reference point.

That is the long answer. The short one is that I don't know what I'm doing :)

**Comment by niemyjski** [comment]
You should just have to do `netcoreapp1.0;net452`

**Comment by roryprimrose** [comment]
Is there a reason that I can't target netstandard? Is this not allowed/supported? For example, what if I wanted my library to support Windows Phone 8.1, net452 and netcoreapp1.0. Isn't that what netstandard1.2 is for?

The solution now compiles, but the package creation only includes the netcoreapp1.0 package while the build output directory contains both netcoreapp1.0 and netstandard1.2. Am I missing a config that defines which versions go in the package?

**Comment by niemyjski** [comment]
Yes, please read this (http://stackoverflow.com/questions/36962930/whats-the-difference-between-the-new-netstandardapp-and-netcoreapp-tfms) I believe for the test runners to pick up different runtimes you need to specify the correct host. netcoreapp is the correct runtime host for net standard

**Comment by roryprimrose** [comment]
It would be really handy if Visual Studio would validate the target frameworks and throw a build error if any of them are not correct. Without this people are just shooting in the dark to resolve their issues.

**Comment by davkean** [comment]
@roryprimrose Yeah, we've got a bunch of issues over on https://github.com/dotnet/sdk/ about providing better errors around invalid TFMs.
