### ISSUE TITLE
Project System: NuGet dependencies in project tree

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn-project-system#139]
_From @davkean on January 14, 2016 21:7_

Tracking the work required to show NuGet dependencies in the visual tree.

- [x] Port CPS's reference node
- [x] Merge in XProj's reference node code, but sit it on top of the existing data coming from the ResolveNuGetPackageAssets target (You'll need a new rule, say "ResolvedPackage" to represent it)
- [x] Add a target that raises project.lock.json as MSBuild "package container" items
- [x] Change ResolveNuGetPackageAssets to consume the package container data from above
- [x] Change reference node to consume said data from the design-time

_Copied from original issue: dotnet/roslyn#7962_

**Comment by davkean** [comment]
This currently will be problematic without a feature from CPS; NuGet dependencies can be deep - if we were to do this via a CPS virtual tree, CPS will want to realize the entire tree up-front, which will be extremely expensive. We'll want delay loaded trees here; xproj ran into something similar.

**Comment by davkean** [comment]
See also:
https://github.com/dotnet/roslyn/issues/10975
https://github.com/dotnet/roslyn/issues/10974
https://github.com/dotnet/roslyn/issues/10973

**Comment by sayedihashimi** [comment]
Should be assigned to @abpiskunov

**Comment by davkean** [comment]
@abpiskunov I've updated above with what we discussed today.
