### ISSUE TITLE
Launch settings sometimes fail to load with the error "The value factory has called for the value on the same instance."

### ISSUE THREAD

**Issue by BillHiebert** [dotnet/roslyn-project-system#1395]
1. Create new asp.net core web application
Occasionally, the debug dropdown with say "Start" instead of listing the profiles from launchsettings.json. 

This is an intermittent problem where attempting to read a property value from a dataflow callback can sometimes lead to an Invalid Operation Exception. When this occurs the launch settings, create an temporary "error" profile which is what shows up in the dropdown. 

From discussions this with the project system team this is caused by state leaking through the dataflow and affecting the AsyncLazy class.

**Comment by srivatsn** [comment]
Fixed by #1396
