### ISSUE TITLE
Migration fails when solution and project file are in the same directory

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn-project-system#1399]
We assume that the backup folder will not be put in the same directory as a project.json/.xproj project. However, for solutions where the solution file and project file are in the same directory, this doesn't hold true, and causes migration failure. We ask CLI to migrate the directory, and since we've already backed up the project.json/xproj, it will find and migrate two projects. This in turn breaks invariants, and causes silent failures.

**Comment by 333fred** [comment]
Fixed with https://github.com/dotnet/roslyn-project-system/pull/1400.

**Comment by jinujoseph** [comment]
can you check if that alaos fixes the case when the project is associated with multiple sln \\mlangfs1\public\Jinuj\IPA\Multisln , open Multisln\ClassLibrary2\src\ClassLibrary1\ClassLibrary1.xproj
