### ISSUE TITLE
[Data loss] Undo in the editor after the project has been saved does not dirty the project

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn-project-system#1401]
1. File -> New Console App (.NET Core)
2. Right-click Edit
3. Select Program.cs, change Build Action -> Content
4. Save the project
5. In the editor, CTRL+Z to undo the changes
6. Close the Solution

Expected: For to be prompted to save changes
Actual: Not prompted to save changes

Not sure what the expectation here is around the Undo stack - should these changes appear in it?

**Comment by davkean** [comment]
tag @333fred

**Comment by 333fred** [comment]
Hmm, I'd have expected https://github.com/dotnet/roslyn-project-system/blob/master/src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Editor/TempFileTextBufferManager.cs#L113 to reset the reiterated version number. I'll look into this.

**Comment by davkean** [comment]
Should these show up in the undo stack?

**Comment by davkean** [comment]
@srivatsn Put this in 1.0, tell if me if you disagree.

**Comment by 333fred** [comment]
I think so; that you can CTRL+Z doesn't surprise me. That it doesn't register the buffer as changed when you does.

**Comment by 333fred** [comment]
Where my feelings here are what I think a customer would expect, not necessarily how we expect the internals of VS to work.

**Comment by 333fred** [comment]
I stepped though this offline with David Pugh, and we're both confused as to why this behavior is occurring. @srivatsn, if you think this is RTM-worthy, I'll pick up investigation tomorrow.

**Comment by srivatsn** [comment]
Ya let's investigate.

**Comment by 333fred** [comment]
Figured this out: https://github.com/dotnet/roslyn-project-system/blob/master/src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Editor/TempFileTextBufferManager.cs#L117. I'm resetting the state flags to what they were originally. I need to get the new state flags and reset just the readonly flag.
