### ISSUE TITLE
"Framework" package is duplicated under NuGet and SDK nodes

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn-project-system#1405]
Build: 26131.0.D15Rel

![image](https://cloud.githubusercontent.com/assets/1103906/22493311/8e54e862-e883-11e6-9ee5-792735cc4c34.png)

**Comment by srivatsn** [comment]
Can you paste in your csproj? I just tried a netstandard library from the template and I don't see the dupe. Same build.

**Comment by srivatsn** [comment]
Also I see in the screen that the node under the SDK is not expandable. Sounds like another dataflow issue that may get fixed by https://github.com/dotnet/roslyn-project-system/pull/1392? @abpiskunov

**Comment by davkean** [comment]
Oh weird, yeah, I can't repro this now - and the node is expandable. I was hit this all new projects, nothing custom.

**Comment by abpiskunov** [comment]
hm that can happen if sdk changes were in, but matching project system changes are not in. Did you end up there by running your dev version of VS or actual installed VS ? If it was dev version, did you sync it with master at that time? If not - that would what i expect :). i see it on my other machine.

**Comment by davkean** [comment]
This was yesterday's build 26131.0 D15REL build, though I cannot repro it.

**Comment by abpiskunov** [comment]
i can not see it either ..

**Comment by abpiskunov** [comment]
So what are we doing with this one? I suggest closing it since it was probably a bits mismatch. If we see it again , will reopen.
