### ISSUE TITLE
Create a new Resource (resx) file an error occurs

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn-project-system#1409]
This bug is created from customer feedback https://developercommunity.visualstudio.com/content/problem/15297/when-creating-new-resource-resx-file-error-occurs.html

When I create a new Resource file, I get following error: "Custom tool ResXFileCodeGenerator failed to produce an output for input file ... but did not log a specific error.". Project is ASP.NET Core on .NET Framework

**Comment by davkean** [comment]
This looks to occur when when RESX generator returns a null output, which it does apparently when it encounters an error.

I can't repro this. Ask the customer for more info.

**Comment by Ponant** [comment]
@davkean, I had this issue several times, so I can certainly confirm it occurs. I made the test on
1) A VS 2017 RC that has been updated successively for each release
2) A fresh new VS 2017 RC (latest as of today) on a new windows 10 Pro.

This is with .Net Core 1.1 projects. There are two kinds of bugs that are frequent for resx's with VS 2017 RC.
1) The one described here and which I often get if I copy paste the whole solution directory and launch the new copied solution. Adding a new resx gives the message you report. In addition, if you double click on the resx you obtain 

![this](https://cloud.githubusercontent.com/assets/19961806/22818562/2951dcd0-ef6e-11e6-8ef7-33a718a70e91.PNG)

2) Rename a resx file from Solution explorer and you have this
![res2](https://cloud.githubusercontent.com/assets/19961806/22818627/7acc3d8a-ef6e-11e6-937f-52eabad3ac36.PNG)

Renaming it again solves 2, but this error message keeps popping up.

**Comment by davkean** [comment]
@Ponant Can you share me the solution?

**Comment by Ponant** [comment]
@davkean , my project is fairly big, so I would rather make a new one and send it to you; jus give me some time and I will come back.

**Comment by Ponant** [comment]
BTW , it is .Net core (.Net 4.6.1)

**Comment by davkean** [comment]
@Ponant A repro project or specific repro steps would be great. Thanks!

**Comment by Ponant** [comment]
I just made it.
1) Console App Core (4.6.1)
2) No update for Nuget
3) Right click Solution explorer-->new Item-->resource file, name and create

Output:
1) "Custom tool ResXFileCodeGenerator failed to produce an output for input file ... but did not log a specific error.". Project is ASP.NET Core on .NET 

2) Rename the file and you get my second pic above

I have to leave in a few minutes so I am not sure I can send it up, let me know if you can repro

**Comment by Ponant** [comment]
It seems to be with only a webapp template (empty is enough)

**Comment by Ponant** [comment]
@davkean 
https://github.com/Ponant/ResxBugVS2017RC

**Comment by davkean** [comment]
Thanks!

**Comment by Ponant** [comment]
could you reproduce? cheers!

**Comment by davkean** [comment]
I haven't tried yet, won't be able to look at this until next week.

**Comment by davkean** [comment]
@Ponant Does your project look like this: 
![image](https://cloud.githubusercontent.com/assets/1103906/22870235/c0d1882a-f1f9-11e6-9e3c-b6fe5ac1e911.png)

**Comment by davkean** [comment]
Okay, investigated my issue above, and it's due to https://github.com/dotnet/roslyn-project-system/issues/1538.

**Comment by davkean** [comment]
Also filed https://github.com/dotnet/roslyn-project-system/issues/1539 to track rename, trying to track the other two issues that you called out.

**Comment by davkean** [comment]
@Ponant Okay, in summary I can repro two bugs with the solution you provided me:

1) Renaming a RESX (or rather any item with metadata) displays an error: https://github.com/dotnet/roslyn-project-system/issues/1539.
2) Moving a project on disk breaks IntelliSense: https://github.com/dotnet/roslyn-project-system/issues/1538.

I cannot repro:

1) Object instance not set an instance of an object when opening a RESX
2) "Custom tool ResXFileCodeGenerator failed to produce an output for input file ... but did not log a specific error"

Can you repro these two issues consistently with a fresh project?

**Comment by Ponant** [comment]
@davkean I can definitely confirm the existence of 1 (Object instance not set an instance of an object when opening a RESX). I have 3 projects which display this form since one week, so the only way to edit or view the resx is to open it with notepad or the like. The other one happened just yesterday.

**Comment by Ponant** [comment]
It is hard to tell you how to make it happen. For instance, as I downloaded the very same project I gave you, I could open the file and no error showed up, which is wierd.
Perhaps the following can help:
1) open 2-3 projects simultaneously
2) create resx's and edit and rename them. VS seems to panic whenever I put a dot in the name of the file.

**Comment by Ponant** [comment]
I added 4-5 resx's from another project and all display "Object instance not set an instance of an object when opening a RESX"

**Comment by davkean** [comment]
Thanks, I'll try against tomorrow. Failing that I might have to get you to attach to VS itself and capture the stack when it occurs.

**Comment by davkean** [comment]
Okay, I spent another hour on this trying to repro. I can now repro the second error "Custom tool ResXFIleCodeGeneator failed to produce an output for input file" and filed: https://github.com/dotnet/roslyn-project-system/issues/1553.

I still cannot, no matter how many projects and different project types, resx's I create, rename, include "." in their names, repro the "object instance not set to an instance of a open when opening a RESX".

If you can consistently repro this, can I ask you to do the following:

1. Start another instance of Visual Studio
2. Choose Debug -> Windows -> Exception Settings
3. Uncheck the checkbox next to Language Runtime Exceptions
4. Expand it, and check System.NullReferenceException
5. Choose Debug -> Attach to Process
6. Choose devenv.exe, make sure you've selected _Managed (v4.6, v4.5, v4.0) code_
7. Click Attach
8. In the other VS instance, repro the bug
9. When VS breaks in the debugger, Copy the stack from Call Stack window and paste it here.

**Comment by Ponant** [comment]
@davkean I will strip out a project and send it to you.

**Comment by Ponant** [comment]
@davkean ok go and have a beer and I will do it today, cheers

**Comment by Ponant** [comment]
@davkean , before doing what you want, can you clone and double click on the res files there?
https://github.com/Ponant/ResBugV2

**Comment by davkean** [comment]
There's no code in that repo. :)

**Comment by Ponant** [comment]
done

**Comment by davkean** [comment]
@Ponant Awesome I got something - from initial reports it looks like https://github.com/dotnet/roslyn-project-system/issues/1499.

**Comment by Ponant** [comment]
So what, we are done?

**Comment by davkean** [comment]
You can pull the repo now I have the source, still debugging - want to absolutely confirm that it's the underlying cause.

**Comment by Ponant** [comment]
I deleted the services folder and close the solution and restart and now I can open the resx again. Funny.

**Comment by davkean** [comment]
Yeah, similar to #1499 - but it's not. Looks like the References are in a bad state and we're null-referring on accessing them.

**Comment by Ponant** [comment]
ok happy to contribute to the mess, cheers

**Comment by davkean** [comment]
Actually, can you keep that code around? I'm seeing a few other issues as well that I'd like us to fix.

**Comment by davkean** [comment]
I'm going to close out this issue, in summary, thanks to @Ponant we got the following bugs from this:

https://github.com/dotnet/roslyn-project-system/issues/1538
https://github.com/dotnet/roslyn-project-system/issues/1539
https://github.com/dotnet/roslyn-project-system/issues/1553
https://github.com/dotnet/roslyn-project-system/issues/1555

**Comment by Ponant** [comment]
Sure, I will leave them

**Comment by Ponant** [comment]
somewhat related https://github.com/aspnet/Home/issues/2075

**Comment by orobert91** [comment]
My "Error List" window gets consistently filled with this error with every .resx file I create on Visual Studio 2017 15.3.3 and .NET Core 2.0. This issue should be reopened.

![untitled](https://user-images.githubusercontent.com/6403705/31789756-299e5220-b4e1-11e7-959d-13a6759c30cc.png)

**Comment by bill-call** [comment]
I am getting the same problem.  I have, in the past tried to move this solution to a different directory, but then moved it back to it's original location.  Based on the history, that may be relevant.

**Comment by bill-call** [comment]
Opened dotnet#2934.
