### ISSUE TITLE
Attempting to set a property on SDK results in an error

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn-project-system#1412]
1. File -> New -> Console App (.NET Core)
2. Choose Microsoft.NETCore.App
3. In Properties attempt to change on of the values:

![image](https://cloud.githubusercontent.com/assets/1103906/22496880/9fc8f0e8-e8a1-11e6-8662-9776245da82e.png)

An error has occurred while saving the edited properties listed below:
	Copy Payload
One or more values are invalid. Specified method is not supported.

**Comment by abpiskunov** [comment]
that is expected .. since sdk is implicit and CPS can not change property - it's not a project item. All properties should be readonly for all sdk's. I can make this change quickly if it is approved for RTM.

**Comment by abpiskunov** [comment]
Proposed fix is to set all SDK items properties to ReadOnly=true for now. There were some boolean flags for old style sdk's that mattered for desktop csproj, but at the moment i am not sure if they would be even used for core; implicit sdk packages would not need property changing for sure. If we want old style SDk to be able to change their properties, we would need to have different xaml rules for old SDK and implicit SDK in the future.
