### ISSUE TITLE
Value for TargetFramework property of project in properties toolbox is a number

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/roslyn-project-system#1416]
- Open or create a .NET Standard or .NET Core project
- Click on the project in Solution Explorer
- In the properties toolbox, scroll down to the TargetFramework property

EXPECTED: TargetFramework property value matches what's in the project file- ie netstandard1.4, netcoreapp1.0, or similar
ACTUAL: TargetFramework property value is a number, such as 65540 or 65536

![image](https://cloud.githubusercontent.com/assets/145043/22500320/96c02db0-e818-11e6-94fa-99c88b170b3b.png)

**Comment by davkean** [comment]
All of these properties are supposed to show - this one in particular is an implementation detail of the project system.

**Comment by davkean** [comment]
Sorry *aren't* supposed to show.

**Comment by srivatsn** [comment]
Yes this will get hidden #389
