### ISSUE TITLE
[Data loss] Changes made to the project in the editor are lost after you've saved it once

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn-project-system#1418]
**Repro 1:**

1. File -> New Console App (.NET Core)
2. Edit ConsoleApp1.csproj
3. Add the following:
``` XML
  <PropertyGroup>
    <Bar>Old Changes</Bar>
  </PropertyGroup>
```

4. While the editor is focused choose File -> Save
5. Without saving, change contents to:

``` XML
  <PropertyGroup>
    <Bar>New Changes</Bar>
  </PropertyGroup>
```

6. Build -> Build Solution

**Expected:** Contents to remain what I typed
**Actual:** Contents are changed back to:
``` XML
  <PropertyGroup>
    <Bar>Old Changes</Bar>
  </PropertyGroup>
```

**Repro 2:**

Starting _after_ step 5 above:

6. Select project in Solution Explorer
7. File -> Save Project

**Expected:** No prompt as it should be a no-op given the project shouldn't be considered "dirty"
**Actual:** 

![image](https://cloud.githubusercontent.com/assets/1103906/22501305/5c80de8e-e8bc-11e6-9e50-dff06054f984.png)

**Comment by davkean** [comment]
@333fred It appears to me after we save the first time, and refresh the project, the project in-memory is being marked dirty.

**Comment by davkean** [comment]
This was really annoying - as I was write a target in the project file, and every second time I build, it lost my changes.

**Comment by 333fred** [comment]
@davkean, I'm reproing either of these on d15rel/26131.01. When you come online could you make sure I'm doing the right steps?

**Comment by davkean** [comment]
Okay, so @333fred  and I sat down and looked at this, we had trouble repro'ing it using my steps, but as part of debugging https://github.com/dotnet/roslyn-project-system/issues/1347 we hit it. It seems like that bug is related.
