### ISSUE TITLE
Updated Version property not respected in incremental builds in Visual Studio

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/roslyn-project-system#1436]
- File \ New Project \ .NET Standard Class Library
- Build
- Inspect DLL in output folder, observe that Product Version is 1.0.0 and File Version is 1.0.0.0
- In VS, right click on project and select edit csproj
- Add the following property: `<Version>2.0.0</Version>`
- Save project file
- Build
- Inspect DLL in output folder

**EXPECTED:** Version numbers are 2.0.0 and 2.0.0.0
**ACTUAL:** Version numbers are 1.0.0 and 1.0.0.0, as previously

Doing a rebuild results in the correct version numbers.

Also, if the project is not open in VS but is edited in another editor and built via command-line MSBuild, the version numbers are set correctly.

I'm not sure whether the actual issue is in the Roslyn project system, the SDK, or both.  It may be related to https://github.com/dotnet/sdk/issues/778.

**Comment by davkean** [comment]
When I was testing this - the AssemblyInfo wasn't being regenerated both via a design-time build or via a build.

**Comment by davkean** [comment]
Once I did a rebuild, however, all future changes worked.

**Comment by dsplaisted** [comment]
This is possibly due to the same underlying issue as https://github.com/dotnet/roslyn-project-system/issues/1418
