### ISSUE TITLE
Remove allocations from LanguageServiceErrorListProvider

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn-project-system#144]
LanguageServiceErrorListProvider allocates an ErrorListDetails, only to decompose the results to pass to IVsLanguageServiceBuildErrorReporter.ReportError - that's 1 unneeded allocation per error/warning/message, and unneeded GC pressure. Let's remove the allocations.

**Comment by alexanderkozlenko** [comment]
Where is the type `LanguageServiceErrorListProvider` located? It seems that there is no such type in the current solution.

**Comment by davkean** [comment]
Yep, sorry - I filed this before I'd finished porting the code. I'm just finishing up the tests now.
