### ISSUE TITLE
VS doesn't restore on build/rebuild

### ISSUE THREAD

**Issue by krwq** [dotnet/roslyn-project-system#1447]
Repro:
- Clone https://github.com/aspnet/antiforgery and sync (i.e. git reset --hard) to 5cb5178619d9211eee0722d8737b425e2eec1375 (this is currently dev~2 or pre-migration)
- Open sln found in the root
- Migrate project when VS asks you to do so
- Build/Rebuild
- Notice that restore doesn't happen and errors that the project is not restored

VS build: 15.0.0-RC.4+26130.1.d15rel
I have previously tested this exact scenario on one of the previous builds (26020) and it has worked before (I was unable to repro it working - possibly some of the nuget packages disappeared - I did errors during restore though which means that at least VS tried to restore).

cc: @srivatsn @rrelyea

**Comment by 333fred** [comment]
@srivatsn I've labelled as blocking release, as this seems like a rather bad one.

**Comment by 333fred** [comment]
Another project that demonstrates this issue: https://github.com/exceptionless/Exceptionless.Net/commit/31ef359ae1f778c7c0a39a268323ad1f3c12381a.

**Comment by srivatsn** [comment]
@natidea can you take a look to see if we're not nominating or if restore is not happening?

**Comment by natidea** [comment]
NuGet is being nominated correctly for all the projects, but I do not see any project.assets.json generated. Let me get some logs to determine if there is a NuGet error.
/cc @alpaix @rrelyea

**Comment by alpaix** [comment]
Duplicate to NuGet/Home#4419. The fix will be inserted into VS soon.
As a temporary workaround add `$(PackageVersion)` property to every .csproj file in the solution
```xml
<PackageVersion>1.0.0</PackageVersion>
```

**Comment by natidea** [comment]
Here is the NuGet Exception:

> System.InvalidOperationException: Sequence contains more than one element at 
> System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source) at 
> NuGet.SolutionRestoreManager.VsSolutionRestoreService.GetNonEvaluatedPropertyOrNull(IVsTargetFrameworks tfms, String propertyName) at 
> NuGet.SolutionRestoreManager.VsSolutionRestoreService.GetPackageVersion(IVsTargetFrameworks tfms) at 
> NuGet.SolutionRestoreManager.VsSolutionRestoreService.ToPackageSpec(ProjectNames projectNames, IVsProjectRestoreInfo projectRestoreInfo) at 
> NuGet.SolutionRestoreManager.VsSolutionRestoreService.ToDependencyGraphSpec(ProjectNames projectNames, IVsProjectRestoreInfo projectRestoreInfo) at 
> NuGet.SolutionRestoreManager.VsSolutionRestoreService.NominateProjectAsync(String projectUniqueName, IVsProjectRestoreInfo projectRestoreInfo, CancellationToken token)
> 

This was introduced by this PR: https://github.com/NuGet/NuGet.Client/pull/1146

Inspecting the project after migration, I see:

| TFM           | PackageVersion |
| ------------- | -------------- |
| net451        | 1.0.0.0        |
| netcoreapp1.1 or netstandard1.3 | 1.2.0 or 1.0.0 |

This is what is causing this exception. I was able to resolve this by removing the `<VersionPrefix>1.2.0</VersionPrefix>` in all projects where it occurred. 

NuGet explicitly does not handle cases where different PackageVersions are returned for different TFMs, though perhaps it shouldn't crash restore, especially if this is a common migrate scenario.

/cc @alpaix @rrelyea @emgarten

**Comment by alpaix** [comment]
We need better error handling for parsing errors. It was assumed initially all exceptions from the Nominate API would be caught without crashing VS. This story is also covered in NuGet/Home#3870.

**Comment by natidea** [comment]
@alpaix To clarify, this does not crash VS, it just breaks restore. But I think that's what you meant. 

I believe the fix to NuGet/Home#4419 only covers the case where the conflict is between 1.0.0.0 and 1.0.0. In the first sample, the entry `<VersionPrefix>1.2.0</VersionPrefix>` is in some projects post migration and this appears to only set PackageVersion for the netcoreapp TFMs. A simple repro is the following project which fails to restore:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>netcoreapp1.0;net451</TargetFrameworks>
    <VersionPrefix>1.2.0</VersionPrefix>
  </PropertyGroup>

</Project>
```

**Comment by davkean** [comment]
Should we move this over to NuGet (you can use: https://github-issue-mover.appspot.com/)

**Comment by natidea** [comment]
This issue was moved to NuGet/Home#4487

**Comment by rrelyea** [comment]
why does migrate put the version into versionprefix?

**Comment by rrelyea** [comment]
@piotrpMSFT - should migration do a fix here. multitargetting projects that mix netfx and netcore-ish TFMs will hit a restore error.

Potential Fix:
have migration use version instead of versionprefix when migrating 1.67.0.* from project.json.
or similar...

Workaround:
Have user change x.y.z in migrated multitargetting project to x.y.z
