### ISSUE TITLE
Dependency Tree error for the first time ...

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn-project-system#1449]
Create a solution with Unit Test (.Net Framework) and ASp.Net Core Web Application (.Net Core) 
Build 

Got this error 

![image](https://cloud.githubusercontent.com/assets/12449387/22565031/96ec2dec-e93b-11e6-8679-ea68d673b842.png)

logs captured here : \\mlangfs1\public\Jinuj\Log\VsProjectFault_e5ad7b01-2e71-42f2-8a60-13aa80853cc1.failure.txt 

**Build :** 26201.1.d15rel
Note: Happened only once, Could not repro the second time.

**Comment by abpiskunov** [comment]
Seems like we still missing a scenario when data sources versions are not in sync. I looked at my changes again and i think i know what it maybe - will need play with it more.
