### ISSUE TITLE
building project that is converted to .net standard project shows build error

### ISSUE THREAD

**Issue by heejaechang** [dotnet/roslyn-project-system#1451]
it is related to https://github.com/dotnet/roslyn-project-system/issues/1450

once project has converted, trying to build the project shows this error

2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(1556,5): error MSB5016: The name ".NETStandard,Version" contains an invalid character ".".  C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets

**Comment by davkean** [comment]
This issue was moved to dotnet/roslyn#16912
