### ISSUE TITLE
when multiple TFMS inside TargetFramework 

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn-project-system#1455]
![image](https://cloud.githubusercontent.com/assets/12449387/22573651/d87ea97e-e95e-11e6-8ecb-49e4dba38c59.png)

should not we be displaying just the highlighted error

Build: 26201.1.d15rel

**Comment by davkean** [comment]
I filed https://github.com/dotnet/sdk/issues/799 to track this. Even that error is not correct, the user specified multiple.

**Comment by davkean** [comment]
Also filed this about inferring .NET Framework: https://github.com/dotnet/sdk/issues/798.
