### ISSUE TITLE
Dependencies are confusing with multiple TFMS 

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn-project-system#1456]
With .NetStandard1.4 as first TFM 
![image](https://cloud.githubusercontent.com/assets/12449387/22573749/460580a8-e95f-11e6-8bd2-c5b93a97038c.png)

with
` <TargetFrameworks>netcoreapp1.0;netstandard1.4;net452</TargetFrameworks> `  when netcoreapp1.0 is first tfm both nuget and SDK node shows NetCore 
![image](https://cloud.githubusercontent.com/assets/12449387/22573814/b2bf1164-e95f-11e6-8361-d26c0e755058.png)

with 
 `<TargetFrameworks>net452;netcoreapp1.0;netstandard1.4</TargetFrameworks>` SDK node disappears 
![image](https://cloud.githubusercontent.com/assets/12449387/22573828/d02253ba-e95f-11e6-9b7a-db94d89c127b.png)

**Build**
26201.1.d15rel

**Comment by abpiskunov** [comment]
This is bigger issue than just Dependencies tree. It should be done on sdk level first to have a consistent story for multi-targeting and how all project items are resolved.evaluated for given set of TFMs. Then we could receive correct data and display it. I suggest to open matching issue in sdk repo and keep this one for tracking to apply corresponding changes, when some work is done there.

**Comment by srivatsn** [comment]
I don't understand the comment - can you explain what needs to happen in the SDK? Today, I assume there's a design time build running for all configurations and collecting all the packagerefs right? If so, shouldn't those items already have the new metadata set on them?
