### ISSUE TITLE
Projects have 6 configurations by default

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn-project-system#1458]
Found via https://twitter.com/Nick_Craver/status/827324233353195521.

Previously, projects had two configurations:

```
Debug|AnyCPU
Release|AnyCPU
```

With this change: https://github.com/dotnet/sdk/commit/e84a17d3257499293971ef4ae9aabf7b8692c65a, we inadvertently caused you to have 6 configurations:

```
Debug|AnyCPU
Debug|x64
Debug|x86
Release|AnyCPU
Release|x64
Release|x86
```

If you have two TFMs, say netcoreapp1.0 and net45, then this doubles, and you end up with 12 under the covers (only 6 of these are "visible" to the user):
```
Debug|AnyCPU|net45
Debug|x64|net45
Debug|x86|net45
Release|AnyCPU|net45
Release|x64|net45
Release|x86|net45
Debug|AnyCPU|netcoreapp1.0
Debug|x64|netcoreapp1.0
Debug|x86|netcoreapp1.0
Release|AnyCPU|netcoreapp1.0
Release|x64|netcoreapp1.0
Release|x86|netcoreapp1.0
```

I've not measured this, this is a significant amount of bookkeeping that CPS has to have behind the screens. I don't think this was intentional - so if we cannot tackle explicit configurations via `<Configurations>`, then we should see if we can back this change out and solve the fix another way?

This is also something that will have compat issue - if we don't fix this now, how will remove these configs in the future without possibly breaking projects?

**Comment by davkean** [comment]
tag @srivatsn @dsplaisted @nguerrera

**Comment by nguerrera** [comment]
Why does that change have that effect?

**Comment by nguerrera** [comment]
Ah. I see it's the conditions that set PlatformTarget.

**Comment by davkean** [comment]
We should just fool the inference by shoving it into another property.

**Comment by nguerrera** [comment]
Yep. I was going to do that :)
