### ISSUE TITLE
Investigate LanguageServiceErrorListProvider's behavior of setting file name to empty when a project file is not set

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn-project-system#146]
When ProjectFile is not set, file name passed to Roslyn is "empty" - this doesn't seem like the right behavior.

**Comment by mavasani** [comment]
@davkean I am looking at this one and seems we need to change [this](http://index/?query=ErrorListD&rightProject=Microsoft.VisualStudio.ProjectSystem.Managed.VS&file=ProjectSystem%5CVS%5CBuild%5CLanguageServiceErrorListProvider.ErrorListDetails.cs&line=38) code to behave differently for null/empty project file. Do we actually have a repro for this case? If so, I think the best we can do is fetch the project file for the active project context from the language service host and use that when project file in the build error is null or empty.
