### ISSUE TITLE
[Configurations] Cannot rename a configuration

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn-project-system#1461]
1. File -> New Class Library (.NET Standard)
2. Right-click Solution, choose Configuration Manager...
3. In Configuration Manager, drop Configuration drop down and choose Edit...
4. Select Debug and click Rename, and enter "Debug2", click OK and Yes to the prompt
5. Click Close

**Expected:** Debug configuration to be renamed
**Actual:** Debug configuration is not renamed

**Comment by srivatsn** [comment]
Tracking this as part of https://github.com/dotnet/roslyn-project-system/issues/694
