### ISSUE TITLE
[Configurations] Copying from a existing configuration does not work

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn-project-system#1462]
This bug was filed assuming that this issue is fixed: https://github.com/dotnet/roslyn-project-system/issues/1458.

1. File -> New Class Library (.NET Standard)
2. Right-click Solution, choose Configuration Manager...
3. In Configuration Manager, drop Configuration drop down and choose New...
4. Enter a name "Debug2",  and choose Copy Settings from Debug
5. Uncheck create new solution configuration

Expected: 

``` XML

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug2|AnyCPU'">
    <DebugSymbols>true</DebugSymbols>
    <Optimize>false</Optimize>
  </PropertyGroup>

```

Actual: 

``` XML

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug2|AnyCPU'" />

```

**Comment by srivatsn** [comment]
Tracking this as part of https://github.com/dotnet/roslyn-project-system/issues/694
