### ISSUE TITLE
Base address is disabled under advanced build property page

### ISSUE THREAD

**Issue by RaulPerez1** [dotnet/roslyn-project-system#1468]
1) Create or open a project
2) Open the project properties
3) Go to the build page
4) Click on the advanced button

Expected: Base address is enabled/disabled based on the output type
Actual: It's always grayed out

**Comment by RaulPerez1** [comment]
The problem is that we're not correctly implementing OutputType in the way that the old project system did. The fix is to do the same thing we're doing for the OutputTypeEx provider

**Comment by RaulPerez1** [comment]
Should be fixed once #1709 is implemented.

**Comment by basoundr** [comment]
Fixed by #1842
