### ISSUE TITLE
New (post project.json) project system

### ISSUE THREAD

**Issue by aL3891** [dotnet/roslyn-project-system#147]
Hey there!
Is this repo where the post project.json project system (for lack of a better name) is going to be developed or is that happening somewhere else?

**Comment by i3arnon** [comment]
Yes. This is for the project system that will be in the next version of Visual Studio (v15).

**Comment by aL3891** [comment]
..and will also be available from the cli? :)

**Comment by davkean** [comment]
This is the repro for post-project.json project system, and will support/be supported by the CLI.
