### ISSUE TITLE
Exception saving file

### ISSUE THREAD

**Issue by onovotny** [dotnet/roslyn-project-system#1471]
I was changing

```
<None Include="..\..\BouncyCastle.snk">
<Link>BouncyCastle.snk</Link>
</None>
```

to

```
<None Include="..\..\BouncyCastle.snk" />
```
And got this. [VsProjectFault_45697bb0-c9f3-4e0d-9378-e99333ef4e60.failure.txt](https://github.com/dotnet/roslyn-project-system/files/752519/VsProjectFault_45697bb0-c9f3-4e0d-9378-e99333ef4e60.failure.txt)

**Comment by davkean** [comment]
👍 We'll take a look.

**Comment by srivatsn** [comment]
Looks like a CPS issue? @lifengl @jviau

**Comment by lifengl** [comment]
This is duplicated to https://github.com/dotnet/roslyn-project-system/issues/1042

**Comment by davkean** [comment]
Dup.
