### ISSUE TITLE
Packing a Class Library targeting .NetCoreApp1.1 generates warning 

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn-project-system#1477]
Create a Class Libary (.Net Core ) 
Build 
Right click properties change TFM from .NetCoreApp1.0 to .NetCoreApp1.1
Build 
Pack 

**Expected**
Packs with out any warning 

**Actual**

1>------ Build started: Project: ClassLibrary3, Configuration: Debug Any CPU ------
1>ClassLibrary3 -> c:\users\corbvt\documents\visual studio 2017\Projects\MegaSln\ClassLibrary3\bin\Debug\netcoreapp1.1\ClassLibrary3.dll
1>Successfully created package 'c:\users\corbvt\documents\visual studio 2017\Projects\MegaSln\ClassLibrary3\bin\Debug\ClassLibrary3.1.0.0.nupkg'.
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(104,5): warning : Issue found with package 'ClassLibrary3'.
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(104,5): warning : Issue: Assembly outside lib folder.
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(104,5): warning : Description: The assembly 'content\Microsoft.DiaSymReader.Native.x86.dll' is not inside the 'lib' folder and hence it won't be added as reference when the package is installed into a project.
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(104,5): warning : Solution: Move it into the 'lib' folder if it should be referenced.
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(104,5): warning : Issue: Assembly outside lib folder.
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(104,5): warning : Description: The assembly 'contentFiles\any\netcoreapp1.1\Microsoft.DiaSymReader.Native.x86.dll' is not inside the 'lib' folder and hence it won't be added as reference when the package is installed into a project.
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(104,5): warning : Solution: Move it into the 'lib' folder if it should be referenced.
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(104,5): warning : Issue: Assembly outside lib folder.
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(104,5): warning : Description: The assembly 'content\Microsoft.DiaSymReader.Native.amd64.dll' is not inside the 'lib' folder and hence it won't be added as reference when the package is installed into a project.
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(104,5): warning : Solution: Move it into the 'lib' folder if it should be referenced.
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(104,5): warning : Issue: Assembly outside lib folder.
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(104,5): warning : Description: The assembly 'contentFiles\any\netcoreapp1.1\Microsoft.DiaSymReader.Native.amd64.dll' is not inside the 'lib' folder and hence it won't be added as reference when the package is installed into a project.
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(104,5): warning : Solution: Move it into the 'lib' folder if it should be referenced.
1>Done building project "ClassLibrary3.csproj".
========== Build: 1 succeeded or up-to-date, 0 failed, 0 skipped ==========

**Build**

26205.00.d15rel

**Comment by davkean** [comment]
These binaries are being added as content items - and hence they are getting packed. @tmat?

**Comment by kazuk** [comment]
I have same issue.

Microsoft.DiaSymReader.Native.props requires `<Pack>false</Pack>`

https://github.com/dotnet/roslyn/issues/15137#issuecomment-278183707

**Comment by srivatsn** [comment]
This is being tracked by https://github.com/dotnet/corefx/issues/14627 and the package is being fixed in NetCoreapp 1.1.1
