### ISSUE TITLE
.NET Core projects go through the upgrade wizard when opened down-level in VS2015

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn-project-system#1487]
1. Create a new SDK project
2. Open Solution in VS 2015

Expected: Fail to load
Actual: Goes through the upgrade, and then fails to load

**Comment by davkean** [comment]
It's going through the upgrade wizard, because legacy project system thinks it's a VS 2005 project due to the lack of a `ToolsVersion` attribute.

A few ways we could solve this:

1. Add back ToolVersions by default, which will cause us to skip the upgrade, and the project will still fail due the additional of the SDK/lack of namespace.
2. Change the project type in the Solution file to be represent the new project factory - the user will get "the project type is not installed prompt". This won't prevent raw project opens though (ie not through the solution)
3. Patch VS 2015 to recognize these projects and give a better error message.

**Comment by srivatsn** [comment]
Just tried this on VS 2015 U3 and the project doesn't go through the upgrade wizard. It fails to load with this message: 
![image](https://cloud.githubusercontent.com/assets/20570/22808831/f29907e4-eee2-11e6-9d47-0df04371dc0f.png)

While not optimal, at least it doesn't let the user load the project and lead to messing up their projects. I think we can live with this.

**Comment by davkean** [comment]
👍
