### ISSUE TITLE
VS2017 RC4 does not package multi-target projects

### ISSUE THREAD

**Issue by roryprimrose** [dotnet/roslyn-project-system#1489]
I've used an existing solution and a new solution after installing RC4. I'm finding that the package on build setting is not working where the project uses multi-targeting.

Here is an example proj file updated after creating a new core library.

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netcoreapp1.0;net452</TargetFrameworks>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
  </PropertyGroup>

</Project>
```

The original value was ```<TargetFramework>netcoreapp1.0</TargetFramework>``` which did produce the package on build.

The package is no longer built if the element is changed to  ```<TargetFrameworks>netcoreapp1.0</TargetFrameworks>``` and defining either a single TFM or mulitple.

**Comment by davkean** [comment]
I just tried and could repro this with rebuild: https://github.com/NuGet/Home/issues/4527. Does it work for you if you just "build"?

**Comment by roryprimrose** [comment]
Yes, I was just doing rebuilds. I can also confirm that the package is built with build, but not rebuild.

**Comment by davkean** [comment]
Great, I'll dupe it against https://github.com/NuGet/Home/issues/4527. Thanks!
