### ISSUE TITLE
Build error after changing .csproj for .NET core, goes away after git clean -xdf

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/roslyn-project-system#1496]
Repro:
1. git clone https://github.com/KirillOsenkov/MSBuildStructuredLog
2. nuget restore
3. msbuild <-- this is important
4. Open MSBuildStructuredLog.sln in VS 2017 RC4 (or newer)
5. Make sure it builds from the IDE (F6)
6. Unload StructuredLogger project and edit the .csproj
7. Replace the .csproj contents with this: https://github.com/KirillOsenkov/MSBuildStructuredLog/blob/d3e5742cbc1c7bfc914acaee594aa09b6da92202/src/StructuredLogger/StructuredLogger.csproj
8. Reload the project
9. Build (you can even Clean/Rebuild)

Expected: build succeeded
Actual: build error: 
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0579	Duplicate 'System.Reflection.AssemblyTitleAttribute' attribute	StructuredLogger(netstandard1.5)	C:\MSBuildStructuredLog\src\StructuredLogger\obj\Debug\net46\StructuredLogger.AssemblyInfo.cs	18	Active
```

This is fixed only by BOTH closing VS and doing git clean -xdf.

If you don't close VS and do git clean -xdf, you get 39 errors.
If you close VS and don't git clean -xdf, you still get the 1 error above.

**Comment by srivatsn** [comment]
I suspect the assemblyinfo file generated by project.json is called differently from the one generated by the SDK and that causes both files to be around until you do a git clean -xdf?

**Comment by KirillOsenkov** [comment]
Does the SDK generate an assembly info file? Where can I find out more about this? I've only seen one file in the repo (in obj) (the other might go to TEMP?)

Also how do I investigate what got passed to Csc? Somehow the log output from inner builds doesn't make it into the logger...

**Comment by srivatsn** [comment]
Yes see here - https://github.com/dotnet/sdk/blob/master/src/Tasks/Microsoft.NET.Build.Tasks/build/Microsoft.NET.GenerateAssemblyInfo.targets

I'm not aware of issues with loggers - the inner build is just a msbuild invocation - do the loggers need to passed through specifically?

**Comment by KirillOsenkov** [comment]
No, it was a problem on my end. Everything is fine.

So the real problem in this bug is that the error (although legit - since both NerdBank.GitVersioning and the SDK are generating the AssemblyTitle attribute) doesn't go away after I fix it unless I git clean and restart VS.

**Comment by srivatsn** [comment]
> doesn't go away after I fix it 

How are you fixing it? By turning off assembly info generation? Are you saying that when that's turned off the temp file from obj is not getting deleted?

**Comment by KirillOsenkov** [comment]
Sorry I got super confused by a similar bug yesterday. Please ignore my comment about NerdBank.GitVersioning. 

The repro steps above still seem to constitute a problem though...

**Comment by davkean** [comment]
This issue was moved to dotnet/sdk#1009
