### ISSUE TITLE
Ordering of multiple <TargetFrameworks> and Solution Explorer contents

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/roslyn-project-system#1497]
The .csproj in question is https://github.com/KirillOsenkov/MSBuildStructuredLog/blob/d3e5742cbc1c7bfc914acaee594aa09b6da92202/src/StructuredLogger/StructuredLogger.csproj

If it specifies `TargetFrameworks` as `net46;netstandard1.5` you get:
![image](https://cloud.githubusercontent.com/assets/679326/22753460/0403644a-edf1-11e6-9f9b-c903068c4910.png)

but if you specify `TargetFrameworks` as 'netstandard1.5;net46' you get:
![image](https://cloud.githubusercontent.com/assets/679326/22753494/22dd8ada-edf1-11e6-8ec2-1ed6e19ddf4c.png)

In both cases the MSBuild references displayed are 14.3.0, whereas the project explicitly conditions the references based on the `TargetFramework` as 15.1.0 for `netstandard1.5`:
```
  <PropertyGroup Condition=" '$(TargetFramework)' == 'netstandard1.5'">
    <DefineConstants>$(DefineConstants);NETCORE</DefineConstants>
  </PropertyGroup>
  <ItemGroup Condition=" '$(TargetFramework)' == 'netstandard1.5' ">
    <PackageReference Include="Microsoft.Build" Version="15.1.0-preview-000523-01" />
    <PackageReference Include="Microsoft.Build.Framework" Version="15.1.0-preview-000523-01" />
    <PackageReference Include="Microsoft.Build.Tasks.Core" Version="15.1.0-preview-000523-01" />
    <PackageReference Include="Microsoft.Build.Utilities.Core" Version="15.1.0-preview-000523-01" />
  </ItemGroup>
  <ItemGroup Condition=" '$(TargetFramework)' == 'net46' ">
    <Reference Include="System" />
    <Reference Include="System.Core" />
    <Reference Include="System.Xml" />
    <Reference Include="System.Xml.Linq" />
    <PackageReference Include="Microsoft.Build" Version="14.3.0" />
    <PackageReference Include="Microsoft.Build.Framework" Version="14.3.0" />
    <PackageReference Include="Microsoft.Build.Tasks.Core" Version="14.3.0" />
    <PackageReference Include="Microsoft.Build.Utilities.Core" Version="14.3.0" />
  </ItemGroup>
```

**Comment by srivatsn** [comment]
The first TFM is considered the active TFM and we don't show dependencies for all TFMs (other than PackageRefs which we do show for all TFMs). https://github.com/dotnet/roslyn-project-system/issues/587 tracks the work to enable dependencies for all TFMs.

The second issue is interesting. If the same package is mentioned with different versions then we seem to just show one - @abpiskunov do you expect to show two items here or just one?

**Comment by abpiskunov** [comment]
If same package belong to multiple TFMs, we just show it once for now.

**Comment by srivatsn** [comment]
Ok added a comment to #587. Let's use that issue to track.
