### ISSUE TITLE
NuGetRestorer.ProjectPropertyChangedAsync should register the restore to specific operations instead of a critical task for everything

### ISSUE THREAD

**Issue by lifengl** [dotnet/roslyn-project-system#1501]
instead of calling RegisterCriticalAsyncTask, it should RegisterAsyncTask and register it for ProjectCriticalOperation.Build | Unload | Rename.  The RegisterCriticalAsyncTask will require the task to be finished before saving a project, which is not necessary in this case.

This is important because "Save" is done in a sync method in VS, but NuGet is running scripts in the background, so it depends on RPC to finish some tasks on the UI thread, so it can easily run into dead locks.

**Comment by natidea** [comment]
@lifengl thinking through this some more: if a user saves while restore is running, is there still any risk of a deadlock since both operations could contend for the UI thread (as Build does)? Or does Save synchronously hold the UI thread until it is completely done, eliminating contention? What about (for example) cases when the user tries to save a readonly file, causing a dialog to pop up?

**Comment by lifengl** [comment]
If Joinable tasks are done correctly, which we hope for, we should not allow NuGet to run in the main thread inside 'Save' operation.  Of course, if a dialogue pops up, RPC calls can pass to the UI thread, and we don't have any infrastructure today to prevent that, so a dead lock might be possible, although the chance should be low.   We don't have a solution for this.

Sent from my phone

On Feb 8, 2017, at 4:16 PM, Nat Ayewah <notifications@github.com<mailto:notifications@github.com>> wrote:


@lifengl<https://github.com/lifengl> thinking through this some more: if a user saves while restore is running, is there still any risk of a deadlock since both operations could contend for the UI thread (as Build does)? Or does Save synchronously hold the UI thread until it is completely done, eliminating contention? What about (for example) cases when the user tries to save a readonly file, causing a dialog to pop up?
