### ISSUE TITLE
Files from the nuget cache appear in the Solution Explorer

### ISSUE THREAD

**Issue by cdmihai** [dotnet/roslyn-project-system#1506]
- `git clean -xdf`. Solution Explorer looks right:
![image](https://cloud.githubusercontent.com/assets/2255729/22762526/9ac8c4ce-ee14-11e6-9111-b6bbf0d859da.png)

- `dotnet restore` at solution level. Solution Explorer shows spurious files from the nuget package cache
![image](https://cloud.githubusercontent.com/assets/2255729/22762547/c0c950c6-ee14-11e6-9998-64e4726a6494.png)

- Right-Click -> Properties on one of the spurious items shows:
![image](https://cloud.githubusercontent.com/assets/2255729/22762668/6da06b4a-ee15-11e6-8890-ee50392e392c.png)

Is this normal? I would not expect things from the nuget cache to appear in the Solution Explorer.
The spurious files represent content files from our `Microsoft.Build.Runtime` nuget package: https://github.com/Microsoft/msbuild/blob/xplat/build/NuGetPackages/Microsoft.Build.Runtime.nuspec#L70-L90.
The dependency to this package is declared via 
`<PackageReference Include="Microsoft.Build.Runtime" Version="15.1.0-preview-000545-01" />`

VS version: 15.0.26206.0 D15REL

**Comment by srivatsn** [comment]
Content files that come from a package will be shown since they're part of the project. This is https://github.com/dotnet/roslyn-project-system/issues/603 which seems to have been "fixed". We should probably show these with some different treatment..

**Comment by cdmihai** [comment]
Maybe put them under a node called "Content Files" like `Content Files/Microsoft.Build.Runtime/<content files>`?. If you have 500 nuget packages in your dependency graph and each brings a content file, you wouldn't want them to show up right under the root. Also, content files are tfm specific. In this case, VS chose the netcoreapp1.0 ones.

Is there an option to turn this of?

**Comment by srivatsn** [comment]
No there isn't a way to turn this off. We'll track showing them differently as part of #603
