### ISSUE TITLE
No way to specify which framework to run

### ISSUE THREAD

**Issue by BillHiebert** [dotnet/roslyn-project-system#1514]
1. Create a new .net core console application
2. Edit the project file and add a 2nd framework. Say net461
3. Build project

When running the project there is no way to specify which output to run.

**Comment by abpiskunov** [comment]
Same problem for unit tests also.

**Comment by kzu** [comment]
Is this somehow related to https://github.com/dotnet/roslyn-project-system/blob/master/src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Debug/DebugProfileEnumValuesGenerator.cs#L69 and "launch settings"?

Do we have documentation at all on how to configure those launch settings or should the old JSON approach still work? https://docs.microsoft.com/en-us/aspnet/core/fundamentals/environments

**Comment by srivatsn** [comment]
Fixed with #1664
