### ISSUE TITLE
Hang while closing the solution 

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn-project-system#1518]
Create a class library (netStandard) change tfms which got me to this state https://github.com/dotnet/roslyn-project-system/issues/1503  
In order to work around that was closing and reopening the sln and I hit the hang.
Captured the dmp here `<internalshare>\public\Jinuj\dmp\solutionClosure.DMP` 

did not repro the second time.

As per @lifengl's analysis

It appears to be a different dead lock.  The project closing is waiting on this task:

165a6de4 <4> Microsoft.VisualStudio.ProjectSystem.LanguageServices.LanguageServiceHost+<UpdateProjectContextAsync>d__24
.165a6ef0 <0> Microsoft.VisualStudio.ProjectSystem.LanguageServices.LanguageServiceHost+<UpdateProjectContextAndSubscriptionsAsync>d__23
..166b6428 <2> Microsoft.VisualStudio.ProjectSystem.LanguageServices.LanguageServiceHost+<OnProjectChangedCoreAsync>d__22

**Comment by lifengl** [comment]
This is another case that JoinableTask chain was not created correctly in the code.  The code on index/ is slightly different, and doesn’t match the code well, but I think the problem still exists.

Here is a more detailed explanation:

CPS is draining critical tasks when the project is closed, and the two tasks it waits on:

122559f8 <0> Microsoft.VisualStudio.ProjectSystem.SemaphoreSlimExtensions+<DisposableWaitAsync>d__1
.12255aa8 <0> Microsoft.VisualStudio.ProjectSystem.LanguageServices.LanguageServiceHost+<HandleAsync>d__26
..12255b94 <0> Microsoft.VisualStudio.ProjectSystem.LanguageServices.LanguageServiceHost+<>c__DisplayClass22_0+<<OnProjectChangedCoreAsync>b__0>d
...12255eb8 <0> Microsoft.VisualStudio.Threading.JoinableTask+<JoinAsync>d__76
....16815c1c <1> Microsoft.VisualStudio.ProjectSystem.LanguageServices.LanguageServiceHost+<OnProjectChangedCoreAsync>d__22

1646b768 <0> Microsoft.VisualStudio.ProjectSystem.SemaphoreSlimExtensions+<DisposableWaitAsync>d__1
.1646b818 <0> Microsoft.VisualStudio.ProjectSystem.LanguageServices.LanguageServiceHost+<HandleAsync>d__26
..1646b904 <0> Microsoft.VisualStudio.ProjectSystem.LanguageServices.LanguageServiceHost+<>c__DisplayClass22_0+<<OnProjectChangedCoreAsync>b__0>d
...1646bbd8 <0> Microsoft.VisualStudio.Threading.JoinableTask+<JoinAsync>d__76
....12151f80 <1> Microsoft.VisualStudio.ProjectSystem.LanguageServices.LanguageServiceHost+<OnProjectChangedCoreAsync>d__22

It is waiting on a semaphore:
        private async Task HandleAsync(IProjectVersionedValue<IProjectSubscriptionUpdate> update, RuleHandlerType handlerType)
        { …
            using (await _gate.DisposableWaitAsync().ConfigureAwait(true))

The semaphore is taken by this task:
165a6de4 <4> Microsoft.VisualStudio.ProjectSystem.LanguageServices.LanguageServiceHost+<UpdateProjectContextAsync>d__24
.165a6ef0 <0> Microsoft.VisualStudio.ProjectSystem.LanguageServices.LanguageServiceHost+<UpdateProjectContextAndSubscriptionsAsync>d__23
..166b6428 <2> Microsoft.VisualStudio.ProjectSystem.LanguageServices.LanguageServiceHost+<OnProjectChangedCoreAsync>d__22

And it waits to switch to the UI thread:

       private async Task<AggregateWorkspaceProjectContext> UpdateProjectContextAsync()
…
          using (await _gate.DisposableWaitAsync().ConfigureAwait(false))
         {
…
                await _commonServices.ThreadingService.SwitchToUIThread();
                await _activeProjectConfigurationRefreshService.RefreshActiveProjectConfigurationAsync().ConfigureAwait(false);

As a direct reason of this dead lock:
The task wants the semaphore doesn’t declare that it waits on the task, which takes the semaphore in the JTF language, so when it is blocking the UI thread, it will not allow the other side to run.  That is very similar to the problem we saw recently inside NuGet (and they happen to use a semaphore as well.)

To fix that, the code need create a JoinableTaskCollection, and a JoinableTaskFactory (it need use CPS threading service to create one), in the code to wait on the semaphore, it need join to the JoinableTaskCollection, and the task gets the semaphore need run the task (when it holds the semaphore) within a new JoinableTask created with the special JoinableTaskCollection.   A sample fix in the NuGet can be found at: https://github.com/NuGet/NuGet.Client/pull/1173

**Comment by davkean** [comment]
@mavasani Can you take this one?
