### ISSUE TITLE
Nuget restore not happening when PackageTargetFallback is added

### ISSUE THREAD

**Issue by jmarolf** [dotnet/roslyn-project-system#1520]
1. Create a new .NET Core console app
2. Modify the project file to add PackageReference like below )
```XML
<ItemGroup>
  <PackageReference Include="Microsoft.CodeAnalysis.Workspaces.Common" Version="1.0.1" />
</ItemGroup>
```
*Note: this will cause many error like so:*

Severity | Description	
------------ | -------------
| Error	|	Package restore failed. Rolling back package changes for 'ConsoleApp4'. |
| Error	|	Package Microsoft.CodeAnalysis.Workspaces.Common 1.0.1 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0) / win. Package Microsoft.CodeAnalysis.Workspaces.Common 1.0.1 supports: |
| Error	|	Package Microsoft.CodeAnalysis.Workspaces.Common 1.0.1 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0) / win-x86. Package Microsoft.CodeAnalysis.Workspaces.Common 1.0.1 supports: |
| Error	|	Package Microsoft.CodeAnalysis.Workspaces.Common 1.0.1 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0) / win-x64. Package Microsoft.CodeAnalysis.Workspaces.Common 1.0.1 supports: |
| Error	|	Package Microsoft.Composition 1.0.27 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package Microsoft.Composition 1.0.27 supports: portable-net45+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile259) |	
| Error	|	Package Microsoft.Composition 1.0.27 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0) / win-x64. Package Microsoft.Composition 1.0.27 supports: portable-net45+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile259) |	
| Error	|	One or more packages are incompatible with .NETCoreApp,Version=v1.0 (win-x86).	 |
| Error	|	Package Microsoft.Composition 1.0.27 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0) / win. Package Microsoft.Composition 1.0.27 supports: portable-net45+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile259)	 |
| Error	|	Package Microsoft.CodeAnalysis.Workspaces.Common 1.0.1 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package Microsoft.CodeAnalysis.Workspaces.Common 1.0.1 supports: |
| Error	|	One or more packages are incompatible with .NETCoreApp,Version=v1.0 (win-x64).	 |
| Error	|	One or more packages are incompatible with .NETCoreApp,Version=v1.0 (win).	 |
| Error	|	Package Microsoft.Composition 1.0.27 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0) / win-x86. Package Microsoft.Composition 1.0.27 supports: portable-net45+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile259)	 |
| Error	|	One or more packages are incompatible with .NETCoreApp,Version=v1.0. |

3. add a `PackageTargetFallback` to the `PropertyGroup` and save the file
```XML
<PropertyGroup>
  <OutputType>Exe</OutputType>
  <TargetFramework>netcoreapp1.0</TargetFramework>
  <PackageTargetFallback>portable-net45+win8</PackageTargetFallback>
</PropertyGroup>
```

Expected: Project system runs nuget restore and errors go away

Actual:  If none of these packages are in the nuget cache, errors persist

**Comment by davkean** [comment]
We definitely explictly handle changes to `<PackageTargetFallback>` (and have for ~4 months) and if I try this it works. However, your last statement seems to indicate that it might have something to do with the NuGet package cache - but even then that case - NuGet successfully restored for me and these errors went away.

Do you have a more concrete repro? What do you mean by the last part around them missing from the packages cache? I explicitly deleted these package from the cache before I saved, and didn't see this.

**Comment by davkean** [comment]
@jmarolf Do you have a more concrete repro?

**Comment by davkean** [comment]
Going to close this, I cannot repro this.
