### ISSUE TITLE
[Configuration] Can't add ARM using UI

### ISSUE THREAD

**Issue by nguerrera** [dotnet/roslyn-project-system#1523]
* File -> New Project -> Console App (.NET Core)
* Click on platform dropdown in toolbar -> Configuration manager
  * Notice that ARM is not a choice
* Type in ARM manually and leave "create project platforms" checked -> OK
  * Get popup error that projects do not support ARM
* Uncheck "create project platforms" -> OK
* Edit project file, add ARM configurations manually:
``` xml
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|ARM'" />
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|ARM'" />
```
* Go back to configuration manager, attempt to set ARM project configuration to match ARM solution configuration.
  * No errors, but it just resets it back to Sln=ARM -> Project=Any CPU

Workaround:

* Edit sln manually in addition to editing sln manually.

@davkean @RaulPerez1 Is there a capability that drives whether a project can target ARM from VS' perspective?

**Comment by davkean** [comment]
Yeah MSBuild property drives this `AvailablePlatforms` I think it's called.

**Comment by nguerrera** [comment]
That works. I don't want to advertise support for something that hasn't been used in RTM. And you can add <AvailablePlatforms>$(AvailablePlatforms);ARM</AvailablePlatforms> to your own targets or csproj as workaround. I'll move this to SDK for post 1.0.
