### ISSUE TITLE
Lightweight solution is turned on for .NET Core projects

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn-project-system#1525]
We're supposed to be opt'd out, but appears we're opted in. Figure out what's supposed to be the behavior.

**Comment by 333fred** [comment]
@davkean, what build? I'm not seeing us doing that on the d15rel/26208.00, unless you mean more generally that it's not supposed to be possible to enable with .net core?

**Comment by davkean** [comment]
Latest build:

This project is DPL loaded:
![image](https://cloud.githubusercontent.com/assets/1103906/22810042/61313ce2-ef8a-11e6-8fa3-8192494265f2.png)

**Comment by jinujoseph** [comment]
we seem's to be setting the registry key to opt out, so DPL should not be enabled for .netcore

**Comment by jviau** [comment]
I am not sure what other issues .NET Core project system has with LSL, but I know one of them was LSL did not recognize the `SDK` attribute. A fix for this is in testing, so it may be possible to leave it enabled?

**Comment by davkean** [comment]
@jviau I've already started seeing lots of broken things, that I'm not comfortable in the state of enabling it for .NET Core.

**Comment by natidea** [comment]
This came up in shiproom. [381882](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/381882) is trying to disable it properly

**Comment by davkean** [comment]
That bug doesn't seem to be talking about disabling it.

**Comment by natidea** [comment]
I think I misread the bug.

**Comment by natidea** [comment]
[381882](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/381882) has been punted. Plan is to disable for .NET Core (for real this time)

**Comment by jinujoseph** [comment]
Tracked here .. [384070 ](https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workitems?id=384070&fullScreen=false&_a=edit)

**Comment by srivatsn** [comment]
Closing since it's tracked by 384070
