### ISSUE TITLE
Error when viewing properties on two .NET Standard Class Libraries

### ISSUE THREAD

**Issue by JoshVarty** [dotnet/roslyn-project-system#1530]
**VS Version:** VisualStudio/15.0.0-RC.4+26206.0

Repro Steps:

1. Create two .NET Standard Class Libraries
2. Select both of them in Solution Explorer
3. Right click > Properties

Expected Result: I'm not really sure, I guess an empty properties window or something. Maybe it's not useful to show the Properties item in the context menu at all when two projects are selected.

Actual Result:

![image](https://cloud.githubusercontent.com/assets/1249087/22841589/09f5c658-ef87-11e6-8dbc-60abc6607f69.png)

**Comment by davkean** [comment]
Thanks - this looks like a CPS bug, I've filed https://devdiv.visualstudio.com/DevDiv/_workitems?id=383804&fullScreen=false&_a=edit.

**Comment by davkean** [comment]
What's supposed to happy is the Properties tool window is supposed to open showing common properties between the projects.
