### ISSUE TITLE
End-to-end with Xamarin projects fail in RC4

### ISSUE THREAD

**Issue by onovotny** [dotnet/roslyn-project-system#1531]
With a solution containing Multi-targeted and single target CPS (.net standard library) projects that are referenced by Xamarin projects, there are several errors/failures:

To repro (this should be clean but it currently fails):
 - Clone https://github.com/onovotny/microsoft-authentication-library-for-dotnet  
 - Set branch to  xamarin-issue-1-rc3 
 - Open sln MSAL.sln 
 - Build sln
 - Run unit tests with Test Explorer
 - F5 for all app projects 

This is a meta-issue for several underlying issues:

iOS Build
https://developercommunity.visualstudio.com/content/problem/18183/cannot-build-ios-app-that-references-cps-netstanda.html

Android Build issues along with android resource warnings
https://developercommunity.visualstudio.com/content/problem/18184/cannot-build-xamarinandroid-app-that-references-cp.html

Xamarin Forms dependency causes OOM on build task
https://developercommunity.visualstudio.com/content/problem/18186/cannot-build-netstandard-class-library-that-refere.html

NuGet repo:
restore errors that cause mscorlib not to be referenced
https://github.com/NuGet/Home/issues/4547 

pri file missing from pack
https://github.com/NuGet/Home/issues/4136 

Actual – fails to build, VS crashes, hangs occasionally. Run unit tests fails. F5 fails

There

**Comment by srivatsn** [comment]
The fixes are external to this repo but @nguerrera is driving these -so assigning to him.

**Comment by onovotny** [comment]
For visibility here, @rrelyea opened up an internal bug 383558 to track the Android issue https://github.com/NuGet/Home/issues/4547

**Comment by onovotny** [comment]
Almost done, https://github.com/NuGet/Home/issues/4136 is the only one left! :)

**Comment by srivatsn** [comment]
The xamarin fixes have been checked in. Closing this issue since the remaining issue is tracked in NuGet.
