### ISSUE TITLE
NuGet restore in Visual Studio does not respect PackageId property of projects

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/roslyn-project-system#1532]
- Open the attached project in Visual Studio: [RestoreProjectIdOverride.zip](https://github.com/dotnet/roslyn-project-system/files/768085/RestoreProjectIdOverride.zip)
- Wait for NuGet restore to complete

**EXPECTED:** Restore completes successfully
**ACTUAL:** Restore error: `Unable to resolve 'ReferencedProjectPackageID (>= 1.0.0)' for '.NETStandard,Version=v1.4'.`

Note that command-line restore (`msbuild /t:restore` or `dotnet restore`) succeeds.

The issue appears to be that the restore operation in VS isn't respecting the `PackageId` property of a project.

To fix this, we likely need changes in both the Roslyn project system and in NuGet:

- Project system: https://github.com/dotnet/roslyn-project-system/blob/master/src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/NuGetRestore.xaml needs to be updated to pass the PackageId property through
- NuGet: https://github.com/NuGet/NuGet.Client/blob/7676e7ff39faf3234e264b7b344e17e6900f3ead/src/NuGet.Clients/NuGet.SolutionRestoreManager/VsSolutionRestoreService.cs needs to be updated to get the PackageId from the property bag and pass it through to the rest of the restore operation

@srivatsn @rrelyea for triage

**Comment by rrelyea** [comment]
If you can pass the data, without a signature change, we'll try to get our side approved and in as well.
@doronmotter

**Comment by srivatsn** [comment]
Sure, @natidea I've moved this to RTM as I believe this is a simple change on our side.
