### ISSUE TITLE
csproj + git = binary content

### ISSUE THREAD

**Issue by JamesNK** [dotnet/roslyn-project-system#1534]
Something about how VS2017 is writing csproj files is making git think they are binary content.

**Comment by JamesNK** [comment]
Is the fix for https://github.com/dotnet/roslyn-project-system/issues/1168 in the latest VS2017RC3 public release?

**Comment by davkean** [comment]
That fix is in. Can you point me some commits that before and after would be preferable that shows the results?

tag @333fred

**Comment by JamesNK** [comment]
https://github.com/JamesNK/Newtonsoft.Json/commits/875d2f43234c74d410d68233a9efadc48090b9bd/Src/Newtonsoft.Json/Newtonsoft.Json.Roslyn.csproj

**Comment by 333fred** [comment]
@JamesNK, any idea how the UTF-16 header got on top of that project file? What happened was that when the project looks for what encoding to save the project as, it sees that header and uses that encoding. This isn't actually restricted to the editor, you'll reproduce the same results if you open that first commit, add a NuGet package, and save the project.

**Comment by 333fred** [comment]
ie, https://github.com/JamesNK/Newtonsoft.Json/commit/bbcb9ca5059b09380030a6e346545786747b9eb1#diff-c0ebee041c2e5566f4762b616a63866c is a UTF-8 encoded file with a UTF-16 header.

**Comment by JamesNK** [comment]
No idea. Migration failed for me so I believe I started by copying and pasting an old csproj file, cleared out its content and used that.

**Comment by 333fred** [comment]
If you remove the header from the file, I believe that the issue should go away. I'd suggest editing it with an external editor, as the VS editor won't notice the removed header until after the project has been saved and reloaded (defeating the purpose).

**Comment by JamesNK** [comment]
Removing the XML UTF-16 header and fixed it.
