### ISSUE TITLE
Edit Project command missing in VS2017 RC4

### ISSUE THREAD

**Issue by wjk** [dotnet/roslyn-project-system#1535]
The title really says it all. I must now manually unload the csproj file to edit its XML in Visual Studio RC.4+26206.0. ☹️ As far as I can recall, this did _not_ occur in older builds of VS2017, but seeing as it was a long time since I did any Core development in full VS, my memory may well be wrong.

**Comment by davkean** [comment]
What project type? .NET Core/.NET Standard?

**Comment by wjk** [comment]
I am targeting netcoreapp1.1.

**Comment by davkean** [comment]
Can you unload the project and add the following?

```
 <ItemGroup>
    <ProjectCapability Include="DiagnoseCapabilities"/>
  </ItemGroup>
```

Reload the project and tell me if the "capability" OpenProjectFile appears in the list?

**Comment by wjk** [comment]
`OpenProjectFile` does not appear in the list of capabilities.

**Comment by srivatsn** [comment]
Can you try removing the project, save the solution and then add it back again? I think this is https://github.com/dotnet/cli/issues/5665. The solution has the wrong guid and removing and adding the project should put the right guid back.

**Comment by wjk** [comment]
@srivatsn Yeah, that fixed it. I actually added this project to my solution using `dotnet sln add`. I've noticed that @piotrpMSFT already mentioned this issue regarding that command. For now I'll just use Notepad's find-and-replace feature to rectify the problem for the other projects in my solution. Thanks!
