### ISSUE TITLE
ContentFiles imported from nuget packages should show up under a virtual package folder in the solution

### ISSUE THREAD

**Issue by davidfowl** [dotnet/roslyn-project-system#1537]
All of these "linked files" are coming from different imported nuget packages.  I would be cleaner if there was a virtual package node under which these files showed up.

![image](https://cloud.githubusercontent.com/assets/95136/22857806/a43820a0-f061-11e6-80af-6455d04fb7c7.png)

**Comment by srivatsn** [comment]
Tracked by https://github.com/dotnet/roslyn-project-system/issues/603
