### ISSUE TITLE
Renaming an item with update metadata displays an errors, and loses metadata

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn-project-system#1539]
1. File -> New Console App (.NET Core)
2. In Solution Explorer, select Class1.cs, change "Copy to Output Directory" to "Always"
3. Rename Class1.cs -> Foo.cs

**Expected:** For Foo.cs to have the same metadata
**Actual:**

```
---------------------------
Microsoft Visual Studio
---------------------------
Two elements must come from the same file.

Parameter name: rightElement
---------------------------
OK   
---------------------------
```

And the metadata is not copied.

This in particular affects RESX the most as by default they have metadata.

**Comment by davkean** [comment]
Open CPS bug: https://devdiv.visualstudio.com/DevDiv/_workitems?id=383812&fullScreen=false&_a=edit.

**Comment by srivatsn** [comment]
Closing since this is tracked by the CPS bug.
