### ISSUE TITLE
Build Failure: Console App (multitfm) - > Class Library (.Net Framework) 

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn-project-system#1546]
**Repro Steps** 
- Create a Console App (.Net Core ) 
- edit csproj and put below ..
```
<PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>netcoreapp1.0;net452;netstandard1.4</TargetFrameworks>
    <RuntimeIdentifier>win7-x64</RuntimeIdentifier>
  </PropertyGroup>
```

- Build ( close and reopen the project to workaround another bug) 
- Add Class Library (.Net Framework ) 
- Add reference from Console to Class Libary 
- Build 

- Add a Static method to Class Library 
- Call that from console application.

- Build 

**Expected** 
Builds successfully 

**Actual**
error CS0012: The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.

**Build** 
26212.0.d15rel

Sample Project :\\mlangfs1\public\Jinuj\TestCases\CoreToNetFramework.zip

**Comment by srivatsn** [comment]
Are you conditioning the ProjectReference to ensure that only the net452 target references the class library? Otherwise yes referencing a framework library from a necoreapp target is not supported.

**Comment by jinujoseph** [comment]
Modifying the console App to below 

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net452;netcoreapp1.0;netstandard1.4</TargetFrameworks>
    <RuntimeIdentifier>win7-x64</RuntimeIdentifier>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CL_framework\CL_framework.csproj" Condition="'$(TargetFramework)' == 'net452'" />
  </ItemGroup>

</Project>
```

Gives me build error 
Program.cs(9,46,9,58): error CS0103: The name 'CL_framework' does not exist in the current context

**Comment by jinujoseph** [comment]
ok i figured out that i need to contion the call as well 
#if NETFX
            Console.WriteLine(CL_framework.Class1.Foo());
#endif
