### ISSUE TITLE
Create integration test to verify multi target framework

### ISSUE THREAD

**Issue by piotroko** [dotnet/roslyn-project-system#1547]
We need to create an integration test verifying “multi- Target Framework Moniker
” features.

**Comment by johnbeisner** [comment]
create a .Net core project
edit csproj - changing to a multi-target framework project
verify the change
-combined intellisense
-language service
-diagnostics shows up for all frameworks
-navigation bar in the editor lists all the frameworks
-context switch between all the frameworks
-building generates artifacts for each framework

**Comment by johnbeisner** [comment]
commit 0df1ac55417ef29f4893a29aff756e1bb816e249
