### ISSUE TITLE
Visual Studio .NET 2015 can't open migrated project

### ISSUE THREAD

**Issue by deastr** [dotnet/roslyn-project-system#1558]
I've an ASP.NET Core project and I've successfully migrated it using "`dotnet migrate`". The problem is VS.NET 2015 can't open it. I'm trying to add it to an existing project but getting this error:

`The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBUild 2003 format, please add xmlsn="http://schemas.microsoft.com/developer/msbuild2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.`

I've checked the MSBuild repository but there aren't any installers, only source code.

What should I do?

I'm using VS.NET 2015 Update 3

```
dotnet --info:

.NET Command Line Tools (1.0.0-rc4-004771)

Product Information:
 Version:            1.0.0-rc4-004771
 Commit SHA-1 hash:  d881d45b75

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0-rc4-004771
```

**Comment by davkean** [comment]
You can only open migrated projects in Visual Studio 2017. You can download a free version here: https://www.visualstudio.com/vs/visual-studio-2017-rc/.

**Comment by deastr** [comment]
@davkean : Does this mean that VS.NET 2015 won't be supported? Will VS.NET 2017+ be required for the new format?

**Comment by davkean** [comment]
Yes, that is correct.
