### ISSUE TITLE
.NET Core projects should build using .NET Core MSBuild

### ISSUE THREAD

**Issue by wjk** [dotnet/roslyn-project-system#1560]
The title really says it all. I am using custom MSBuild tasks that are written for the .NET Core version of MSBuild, to ensure compatibility with `dotnet build`. However, when I try to build my project in Visual Studio, it builds the project using the full-framework version of MSBuild, which then complains it cannot find the .NET Core runtime libraries (`System.Runtime` et al). I am using VS 2017 RC4 build 20206. Thanks!

**Comment by davkean** [comment]
We're aware of this, and is something that won't be tackled in the short term (there's lots of dependencies that VS has on desktop MSBuild, it's non-trivial to switch it out).

In the meantime, you should be targeting .NET Standard for your build tasks to run both on .NET Framework and .NET Core.

**Comment by wjk** [comment]
@davkean I changed my two task DLLs to reference `netstandard1.3` instead of `netcoreapp1.1`. I still get a DLL-not-found error, though, this time for `System.Runtime.InteropServices.RuntimeInformation`. I cannot target any lower version of .NET Standard, because 1.3 is the lowest version the MSBuild DLLs themselves target. What am I doing wrong here? Thanks!

**Comment by davkean** [comment]
You need to carry that dll with you.

**Comment by wjk** [comment]
Yep, that did it. Thanks for your assistance!
