### ISSUE TITLE
VS 2017 UI thread not responding after upgrading an ASP.NET Core project

### ISSUE THREAD

**Issue by ncarandini** [dotnet/roslyn-project-system#1561]
## UI thread not responding after upgrading an ASP.NET Core project from VS 2015 project.json to VS 2017 .csproj
Repro: https://github.com/ncarandini/VS2017RC4-issue
Video: https://1drv.ms/v/s!Au9T1EY0TwHfnqgkqT3sVOQ45ixVXQ

### Issue description
After the conversion successfully completed, the VS UI stopped to respond to my mouse input. I’ve opened the task manager and found that the app was really busy to do something with more than 37% of CPU. So I’ve just waited for some time, but eventually I killed the process. Alas, opening the same (now converted) project from a new instance of VS gave the same result. The VS process was very busy doing something and the UI thread non responding to my input.
 
Trying some other times to open the same solution after killing the VS process, I’ve noted that the UI stopped to work while trying to move from the showed file source to another one.

### Workaround
The fact that opening the converted solution showed the same files that were shown on VS2015 was a clear indication that the .vs hidden folder wasn’t (probably) changed by the conversion process.
 
So I did backup the .vs folder (for your inspection, if needed) and deleted it. And voilà, the VS 2017 recreated it and everything went back to normal.

### Repro instruction
1) Clone my project: https://github.com/ncarandini/VS2017RC4-issue
2) Open the solution with VS2017 and convert it.

You should end with the converted project and VS showing many source files. If you move to another tab the UI stop responding.

### Video
The video shows:
1) The conversion and VS stop responding
2) Opening the converted project an VS still stop responding
3) Deleting the .vs folder and opening the VS once again, with all passing with flying colors

**Comment by mavasani** [comment]
Thanks for the detailed report @ncarandini. I am unable to repro this issue on our latest VS2017 drops (d15rel 26213.1), most likely this is the deadlock issue that recently got fixed.

**Comment by davkean** [comment]
This is very likely the Roslyn hang. 

@ncarandini if you can still repro it, I can make 100% sure that it is if you create me a dump, launch %WINDIR%\SysWow64\Taskmgr.exe (must be 32-bit), right click on Visual Studio and click _Create dump file_.

**Comment by ncarandini** [comment]
Hi David,
I’ve already done it, you can find it here: https://1drv.ms/u/s!Au9T1EY0TwHfnqgl87mF00tbrHWsNA

Nicolò

Da: David Kean [mailto:notifications@github.com]
Inviato: martedì 14 febbraio 2017 22:24
A: dotnet/roslyn-project-system <roslyn-project-system@noreply.github.com>
Cc: Nicolò Carandini <n.carandini@outlook.com>; Mention <mention@noreply.github.com>
Oggetto: Re: [dotnet/roslyn-project-system] VS 2017 UI thread not responding after upgrading an ASP.NET Core project (#1561)


This is very likely the Roslyn hang.

@ncarandini<https://github.com/ncarandini> if you can still repro it, I can make 100% sure that it is if you create me a dump, launch %WINDIR%\SysWow64\Taskmgr.exe (must be 32-bit), right click on Visual Studio and click Create dump file.

**Comment by ncarandini** [comment]
@davkean can you please check if you can successfully open the [Entropy solution](https://github.com/aspnet/Entropy) with your version of VS2017 RC (next) ?
Today I had the same experience: I've opened the solution with VS2017RC4 and the UI stopped responding, with a mean of 37% CPU shown in the Task Manager.
I deleted the .vs folder, reopened the solution and solved the issue.

**Comment by davkean** [comment]
I cannot repro this either RC4 or the latest internal builds we have, on either Entropy or your repro solution.

The dump you created, doesn't look like a deadlock - it looks like it's doing work inside WPF. 

Is this a 100% repro for you?

**Comment by ncarandini** [comment]
This is really odd.
Today I'll install VS2017RC4 on another PC so I can try to reproduce it on another PC.

For the dump, as shown on the video I've made (linked on the first post of this thread), VS2017RC4 doesn't freeze and still respond to the Task Manager. The issue is about the UI thread not responding, and the task using more that 35% of CPU time, most likely on the process UI thread, blocking the UI responsiveness.

Too bad is not reproducible at your side. Let's see if is something only related to my PC, where I use to have VS2015 and VS2017RC3 SxS and now only VS2017RC4, so maybe on the install/uninstall/update processes something is creating this issue only here, in a sort of "Doesn't work on my machine".

If I'll not be able to repro on my other PC, I'll ask to close this issue.

**Comment by ncarandini** [comment]
The Entropy project is now already converted to VS2017 in GitHub, so it's no more a valid repro.
