### ISSUE TITLE
Project System calls nuget nominate API over and over again

### ISSUE THREAD

**Issue by zhili1208** [dotnet/roslyn-project-system#1565]
https://github.com/NuGet/Home/issues/4575
repro Steps:
Take a copy of \mlangfs1\public\Jinuj\TestCases\MultiTargetting\MultiTargetting to your machine
Delete the CoreLib and Lib Folder
your folder structure should look like this
![image](https://cloud.githubusercontent.com/assets/12449387/22901598/1cad2dce-f1e7-11e6-8a7d-2149c79bc0b4.png)
now open the solution and it should repro

Roslyn project system keep calling NuGet nominate API over and over again here.

I removed project reference and .netcoreapp package reference from client.csproj. This issue still repros.

When I remove the . Microsoft.NET.Sdk package reference, it will not repro any more.
@natidea @jinujoseph

**Comment by srivatsn** [comment]
Using the SDK as a packagereference is not supported. Those were RC1 style projects that need to be converted to use the SDK attribute. 

That entire project should look like this instead:

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp1.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\CoreCL\CoreCL.csproj" />
  </ItemGroup>
</Project>
```
