### ISSUE TITLE
Build Tab Error

### ISSUE THREAD

**Issue by doktrova** [dotnet/roslyn-project-system#1567]
This is happening when creating Net Standard 1.6  Class Library Project.

**An error occurred trying to load the page.
Conversion from string "" to type 'Boolean' is not valid.**

This is my _csproj_ file:

```
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" />
  <PropertyGroup Label="Globals">
    <SccProjectName>SAK</SccProjectName>
    <SccProvider>SAK</SccProvider>
    <SccAuxPath>SAK</SccAuxPath>
    <SccLocalPath>SAK</SccLocalPath>
    <ProjectGuid>{2ABBEB18-B298-4ADC-A379-C26033A572D0}</ProjectGuid>
    <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
    <Platform Condition=" '$(Platform)' == '' ">AnyCPU</Platform>
  </PropertyGroup>
  <PropertyGroup>
    <TargetFramework>netstandard1.6</TargetFramework>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug|AnyCPU'">
    <PlatformTarget>AnyCPU</PlatformTarget>
    <DebugSymbols>true</DebugSymbols>
    <DebugType>full</DebugType>
    <Optimize>false</Optimize>
    <OutputPath>bin\Debug\</OutputPath>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release|AnyCPU'">
    <PlatformTarget>AnyCPU</PlatformTarget>
    <DebugType>pdbonly</DebugType>
    <Optimize>true</Optimize>
    <OutputPath>bin\Release\</OutputPath>
    <DefineConstants>TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>
  <PropertyGroup Label="Configuration">
    <RootNamespace>TypedLogic.Common</RootNamespace>
    <AssemblyName>TypedLogic.Common</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Interfaces\ILogger.cs" />
    <EmbeddedResource Include="**\*.resx" />
  </ItemGroup>
  <Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />
</Project>
```

**Comment by srivatsn** [comment]
Are you on the latest update to the RC? (Can you check the version of VS in Help->About)? There was a bug in this area that was fixed in one of the recent updates.

Also this project is not using the SDK anywhere or pulling in NETStandard.Library and so this project will build as a library targeting .NET 4.0 app. 

With the latest RC, your project can look like this:
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard1.6</TargetFramework>
  </PropertyGroup>
</Project>
```

This is assuming that:
- your csproj is called TypedLogic.Common.csproj so that the RootNamespace and AssemblyName get their value from the name of the csproj.
- That you have just that one cs file (The default is to include **\*.cs)

**Comment by doktrova** [comment]
Thank you @srivatsn ! Adding Sdk="Microsoft.NET.Sdk" to my project tag fixed the issue. Not sure why it wasn't there in the first place.

**Comment by davkean** [comment]
@doktrova Above project looks like you've converted a normal .NET Framework project, is that correct?

**Comment by doktrova** [comment]
@davkean No that one I  started as standard library not in the latest RC Build. It just stopped working so I  changed the target framework a bunch of times to see if I can get it to work.
