### ISSUE TITLE
VS crash if you add a wrong condition to project reference 

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn-project-system#1568]
**Repro Steps**

- Create Console Application (.Net Core)
- Create Class Library (.Net Framework) 
- Add reference from Console to class library 
- Build 
- Edit Console Application and add following condition to the 
```
<ItemGroup>
    <ProjectReference Include="..\ClassLibrary1\ClassLibrary1.csproj" Condition="net452" />
  </ItemGroup>
```

**Expected** 
We should probably indicate there is a wrong input and unload that project

**Actual**
VS will crash

Note: Right way to condition this is 

```
<ItemGroup>
    <ProjectReference Include="..\ClassLibrary1\ClassLibrary1.csproj" Condition="'$(TargetFramework)' == 'net452'" />
  </ItemGroup>
```

Build : 26213.d15rel

**Comment by davkean** [comment]
VS crashes?

**Comment by davkean** [comment]
Dup'ing against an uber issue tracking this: https://github.com/dotnet/roslyn-project-system/issues/1570

**Comment by jinujoseph** [comment]
just to answer the question, it was a crash for me
