### ISSUE TITLE
Dependency tree missing dependencies

### ISSUE THREAD

**Issue by davidfowl** [dotnet/roslyn-project-system#1578]
Not sure what caused but when I update the ASP.NET Core package to 1.2.0-* from our myget feed the dependencies for the `Microsoft.AspNetCore` package disappear. If you look at the screenshot below, there's a picture of the 1.1.0 project template for ASP.NET Core and a modified template that uses 1.2.0-*.

![image](https://cloud.githubusercontent.com/assets/95136/23013410/4fbbd572-f3df-11e6-90bb-c3aec189293c.png)

Here are the project files:

1.1.0

```XML
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp1.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="wwwroot\" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.0.0" />
    <PackageReference Include="Microsoft.AspNetCore" Version="1.1.0" />
  </ItemGroup>
</Project>
```

1.2.0

```XML
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp1.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="wwwroot\" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore" Version="1.2.0-*" />
  </ItemGroup>

</Project>
```

/cc @abpiskunov

**Comment by abpiskunov** [comment]
This type of issues should be addressed by a PR that is pending now and should be submitted today.

Thanks,
Anton

On Feb 16, 2017, at 12:34 AM, David Fowler <notifications@github.com<mailto:notifications@github.com>> wrote:


Not sure what caused but when I update the ASP.NET<http://ASP.NET> Core package to 1.2.0-* from our myget feed the dependencies for the Microsoft.AspNetCore package disappear. If you look at the screenshot below, there's a picture of the 1.1.0 project template for ASP.NET<http://ASP.NET> Core and a modified template that uses 1.2.0-*.

[image]<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcloud.githubusercontent.com%2Fassets%2F95136%2F23013410%2F4fbbd572-f3df-11e6-90bb-c3aec189293c.png&data=02%7C01%7Canton.piskunov%40microsoft.com%7C8981530c210f4de93e5f08d456469336%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636228308493786837&sdata=pshsIFgCQ4w3yPGxCtsn4YHYSxiY3OFjWy5aevxEi7g%3D&reserved=0>

Here are the project files:

1.1.0

<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp1.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="wwwroot\" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.0.0" />
    <PackageReference Include="Microsoft.AspNetCore" Version="1.1.0" />
  </ItemGroup>
</Project>

1.2.0

<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp1.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="wwwroot\" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore" Version="1.2.0-*" />
  </ItemGroup>

</Project>

/cc @abpiskunov<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fabpiskunov&data=02%7C01%7Canton.piskunov%40microsoft.com%7C8981530c210f4de93e5f08d456469336%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636228308493786837&sdata=novEtVBngBqt7JskIWd4jrDnUwLqutY25eM2IZncVmQ%3D&reserved=0>

**Comment by srivatsn** [comment]
This should be fixed by https://github.com/dotnet/roslyn-project-system/pull/1469
