### ISSUE TITLE
Known list of elements that can be removed from project file

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn-project-system#158]
__Note:__ This is a work in progress.

This a list of known elements that appear in templates today that can be removed:

#### DefaultTargets attribute
``` XML
<Project DefaultTargets="Build" ...>
</Project>
```
DefaultTargets defaults to "Build" in Microsoft.Common.CurrentVersion.targets.

#### AppDesigner Item
``` XML
<ItemGroup>
  <AppDesigner Include="My Project"/>
</ItemGroup>
```

AppDesigner folder is indicated via the `AppDesignerFolder` _property_ for both C# and VB, not via this item.

#### AppDesignerFolder property
``` XML
<PropertyGroup>
  <AppDesignerFolder>Properties</AppDesignerFolder>
</PropertyGroup>
```

AppDesignerFolder defaults to "Properties" for C# and "My Project" for VB, we do not need to list the default in the project.

#### BeforeBuild/AfterBuild targets

``` XML 
  <!-- To modify your build process, add your task inside one of the targets below and uncomment it. 
       Other similar extension points exist, see Microsoft.Common.targets.
  <Target Name="BeforeBuild">
  </Target>
  <Target Name="AfterBuild">
  </Target>
  -->
```

These are commented out and only add noise.

**Comment by jmarolf** [comment]
[fixed with interal PR](https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_git/VS/pullrequest/39480)
