### ISSUE TITLE
VS 2017 RC - Solution Explorer cuts off Publish window

### ISSUE THREAD

**Issue by scottaddie** [dotnet/roslyn-project-system#1592]
Create a new ASP.NET Core project targeting .NET Core, using the Web Application project template. Right-click the project in Solution Explorer, and select **Publish**. Notice the empty black area to the left of Solution Explorer that cuts off the Publish window's Folder icon/option (outlined in red below).

![publish_window_bug](https://cloud.githubusercontent.com/assets/10702007/23099057/984284f8-f623-11e6-938b-f9ab6c400b0c.png)

I'm using VS 2017 RC on Windows 10 (v1607) with a display resolution of 3,200 x 1,800. Dragging the Solution Explorer splitter further to the left indicates that the aforementioned empty black area is attached to the Solution Explorer window.

@morrisjoe

**Comment by mlorbetske** [comment]
Hi @scottaddie, moving this to https://github.com/aspnet/Tooling/issues/1000
