### ISSUE TITLE
Go To Defintion does not work with more than one TargetFrameworks and extension methods

### ISSUE THREAD

**Issue by srivatsn** [dotnet/roslyn-project-system#1598]
Reported through [VS Feedback](https://developercommunity.visualstudio.com/content/problem/20625/go-to-define-not-works-well-with-more-than-one-tar.html)

1. create an new netstandard library;
2. modify `<TargetFramework>netstandard1.4</TargetFramework>` to `<TargetFrameworks>netstandard1.4;net46</TargetFrameworks>`;
3. Add an `PackageReference` to Dapper;
4. Add an cs file as below;
5. switch between netstandard1.4 and net46, and press F12;

Expect: Go to the define for the both TargetFramework
Actual: VS say can not found the define for one of the TargetFrameworks

The project files:
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard1.4;net46</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="1.50.2" />
  </ItemGroup>

</Project>
```
```cs
using Dapper;
using System.Data.SqlClient;

namespace ClassLibrary1
{
    public class Test
    {
        public void T()
        {
            new SqlConnection().Execute("");
            //                  ^switch between net46/netstandard1.4, and press F12 here, 
        }
    }

}
```

**Comment by mavasani** [comment]
Doesn't repro on the latest bits.
