### ISSUE TITLE
Inconsistent slash when changing item type

### ISSUE THREAD

**Issue by sayedihashimi** [dotnet/roslyn-project-system#1605]
I created a new ASP.NET Core project and I modified two files from `Content` to `None`. After doing that I noticed that it uses a mix of `\` and `/`. Shouldn't we be consistent here and exclusively use one or the other?

```xml
  <ItemGroup>
    <None Include="wwwroot/css\site.css" />
    <None Include="wwwroot/images\banner1.svg" />
  </ItemGroup>
```

Another minor note which may already be tracked. Before modifying the item type from `Content` to `None` I had the `.csproj` file opened (via the Edit project gesture in solution explorer) and the changes were not reflected in the project file that was opened in the editor.

**Comment by davkean** [comment]
Closed in lieu of https://devdiv.visualstudio.com/DevDiv/Managed%20Project%20System/_workItems?id=397480&fullScreen=false&_a=edit
