### ISSUE TITLE
Referencing a higher framework project shows different errors in error list and output window

### ISSUE THREAD

**Issue by BillHiebert** [dotnet/roslyn-project-system#1606]
1. New Class Libary (DotNet core)
2. Add New Console application (DotNet core)
3. Reference the class library from the console application
4. Edit the console applications project file and change the TFM from .netcoreapp1.1 to .netcoreapp1.0
5. Build the console applicatoin
Output window shows two errors, the first one is useful, then 2nd is confusing
```
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.Sdk.Common.targets(73,5): error : Project 'c:\users\billhie\documents\visual studio 2017\Projects\ConsoleApp1\ClassLibrary1\ClassLibrary1.csproj' targets '.NETCoreApp,Version=v1.1'. It cannot be referenced by a project that targets '.NETCoreApp,Version=v1.0'.
Done building project "ClassLibrary1.csproj" -- FAILED.
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.Sdk.targets(92,5): error : Cannot find project info for 'c:\users\billhie\documents\visual studio 2017\Projects\ConsoleApp1\ClassLibrary1\ClassLibrary1.csproj'. This can indicate a missing project reference.
Done building project "ConsoleApp1.csproj" -- FAILED.
```
The error list only shows one error and unfortunately it is the 2nd one.

![image](https://cloud.githubusercontent.com/assets/1553785/23272029/9081bc00-f9ae-11e6-855e-81a68dfb3f27.png)

**Comment by davkean** [comment]
This issue was moved to dotnet/sdk#910
