### ISSUE TITLE
Opening a source file in Mutil-TF project doesn't set the correct editor navigation context bar value

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn-project-system#1613]
1. Create a new C# net core app
2. Add a new source file to the project
3. Change TF -> TFs with "netstandard1.4;net46" and reload project
4. Close all source files and close solution
5. Re-open solution and open one of the source files in the project
6. Switch editor navigation context bar value from netstandard1.4 to net46
7. Now open the second file in the project

**Expected:** Editor navigation context bar for the second source file has net46 as the active TF

**Actual:** Editor navigation context bar for the second source file has netstandard1.4 as the active TF

**Comment by abpiskunov** [comment]
just tried in latest rel branch from yesterday 26223 and it seems that tfms in the editor combo are listed alphabetically now and when i open any cs file first time - active tfm is set to whatever is first alphabetically, not the first in the TargetFrameworks property.

**Comment by mavasani** [comment]
> just tried in latest rel branch from yesterday 26223 and it seems that tfms in the editor combo are listed alphabetically now and when i open any cs file first time - active tfm is set to whatever is first alphabetically, not the first in the TargetFrameworks property.

This is by design, and even true for shared projects. I don't think we control the ordering of projects in navigation bar, it always alphabetizes it. @dpoeschl  to confirm.

**Comment by mavasani** [comment]
Just to clarify - I meant the ordering in navigation bar is by design. However, we should be setting the active context to match the first TFM, not the one that comes alphabetically first.

I debugged further into this and the issue seems to be how Roslyn is computing the active context. I am testing a fix.

**Comment by abpiskunov** [comment]
Ordering is fine - i am talking about incorrect project+trm item selected in the list there. First one is selected - not the one that corresponds to Active TFM.

**Comment by mavasani** [comment]
@abpiskunov Can you give your explicit repro steps? I am unable to repro your scenario on the latest build with following steps:

1. Create a C# netstandard library
2. Change TF -> TFs `<TargetFrameworks>netstandard1.4;net46</TargetFrameworks>` so that second TF is alphabetically first.
3. Close and reload solution
4. Class1.cs opens with active navigation context set to netstandard1.4, which is second in the navigation context bar.

**Comment by abpiskunov** [comment]
yep - i did same repro steps you did. Probably it was fixed with some of the latest changes? i saw that on week old build.
