### ISSUE TITLE
Csproj intellisense

### ISSUE THREAD

**Issue by byyyt** [dotnet/roslyn-project-system#1619]
Have the latest VS 2017 RC. Trying out the new csproj based .NET Core project.

Question: Is there supposed to be intellisense of any kind when editing csproj? Even for basic stuff like **OutputType** and **TargetFramework**.
Cause I have only Autocompletion for existing elements, but no Intellisense.
Not sure if there is a problem, or it's just not implemented.

Another question: Is there a documentation draft/wiki on the new csproj format? What kind of settings are available, the format, etc. Can find anything for the "modern" csproj.

**Comment by 333fred** [comment]
@byyyt, how are you editing the project file? I tested this with the latest internal build and have intellisense working correctly. @RaulPerez1

**Comment by byyyt** [comment]
Well, Open the project file with "Edit <name>.csproj" from context menu. Nothing fancy, just default Console project file. Well I do have the "latest" publicly available VS 2017 Enterprise RC.

**Comment by RaulPerez1** [comment]
> Cause I have only Autocompletion for existing elements, but no Intellisense.

I think that what you're seeing is what's currently implemented, e.g. you're getting the list with available tags but you don't get a list of available values once the tag is inserted. Can you confirm that my statement is accurate into what you're seeing and expecting?

**Comment by srivatsn** [comment]
This requires a msbuild language service which is tracked by https://github.com/dotnet/roslyn-project-system/issues/766
