### ISSUE TITLE
Decorator settings for TypeScript in the new csproj format

### ISSUE THREAD

**Issue by deastr** [dotnet/roslyn-project-system#1621]
There are two settings in VS.NET 2015 csproj: `<TypeScriptEmitDecoratorMetadata>` and `<TypeScriptExperimentalDecorators>`. Are these settings in the new format? If not, will they be?

**Comment by srivatsn** [comment]
I don't know what component was reading these properties but whoever it was will continue to read it, if that scenario is still supported. I suggest asking about the scenario on https://github.com/aspnet/tooling
