### ISSUE TITLE
Shared project don't have icon in deeper hierarchies for GraphNodes

### ISSUE THREAD

**Issue by abpiskunov** [dotnet/roslyn-project-system#1623]
![image](https://cloud.githubusercontent.com/assets/1592091/23324663/fed633b6-faa3-11e6-8b8d-57c3e8bbd4ac.png)

**Comment by abpiskunov** [comment]
Fix is easy, just add it to the icons collection at line 65: https://github.com/dotnet/roslyn-project-system/blob/master/src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/Tree/Dependencies/ProjectDependenciesSubTreeProvider.cs#L65

**Comment by davkean** [comment]
Let me take this so that I can get some experience in the dependency node side of things.

**Comment by davkean** [comment]
@abpiskunov Why _do_ we show nested Shared Projects? They aren't included in parent projects like project references.
