### ISSUE TITLE
Solution level stylecop.json & stylecop.ruleset

### ISSUE THREAD

**Issue by prasannapattam** [dotnet/roslyn-project-system#1626]
I have a solution with multiple projects in it. I want to define the same stylecop configuration and ruleset for all projects in the solution. In Visual Studio 2015, I used to define this configuration like this in project.json

  "buildOptions": {
   "additionalArguments": [ "/ruleset:../../../stylecop.ruleset", "/additionalfile:../../../stylecop.json" ]
  }

I define stylecop.ruleset and stylecop.json as the solution items (only once) and specify the relative path in each project.json. 

How can I do this in VS 2017 csproj.

**Comment by davkean** [comment]
The equivalent of this is to create a file called "Directory.Build.props" alongside your solution (or in any parent folder above the project) and add the following props pointing to this:

``` XML
<Project>

  <PropertyGroup>
    <CodeAnalysisRuleSet>stylecop.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>

  <ItemGroup>
    <AdditionalFiles Include="stylecop.json" />
  </ItemGroup>
  
</Project>
```

Note, you'll can also make use of one of the [MSBuild reserved properties](https://msdn.microsoft.com/en-us/library/ms164309.aspx), such as $(MSBuildThisFileDirectory) in front of the file names to get paths that resolve correctly for all projects regardless of where they are in the tree.

**Comment by prasannapattam** [comment]
That worked. Thanks.

I defined the props file at the solution level and used  $(MSBuildThisFileDirectory) for the full path.
