### ISSUE TITLE
Why does VS2017 RC write Compile elements into the .csproj file

### ISSUE THREAD

**Issue by blackdwarf** [dotnet/roslyn-project-system#1643]
Moving from dotnet/cli#5837 on behalf of @bruce31

## Steps to reproduce
Use VSCode and cli tools to create a class library csproj targetting net461 that happens to include a class that inherits from a windows form control.
This builds happily with dotnet build

Open project with VS2017 RC

## Expected  behavior
csproj file should not be altered 
Especially references to .cs files should not be introduced.

## Actual behavior
.csproj file updated with

` <ItemGroup>`
`    <Compile Update="Dialogs\AssemblyDialog.cs">  `
`       <SubType>Form</SubType>  `
`   </Compile> `
`</ItemGroup>`

**Comment by davkean** [comment]
Yes this is known, see: https://github.com/dotnet/roslyn-project-system/issues/182 which is tracking it.

We haven't yet brought up "WinForms" support - this will be part of that.
