### ISSUE TITLE
Modifying a project adds BOM at the start of the project

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn-project-system#1651]
1. File -> New Project
2. Check Create new Git repository
3. Right-click on project and choose Edit
4. CTRL+S

Expected: For no changes to the project
Actual: The project has changes if you run git diff you see:

``` XML
-<Project Sdk="Microsoft.NET.Sdk">
+<EF><BB><BF><Project Sdk="Microsoft.NET.Sdk">

   <PropertyGroup>
     <OutputType>Exe</OutputType>
```

**Comment by davkean** [comment]
No idea who's bug this is @333fred.

**Comment by 333fred** [comment]
This is an msbuild issue, I'll move it over there. The issue is that we assume, in the absence of a utf header, that the default encoding of a file is UTF-8 w/ BOM, even if the file's original encoding was UTF-8 w/o BOM.

**Comment by 333fred** [comment]
This issue was moved to Microsoft/msbuild#1768
