### ISSUE TITLE
Cannot remove the AnyCpu platform

### ISSUE THREAD

**Issue by BillHiebert** [dotnet/roslyn-project-system#1662]
1. New DotNet Core console application 
2. Open solution configurations and add an x64 platform
3. In the platform dropdown for the project there should be two platforms: x64 and AnyCpu.  Choose Edit... and remove the AnyCPU platform. Answer yes to the prompt to remove it.

Everything succeeds, but the platform remains. Note that you can remove the x64 platform.

**Comment by srivatsn** [comment]
This is known and I believe should be addressed with changes that @RaulPerez1 is making for https://github.com/dotnet/roslyn-project-system/issues/694
