### ISSUE TITLE
Should not show compiler errors until after the first restore

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn-project-system#1695]
1. File -> New -> Web Application (.NET Core)

--Notice that there's errors in Startup.cs, which go away after restore--

We should stop reporting errors until after the first restore and we've got something useful. Thousands of errors about types that don;t exist yet because we've not restored is not helpful.

**Comment by srivatsn** [comment]
Dupe of https://github.com/dotnet/roslyn-project-system/issues/928
