### ISSUE TITLE
Implement VsLangProj.ProjectProperties 

### ISSUE THREAD

**Issue by RaulPerez1** [dotnet/roslyn-project-system#1709]
We've been playing whack a mole with property page issues and the right fix is really to implement VsLangProj.ProjectProperties which ensures more backwards compatibility with the old project system.

After the work is done we should be able to remove all of the instances of OutputTypeEx around the project system and the XAML rules.

The following issues should be fixed once it is implemented:

https://github.com/dotnet/roslyn-project-system/issues/1468
https://github.com/dotnet/roslyn-project-system/issues/1378
https://github.com/dotnet/roslyn-project-system/issues/1300
https://github.com/dotnet/roslyn-project-system/issues/1298

**Comment by basoundr** [comment]
Fixed by #1842
