### ISSUE TITLE
New .csproj cannot reference GAC assemblies

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn-project-system#1739]
You can no longer reference some GAC assemblies without specifying a HintPath, at which point there isn't much point in using the GAC at all.

Class1.cs:
```c#
using System;
using Microsoft.SolverFoundation.Services;

public class Class1
{
    public static readonly Type X = typeof(ISolver);
}
```

Old .csproj, working:
```xml
<Project ToolsVersion="15.0">
  <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" />
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFrameworkVersion>v4.6.2</TargetFrameworkVersion>
    <OutputPath>bin\$(Configuration)\</OutputPath>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Microsoft.Solver.Foundation" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="*.cs" />
  </ItemGroup>
  <Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />
</Project>
```

New .csproj fails to find the reference:
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net462</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Microsoft.Solver.Foundation" />
  </ItemGroup>

</Project>
```

This also does not work: `<Reference Include="Microsoft.Solver.Foundation, Version=3.0.2.10889, Culture=neutral, PublicKeyToken=31bf3856ad364e35" />`.

Why is this broken?

**Comment by jnm2** [comment]
I'm also witnessing a weird phenomenon where some GAC assemblies *can* be referenced and the build succeeds, but Visual Studio shows build warnings and reference node warning icons saying the reference could not be resolved and if you open any of the .cs files, the editor creates a whole bunch of errors as though the reference was not referenced at all. The weird part is, it _builds_ fine. For example, `<Reference Include="DevExpress.Data.v16.2, Version=16.2.4.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a, processorArchitecture=MSIL">`.

But the moment I add a `<SpecificVersion>false</SpecificVersion>` or a <SpecificVersion>true</SpecificVersion>` subelement, it goes back to not building at all.

I would really like to understand this phenomenon.

I don't want to use HintPaths because of the chance something will be different across developer machines and the build server, and why should I have to add ugly GAC paths?

**Comment by jnm2** [comment]
As it turns out, HintPath with SpecificVersion false is not a useful workaround because the HintPath does not exist on different machines.

**Comment by jnm2** [comment]
Adding this to the bottom of the new csproj and reopening the solution fixes all problems:

```xml
  <!-- Workaround for https://github.com/dotnet/roslyn-project-system/issues/1739 -->
  <PropertyGroup>
    <AssemblySearchPaths>$(AssemblySearchPaths);{GAC}</AssemblySearchPaths>
  </PropertyGroup>
```

**Comment by jmarolf** [comment]
I can repro this.  I'll need to look into what has changed regarding the GAC.

This should work in the mean time.

```XML
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net462</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Solver.Foundation" Version="3.1.0" />
  </ItemGroup>

</Project>
```

**Comment by davkean** [comment]
This issue was moved to dotnet/sdk#987
