### ISSUE TITLE
New dotnet core project class library create a netcoreapp1.0 target framework instead of netstandard

### ISSUE THREAD

**Issue by cdie** [dotnet/roslyn-project-system#1753]
When creating a new dotnet core project class library in VS 2017, I always got a netcoreapp1.1 as targetframework, whereas I expect to have netstandard1.6 (or another version, which I would like to chosse when creating library, just like full framework targeting).

**Comment by davkean** [comment]
To create a .NET Standard library, you need to choose the _Class Library (.NET Standard)_ template. The _Class Library (.NET Core)_ is akin to the _Class Library (.NET Framework)_ where it lets you use surface area that specific to .NET Core and is outside of the .NET Standard.
