### ISSUE TITLE
ServiceHub.RoslynCodeAnalysisService32.exe stays running after VS has been closed

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/roslyn-project-system#1770]
I haven't been able to reproduce this issue but after closing VS gracefully the ServiceHub.RoslynCodeAnalysisService32 process stayed running and kept a handle on several DLLs.

Wasn't sure what information was needed to properly diagnose the issue so I took a dump of the process: `\\NTaylorMullen\SHARED\Dumps\ServiceHub.RoslynCodeAnalysisService32.DMP`

**Comment by davkean** [comment]
This issue was moved to dotnet/roslyn#17920
