### ISSUE TITLE
Roadmap update and broken links

### ISSUE THREAD

**Issue by shaggygi** [dotnet/roslyn-project-system#1792]
I noticed on the [Roadmap](https://github.com/dotnet/roslyn-project-system/blob/bb931d8a8710a26c393cddc863664fbe4b76f8d4/docs/repo/Roadmap.md) page the feature link point to older Roslyn labels from before moving to this repo.  I would update, but there are many separated labels now.

Also, would it be possible to add a few updates to the next couple of planned releases on this page?

Thx

**Comment by davkean** [comment]
Yeah, I've been meaning to do this - will update it this week.
