### ISSUE TITLE
Xml documentation file not created by MSBuild

### ISSUE THREAD

**Issue by gmsDave** [dotnet/roslyn-project-system#1793]
I have an asp.net core web api project that I have recently converted from project.json to .csproj.  I am using Swashbuckle to generate a Swagger UI which relies on the generated xml documentation file.  In project.json, this was created using and "xmlDoc": "true" element in the "buildOptions". In .csproj, it looks like this was converted to a GenerateDocumentationFile element in a PropertyGroup xml.  All seems well - when I build and run the project through VS2017, the file is created and the swagger UI works as expected:

![image](https://cloud.githubusercontent.com/assets/18301427/24087802/236b326a-0ce9-11e7-8070-695d5834730d.png)

Taking a look at the bin folder and the expected .xml file exists

![capture4](https://cloud.githubusercontent.com/assets/18301427/24087834/6d4cf7a6-0ce9-11e7-8074-ce547259f64c.jpg)

When I run a build, either through TFS (on-prem) using the Visual Studio Build task:

![image](https://cloud.githubusercontent.com/assets/18301427/24087847/988c921e-0ce9-11e7-90ff-ebc95dd345d3.png)

or from a command line:

![capture2](https://cloud.githubusercontent.com/assets/18301427/24087959/9aead0d8-0cea-11e7-8198-a94dbe85b9f7.JPG)

the xml doc file isn't generated:

![capture3](https://cloud.githubusercontent.com/assets/18301427/24088089/ec79d6fa-0ceb-11e7-9fff-84e98f1f35ab.png)

I'm wondering if this is a bug or if there is a switch or option that I need to enable. Here is a snippet of my .csproj file:

![capture1](https://cloud.githubusercontent.com/assets/18301427/24088008/2d42896c-0ceb-11e7-81ae-1b0fd0ca713f.JPG)

Note that I am targeting the full .net framework - not sure if that matters.  Here is the build log from the TFS task: 

[6_Build solution CIMS.NETCIMS.sln.txt](https://github.com/dotnet/roslyn-project-system/files/853882/6_Build.solution.CIMS.NETCIMS.sln.txt)

and here is from the manual one I did from the command line:

[manual_build.txt](https://github.com/dotnet/roslyn-project-system/files/853883/manual_build.txt)

**Comment by davkean** [comment]
Ah, thought this was not occurring when building though VS, however, it is. I'll move this to the SDK.

**Comment by davkean** [comment]
This issue was moved to dotnet/sdk#1010
