### ISSUE TITLE
Setting PlatformTarget doesn't work for solution configuration manager

### ISSUE THREAD

**Issue by davidmatson** [dotnet/roslyn-project-system#1805]
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net452</TargetFramework>
    <RuntimeIdentifiers>win-x64</RuntimeIdentifiers>
    <AssemblyName>Testx64</AssemblyName>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>
</Project>
```

Expected:
Solution Configuration Manager shows 1 Platform: x64.

Actual:
Solution Configuration Manager shows 1 Platform: AnyCPU.

**Comment by davkean** [comment]
Thanks - we're aware of this, and tracking it a part of https://github.com/dotnet/roslyn-project-system/issues/694, which has a PR out: https://github.com/dotnet/roslyn-project-system/pull/1771.
