### ISSUE TITLE
Adding x64 project platform via solution Configuration Manager uses wrong Configuration

### ISSUE THREAD

**Issue by davidmatson** [dotnet/roslyn-project-system#1806]
With the solution in Debug configuration and the following csproj:
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net452</TargetFramework>
    <RuntimeIdentifiers>win-x64</RuntimeIdentifiers>
    <AssemblyName>Testx64</AssemblyName>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>
</Project>
```

Go to the solution's Configuration Manager, and select the Platform dropdown next to the project. Create an x64 item.

Expected:
The platform is created for all configurations (Debug and Release) or, less ideally, just the current configuration (Debug).

So:
```xml
<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'" />
<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'" />
```

or possibly:
```xml
<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'" />
```

Actual:
The platform is created only for the non-current configuration (Release):
```xml
<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'" />
```

**Comment by davkean** [comment]
Thanks - we're aware of this, and tracking it a part of https://github.com/dotnet/roslyn-project-system/issues/694, which has a PR out: https://github.com/dotnet/roslyn-project-system/pull/1771.
