### ISSUE TITLE
Can't remove AnyCPU from project platform list in solution Configuration Manager

### ISSUE THREAD

**Issue by davidmatson** [dotnet/roslyn-project-system#1807]
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net452</TargetFramework>
    <RuntimeIdentifiers>win-x64</RuntimeIdentifiers>
    <AssemblyName>Testx64</AssemblyName>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'" />
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'" />
</Project>
```

Expected:
Solution Configuration Manager lists one Platform for this project: x64

Actual:
Solution Configuration Manager lists two Platforms for this project: Any CPU and x64.
Choosing <Edit...> and Remove on the Any CPU configuration does nothing (can't delete that platform).

**Comment by davkean** [comment]
Thanks - we're aware of this, and tracking it a part of https://github.com/dotnet/roslyn-project-system/issues/694, which has a PR out: https://github.com/dotnet/roslyn-project-system/pull/1771.
