### ISSUE TITLE
Don't get XML completion in project file when you have another language installed

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn-project-system#1813]
Installed English & Japanese, don't get IntelliSense when editing project file:

![image](https://cloud.githubusercontent.com/assets/1103906/24134297/85a75bc4-0e57-11e7-9a0d-8f39a330b4ef.png)

**Comment by davkean** [comment]
@tmeschter Talk to @RaulPerez1 about how this thing is registered. Thought there was another bug on this but I cannot find it.

**Comment by davkean** [comment]
Confirmed that if switch back to English, then I get intellisense.

**Comment by RaulPerez1** [comment]
#1719 is the bug you're thinking about and has a workaround. There's a bug on the VS side tracking the bug (it's a setup issue)

**Comment by davkean** [comment]
Dup'ing against: https://github.com/dotnet/roslyn-project-system/issues/1719
