### ISSUE TITLE
Migrating a VS 2015 solution to VS 2017 does not stick

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn-project-system#1824]
_From @weshaggard on March 22, 2017 16:20_

@andre-artus commented on [Wed Mar 22 2017](https://github.com/dotnet/coreclr/issues/10389)

I have migrated a solution with .NET Core projects from 2015 to 2017, seems to work. Can build, run, publish, all the good things. 

But, when I close the solution and try to reopen it I get a "needs migration" message on the projects and the projects do not load. When this happened at first I thought maybe something went wrong so I reverted to the old state and did everything again. I'm still having the issue. I cannot work like this constantly reverting and re-migrating.

_Copied from original issue: dotnet/sdk#1030_

**Comment by 333fred** [comment]
_From @livarcocc on March 22, 2017 16:41_

@333fred Should this go to project-system?

**Comment by 333fred** [comment]
@weshaggard I believe I know what bug this is. To unblock yourself, reset your repository to the unmigrated state, and delete the .vs folder. When you reopen the solution, accept the migration prompt, and it should work correctly.

**Comment by 333fred** [comment]
Opened internal bug https://devdiv.visualstudio.com/DevDiv/_workitems?id=398791&fullScreen=false&_a=edit for this.

**Comment by andre-artus** [comment]
Thanks Fred, I just started a new solution and moved the projects to it as a workaround.

**Comment by davkean** [comment]
Closing this bug in lieu of the one above.
