### ISSUE TITLE
Project System: Backwards Compat

### ISSUE THREAD

**Issue by SamuelCox** [dotnet/roslyn-project-system#185]
Will the move from project.json to the new .csproj mean VS 15 will be required for any such project, or will there be some form of backwards compat?

**Comment by davkean** [comment]
It depends on the project type. Traditional .NET Framework-based projects will continue be able to open in both VS 2015 and VS 15. 

xproj/project.json will likely be converted automatically to csproj-based projects in VS 15, and they will not be able to be opened downlevel in VS 2015.

**Comment by davkean** [comment]
Feel free to open this if I didn't answer your question.

**Comment by SamuelCox** [comment]
Nope, that's great. Thanks! :)
