### ISSUE TITLE
PackageReference - custom project type

### ISSUE THREAD

**Issue by dazinator** [dotnet/roslyn-project-system#1858]
I have raised this issue on `VSProjectSystem` but also raising it here because I think it might be related more to Roslyn.

I have been trying to get `PackageReference` working, for my custom project type.

It seems it works fine, in that I can manage nuget packages, and the project file as well as solution explorer, looks correct.

But when editing a csharp file, Roslyn is not finding any of the referenced assemblies from the nuget package.

In the screenshot below, you can see that I added a Nuget package to my project, and that the nuget package shows up in solution explorer. I can see a `<PackageReference>` has been added correctly to my project file, but my `csharp` code won't compile because it can't find the assemblies within those referenced nuget packages:

![image](https://cloud.githubusercontent.com/assets/3176632/24332881/1f2d5cac-1246-11e7-93a2-f304fcf3fb76.png)

Here is what my project file looks like, for my custom project type:

```

<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup Label="Globals">
    <CustomProjectExtensionsPath>$(LocalAppData)\CustomProjectSystems\DnnVsProjectSystem\</CustomProjectExtensionsPath>
    <ProjectGuid>b7ef28be-b8ad-48b2-aa93-817b3cfc9deb</ProjectGuid>
  </PropertyGroup>
  <Import Project="$(CustomProjectExtensionsPath)DnnVsProjectSystem.props" />
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net45</TargetFramework>
    <OutputPath>bin\$(Configuration)</OutputPath>
    <RootNamespace>DnnVsProjectSystem27</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <None Include="**\*.txt" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="obj\**" />
    <EmbeddedResource Remove="obj\**" />
    <None Remove="obj\**" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="DotNetNuke.Core" Version="7.4.2.216" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="System.Web" />
    <Reference Include="System.Windows.Forms" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="View1.ascx.cs">
      <DependentUpon>View1.ascx</DependentUpon>
      <SubType>ASPXCodeBehind</SubType>
    </Compile>
    <Compile Update="View1.ascx.designer.cs">
      <DependentUpon>View1.ascx</DependentUpon>
      <SubType>ASPXCodeBehind</SubType>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <None Update="View1.ascx">
      <Generator>DnnAscxDesignerClassGenerator</Generator>
    </None>
  </ItemGroup>
 
  <Import Project="$(CustomProjectExtensionsPath)DnnVsProjectSystem.targets" />
  <Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />
</Project>

```

I have found that if I:

1. Unload my project, rename the extension from `dnnproj` to `csproj`
2. Remove the csharp imports

Now everything works fine, and Roslyn has no problem resolving those assemblies in the nuget packages.

I am not sure what I need to do to resolve this problem. As far as I can tell, I have all the same capaiblities, and XAML rule files enabled in my project system... Any guidance appreciated.

**Comment by dazinator** [comment]
I think I have found the cause of this issue. See https://github.com/Microsoft/VSProjectSystem/issues/219

**Comment by srivatsn** [comment]
Closing this since the issue in the SDK (https://github.com/dotnet/sdk/issues/1051)
