### ISSUE TITLE
Failed to resolve dotnet packages on some machines because feed defined in local NuGet.Config is ignored

### ISSUE THREAD

**Issue by hongdai** [dotnet/roslyn-project-system#1871]
Failed to resolve dotnet packages on some machines because feed defined in local NuGet.Config is ignored

For example, the below output shows the local config file is used, however the local feed is missing:

Unable to resolve 'dotnet-svcutil (>= 0.5.10306-preview)' for '.NETCoreApp,Version=v1.1'.
NuGet Config files used:
C:\Users\pennerg\AppData\Roaming\NuGet\NuGet.Config
C:\Program Files (x86)\NuGet\Config\Microsoft.VisualStudio.Offline.config
**C:\Users\pennerg\AppData\Local\Temp\WCFConnectedService\2017_Mar_21_06_41_30\svcutil_bootstrap\NuGet.Config**
**Feeds used:
https://api.nuget.org/v3/index.json
C:\Program Files (x86)\Microsoft SDKs\NuGetPackages**

I can use **dotnet add package -s <local feed>** to restore the package successfully. The problem is I need to create a process for this operation in the runtime and it's pretty expensive. **Is there an equivalent API I could use?**

**Any recommendation I can always resolve the package successfully?** It's a pretty bad experience for our customers.

Thanks,
Hong

**Comment by davkean** [comment]
I'm not understanding the bug or the issue, can you clarify?

**Comment by hongdai** [comment]
1. The app is in: C:\Users\pennerg\AppData\Local\Temp\WCFConnectedService\2017_Mar_21_06_41_30\svcutil_bootstrap
2. Under the root of the app, I have a local NuGet.Config that has the following package source information:
```
 <packageSources>
    <add key="SvcUtilLocalFeed" value="C:\myfeed" />
  </packageSources>
```
3. My project file depends on below package that is located under C:\myfeed
 `<PackageReference Include="dotnet-svcutil" Version="0.5.10327.0-preview"></PackageReference>
`
4. **dotnet restore** failed on some machines because it ignored the feed in the local NuGet.config, the log below shows **c:\myfeed is not used.**

Unable to resolve 'dotnet-svcutil (>= 0.5.10306-preview)' for '.NETCoreApp,Version=v1.1'.
NuGet Config files used:
C:\Users\pennerg\AppData\Roaming\NuGet\NuGet.Config
C:\Program Files (x86)\NuGet\Config\Microsoft.VisualStudio.Offline.config
C:\Users\pennerg\AppData\Local\Temp\WCFConnectedService\2017_Mar_21_06_41_30\svcutil_bootstrap\NuGet.Config

**Feeds used:
https://api.nuget.org/v3/index.json
C:\Program Files (x86)\Microsoft SDKs\NuGetPackages**

**Comment by davkean** [comment]
This issue was moved to NuGet/Home#4907

**Comment by hongdai** [comment]
@davkean Do you recommend to use **dotnet add package -s** in this case instead of a local feed? Is there an equivalent API I could use? Thanks!

**Comment by davkean** [comment]
I've moved this over to NuGet - I don't have the context to answer your question.

**Comment by hongdai** [comment]
But does NuGet owns dotnet commands?

**Comment by davkean** [comment]
They own some dotnet commands - your problem is with the feed not being used, that is NuGet-related. I don't have enough context to answer questions around this.

**Comment by hongdai** [comment]
I don't need to use the feed if I use **dotnet add package -s** . Who is the owner for the dotnet add package command? I would like to know if there is an equivalent API.
