### ISSUE TITLE
Debug Property Page Command line arguments too small on 200% DPI

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/roslyn-project-system#1895]
![image](https://cloud.githubusercontent.com/assets/679326/24482320/2e94424e-14a5-11e7-9a04-9885908af4e6.png)

**Comment by srivatsn** [comment]
This has been fixed for 15.1

**Comment by davkean** [comment]
Yeah, this is: https://github.com/dotnet/roslyn-project-system/issues/427.
