### ISSUE TITLE
Customer migration from xproj (Project system)

### ISSUE THREAD

**Issue by sayedihashimi** [dotnet/roslyn-project-system#213]

**Comment by davkean** [comment]
This needs to happen both via the command-line and VS.

**Comment by davkean** [comment]
A couple of approaches for this:

1) CPS itself doesn't allow IVsUpdateProjectViaFactory (spelling?) but you could have a non-CPS project factory that does, have us as a preferred factory and simply delegate via IFlavoredProjectCompatibilityProvider.
2) Introduce a new CPS project factory that only handles xproj, and converts the new file to csproj and returns the project factory for csproj.
3) Fail the project open via IVsRetargetProject to cause it to unload and then have a "converter" that converts from xproj -> csproj. Might have to rename project.

**Comment by srivatsn** [comment]
Remaining work here is to make a prettier migration report.

**Comment by srivatsn** [comment]
Remaining work is tracked by #507. So closing this issue
