### ISSUE TITLE
Global.json replacement

### ISSUE THREAD

**Issue by sayedihashimi** [dotnet/roslyn-project-system#215]

**Comment by davkean** [comment]
@sayedihashimi What does global,json do other than for source swapping? Source swapping is being tracked by https://github.com/dotnet/roslyn-project-system/issues/195. This currently doesn't have enough information to flesh out or cost.

**Comment by sayedihashimi** [comment]
Bill knows all the details, one other thing it does is help with sdk version.

**Comment by davkean** [comment]
Bill was in the room when I wrote that. :) 

We're tracking SDK versions here: https://github.com/dotnet/roslyn-project-system/issues/191 and source swapping #195. Going to close this in lieu of those.
