### ISSUE TITLE
Opening a targets file or project file results in warnings about unrecognized properties and items

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn-project-system#220]
Opening a targets file or project file in Visual Studio results in warnings about unrecognized properties and items. We should stop this warning from occurring. Looking at the schema, it seems impossible to have a schema that both provides IntelliSense for available properties/items, while at the same time not warning when you enter an "unrecognized" property/item.

**Comment by Mike-EEE** [comment]
This is where a [POCO-based schema system](https://github.com/dotnet/roslyn-project-system/issues/37) would be worth its weight in gold and then some. :)

**Comment by basoundr** [comment]
@RaulPerez1 is looking at it.

**Comment by srivatsn** [comment]
This is fixed now.
