### ISSUE TITLE
T4 template support

### ISSUE THREAD

**Issue by gulbanana** [dotnet/roslyn-project-system#224]
Currently, .tt templates function only in .csproj - they are not available to .xproj and therefore to asp.net core. Can we please have T4 support in the new project system?

**Comment by sayedihashimi** [comment]
We added T4 support to xproj in a previous release.

@billhiert @davkean this is an item we missed in our recent parity excersize. It's needed for .resx, TS (I think) and customer templates.

**Comment by gulbanana** [comment]
Oh, I missed the addition to xproj. Well, good to hear it's on the radar.

**Comment by davkean** [comment]
@sayedihashimi What's the actual feature? Single-file generators? If so, then these should already work.

**Comment by sayedihashimi** [comment]
Yeah Single File Generators, so can we close this?

**Comment by gulbanana** [comment]
I see that any CPS project gets resx and tt if it uses
<ProjectCapability Include="SingleFileGenerators;" /> 
Sounds fine to me!

**Comment by gulbanana** [comment]
(I found this documented here: https://github.com/Microsoft/VSProjectSystem/blob/master/doc/scenario/add_single_file_generator.md)
