### ISSUE TITLE
Error list shows wrong order for errors scraped from MSBUILD output

### ISSUE THREAD

**Issue by ljw1004** [dotnet/roslyn-project-system#248]
**REPRO**
1. Create a new C#/VB console app.
2. Under project properties, add this custom pre-build step:

```
echo a.txt(15): error EX2: one && echo a.txt(5): error EX1: two && echo a.txt(20): error EX3: three
```
1. Build

**What I expect**

In the error list, if the error list isn't sorting by any particular column, then it should display the errors in the order they were emitted: `one, two, three`. This indeed was the behavior back in VS2012. (however it regressed by VS2015).

**What I get**

Instead, it sorts the errors by line number (even if the "line number" column hasn't been chosen as a sort order).

**Notes**

I attempted this repro with both ".csproj" and ".msbuildproj". It repro'd in both.

Version: VS 15.0.25408.0 ("preview 3")

**Comment by davkean** [comment]
With the new project system, I can get the correct order if I remove all sorting in Visual Studio 2015:

![image](https://cloud.githubusercontent.com/assets/1103906/16201999/ba58e5ac-36c8-11e6-9bd6-ced0070bd45b.png)

If I do the same thing in Visual Studio "15", however, it looks like we regressed something:

![image](https://cloud.githubusercontent.com/assets/1103906/16201976/9aa46902-36c8-11e6-8957-e54df3a5d553.png)

**Comment by ljw1004** [comment]
I ran into this again with .NETCore in VS2015 Update3:
![errorlist](https://cloud.githubusercontent.com/assets/3316258/16424211/12c67eba-3d14-11e6-9069-52efe05a9a15.png)

**Comment by davkean** [comment]
This looks correct in C#/VB CPS in RTM: 

![image](https://cloud.githubusercontent.com/assets/1103906/24186116/e4e39f3e-0f2a-11e7-9a3f-7d1895e6c502.png)

If this still repro's in the legacy project system, we have no plans on investing in it. We plan on replacing it: https://github.com/dotnet/roslyn-project-system/blob/master/docs/repo/roadmap.md
