### ISSUE TITLE
Error list doesn't show codes for errors scraped from MSBUILD output

### ISSUE THREAD

**Issue by ljw1004** [dotnet/roslyn-project-system#249]
**REPRO**
1. Create a new C#/VB console app.
2. Under project properties, add this custom pre-build step:

```
echo a.txt(15): error EX2: one && echo a.txt(5): error EX1: two && echo a.txt(20): error EX3: three
```
1. Build

**What I expect**

In the error list, the "Code" column should be populated.

**What I get**

It isn't.

**Notes**

I attempted this repro with both ".csproj" and ".msbuildproj". It repro'd in both.

Note that this scenario has never worked since the "Code" column was first introduced. I merely filed this issue as a feature request.

Version: VS 15.0.25408.0 ("preview 3")

See also #248

**Comment by davkean** [comment]
While I _can_ repro this with the legacy csproj/msvbprj, I cannot repro this in Visual Studio 2015 or Visual Studio "15" with the _new_ project system:

Visual Studio 2015:
![image](https://cloud.githubusercontent.com/assets/1103906/16201789/c32d7c02-36c7-11e6-9076-87720d9fbf9a.png)

Visual Studio 15:
![image](https://cloud.githubusercontent.com/assets/1103906/16201847/ff8ccde2-36c7-11e6-8bca-3ffb73097135.png)

**Comment by ljw1004** [comment]
That's funny. Here's my screenshot using VS "15" preview 3, with the new project system:

![repro](https://cloud.githubusercontent.com/assets/3316258/16202300/e8de42a4-36c9-11e6-8b8d-17d655b30ce0.png)

**Comment by davkean** [comment]
Hmm, even without our latest bits (which aren't included in the box) I cannot repro this - I suspect it's a change in CPS, looking...

**Comment by davkean** [comment]
This looks correct in C#/VB CPS in RTM: 

![image](https://cloud.githubusercontent.com/assets/1103906/24186116/e4e39f3e-0f2a-11e7-9a3f-7d1895e6c502.png)

If this still repro's in the legacy project system, we have no plans on investing in it. We plan on replacing it: https://github.com/dotnet/roslyn-project-system/blob/master/docs/repo/roadmap.md
