### ISSUE TITLE
Browse object properties for "Folder" itemtype do not show in /exp debugging session.

### ISSUE THREAD

**Issue by IObsequious** [dotnet/roslyn-project-system#257]
I would like to thank you in advance for this project. Finally... Finally! we can customize the project experience like a normal human being would...

**Scenario**
- I want to add a simple property to a folder node within a project.

**Problem**
- Configuring the property viz "folder.xaml" does not work. Debugging sessions yield property-naked folders

**Reproduction**
      1. Create a new project viz File > New > Project > Templates > Visual C# > Extensibility >  Property Type
      2. Focus on the *.ProjectType project
      3. Find "BuildSystem\Rules". folder
      4. Open "folder.xaml"
      5. Add a simple property (e.g. `<StringProperty name="FoonaldTrump" />`)
      6. Save. Press F5
      7. In Debugger, create a new project from your new Project Type
      8. Once project loads, right click project node and choose Add > NewFolder.
      9. Right click the folder with your cursor. Look in the properties window. For me, no configurations appear. 

Let me know if this is indeed an issue, or if I need some guidance on how this type of configuration works. FYI: I am able to configure and subsequently see expected results for all of the other files just fine. Keep up the great work!

**Comment by IObsequious** [comment]
I just realized that my issue is more about the project system, and not Roslyn. I am moving it there.

**Comment by davkean** [comment]
This is well-known feature gap and is on the backlog for Visual Studio "15".
