### ISSUE TITLE
Console app Build related property pages

### ISSUE THREAD

**Issue by srivatsn** [dotnet/roslyn-project-system#263]
Get the Build and Build events and Reference Paths pages up.

**CSharp-ConsoleApplication** 

   - [x]  Build Properties Page
   - [x]  BuildEvent Properties Page
   - [x]  ReferencesPath Properties Page 

**VB-ConsoleApplication**
  
  - [x] References Properties Page

**Comment by jinujoseph** [comment]
**Pending List** 
 - [ ]  Build Properties Advance Page: CheckForOverflowUnderflow 
 - [ ]  References Page: Implement GetCurrentImportsList()
 - [ ]  References Page: Add Service Reference not working
