### ISSUE TITLE
Roslyn analyzers + code fixes don't work properly in VS when installed into .NET Core project via a nuget package

### ISSUE THREAD

**Issue by sayedihashimi** [dotnet/roslyn-project-system#285]
Originally posted at: https://github.com/dotnet/core/issues/91 by @HellBrick 

_(I can't seem to find a repo for raising VS .NET Core tooling issues, so if there's a more appropriate place for this, please tell and I'll be glad to repost it there.)_

Here's what happens when a nuget package that contains Roslyn analyzers + code fixes is installed into a .NET Core project via `install-package $(AnalyzerPackage)`:
1. Analyzer package is added to `References > .NETStandard` node of Solution Explorer instead of `References > Analyzers`.
2. Which also means there's no UI for changing rule severity.
3. Analyzers are not invoked when the code is being edited. The warnings are reported only when the project is built.
4. Even then no squiggles are displayed at the warning location, the warnings are only surfaced in the error list.
5. And probably the most tragic part: the code fixes attached to the analyzer warnings simply can't be triggered.

**Comment by srivatsn** [comment]
1 and 2 should get fixed once we implement #88 and 3,4,5 should get fixed once we implement #131

**Comment by srivatsn** [comment]
This is now fixed.
