### ISSUE TITLE
Need to split up ResolveNuGetPackageAssets's ReferenceCopyLocalPaths 

### ISSUE THREAD

**Issue by eerhardt** [dotnet/roslyn-project-system#296]
From an email message with @davkean and @jasonmalinowski:

From: David Kean 
Sent: Thursday, July 07, 2016 11:29 AM
To: Eric Erhardt ; Jason Malinowski 
Subject: RE: How to "extend/customize" ResolveNuGetPackageAssets's ReferenceCopyLocalPaths for .net core

Eric, this task as it stands today doesn’t work for .NET Core projects. We’re going to have to change it significantly. 

I think we should split it up in multiple concerns:

1)	Target for raising package items from project.lock.json (for consumption by the new dependency nodes)
2)	Target for translating those packages into `<Reference>, <Compile> etc `
3)	Target for translating those packages into Copy Local items for build
4)	Target for translating those packages into Copy Local items for publish

Traditional .NET projects will share 1) and 2), .NET Core projects/UWP will override 3 and 4.

From: Eric Erhardt 
Sent: Thursday, July 7, 2016 9:16 AM
To: Jason Malinowski ; David Kean 
Subject: RE: How to "extend/customize" ResolveNuGetPackageAssets's ReferenceCopyLocalPaths for .net core

I tried my approach below of setting <CopyNuGetImplementations> during the “build” and “publish” targets, but this doesn’t work with the current Microsoft.NuGet.targets that I have.

The reason it doesn’t work is because Microsoft.NuGet.targets inspects that property statically, and not during a Target.  So when Microsoft.NuGet.targets is loaded it says:

```xml
    <CopyNuGetImplementations Condition="'$(CopyNuGetImplementations)' == '' and (('$(OutputType)' != 'library' and ('$(OutputType)' != 'winmdobj' or '$(AppxPackage)' == 'true')) or '$(TargetFrameworkIdentifier)' == '.NETFramework')">true</CopyNuGetImplementations>
```
...
```xml
  <!-- If a NuGetRuntimeIdentifier wasn't already specified, let's go generate it -->
  <PropertyGroup Condition="'$(NuGetRuntimeIdentifier)' == '' and '$(CopyNuGetImplementations)' == 'true'">
    <NuGetRuntimeIdentifier>$(_NuGetRuntimeIdentifierWithoutAot)</NuGetRuntimeIdentifier>
    <NuGetRuntimeIdentifier Condition="'$(UseDotNetNativeToolchain)' == 'true'">$(_NuGetRuntimeIdentifierWithoutAot)-aot</NuGetRuntimeIdentifier>
  </PropertyGroup>
```

Is there another way I can get this functionality?  Basically I need the following:

•	Today, all "CopyLocal" items get placed in the output folder during "Build"
o	.NET Core needs a way to say not to copy .dlls from NuGet packages during Build
o	.NET Core also needs a way to tell this target to copy all .dlls during Publish
•	But we need to be able to customize it for "portable" apps, i.e. "Trim for type: platform"

From: Eric Erhardt 
Sent: Wednesday, July 06, 2016 7:00 PM
To: Jason Malinowski ; David Kean 
Subject: Re: How to "extend/customize" ResolveNuGetPackageAssets's ReferenceCopyLocalPaths for .net core

type: platform is a type of NuGet dependency in the project.json file currently.

See:
https://github.com/NuGet/Home/issues/2303

I assume when dependencies are defined solely on the .csproj, it will be some custom item metadata under PackageDependency (or whatever the item is named).
Sent from my phone

________________________________________
From: Jason Malinowski
Sent: Wednesday, July 6, 2016 6:49:54 PM
To: Eric Erhardt; David Kean
Subject: RE: How to "extend/customize" ResolveNuGetPackageAssets's ReferenceCopyLocalPaths for .net core 
 
> in “type: platform” dependencies and under
 
Pardon the ignorance, but how do these get defined? From the perspective of a consumer of a NuGet package, how do I know what is what?
 
Jason Malinowski
 
From: Eric Erhardt 
Sent: Wednesday, July 6, 2016 3:10 PM
To: Jason Malinowski ; David Kean
Subject: How to "extend/customize" ResolveNuGetPackageAssets's ReferenceCopyLocalPaths for .net core
 
Hey Jason and David,
 
(if you aren’t the right people to ask this question, please include whomever is)
 
I’m working on prototyping .net core “build” and “publish” on msbuild.  In the meeting Design Session: Build and Publish in .NET Core MSBuild  (Web view), we decided that “build” and “publish” would work like it does today in the CLI.  Specifically:
 
•         Build only puts the app’s compiled .dll in the output directory, along with:
o   A deps.json file
o   A runtimeconfig.json file
o   A runtimeconfig.dev.json file
o   Any Project-to-Project references’ outputs
•         Any assemblies that come from nuget packages are not placed in the output directory.
•         “publish” then goes and makes your app “runnable” on other machines.  Specifically it:
o   When publishing a “portable” app, you get:
  All runtime assemblies that are not in “type: platform” dependencies and under (i.e. in the “Shared Framework”)
o   When publishing a “self-contained” app, you get:
  Every assembly you depend on, even .net framework base class library assemblies
 
I’m trying to enable this behavior.
 
I see that I can set:

```xml
<CopyNuGetImplementations>false</CopyNuGetImplementations>
```

During “build” and set it back to “true” during “Publish”.  But how do I enable the “type: platform” behavior so the “Shared Framework” assemblies never get copied to the output directory when publishing a “portable” app?
 
Any thoughts on this?
 
Eric

**Comment by natidea** [comment]
One of the key tasks here is splitting up `ReferenceCopyLocalPaths` between Build and Publish. In my investigation, I observe that the output of the NuGet task does not solely determine what ends up in `ReferenceCopyLocalPaths`. Another target `ResolveAssemblyReferences` further adds to this based on the `Reference` item. 

Fortunately, I think we can manipulate the item before the files are actually copied using the `PrepareForRunDependsOn` property, but more investigation needed.

**Comment by srivatsn** [comment]
This is now done.
