### ISSUE TITLE
Current state of csproj, project.json, Visual Studio 2015 and CLI?

### ISSUE THREAD

**Issue by colin-young** [dotnet/roslyn-project-system#300]
I'm trying to determine the current state of project files, especially as it concerns active development of a library and tooling in Visual Studio and CLI.

1. solution has multiple projects, projects have intra-solution project dependencies
1. using `n.m.x-beta-{nnnnn:buildnumber}` version format
1. developer day-to-day work in Visual Studio 2015 update 3
1. build server packages output using `dotnet pack`
1. dependencies managed in project.json
1. xUnit unit tests run for both developer and build server

Up till now I've been using `"version": "1.0.0-beta-*"` and having a pre-compile step on the build server replace * with the build number. On dev workstations I've just kind of ignored it and VS seems to have just gone and replaced it as `1.0.0-beta` and since everything was project-to-project it all seemed to work, save for a couple warnings. Recently (e.g. after upgrading to RTM bits) I've run into issues with one of my library solutions where this setup no longer works. I've attempted to use the `"My.Project" { "version": "1.0.0-beta-*", "target": "project" }` way of referencing, but that only works if I drop the splat/asterisk/*. And when I say "works" I mean I can build and package from the command line, but Visual Studio is no longer happy, and I get all sorts of errors: 

- "Your project.json doesn't list 'win' as a targeted runtime. You should add '"win": {}' ... " (um, yes it does)
- "NuGet Package restore failed for project <blah> for '<one of my p-2-p references> (>= <the version it is defined as>'," 
- my favorite: "Unable to satisfy conflicting requests for '<some assembly whether System, Microsoft or one of mine>': <a list of several packages that require this assembly, _every one of them depending on the exact same version_>"

Is it possible to set up a solution in such a way that I can support all the numbered points at the top? Is there anything documenting it?

**Comment by gulbanana** [comment]
this repository's new project system isn't used at all in VS2015. it's being developed for the next VS release

**Comment by colin-young** [comment]
So where do I go to find info on that? I realize that we're talking a lot of alpha- or beta- state software and tools here, but that just underscores the need for clear direction on where to go to look for answers and to provide feedback.
