### ISSUE TITLE
S2: As an existing developer of .NET Core projects, I can quickly migrate from xproj to csproj based project system and continue development without disruption

### ISSUE THREAD

**Issue by morrisjoe** [dotnet/roslyn-project-system#319]
| User Story | VS | VS Code / CLI |
| --- | --- | --- |
| 2a.   I can easily migrate an existing .NET Core project from Dev14 to Dev15 using IDE and continue to use Microsoft tools for my development | P1 | P1 |
| 2b.   I can easily migrate an existing .NET Core project from the command line (CLI) | P1 | P1 |

**Comment by 333fred** [comment]
Isn't this #213?

**Comment by morrisjoe** [comment]
@333fred  Yes. Linked that
