### ISSUE TITLE
S7: As a developer, I can reuse project components by expressing needed references

### ISSUE THREAD

**Issue by morrisjoe** [dotnet/roslyn-project-system#324]
| User Story | VS | VS Code / CLI |
| --- | --- | --- |
| 7a.    I can add/remove reference to NuGet packages via NuGet packages UI | P1 | n/a |
| 7b.    I can add/remove reference to NuGet packages via editing (with intellisense support) of the project file | P1 | P2 |
| 7c.   I can use Ctrl+. from the editor to add references to NuGet packages /usings | P1 | n/a |
| 7d.   I can add P2P references between my .NET Core projects via UI (ASP.NET Core to .NET Core, .NET Core to .NET Core, .NET Core to.NET framework class library etc.) | P1 | n/a |
| 7e.    I can add P2P references between my .NET Core projects via editing (with intellisense support) of the project file (ASP.NET Core to .NET Core, .NET Core to .NET Core, .NET Core to .NET framework class library etc.) | P1 | P2 |
| 7f.    When I add dependency via NuGet package manager UI, auto-restore automatically gets triggered to resolve dependency graph and update all affected project dependencies in my entire solution. | P1 | P2 |
| 7g.    When I add dependency via manually editing the csproj/json file and save the file, auto-restore automatically gets triggered to resolve dependency graph and update all affected project dependencies in my entire solution. | P1 | P2 |
| 7h.    I can add P2P references from an old desktop project (e.g. WPF app) to a new-project-system project that targets net461. | P1 | P2 |
| 7i.    I can visualize my project's dependencies using Solution Explorer | P1 | n/a |
| 7j.    I can convert PCL to netstandard and add a reference to it from my .NET Core projects | P2 | n/a |
| 7k.    I can swap NuGet references for Project references | P2 | n/a |

**Comment by gulbanana** [comment]
how about reverse references, as in a reference from an old desktop project (e.g. wpf application) to a new-project-system project that targets net461?

**Comment by morrisjoe** [comment]
@gulbanana  @srivatsn . Good point. I missed that and have now added as 7f.
