### ISSUE TITLE
S10: As a developer, I can publish my .NET Core App (console, web) 

### ISSUE THREAD

**Issue by morrisjoe** [dotnet/roslyn-project-system#326]
| User Story | VS | VS Code / CLI |
| --- | --- | --- |
| 10a. I can publish to file system | P1 | P1 |
| 10b. I can publish to Azure | P1 | P1 |
| 10c. I can publish using kudu | P1 | P1 |
| 10d. I can CI deploy | P1 | P1 |
| 10e. I can publish to Docker container | P1 | P1 |
| 10f. I can publish to on-prem Windows Server for ASP.NET Core hosting | P1 | P1 |

**Comment by sayedihashimi** [comment]
No support for class library here, just apps
