### ISSUE TITLE
Do not persist <Service> item into the project file

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn-project-system#345]
Test Explorer persists the following into test projects:

``` XML
<ItemGroup>
    <Service Include="{82A7F48D-3B50-4B1E-B82E-3ADA8210C358}" />
  </ItemGroup>
```

We should better understand the reasons behind it and come up with a better mechanism for this, such as dynamic capabilities driven by targets in packages.

**Comment by Mike-EEE** [comment]
So funny, I have been noticing that just today while upgrading my projects to NuGet 3.0.  Wondering where that was coming from. :stuck_out_tongue:

**Comment by nil4** [comment]
This is still happening with VS 2017 RC (15.0.26206.0 D15REL).

**Comment by davkean** [comment]
Yes, we haven't fixed this - are you seeing this with .NET Core projects?

**Comment by nil4** [comment]
Yup, I have a netstandard-1.5 library and its tests are in a netcoreapp1.0 project. Every time I run the tests from VS, it adds the `<Service>` element to the test project.

**Comment by srivatsn** [comment]
Tracked by https://github.com/Microsoft/vstest/issues/472

**Comment by davkean** [comment]
Side note - this was entirely removed for 15.7.

**Comment by StingyJack** [comment]
I'm getting a different Guid (T4 template i think). @davkean  Is the removal you mention for the Guid in your OP or for any `<Service Include />` ? 
``` xml
 <ItemGroup>
    <Service Include="{508349B6-6B84-4DF5-91F0-309BEEBAD82D}" />
  </ItemGroup>
```

**Comment by davkean** [comment]
File a new bug for that - this only addressed the Test Explorer's usage. This is a public API from the project system that let's components persist this so we cannot break it.

**Comment by StingyJack** [comment]
k, ty
