### ISSUE TITLE
Renaming a project should rename the containing folder

### ISSUE THREAD

**Issue by terrajobst** [dotnet/roslyn-project-system#356]
I often find that after renaming projects that I forgot to rename the containing folder. For example, let's say I have a solution like this:

```
Solution
│   MySolution.sln
│
└───ClassLibrary1
        ClassLibrary1.csproj
```

Now let's say I rename `ClassLibrary1.csproj` to `Awesome.Feature.csproj`. The outcome looks like this:

### Actual

```
Solution
│   MySolution.sln
│
└───ClassLibrary1
        Awesome.Feature.csproj
```

### Expected

```
Solution
│   MySolution.sln
│
└───Awesome.Feature
        Awesome.Feature.csproj
```

**Comment by joakimskoog** [comment]
Yes! Yes, a thousand times yes!

**Comment by AlexZeitler** [comment]
:+1: 
What about namespaces?
In the end I would like to have a replacement for this:
https://alexanderzeitler.com/articles/rename-visual-studio-project-namespaces-and-folders-automate-everything/

**Comment by Mike-EEE** [comment]
what @joakimskoog said. We have to essentially remove the project from the solution, rename the folder, and then re-add the project to complete the process.  Then there's the risk of losing references altogether, and have to re-add them to all the projects that were referencing the project in question as well (although this doesn't seem as bad now as it has in the past).  Still, it's a pain.  Lots of considerations as described, with default namespaces and such.  You are nearly guaranteed to rename *something* within your project at least once during its lifetime.  For me it always seems like it happens within the first week or so.  These sorts of friction points deter considerations.  This would be an **awesome** improvement. :+1:

**Comment by petarvucetin** [comment]
+100

**Comment by terrajobst** [comment]
Closing because it's a duplicate of #111.
