### ISSUE TITLE
Get prompt to rename a type when moving it from one folder to another 

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn-project-system#363]
1. Create a new project with Class1.cs
2. Create a new folder called "Bar"
3. Drag Class1.cs into "Bar"

_Expected:_ No prompt for rename
_Actual:_ Prompt for rename

**Comment by davkean** [comment]
tag @jinujoseph

**Comment by srivatsn** [comment]
@jinujoseph is this fixed - I remember some change around this.

**Comment by 333fred** [comment]
One question I have on this: do we want to do namespace renames? If we move a file from a path that is a valid namespace to a path that is a valid namespace, it seems reasonable that we should prompt to move the namespace the contained class is in.

**Comment by davkean** [comment]
Move or sync it? My opinion is that I don't think we should ever prompt - we should just add an undo unit so that the user can under the rename.

**Comment by 333fred** [comment]
Filled https://github.com/dotnet/roslyn-project-system/issues/1035 for that idea.
