### ISSUE TITLE
Seamless project reload still pops up the reload dialog

### ISSUE THREAD

**Issue by srivatsn** [dotnet/roslyn-project-system#364]
With the latest CPS bits and with the HandlesOwnReload capability added, if I change the project file on disk, the tree updates immediately but I still see the dialog asking me to reload the project.

**Comment by davkean** [comment]
When I was playing around with this, it's because something is marking the project as dirty - hence the prompt, because we think there's unsaved changes.

**Comment by srivatsn** [comment]
This doesn't seem to happen anymore.
