### ISSUE TITLE
Shared Project template shows up twice in C# and none in VB

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn-project-system#375]
The Shared Project template shows up twice in C#:

![image](https://cloud.githubusercontent.com/assets/1103906/17985951/37e5e082-6acd-11e6-8e11-71cce7ccce5c.png)

And doesn't show up in VB :

![image](https://cloud.githubusercontent.com/assets/1103906/17986287/c59b718e-6ace-11e6-88af-96edc6d64be5.png)

**Comment by davkean** [comment]
@jmarolf Were you playing around with these for WIllow?

**Comment by jmarolf** [comment]
@davkean @rchande  was this a willow install?  I'll do a pass and see what other duplicates show up that we can eliminate.

**Comment by davkean** [comment]
Yes this was a willow install.

**Comment by jmarolf** [comment]
Fixed with https://devdiv.visualstudio.com/DevDiv/IDE%20Experience/_git/VS/pullrequest/35998 
 
![image](https://cloud.githubusercontent.com/assets/9797472/18975230/7972c26c-865d-11e6-9c5a-f760f0f3b099.png)

Verified in bcb2 build 25729.00
