### ISSUE TITLE
Switch to control load behavior of new project system

### ISSUE THREAD

**Issue by srivatsn** [dotnet/roslyn-project-system#381]

**Comment by jinujoseph** [comment]
Resolved via 
[https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/35219?path=%2Fsrc%2FSetupPackages%2FCoreIde%2FCommunityExtra%2Fcore%2FPkgDef%2FVB_Project_Reg_VS_26699.3643236F_FC70_11D3_A536_0090278A1BB8.pkgdef&_a=overview] and [https://github.com/dotnet/sdk/pull/129]
