### ISSUE TITLE
Hide properties from Project browse object

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn-project-system#389]
We should hide the majority of these browse objects, and bring it back to what legacy csproj is showing:

![image](https://cloud.githubusercontent.com/assets/1103906/18023517/dc8a5f0a-6bae-11e6-95bf-b0ffb130e756.png)

**Comment by srivatsn** [comment]
We need to add Visible=False on the rules.

**Comment by adrianvmsft** [comment]
Grouping some of them into categories would also be helpful

**Comment by davkean** [comment]
We're going to cut them back to the same as existing project system - then be very deliberate about what's exposed.

**Comment by abpiskunov** [comment]
Related https://github.com/dotnet/roslyn-project-system/issues/59

**Comment by jinujoseph** [comment]
Validate #841 and #814 , when fixing this issue

**Comment by jinujoseph** [comment]
blocked by CPS bug : 369757
