### ISSUE TITLE
Get an error about missing "ResolveDependenciesDesignTime" in Shared Project

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn-project-system#393]
1. Create a C# shared project:

```
Error	MSB4057	The target "ResolveDependenciesDesignTime" does not exist in the project.	SharedProject1	c:\users\davkean\documents\visual studio 15\Projects\SharedProject1\SharedProject1\SharedProject1.shproj	1	
````

**Comment by davkean** [comment]
tag @abpiskunov

**Comment by srivatsn** [comment]
The rule has been updated to look for the new property. Next vs build will have the fix.

**Comment by srivatsn** [comment]
Actually with the updated rule, there is still an error - it says 

`Error	MSB4057	The target "ResolvePackageDependenciesDesignTime" does not exist in the project.`

**Comment by davkean** [comment]
We shouldn't be putting dependencies in Shared Projects. We should turn off the capability.
