### ISSUE TITLE
Dependencies sub nodes have objects for opening properties and View in object browser

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn-project-system#398]
![image](https://cloud.githubusercontent.com/assets/1103906/18023791/60e8013c-6bb2-11e6-8c0b-2b01c93ee7ca.png)

I would expect this to only have "Scope to this" and "New Solution Explorer View"

**Comment by lorcanmooney** [comment]
It's just one users opinion, but personally I find the dependency type nodes hide the information I want to see. For me, the icons already provide a fairly clear distinction, and having to drill down into multiple hierarchies to get the full picture is more of an annoyance (albeit a minor one).

**Comment by davkean** [comment]
@lorcanmooney Thanks for your opinion.
