### ISSUE TITLE
We should hide the Assemblies tab for .NET Core apps

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn-project-system#400]
![image](https://cloud.githubusercontent.com/assets/1103906/18023814/bd412544-6bb2-11e6-9e71-d26af8f49ab1.png)

**Comment by davkean** [comment]
This should be hidden behind a capability for desktop support.

**Comment by RaulPerez1** [comment]
Blocked by CPS, AssemblyReference, which is the capability used to block the this tab is used for other things and removing it results in a CPS load failure.

**Comment by davkean** [comment]
I'm not sure AssemblyReference is the right capability here, we support assembly references, just not from framework or extension locations.

**Comment by RaulPerez1** [comment]
Agreed, however that's one of the extensibility issues with CPS I mentioned offline. Currently this is the only way to control the tabs. We're having a separate conversation about changes needed to support the right extensibility points.

**Comment by gulbanana** [comment]
Are references of this type ok within an ItemGroup with Condition="$(TargetFramework) == 'net461'"?

**Comment by davkean** [comment]
Yes, and we'll let you consume when targeting .NET Framework.

**Comment by abpiskunov** [comment]
To clarify, if my project has a target net461, how do i add a framework assembly reference if we would hide that tab in Add Reference dialog?

**Comment by RaulPerez1** [comment]
I'm a bit fuzzy on the high level picture, if your project is targeting 4.6.1 it wouldn't be pulling in the .Net Core SDK right? If that is the case then you'll still get the tab on the reference manager since it would be the SDK targets that force it to be gone. If that is not the case lets chat.

**Comment by davkean** [comment]
The capabilities will be/should be set based on the target framework in the SDK. When targeting .NET 4.6.1, the capability will be present (or not present). 

What we don't have, is a good experience when you target both - we're basically going to pick the TFM that is first listed as the "current TFM" - that will dictate whether it shows up or not.

**Comment by gulbanana** [comment]
Sounds ok, as long as there aren't conflicting capabilities which mean we have to swap the order back and forth.. X(

**Comment by abpiskunov** [comment]
@davkean Yes, i was more interested in the scenario when we have both - taking first TFM will look confusing ...

**Comment by davkean** [comment]
@abpiskunov Until we can update the rest of VS to understand multiple TFMs - what's your alternative?

**Comment by abpiskunov** [comment]
In dnx/dotnet project system we provided our own implementation of Assemblies tab provider , that allowed adding assemblies only for full framework targets. We had another level of targets under Assemblies tab for each project TFM and displayed assemblies to be selected only for full desktop tfms.

**Comment by davkean** [comment]
Can you post a screen shot? I don't the bits installed.

**Comment by abpiskunov** [comment]
![image](https://cloud.githubusercontent.com/assets/1592091/20993368/9a722a26-bc9e-11e6-9c66-0ff42da0587c.png)
in .Net 4.6 tab we show assemblies to be selected, however if .NetCoreApp is selected - it does not display any assemblies
