### ISSUE TITLE
Build Events -> Edit Build Events crashes VS

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn-project-system#405]
System.InvalidCastException: 'Unable to cast COM object of type 'System.__ComObject' to interface type 'Microsoft.VisualStudio.Shell.Interop.IVsBuildMacroInfo'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{9015B3AB-9FE2-430D-B79F-E0E581BD5B8B}' failed due to the following error: No such interface supported (Exception from HRESULT: 0x80004002 (E_NOINTERFACE)).'

```
>   Microsoft.VisualStudio.Editors.dll!Microsoft.VisualStudio.Editors.PropertyPages.BuildEventsPropPage.GetTokenValue(string MacroName) Unknown
    Microsoft.VisualStudio.Editors.dll!Microsoft.VisualStudio.Editors.PropertyPages.BuildEventsPropPage.GetTokenValues(ref string[] Values, Microsoft.VisualStudio.Editors.PropertyPages.BuildEventsPropPage.GetTokenValueFunc valueHelper) Unknown
    Microsoft.VisualStudio.Editors.dll!Microsoft.VisualStudio.Editors.PropertyPages.BuildEventsPropPage.LaunchEventBuilder(Microsoft.VisualStudio.Editors.PropertyPages.BuildEventsPropPage Parent, Microsoft.VisualStudio.Editors.PropertyPages.BuildEventsPropPage.GetTokenValueFunc valueHelper, string WindowTitleText, ref string CommandLine) Unknown
    Microsoft.VisualStudio.Editors.dll!Microsoft.VisualStudio.Editors.PropertyPages.BuildEventsPropPage.PreBuildBuilderButton_Click(object sender, System.EventArgs e)  Unknown
    System.Windows.Forms.dll!System.Windows.Forms.Control.OnClick(System.EventArgs e)   Unknown
    System.Windows.Forms.dll!System.Windows.Forms.Button.OnClick(System.EventArgs e)    Unknown
    System.Windows.Forms.dll!System.Windows.Forms.Button.OnMouseUp(System.Windows.Forms.MouseEventArgs mevent)  Unknown
    System.Windows.Forms.dll!System.Windows.Forms.Control.WmMouseUp(ref System.Windows.Forms.Message m, System.Windows.Forms.MouseButtons button, int clicks)   Unknown
    System.Windows.Forms.dll!System.Windows.Forms.Control.WndProc(ref System.Windows.Forms.Message m)   Unknown
    System.Windows.Forms.dll!System.Windows.Forms.ButtonBase.WndProc(ref System.Windows.Forms.Message m)    Unknown
    System.Windows.Forms.dll!System.Windows.Forms.Button.WndProc(ref System.Windows.Forms.Message m)    Unknown
    System.Windows.Forms.dll!System.Windows.Forms.Control.ControlNativeWindow.OnMessage(ref System.Windows.Forms.Message m) Unknown
    System.Windows.Forms.dll!System.Windows.Forms.Control.ControlNativeWindow.WndProc(ref System.Windows.Forms.Message m)   Unknown
    System.Windows.Forms.dll!System.Windows.Forms.NativeWindow.DebuggableCallback(System.IntPtr hWnd, int msg, System.IntPtr wparam, System.IntPtr lparam)  Unknown

```

**Comment by davkean** [comment]
Make sure you look at https://github.com/dotnet/roslyn-project-system/issues/819 which has a different stack.

**Comment by RaulPerez1** [comment]
Root cause is that the CPS hierarchy does not implement IVsBuildMacroInfo while the old project system hierarchy did so the cast fails and crashes.

**Comment by davkean** [comment]
Okay, do we think this is something that is applicable to all project types? If so, we should implement it in CPS, otherwise, make use of the new ability to add interfaces to the project node via the new COM aggregation they did.

**Comment by RaulPerez1** [comment]
I was browsing through the VS codebase to see where else that interface is used and I found only a handful of hits so I'm not sure that it's worth doing it that way unless we want to preserve absolute backwards compatibility. The CPS way of doing this is to import IProjectPropertiesProvider and from there getting the project storage and eventually calling GetEvaluatedPropertyValueAsync.

**Comment by davkean** [comment]
We're trying to avoid having two separate paths for the AppDesigner/prop pages. We have to continue to support IVsBuildMacroInfo because it still sits on the old project system. Given its one method, it looks much simpler to just shim it in CPS like we're doing with most of old interfaces.

**Comment by davkean** [comment]
Looks like it's also used in text templating, so you'd also have to have that branch for both versions.
