### ISSUE TITLE
Rename prompt should respect UI suppression for automation

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn-project-system#408]
The Rename prompt doesn't appear to respect UI suppression modal for automation purposes, instead we show the dialog

**Comment by adrianvmsft** [comment]
This issue makes it very difficult to stabilize the CPS automation, it shows up all over the place. Sometimes it gets displayed after the project was closed.

**Comment by jinujoseph** [comment]
I will work on getting this taken care

**Comment by jinujoseph** [comment]
closed with https://github.com/dotnet/roslyn-project-system/pull/579
