### ISSUE TITLE
Project Template renaming

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn-project-system#409]
The new names of the C#/VB templates are listed below, note these are in priority order and hence, some of the priorities should change:

Existing Name|New Name|Notes
----------------|------------|---------
WPF Application| WPF App (.NET Framework)
Windows Form Application| Windows Forms App (.NET Framework)
N/A| Console App (.NET Core)
Console Application| Console App (.NET Framework)
N/A| Class Library (.NET Standard)
Class Library|Class Library (.NET Framework)
Class Library (Portable)|Class Library (Portable)|Should we put this in a legacy node?
Shared Project| Shared Project
Windows Service|Windows Service (.NET Framework)
Empty Project|Empty Project (.NET Framework)|Relevant? We should pull usage.
WPF Browser Application|WPF Browser App (.NET Framework)|Should we put this in a legacy node?
WPF Custom Control Library|WPF Control Library (.NET Framework)
WPF User Control Library|WPF User Control Library (.NET Framework)
Windows Forms Control Library|Windows Forms Control Library (.NET Framework)

_Tree:_

In the root of the Visual C#/VB tree nodes, only the following templates (.NET Framework/.NET Core) should exist, all others should live in their respective sub nodes. 

These templates should also exist in their appropriate sub nodes.

WPF App (.NET Framework)
Windows Forms App (.NET Framework)
Console App (.NET Core)
Console App (.NET Framework)
Class Library (.NET Standard)
Class Library (.NET Framework)
Shared Project

**Comment by davkean** [comment]
@srivatsn Who do you want to pick this up?

**Comment by jmarolf** [comment]
[fixed with interal PR https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_git/VS/pullrequest/39480]
