### ISSUE TITLE
Project System: Silently watson on unrecoverable exceptions

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn-project-system#41]
_From @davkean on May 10, 2016 23:51_

Property pages/Application Designer has a pattern of wrapping calls in try...catch and swallowing them - we should silently watson when we hit those blocks so that we can see stacks and hit counts.

_Copied from original issue: dotnet/roslyn#11229_

**Comment by mavasani** [comment]
This is now done for both MS.VS.Editors and MS.VS.AppDesigner projects. We should continue tuning the crash telemetry logging as an ongoing activity.
