### ISSUE TITLE
Prefer 32-bit can't be set when targeting .NET Core

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn-project-system#414]
Probably hard coded in page to .NET Framework 4.5

![image](https://cloud.githubusercontent.com/assets/1103906/18107228/fa0c6db0-6ebb-11e6-8517-80fd636279ef.png)

**Comment by RaulPerez1** [comment]
This was fixed with #929

**Comment by iskiselev** [comment]
Issue is still reproducible when TargetFramwork=net40

**Comment by davkean** [comment]
@iskiselev Prefer 32-bit isn't supported on .NET Framework 4.0, it was added in 4.5.
