### ISSUE TITLE
Portable PBD isn't showing up when targeting .NET Core

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn-project-system#415]
![image](https://cloud.githubusercontent.com/assets/1103906/18107330/3ff9e320-6ebc-11e6-964e-60db98e4a636.png)

**Comment by RaulPerez1** [comment]
@dotnet/project-system - Under what conditions can portable (or embedded) be set? The issue here is that the control is hardcoding 3 of the 5 options instead of conditionally initializing it based on the project.

**Comment by srivatsn** [comment]
@tmat?

**Comment by tmat** [comment]
This dialog is odd. The compiler doesn't have "internal error reporting". Why is check for overflow/underflow disabled?

**Comment by tmat** [comment]
Re PDB - the list should always include portable and embedded.

**Comment by srivatsn** [comment]
@tmat - "Internal error reporting" maps to csc's /errorreport switch. The disabled checkbox for overflow\underflow has been fixed - https://github.com/dotnet/roslyn-project-system/issues/416

**Comment by tmat** [comment]
I think we should remove "Internal error reporting". This is what it does in Roslyn:
http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp/CommandLine/CSharpCommandLineParser.cs,1066

**Comment by srivatsn** [comment]
Fixed by #929
