### ISSUE TITLE
Fields and labels not correctly sized on Project Properties Debug tab

### ISSUE THREAD

**Issue by srivatsn** [dotnet/roslyn-project-system#427]
This is a regression for desktop projects:
1. Create a desktop console application and open the Debug property page:

![image](https://cloud.githubusercontent.com/assets/20570/18140844/1de31224-6f6c-11e6-9c59-16e7906838a1.png)

**Comment by davkean** [comment]
What is that page...

**Comment by davkean** [comment]
Looks a whole lot of broken

**Comment by davkean** [comment]
This is probably multiple monitors with different DPIs, will investigate this week.

**Comment by davkean** [comment]
I've been unable to repro this - if you can repro this, can you list:

Resolutions of all screens
DPI of all screens

**Comment by davkean** [comment]
@srivatsn Do you have a repro for this?

**Comment by srivatsn** [comment]
No, I can't seem to repro it anymore. Tried various configurations.

**Comment by flcdrg** [comment]
I see this on a Dell XPS 15 9550 laptop running 384x2160 at 250%

![image002](https://cloud.githubusercontent.com/assets/384747/22917835/04c449f4-f2d7-11e6-816d-d73baadebef3.jpg)

With 15.0.0-RC.4+26206.0 and WPF project open.

**Comment by srivatsn** [comment]
Pulling this into 15.1 - there's bunch of VS Feedback around this. In https://developercommunity.visualstudio.com/content/problem/22367/vs-2017-rc-project-properties-window-debug-tab-con.html there's a MSFT person as well who can repro it. Can you try contacting them?

**Comment by adammodlin** [comment]
@srivatsn Hi, that was me. I do indeed have multiple monitors (2 1920x1200, 1 1080x1920). Not sure about DPI scaling settings. I'm seeing this in C# library projects, not in desktop apps.

**Comment by davkean** [comment]
@adammodlin Can you tell me exact monitors you are running?

**Comment by adammodlin** [comment]
@davkean Yes, here are the monitors (and the order they are daisy chained in case that matters):

Surface Pro 3 dock --> Dell U2415 --> Dell U2415 --> Dell P2414Hb.

They are all connected via DP or miniDP.

**Comment by srivatsn** [comment]
I've run into 5 more dupes on this on vsfeedback. We should prioritize this,

**Comment by flcdrg** [comment]
Seeing as I can repro this on my laptop, I thought I'd have a stab at pulling down the repo and firing it up. Any pointers on how the property pages work? Doesn't look like you're using the forms designer.

**Comment by davkean** [comment]
@flcdrg Thanks for the offer. The forms designer stopped opening when moved over to dogfood our repro in itself - we don't yet have WinForms support. I have an idea on what might be causing this - if I give you a branch to build can you test it?

**Comment by flcdrg** [comment]
Yes, happy to do that.

**Comment by tomeo** [comment]
![image](https://cloud.githubusercontent.com/assets/1422856/23943728/bac1a81e-0970-11e7-88ea-ab04cf8497e4.png)
Same problem in latest VS update. 2560x1440

**Comment by kroehne** [comment]
Is there any workaround?

14.0.0-RTW+26228.4 
 
![image](https://cloud.githubusercontent.com/assets/11849477/24085112/e322a1c2-0cf5-11e7-889f-4493cfbceda2.png)

**Comment by davkean** [comment]
@flcdrg I have a PR out, can you pull that branch and see if this resolves your issue?

**Comment by flcdrg** [comment]
Taking a look now..

**Comment by flcdrg** [comment]
Confirmed at my end that Debug tab looks correct now.

FYI I'm also seeing the 'opposite' problem for the Build tab. In that case the tab is stretching too far and ending up with a horizontal scrollbar. Do you want a new issue for that?

**Comment by davkean** [comment]
Thanks for the confirmation - I saw the same thing with the Build page and fixed that also: https://github.com/dotnet/roslyn-project-system/pull/1808.

**Comment by adammodlin** [comment]
@davkean Sure I can try to verify it tonight...what's the process behind getting that specific PR built?

**Comment by davkean** [comment]
@adammodlin:

1. Git clone https://github.com/davkean/roslyn-project-system.git
2. git checkout origin/DebugScaling
3. Open VS Command Prompt
4. Run Build.cmd
5. devenv /RootSuffix RoslynDev

This will start a new instance of VS with the changes (won't affect your main instance).

**Comment by davkean** [comment]
Thanks all, we've confirmed that we've fixed this for all DPIs.

**Comment by davkean** [comment]
This fixed via https://github.com/dotnet/roslyn-project-system/pull/1803
