### ISSUE TITLE
Files referenced from ..\ appear as broken files

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn-project-system#434]
Files do open when double clicked, but VS shows the broken link and broken folder icons. Relevant csproj and project: https://github.com/333fred/NetworkTables/blob/up-ref-files/src/FRC.NetworkTables/NetworkTables.csproj

![image](https://cloud.githubusercontent.com/assets/2371880/18213006/ec9db72e-70fa-11e6-94a6-701b9971f032.png)

**Comment by davkean** [comment]
Lifeng said that maybe the rules are screwed, can you make sure you have the right rules?

**Comment by 333fred** [comment]
Yeah, it's probably something wrong with my hacked together csproj. They appear correctly when I modify the .NET Core template to add a upper folder.

**Comment by 333fred** [comment]
![image](https://cloud.githubusercontent.com/assets/2371880/18216985/136b1ee6-710f-11e6-9d19-5ebd485e78c6.png)

**Comment by 333fred** [comment]
Scratch that again. I've narrowed down the behavior as follows:

* When adding a reference to an upper-level folder, the reference appears correctly if it's added while the project is open. When the project is closed and reopened, or if the reference is added while the project is closed, it has the behavior of the first screenshot, namely appearing as broken links. Note that while the icons are the broken link icons, the files and folders can still be opened.

**Comment by 333fred** [comment]
This appears to have been fixed in the latest wpt builds. #435 is still present.
