### ISSUE TITLE
Adding New Class File Fails

### ISSUE THREAD

**Issue by natidea** [dotnet/roslyn-project-system#436]
Build: wpt 25702.00
Template: DotNet-Core-Sdk\20160902-1

Create new .NET Core Console Application.
Right click project -> Add -> Class

Expected
Class Dialog

Actual
![image](https://cloud.githubusercontent.com/assets/7732033/18217956/8abf2b90-7114-11e6-93af-8d934e2c1fe1.png)

**Comment by 333fred** [comment]
Closing as a duplicate of #392
