### ISSUE TITLE
"Unrecognized Guid Format" when trying to add a class through solution explorer

### ISSUE THREAD

**Issue by basoundr** [dotnet/roslyn-project-system#438]
![image](https://cloud.githubusercontent.com/assets/10550513/18218261/572a021c-7116-11e6-8e63-8c19210753cf.png)

I see that there was already an issue opened #392 but fixed.

Installed 25702.00 wpt build and 20160902-1 drop of core sdk

**Comment by 333fred** [comment]
Closing as a duplicate of #392
