### ISSUE TITLE
Empty values for certain fields in the application property page

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn-project-system#439]
Application page for a default .net core app:

![applicationpage2](https://cloud.githubusercontent.com/assets/10605811/18218353/fd9285ca-7116-11e6-8f19-3bae3dd033ef.png)

**Comment by srivatsn** [comment]
Assembly name and namespace are empty because of https://github.com/dotnet/sdk/issues/106. TFM is empty because it doesn't recognize NETCoreApp as a valid tfm.

**Comment by srivatsn** [comment]
Tracking the TFM work in #582
