### ISSUE TITLE
VS thinks we are using C# 2.0

### ISSUE THREAD

**Issue by basoundr** [dotnet/roslyn-project-system#440]
Cannot use `var`. 

Error	CS8023	Feature 'implicitly typed local variable' is not available in C# 2.  Please use language version 3 or greater.	Test Console Application.csproj	c:\users\basoundr\documents\visual studio 15\Projects\Test Console Application\Test Console Application\Program.cs	13	Active

I remember this issue being discussed but I am not sure if an issue had already been opened.

**Comment by 333fred** [comment]
This is related to @davkean's language service work. No arguments are getting passed to the language service right now, so it thinks we're using old C#.

**Comment by mavasani** [comment]
Yes, even bunch of diagnostic related things should get addressed with new LS:

1. Diagnostic suppressions via nowarm don't work
2. No analyzer intellisense diagnostics. Even the build diagnostics for analyzers have no squiggles.
3. Project code analysis ruleset is not respected by intellisense

**Comment by srivatsn** [comment]
This is fixed with #369

**Comment by CEL-DavidReed** [comment]
This is happening again in Microsoft Visual Studio Professional 2022 (64-bit) Version 17.0.3 as at 21/12/2022.

**Comment by drewnoakes** [comment]
> This is happening again in Microsoft Visual Studio Professional 2022 (64-bit) Version 17.0.3 as at 21/12/2022.

Please file a feedback ticket (via the Help menu) and include as much detail as you can.
