### ISSUE TITLE
No default root namespace

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn-project-system#442]
When creating a new class, the $rootnamespace$ field is not filled in, resulting in an empty namespace and compilation errors.

![image](https://cloud.githubusercontent.com/assets/2371880/18219287/63f1ba74-711d-11e6-8363-7627f6ae57e5.png)

**Comment by 333fred** [comment]
I'm not sure if this is an issue with the template or not, if it is then this belongs in the sdk repo.

**Comment by srivatsn** [comment]
Yes this is https://github.com/dotnet/sdk/issues/106
