### ISSUE TITLE
Build/Rebuild/Clean should not show up for net core projects that failed to load

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn-project-system#444]
Edit the csproj to clear off the TargetFrameworkIdentifier and attempt to reload the project - project load fails (as expected), but solution explorer context menu still shows build/rebuild/clean options:

![contextmenuloadfailed](https://cloud.githubusercontent.com/assets/10605811/18219549/57fc28d8-711f-11e6-9b54-a049822bcd95.png)

**Comment by davkean** [comment]
Why did the project fail to reload?

**Comment by mavasani** [comment]
I accidentally cleared off the contents of TargetFrameworkIdentifier: `<TargetFrameworkIdentifier></TargetFrameworkIdentifier>`

**Comment by srivatsn** [comment]
Doesn't seem to repro anymore
