### ISSUE TITLE
Issues adding P2P reference from Desktop project to Net core project

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn-project-system#447]
1. Create a net core console app

2. Add a desktop console app to the solution and make it the startup project

3. Add P2P ref from desktop app to net core app

  ```
Severity	Code	Description	Project	File	Line	Source	Suppression State
Warning		The project 'ConsoleApplication2' cannot be referenced. The referenced project is targeted to a different framework family (.NETCoreApp)	ConsoleApplication1			Build	
 ```

4. Instantiate a public type defined in net core app in the main method of desktop app.
5. Solution builds fine but throws the below runtime exception:

```
Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
   at ConsoleApplication1.Program.Main(String[] args)
Press any key to continue . . .
```

**Comment by davkean** [comment]
This particular case is by design. You cannot reference .NETCoreApp from desktop - they are too different platforms. I would expect you to be able to reference .NET Standard, however.
