### ISSUE TITLE
Unfriendly error dialog when choosing to not add unsupported reference

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn-project-system#448]
1. Create a net core console app

2. Add a desktop console app to the solution

3. Attempt P2P ref from net core app to desktop app. As expected, we get an unsupported reference dialog:

![unsupportedreference1](https://cloud.githubusercontent.com/assets/10605811/18220660/0e835028-7129-11e6-898e-205d3ce14fd1.png)

Clicking on 'No' causes the following error dialog to show up, which seems like something crashed underneath.

![unsupportedreference2](https://cloud.githubusercontent.com/assets/10605811/18220687/5a5123b8-7129-11e6-984d-4d35b2ca8794.png)

**Comment by srivatsn** [comment]
This should be fixed now.
