### ISSUE TITLE
Context menu items for NuGet and Projects nodes in solution explorer

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn-project-system#449]
![contextmenu](https://cloud.githubusercontent.com/assets/10605811/18220894/624cdbf0-712b-11e6-8e21-ccf5f2ab8593.png)

1. View in object browser is a no-op
2. Add Fakes Assembly throws "Language not supported" dialog
3. Properties window is empty

**Comment by abpiskunov** [comment]
what is exactly you asking in this issue? To not show Properties menu item for root sub trees like Projects, Assemblies etc ?

**Comment by mavasani** [comment]
I am not sure what needs to show up here, but the existing commands seem to be non-useful - if nothing relevant is applicable for the nodes, then I am fine with even having no context menu.

**Comment by abpiskunov** [comment]
yes, sounds good

**Comment by srivatsn** [comment]
Dupe of #398
