### ISSUE TITLE
Unresolved project dependency icon not refreshed

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn-project-system#452]
1. Create 2 net core apps, and add a P2P reference from one to another.
2. Restore packages and build solution.

Build succeeds with 0 errors in the error list. However, the Project dependency shows up as unresolved with warning icon. Even doing a rebuild doesn't change the icon.

![projectdep](https://cloud.githubusercontent.com/assets/10605811/18221286/fd39e852-712f-11e6-8a52-d4352831bd47.png)

Another repro:
1. Create 2 net core apps, restore packages and build solution.
2. Add P2P reference from one to another and build solution again.
3. Rename the referenced project. Project dependency shows up as unresolved from now on and even doing a successful rebuild doesn't change the icon.

**Comment by basoundr** [comment]
This seems to be an issue related to #597. I dont see it any longer, hence closing this issue. @mavasani if you happen to see this, please reopen. Verified on d15rel 25831.0.
