### ISSUE TITLE
P2P References Don't Show Nested Refs

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn-project-system#453]
NuGet references show the transitive references that it depends on, but P2P references don't show this. Below, Lib1 depends on SharedProject1, and App1 depends on Lib1. You can't see that Lib1 depends on SharedProject1. I'm not sure how far we want to take this: is this by design, or should I be able to see the NuGet packages that SharedProject1 depends on by expanding the dependencies of App1?

![image](https://cloud.githubusercontent.com/assets/2371880/18221431/f87d88a8-7131-11e6-8cdb-b777d4326664.png)

**Comment by abpiskunov** [comment]
fixed with #675
