### ISSUE TITLE
Use EventHandler<TEventArgs>?

### ISSUE THREAD

**Issue by justinvp** [dotnet/roslyn-project-system#454]
I noticed in the screenshot in #451 that there are some concrete `XxxEventHandler` delegates:

![](https://cloud.githubusercontent.com/assets/20570/18221293/186cb7ee-7130-11e6-87c5-b2d18123f93c.png)

For example:

 - `DependenciesChangedEventHandler`
 - `ProjectContextEventHandler`

Could these be removed and uses replaced with `EventHandler<TEventArgs>` (e.g. `EventHandler<DependenciesChangedEventArgs>` and `EventHandler<ProjectContextEventArgs>`), or is there a reason these events can't use `EventHandler<TEventArgs>`?

**Comment by davkean** [comment]
@abpiskunov was there a reason for creating specific delegates? If not, we should fix this before we ship.

**Comment by abpiskunov** [comment]
yes, i will fix them soon

**Comment by abpiskunov** [comment]
fixed with #475
