### ISSUE TITLE
I want an example on how to work with .csproj

### ISSUE THREAD

**Issue by ArsenShnurkov** [dotnet/roslyn-project-system#462]
I.e. how to do following tasks programmatically:
1) load .csproj file content knowing it's filename;
2) print list of dependencies (Project references, assembly references and packages);
3) change dependencies (for example - change version of referenced assembly, or how to remove dependency as package and add dependency as project reference instead);
4) save modified .csproj file back to disk;
I want to have a console utility or set of msbuild tasks whose do such kind of things, that is why I am asking how to use this library as underlying implementation. Thanks.

**Comment by davkean** [comment]
Sorry for the late reply, I missed this. 

There is a non-trivial amount of code to get this correct. dotnet.exe is adding project manipulation APIs for doing this (adding packages/project references) - you should consider wrapping it instead.

**Comment by davkean** [comment]
I'm going to close this - feel free to file a new issue if you would like to discuss further.
