### ISSUE TITLE
Disable hosting process for managed projects

### ISSUE THREAD

**Issue by tommcdon** [dotnet/roslyn-project-system#463]
The VS diagnostics team has done the work to improve This is a work item to track the disablement of the hosting process for managed WPF, Winforms, console app projects.

**Comment by davkean** [comment]
There's seems to be a few things that need to happen:

1) The checkbox needs to be removed.
2) The project system code needs to be removed (we should maintain the IVsHierarchy/DTE.Project.Properties properties for compat)
3) The hosting process code needs to be deleted (vshost, Microsoft.VisualStudio.HostingProcess.Utilities.dll and Microsoft.VisualStudio.HostingProcess.Utilities.Sync.dll)
4) The setup authoring  code that authors vshost.exe, Microsoft.VisualStudio.HostingProcess.Utilities.dll and Microsoft.VisualStudio.HostingProcess.Utilities.Sync.dll

For the next preview, we may be able to take a staggered approach by just switch the project system default to false, and not respect the value in the project file.

**Comment by srivatsn** [comment]
The checkbox has been removed. I think @tmat is tracking the remaining cleanup.

**Comment by srivatsn** [comment]
Since this is in the native project system, created an internal bug to track the work.
