### ISSUE TITLE
XProj migration factory showing up in File -> New Project

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn-project-system#466]
![image](https://cloud.githubusercontent.com/assets/1103906/18404071/4bd1bdc4-769d-11e6-9da1-bbf1bccdba9e.png)

tag @333fred

**Comment by davkean** [comment]
This is 25709 WPT build.

**Comment by 333fred** [comment]
Annoyingly, I can't seem to replicate this with an older build. Looking at the code for `ProvideProjectFactoryAttribute`, I believe what we need to do is remove the different parameters being passed to it other than `typeof(XprojProjectFactory)`. But it's hard to test.

**Comment by 333fred** [comment]
Should be fixed after we next insert.
