### ISSUE TITLE
The vsix versions have to increase for every build

### ISSUE THREAD

**Issue by srivatsn** [dotnet/roslyn-project-system#479]
Today the version of the vsixes that we produce are 2.0.0.0. This means that when I do a build-to-build upgrade in willow, I don't get any new project system bits because the vsixinstaller thinks the vsix is already installed. We should have the buildnumber as version component similar to what we do for the templates vsix. 

@natidea assigning to you since you fixed up the versioning for the templates vsixes.

**Comment by srivatsn** [comment]
@mavasani has fixed this.

**Comment by natidea** [comment]
@srivatsn I think we also need to tweak the versions in the Editor swr files. This one is still hardcoded to 15.0.0.1: https://github.com/dotnet/roslyn-project-system/blob/master/src/VsixV3/EditorsPackage/Microsoft.VisualStudio.Editors.swr

**Comment by srivatsn** [comment]
This is now really done. Editor vsix has also been fixed.
