### ISSUE TITLE
Support project-to-project references from native project system and web sites

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn-project-system#486]
This might be a no-op but the native project system sniffs for IntellIsenseUnknown property which we are now returning nothing. Need to figure out what's going to break between native project system and venus and us.

**Comment by srivatsn** [comment]
I verified one basic scenario and it works. Assigning to @nguerrera since he's planning to test P2Ps in general.

**Comment by basoundr** [comment]
This is working. Needs to be tested still.
