### ISSUE TITLE
Source files for a project sometimes open in the miscellaneous project

### ISSUE THREAD

**Issue by srivatsn** [dotnet/roslyn-project-system#489]
With the new language service, create a console application. Open Program.cs. 

Observed: The file gets opened in the miscellaneous project (The project selector dropdown shows Miscellaneous project). A lot of IDE functionality is missing - like CodeLens, analyzers etc. *This only happens sometimes*. Sometimes, it opens in the correct project context and when it does everything works correctly.

I haven't been able to figure out any pattern to repro unfortunately.

**Comment by mavasani** [comment]
I see that first time I open a project in a new VS instance, the files end up in correct project, but closing and re-opening the project in the same VS instance always causes the file to go into misc project.

**Comment by davkean** [comment]
This is caused by the Handlers being empty on that first call back. Apparently a CPS bug.

**Comment by srivatsn** [comment]
Looks like this is still happening.

**Comment by mavasani** [comment]
Yes, not as frequently as before, but it still happens time to time.

**Comment by davkean** [comment]
As soon as I can get my VS install back up - I'll look at it again...

**Comment by srivatsn** [comment]
Looks like the only issue left is that we don't get out of restore state which is a roslyn bug.
