### ISSUE TITLE
Project System: Hosting process

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn-project-system#50]
_From @davkean on April 29, 2016 22:23_

We need to determine if we're going to implement the hosting process. We're waiting on the debugger team to provide data on how much time this saves on F5.

We'll also need an async way of initializing this - it's currently the top three of UI delays.

_Copied from original issue: dotnet/roslyn#10995_

**Comment by davkean** [comment]
_From @mikedn on April 30, 2016 6:35_

FWIW I consider the hosting process an annoyance because it pollutes the project output directory with unwanted files and changes the name of the process being debugged. Usually I turn off the hosting process and I never noticed any F5 delays or any other kind of problems.

**Comment by svick** [comment]
What is the difference between this issue and #66?

**Comment by davkean** [comment]
@svick Nothing. :) 

Just thought we weren't already tracking this.

**Comment by davkean** [comment]
Dupe of https://github.com/dotnet/roslyn-project-system/issues/66
