### ISSUE TITLE
Rename some tools packages IDs as part of the move to msbuild

### ISSUE THREAD

**Issue by morrisjoe** [dotnet/roslyn-project-system#501]
Looking very likely that we’ll have to rename some tools packages IDs as part of the move to msbuild. 
As such, customers migrating projects from project.json to MSBUILD will need to change package IDs (along with versions) for these packages. Is there scope to have the migrate experience do this?

Discussion between Damian and Brian....
While renaming the tools during the migration is admittedly a simple feature, there are a few things I’m worried about and which make me extremely hesitant to commit to this as a migration experience.

First thing is how will Migration determine the new versions of these tools? 
What if these new tool implementations have new imports, will migration need to know about this as well? 
What if the tools have moved from tools to tasks, and should now be dependencies?  
What if the tool was before invoked via script, and now shouldn’t be, does migration need to know to do special transformations for this special set of tools?
Will the tools be running on the same version of the shared framework as before or on 1.1.0? Does this mean we have to change the app’s version of the shared framework too, which will cause breakage? 

I’m hesitant because of how much semantic knowledge of tools this brings into the migration utility, but pragmatically I recognize the need.

Damian, can you construct a concrete list of which tools need to undergo changes and the full set of changes they would need, so we can figure out the requirements around this?

**Comment by muratg** [comment]
:watch:

**Comment by muratg** [comment]
@morrisjoe is this tracked elsewhere?

**Comment by morrisjoe** [comment]
Yes. As requested by @Srivatsn, I moved it to https://github.com/dotnet/cli/issues/4243
