### ISSUE TITLE
Remove old source code for AppDesigner/Editors

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn-project-system#510]
We need to remove the old source for AppDesigner/Editors from the VS tree.

**Comment by mavasani** [comment]
Dupe of VSO [247536](https://devdiv.visualstudio.com/DevDiv/_workitems?_a=edit&id=247536&triage=true)? By the way, we should do this soon as multiple teams have ended up changing the old sources and then hitting runtime exceptions.

**Comment by basoundr** [comment]
Blocked until LOC is completely moved over to GitHub and the insertion happens from the new source

**Comment by srivatsn** [comment]
UAP builds against the old sources. Fix that when deleting the sources.

**Comment by davkean** [comment]
This has been resolved.
