### ISSUE TITLE
F5 is broken for a console application

### ISSUE THREAD

**Issue by srivatsn** [dotnet/roslyn-project-system#513]
Create a console application, restore and F5:

![image](https://cloud.githubusercontent.com/assets/20570/18896877/2c272cfc-84da-11e6-8bb2-f45eef6aa573.png)

Is this related to the startup project work or launch profiles?

@basoundr @BillHiebert

**Comment by basoundr** [comment]
I was able to get it a few times but now I am not able to get it. On F5, the application seems to be starting and completes without doing anything.

The Debug window says this:
The program '[4256] dotnet.exe' has exited with code -2147450749 (0x80008083).
The program '[4256] dotnet.exe: Program Trace' has exited with code 0 (0x0).

**Comment by 333fred** [comment]
Relevant? http://stackoverflow.com/questions/38175242/the-program-13492-dotnet-exe-has-exited-with-code-2147450749

**Comment by 333fred** [comment]
There are also a couple of issues in aspnet/tooling: https://github.com/aspnet/Tooling/issues/646 and https://github.com/aspnet/Tooling/issues/538. Maybe this has something to do with the version of the cli that ships with VS?
