### ISSUE TITLE
xaml rules should be moved to props file instead of targets

### ISSUE THREAD

**Issue by abpiskunov** [dotnet/roslyn-project-system#519]
There is incorrect order in loading xaml rules - core xaml rules always loaded last since they live in CSharp.targets file and web xaml rules are brought by nuget package. MyProject.nuget.targets is loaded first (with web rules) and then CSharp.tagets are loaded. 

To solve this particular issue core xaml rules should be moved to props file instead of targets. However overall design might be revisited and CSharp.targets shoudl be loaded before nuget targets (to allow user's packages to override default features). Should we consider that?

**Comment by davkean** [comment]
We should set an expectation that overridable props and items (both from packages and project file) should be props, including our capabilities, and options.

**Comment by abpiskunov** [comment]
What milestone this is scheduled for?

**Comment by srivatsn** [comment]
The ordering of rules has been fixed. The designtime targets are loaded before the SDK now.
