### ISSUE TITLE
LanguageServiceHost is not receiving any project change events for references/command line options

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn-project-system#520]
1. Get a latest wpt build (I have 529.00 - project template is based off PackageReferences in the project file for NetCore SDK).
2. Create a DotNet core console application and open Program.cs - make sure the file does not open in Miscellaneous files (https://github.com/dotnet/roslyn-project-system/issues/489). If it does, then you might have to restart VS and try again.
3. Restore the project and build - verify build succeeds

Got: Intellisense errors around missing system types. When I attach a debugger for the above steps, I see that we receive Handle callbacks for SourceItemHandler, but none in MetadataReferenceItemHandler or CommandLineItemHandler - so we never set options or references for the project.

![referencesmissing](https://cloud.githubusercontent.com/assets/10605811/18998238/ae6d7fae-86ec-11e6-81af-b0270aaa6a28.png)

**Comment by davkean** [comment]
Design-time build is likely broken

**Comment by davkean** [comment]
This is not repro'ing for me after @srivatsn's change./
