### ISSUE TITLE
should apply globbing exclusion rules for compile and resx for bin and obj folders

### ISSUE THREAD

**Issue by abpiskunov** [dotnet/roslyn-project-system#522]
![image](https://cloud.githubusercontent.com/assets/1592091/19008022/f0978d96-8757-11e6-931d-23ba43c5aed1.png)

**Comment by davkean** [comment]
This is before restore state - we're going to have bugs galore in this when the SDK isn't present.

**Comment by abpiskunov** [comment]
actually restore happened already there and build succeeded - that's where that obj folder came from.

**Comment by srivatsn** [comment]
Keeping this around to track work for handling unrestored state.

**Comment by davkean** [comment]
No longer relevant given the SDK changes where we reference it by default.
