### ISSUE TITLE
AbstractSpecialFileProvider leaks a FileStream

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn-project-system#523]
We leak a FileStream here: https://github.com/dotnet/roslyn-project-system/blob/616530489cfe2153fe3ceca4849d4b18bda2cee6/src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/SpecialFileProviders/AbstractSpecialFileProvider.cs#L220.

I don't have a repro since I just saw it through inspection, but if someone attempted to delete the file immediately after we created it - it would fail to due a handle being open.

**Comment by srivatsn** [comment]
Fixed by #946

**Comment by davkean** [comment]
Ha, forgot that I filed this. Just saw it again and chose to fix it. :)
