### ISSUE TITLE
Adding a new project configuration leads to build error

### ISSUE THREAD

**Issue by natidea** [dotnet/roslyn-project-system#527]
Repro:
- Create a New .NETCore Console Application
- Ensure it restores and builds successfully for both Debug and Release configurations
- Use Debug|Release selector to Open Configuration Manager
- Under Active Solution configuration, choose `<New...>`
- Enter new configuration name (e.g. Wallaby) and Copy Settings From `Debug`
- Rebuild solution

Expected:
- Successful build

Actual
- Build Error:

```
Error       The OutputPath property is not set for project 'ConsoleApplication3.csproj'.  
Please check to make sure that you have specified a valid combination of Configuration 
and Platform for this project.  Configuration='Wallaby'  Platform='AnyCPU'.  
This error may also appear if some other project is trying to follow a project-to-project 
reference to this project, this project has been unloaded or is not included in the solution, 
and the referencing project does not build using the same or an equivalent Configuration or Platform.
    ConsoleApplication3 
C:\Program Files (x86)\Microsoft Visual Studio\VS15Preview\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets 731 
```

**Comment by mavasani** [comment]
What happens if you restore again and try to rebuild?

**Comment by natidea** [comment]
Restore works fine, (actually rebuild triggers the restore). [This comment](https://github.com/dotnet/sdk/issues/203#issuecomment-251215206) by @nguerrera may point to the problem:

> Our targets specify OutputPath for release and debug, but nothing else.

**Comment by davkean** [comment]
Yeah, this is the problem with the implicit configurations - someone really needs to sit down and design how these are going to work and how users are going to add/remove/rename configurations.

**Comment by nguerrera** [comment]
This will be "fixed" shortly in SDK. But work remains to actually manage the configurations. That will be tracked by #694
