### ISSUE TITLE
VS hangs when you show all folders in Core Web App 

### ISSUE THREAD

**Issue by srivatsn** [dotnet/roslyn-project-system#535]
Install WPT 25803.00 and apply all work-arounds, fixes, etc.  Eliminate App Insights.

Create a Core Web Application Project (no auth)

Only the Controllers folder is displayed in Solution Explorer:
![image](https://cloud.githubusercontent.com/assets/20570/19092590/3b4dd9ee-8a3c-11e6-80a4-969376c4f23a.png)

Click on the Project node and select the Show All Files button:

![image](https://cloud.githubusercontent.com/assets/20570/19092680/99088fb6-8a3c-11e6-893f-e0cc85542836.png)

Result: VS hangs

Note: If I restart VS and reopen the project, I can now Show All Files.

**Comment by mavasani** [comment]
I am unable to create a net core web app on latest wpt/d15prerel builds - I get an object reference not set to an object dialog on attempting to create it. @srivatsn Can you create one?

**Comment by srivatsn** [comment]
@balachir @jinujoseph - known?

**Comment by jinujoseph** [comment]
I just tried this on d15prerel - 25825.2 and was able to create fine and did not see the hang as well.
![image](https://cloud.githubusercontent.com/assets/12449387/19735026/aea679fe-9b5e-11e6-8d93-f7648959f7d7.png)

**Comment by mavasani** [comment]
Thanks @jinujoseph - I am closing this issue.
