### ISSUE TITLE
Create NuGet packages for the AppDesigner and Editors binaries

### ISSUE THREAD

**Issue by srivatsn** [dotnet/roslyn-project-system#536]
Microsoft.VisualStudio.AppDesigner.dll and Microsoft.VisualStudio.Editors.dll used to be in the GAC and are not in VS "15". There are VS extensions that reference this binary from the GAC in 2015 that will be broken in VS "15". We should create nuget packages for these binaries so that they can be referenced.

**Comment by AlexEyler** [comment]
Hey Sri - is this still being targeted for RC? We'd really like to be able to tell the teams that depend on these DLLs that there is a reference story for them.
