### ISSUE TITLE
Properties Page doesn't load some times 

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn-project-system#539]
**Repro**

Open a RoslynDev Hive 
Create a console application 
Right click the project and select properties 

**Expected** 
Properties page should load 

**Actual**

you some times get this error 
![image](https://cloud.githubusercontent.com/assets/12449387/19124812/8a0397f6-8ae9-11e6-832c-77a6cf36a028.png)

or will see some thing like 
The project configuration "Debug|AnyCPU" was not found in the project manifest.

**Comment by jinujoseph** [comment]
The issue lies here https://github.com/dotnet/roslyn-project-system/blob/d84bb9c78b4a0f86cbd7f6f4cc176cee01ca4001/src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Configurations/TargetFrameworkProjectConfigurationDimensionProvider.cs#L63 

comment that check and properties page should load fine.
@manish has more context on this ..

**Comment by mavasani** [comment]
Should get fixed with https://github.com/dotnet/roslyn-project-system/pull/534 - but I'll try to create a separate PR just for this change.
