### ISSUE TITLE
If project is open in VS, editing csproj outside VS using notepad and save, causes VS hang

### ISSUE THREAD

**Issue by balachir** [dotnet/roslyn-project-system#541]
**INSTALL STEPS**
Install VS build WPT.25803.01
Install CLI 1.0.0-preview3-003716
Point to the private MyGet feeds for restore

**REPRO STEPS**
1. File > New Project > ASP.NET Core Web Application (.NET Core) > Empty : EmptyWebAppOnCore8
2. Build solution
3. Right-click project > open in File Explorer
4. Open EmptyWebAppOnCore8.csproj using notepad
5. Change version of Microsoft.NETCore.Web from 1.0.0-alpha-20160925-1 to 1.0.0-alpha-20160928-1, and save changes in notepad
6. Switch back to VS

**ACTUAL**
VS is in a hung state. Call stack is attached 

[VSHang-CallStack.txt](https://github.com/dotnet/roslyn-project-system/files/512170/VSHang-CallStack.txt)

**Comment by davkean** [comment]
👍

**Comment by abpiskunov** [comment]
@balachir stack trace shows that some context menu was about to show and got stuck waiting for UI thread - did you open any (next time could you get a dump instead of the stack :) )?

**Comment by srivatsn** [comment]
This hasn't been reported lately and our daily testing includes this scenario. If this hang happens again, please reopen this bug.
