### ISSUE TITLE
Null Reference at Microsoft.VisualStudio.ProjectSystem.VS.Renamer.<OnWorkspaceChangedAsync>d__12.MoveNext()

### ISSUE THREAD

**Issue by jviau** [dotnet/roslyn-project-system#545]
**Repro**
Drag/drop an item in a shared project between 2 folders.

**Expected**
Item moves.

**Actual**
VS crashes due to a null reference.

**Comment by davkean** [comment]
@srivatsn This is quite bad - and we must fix for RC.

**Comment by davkean** [comment]
I cannot repro this, instead, occasionally I get: 

---------------------------
Microsoft Visual Studio
---------------------------
'path' cannot be an empty string ("") or start with the null character.

Parameter name: path
---------------------------
OK   
---------------------------

With this stack:
 	Microsoft.VisualStudio.Validation.dll!Microsoft.Requires.NotNullOrEmpty(string value, string parameterName)	Unknown
>	Microsoft.VisualStudio.ProjectSystem.dll!Microsoft.VisualStudio.ProjectSystem.PathHelper.EnsureTrailingSlash(string path) Line 366	C#
 	System.Core.dll!System.Linq.Enumerable.WhereSelectEnumerableIterator<string, string>.MoveNext()	Unknown
 	System.Core.dll!System.Collections.Generic.HashSet<string>.UnionWith(System.Collections.Generic.IEnumerable<string> other)	Unknown
 	System.Core.dll!System.Collections.Generic.HashSet<string>.HashSet(System.Collections.Generic.IEnumerable<string> collection, System.Collections.Generic.IEqualityComparer<string> comparer)	Unknown
 	Microsoft.VisualStudio.ProjectSystem.Implementation.dll!Microsoft.VisualStudio.ProjectSystem.Items.FoldersProjectItemProvider.SourceItemsProvider_ItemsRemoved(System.Collections.Generic.ICollection<Microsoft.VisualStudio.ProjectSystem.Properties.IProjectPropertiesContext> removedItems, Microsoft.VisualStudio.ProjectSystem.DeleteOptions deleteOptions) Line 1270	C#
 	Microsoft.VisualStudio.ProjectSystem.dll!Microsoft.VisualStudio.ProjectSystem.ProjectItemProviderBase<Microsoft.VisualStudio.ProjectSystem.IProjectSourceItem>.OnItemsIdentityChangedAsync(System.Collections.Generic.IEnumerable<System.Collections.Generic.KeyValuePair<Microsoft.VisualStudio.ProjectSystem.IProjectItem, System.Tuple<string, string>>> renamedItems) Line 831	C#
 	Microsoft.VisualStudio.ProjectSystem.Implementation.dll!Microsoft.VisualStudio.ProjectSystem.Items.SourceItemsService.SetUnevaluatedIncludesAsync(System.Collections.Generic.IReadOnlyCollection<System.Collections.Generic.KeyValuePair<Microsoft.VisualStudio.ProjectSystem.IProjectItem, string>> renames) Line 427	C#
 	[Resuming Async Method]

**Comment by jinujoseph** [comment]
Doesn't repro for me , also synced with @jviau and found to be no repro.
