### ISSUE TITLE
`dotnet migrate` first time setup hangs

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn-project-system#548]
When attempting to run `dotnet migrate` from VS where first time setup has never been run or needs to be rerun, the dotnet instance will hang. It appears to fully complete in all but exiting. All cli commands seem to work, and I can even open a parallel VS instance and migrate another project without issue. I see a `1.0.0-preview3-003770.inprogress.dotnetSentinel` file created in my `.nuget/packages` directory. 

Repro:

1. Get into a state where first time setup needs to run.
2. Attempt to migrate an xproj from inside VS.
3. Wait a minute for the first time setup to run.
4. dotnet is now installed and will work, but the migrate started by VS does not finish.
5. After killing the dotnet started by VS, the inprogress sentinel file goes away, and cli commands again need to run first time setup.

@livarcocc, any insight into what might be causing this? The code that executes the command is here: https://github.com/dotnet/roslyn-project-system/blob/master/src/Microsoft.VisualStudio.ProjectSystem.CSharp.VS/ProjectSystem/VS/Xproj/MigrateXprojProjectFactory.cs#L108

**Comment by livarcocc** [comment]
How long did you wait? It seems like the first experience is still running or maybe something went wrong with it. Can you see the output of the migrate command? It should have what is happening to first run there too.

**Comment by 333fred** [comment]
Thanks @nguerrera, the real issue is that I'm deadlocking the output by not using event-based calls. I have it fixed locally, I'll update the tests this afternoon.
