### ISSUE TITLE
Default names for templates, don't match new naming structure

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn-project-system#550]
![image](https://cloud.githubusercontent.com/assets/1103906/19160896/86ed0f30-8ba6-11e6-9f5f-d9b72cc6fd3c.png)

This should be "App", Console App has the same problem. Ditto for VB.

**Comment by jmarolf** [comment]
[Fixed in this internal PR](https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_git/VS/pullrequest/39936)
