### ISSUE TITLE
WPF Custom Control Library hasn't been updated with new naming

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn-project-system#551]
![image](https://cloud.githubusercontent.com/assets/1103906/19160952/bdaf7314-8ba6-11e6-8ac6-daa7809bff4e.png)

This should be called "WPF Control Library (.NET Framework)".

**Comment by jmarolf** [comment]
[fixed with internal PR](https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_git/VS/pullrequest/39938)
