### ISSUE TITLE
Add Restore Packages to Visual Studio UI

### ISSUE THREAD

**Issue by RickStrahl** [dotnet/roslyn-project-system#557]
Currently there appears to be no good way to restore packages from the Visual Studio UI. 

This seems to be quite a common task for me - when editing project.json many times today the package manager gets confused and refuses to resolve references properly. The UI actually says to Restore Packages, but there's nowhere to do this through the UI.

I know I can shell out to the command line and do `dotnet restore` but that's not really obvious especially to a new user.

Suggest when the UI asks to Restore Packages (yellow stripe) there's a link or button to do it from there. 
 Also on the References node there already is a Restore Packages but it's not working properly - Restore Packages doesn't seem to have any effect, where `dotnet restore` does work to clean up references.

**Comment by davkean** [comment]
Does Solution -> Restore Package not show up for you?

**Comment by srivatsn** [comment]
Closing since there's a menu item for this.
