### ISSUE TITLE
Building quickly after project creation leads to hang or restore failure

### ISSUE THREAD

**Issue by nguerrera** [dotnet/roslyn-project-system#569]
Repro steps:
1. File -> New project
2. Console App (NET Core)
3. Hit Ctrl+Shift+B

Depending on timing:
- Step 3 as fast as you can -> hangs VS (Dump saved to `<internal file share>\nicholg\roslyn-project-system_569\`)
- Step 3 pretty fast, but not too fast -> restore fails
- Give it a second before step 3 -> restore + build succeeds

**Comment by nguerrera** [comment]
Dump saved to <internal file share>\nicholg\roslyn-project-system_569\

**Comment by natidea** [comment]
Fixed by https://github.com/dotnet/roslyn-project-system/pull/685
