### ISSUE TITLE
Shared Projects show up in the Debugger Startup List

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn-project-system#571]
![image](https://cloud.githubusercontent.com/assets/1103906/19208287/646d573c-8cad-11e6-8d10-404f29146fbe.png)

If you select it, the selection doesn't change.

**Comment by basoundr** [comment]
Fixed in wpt branch with commit b916a86f

**Comment by basoundr** [comment]
Could someone verify this? I am leaving the assigned empty since David is on vacation

**Comment by basoundr** [comment]
Tagging @srivatsn so we still track this

**Comment by basoundr** [comment]
Had to revert the changes made to wpt branch. Trying to get it into d15prerel branch. Will update once the changes get through

**Comment by basoundr** [comment]
825b8df0 . Fixed in D15Prerel for RC2.
