### ISSUE TITLE
CodeLens is null-referring in the background on CPS projects

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn-project-system#575]
Stack:

This is 25806.00 WPT.

This is happening a lot just in the background CPS projects - can't seem to figure out what's triggering it.

```
>	mscorlib.dll!System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(System.Runtime.Remoting.Messaging.IMessage reqMsg, System.Runtime.Remoting.Messaging.IMessage retMsg)	Unknown
 	mscorlib.dll!System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(ref System.Runtime.Remoting.Proxies.MessageData msgData, int type)	Unknown
 	Microsoft.VisualStudio.Alm.Shared.CodeAnalysisClient.dll!Microsoft.VisualStudio.Alm.Roslyn.Client.VisualStudioWorkspaceHost.Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.IVisualStudioWorkspaceHost.OnProjectAdded.AnonymousMethod__0(System.Threading.Tasks.Task _)	Unknown
 	mscorlib.dll!System.Threading.Tasks.ContinuationTaskFromTask.InnerInvoke()	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task.Execute()	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task.ExecutionContextCallback(object obj)	Unknown
 	mscorlib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)	Unknown
 	mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task.ExecuteWithThreadLocal(ref System.Threading.Tasks.Task currentTaskSlot)	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task.ExecuteEntry(bool bPreventDoubleExecution)	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()	Unknown
 	mscorlib.dll!System.Threading.ThreadPoolWorkQueue.Dispatch()	Unknown
 	mscorlib.dll!System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()	Unknown
 	[Native to Managed Transition]	
 	kernel32.dll!73e762c4()	Unknown
 	[Frames below may be incorrect and/or missing, no symbols loaded for kernel32.dll]	
 	ntdll.dll!77360609()	Unknown
 	ntdll.dll!773605d4()	Unknown

```

**Comment by davkean** [comment]
This is my debugger log, everyone one of these nullrefs has a stack like above:

Exception thrown: 'System.NullReferenceException' in mscorlib.dll
Exception thrown: 'System.NullReferenceException' in mscorlib.dll
Exception thrown: 'System.NullReferenceException' in mscorlib.dll
Exception thrown: 'System.NullReferenceException' in mscorlib.dll
Exception thrown: 'System.NullReferenceException' in mscorlib.dll
Exception thrown: 'System.NullReferenceException' in mscorlib.dll
Exception thrown: 'System.NullReferenceException' in mscorlib.dll
Exception thrown: 'System.NullReferenceException' in mscorlib.dll
Exception thrown: 'System.NullReferenceException' in mscorlib.dll
Exception thrown: 'System.NullReferenceException' in mscorlib.dll
Exception thrown: 'System.NullReferenceException' in mscorlib.dll
Exception thrown: 'System.NullReferenceException' in mscorlib.dll
Exception thrown: 'System.NullReferenceException' in mscorlib.dll
Exception thrown: 'System.NullReferenceException' in mscorlib.dll
Exception thrown: 'System.NullReferenceException' in mscorlib.dll
The thread 0x15c4 has exited with code 0 (0x0).
Exception thrown: 'System.NullReferenceException' in mscorlib.dll
Exception thrown: 'System.NullReferenceException' in mscorlib.dll
Exception thrown: 'System.NullReferenceException' in mscorlib.dll
Exception thrown: 'System.NullReferenceException' in mscorlib.dll
Exception thrown: 'System.NullReferenceException' in mscorlib.dll
Exception thrown: 'System.NotSupportedException' in mscorlib.dll
Exception thrown: 'System.InvalidOperationException' in Microsoft.Build.dll
Exception thrown: 'System.NullReferenceException' in mscorlib.dll
Exception thrown: 'System.NotSupportedException' in mscorlib.dll
Exception thrown: 'System.NullReferenceException' in mscorlib.dll
Exception thrown: 'System.NotSupportedException' in mscorlib.dll
Exception thrown: 'System.NotSupportedException' in mscorlib.dll
Exception thrown: 'System.NullReferenceException' in mscorlib.dll
Exception thrown: 'System.NotSupportedException' in mscorlib.dll
Exception thrown: 'System.InvalidOperationException' in Microsoft.Build.dll
Exception thrown: 'System.NotSupportedException' in mscorlib.dll
Exception thrown: 'System.NotSupportedException' in mscorlib.dll
Exception thrown: 'System.NotSupportedException' in mscorlib.dll
Exception thrown: 'System.NotSupportedException' in mscorlib.dll
Exception thrown: 'System.InvalidOperationException' in Microsoft.Build.dll
Exception thrown: 'System.NotSupportedException' in mscorlib.dll
Exception thrown: 'System.NotSupportedException' in mscorlib.dll
Exception thrown: 'System.NotSupportedException' in mscorlib.dll
Exception thrown: 'System.NotSupportedException' in mscorlib.dll
Exception thrown: 'System.InvalidOperationException' in Microsoft.Build.dll
Exception thrown: 'System.NullReferenceException' in mscorlib.dll
Exception thrown: 'System.NotSupportedException' in mscorlib.dll
Exception thrown: 'System.NullReferenceException' in mscorlib.dll
Exception thrown: 'System.NotSupportedException' in mscorlib.dll
Exception thrown: 'System.NotSupportedException' in mscorlib.dll
Exception thrown: 'System.NotSupportedException' in mscorlib.dll
Exception thrown: 'System.InvalidOperationException' in Microsoft.Build.dll
Exception thrown: 'System.NullReferenceException' in mscorlib.dll
Exception thrown: 'System.NotSupportedException' in mscorlib.dll
Exception thrown: 'System.NotSupportedException' in mscorlib.dll
Exception thrown: 'System.NullReferenceException' in mscorlib.dll
Exception thrown: 'System.NotSupportedException' in mscorlib.dll
Exception thrown: 'System.NotSupportedException' in mscorlib.dll
Exception thrown: 'System.NullReferenceException' in mscorlib.dll
Exception thrown: 'System.InvalidOperationException' in Microsoft.Build.dll
Exception thrown: 'System.NotSupportedException' in mscorlib.dll
Exception thrown: 'System.NotSupportedException' in mscorlib.dll
Exception thrown: 'System.NullReferenceException' in mscorlib.dll
Exception thrown: 'System.NotSupportedException' in mscorlib.dll
Exception thrown: 'System.NullReferenceException' in mscorlib.dll
Exception thrown: 'System.NotSupportedException' in mscorlib.dll
Exception thrown: 'System.InvalidOperationException' in Microsoft.Build.dll
Exception thrown: 'System.NullReferenceException' in mscorlib.dll
Exception thrown: 'System.NotSupportedException' in mscorlib.dll
Exception thrown: 'System.NotSupportedException' in mscorlib.dll
Exception thrown: 'System.NullReferenceException' in mscorlib.dll
Exception thrown: 'System.NotSupportedException' in mscorlib.dll
The thread 0x3278 has exited with code 0 (0x0).
Exception thrown: 'System.NotSupportedException' in mscorlib.dll
Exception thrown: 'System.NullReferenceException' in mscorlib.dll
The thread 0x7f0c has exited with code 0 (0x0).
Exception thrown: 'System.InvalidOperationException' in Microsoft.Build.dll
Exception thrown: 'System.NullReferenceException' in mscorlib.dll
Exception thrown: 'System.NotSupportedException' in mscorlib.dll
Exception thrown: 'System.NotSupportedException' in mscorlib.dll
Exception thrown: 'System.NotSupportedException' in mscorlib.dll
Exception thrown: 'System.NullReferenceException' in mscorlib.dll
Exception thrown: 'System.NotSupportedException' in mscorlib.dll
Exception thrown: 'System.InvalidOperationException' in Microsoft.Build.dll
Exception thrown: 'System.NotSupportedException' in mscorlib.dll
Exception thrown: 'System.NullReferenceException' in mscorlib.dll
Exception thrown: 'System.NotSupportedException' in mscorlib.dll
Exception thrown: 'System.NotSupportedException' in mscorlib.dll
Exception thrown: 'System.NullReferenceException' in mscorlib.dll
Exception thrown: 'System.NotSupportedException' in mscorlib.dll
Exception thrown: 'System.InvalidOperationException' in Microsoft.Build.dll
Exception thrown: 'System.NullReferenceException' in mscorlib.dll
Exception thrown: 'System.NotSupportedException' in mscorlib.dll
Exception thrown: 'System.NullReferenceException' in mscorlib.dll
Exception thrown: 'System.NotSupportedException' in mscorlib.dll
Exception thrown: 'System.NotSupportedException' in mscorlib.dll
Exception thrown: 'System.NullReferenceException' in mscorlib.dll
Exception thrown: 'System.NotSupportedException' in mscorlib.dll
Exception thrown: 'System.InvalidOperationException' in Microsoft.Build.dll
Exception thrown: 'System.NotSupportedException' in mscorlib.dll
Exception thrown: 'System.NotSupportedException' in mscorlib.dll
Exception thrown: 'System.NotSupportedException' in mscorlib.dll
Exception thrown: 'System.NotSupportedException' in mscorlib.dll
The thread 0x5450 has exited with code 0 (0x0).
Exception thrown: 'System.InvalidOperationException' in Microsoft.Build.dll
Exception thrown: 'System.NullReferenceException' in mscorlib.dll
Exception thrown: 'System.NotSupportedException' in mscorlib.dll
Exception thrown: 'System.NullReferenceException' in mscorlib.dll
Exception thrown: 'System.NotSupportedException' in mscorlib.dll
Exception thrown: 'System.NotSupportedException' in mscorlib.dll
Exception thrown: 'System.NullReferenceException' in mscorlib.dll
Exception thrown: 'System.NotSupportedException' in mscorlib.dll
Exception thrown: 'System.InvalidOperationException' in Microsoft.Build.dll
Exception thrown: 'System.NullReferenceException' in mscorlib.dll
Exception thrown: 'System.NotSupportedException' in mscorlib.dll
Exception thrown: 'System.NullReferenceException' in mscorlib.dll
Exception thrown: 'System.NotSupportedException' in mscorlib.dll
Exception thrown: 'System.NotSupportedException' in mscorlib.dll
Exception thrown: 'System.NullReferenceException' in mscorlib.dll
Exception thrown: 'System.NotSupportedException' in mscorlib.dll
Exception thrown: 'System.InvalidOperationException' in Microsoft.Build.dll
Exception thrown: 'System.NotSupportedException' in mscorlib.dll
Exception thrown: 'System.NotSupportedException' in mscorlib.dll
Exception thrown: 'System.NullReferenceException' in mscorlib.dll
Exception thrown: 'System.NotSupportedException' in mscorlib.dll
Exception thrown: 'System.NotSupportedException' in mscorlib.dll
Exception thrown: 'System.InvalidOperationException' in Microsoft.Build.dll
Exception thrown: 'System.NotSupportedException' in mscorlib.dll
Exception thrown: 'System.NullReferenceException' in mscorlib.dll
Exception thrown: 'System.NotSupportedException' in mscorlib.dll
Exception thrown: 'System.NullReferenceException' in mscorlib.dll
Exception thrown: 'System.NotSupportedException' in mscorlib.dll
Exception thrown: 'System.NotSupportedException' in mscorlib.dll
Exception thrown: 'System.NullReferenceException' in mscorlib.dll
Exception thrown: 'System.InvalidOperationException' in Microsoft.Build.dll
Exception thrown: 'System.NotSupportedException' in mscorlib.dll
Exception thrown: 'System.NullReferenceException' in mscorlib.dll
Exception thrown: 'System.NotSupportedException' in mscorlib.dll
Exception thrown: 'System.NotSupportedException' in mscorlib.dll
Exception thrown: 'System.NullReferenceException' in mscorlib.dll
Exception thrown: 'System.NotSupportedException' in mscorlib.dll
Exception thrown: 'System.InvalidOperationException' in Microsoft.Build.dll
Exception thrown: 'System.NullReferenceException' in mscorlib.dll
Exception thrown: 'System.NotSupportedException' in mscorlib.dll
Exception thrown: 'System.NullReferenceException' in mscorlib.dll
Exception thrown: 'System.NotSupportedException' in mscorlib.dll
Exception thrown: 'System.NotSupportedException' in mscorlib.dll
Exception thrown: 'System.NullReferenceException' in mscorlib.dll
Exception thrown: 'System.NotSupportedException' in mscorlib.dll
Exception thrown: 'System.InvalidOperationException' in Microsoft.Build.dll
Exception thrown: 'System.NullReferenceException' in mscorlib.dll
Exception thrown: 'System.NotSupportedException' in mscorlib.dll
Exception thrown: 'System.NotSupportedException' in mscorlib.dll
Exception thrown: 'System.NotSupportedException' in mscorlib.dll
Exception thrown: 'System.NullReferenceException' in mscorlib.dll
Exception thrown: 'System.NotSupportedException' in mscorlib.dll
Exception thrown: 'System.NullReferenceException' in mscorlib.dll
Exception thrown: 'System.InvalidOperationException' in Microsoft.Build.dll
Exception thrown: 'System.NotSupportedException' in mscorlib.dll
Exception thrown: 'System.NullReferenceException' in mscorlib.dll
Exception thrown: 'System.NotSupportedException' in mscorlib.dll

**Comment by srivatsn** [comment]
@panopticoncentral this code is now gone right?

**Comment by panopticoncentral** [comment]
@srivatsn Yes, it will be gone as soon as we move CodeLens over.
