### ISSUE TITLE
New Console Application (.NET Core) - Dependencies node only shows the first level

### ISSUE THREAD

**Issue by balachir** [dotnet/roslyn-project-system#580]
**INSTALL STEPS**
WPT.25810.00
Add private MyGet feeds to Package Manager Settings

**REPRO STEPS**
1. New Console Application (.NET Core)
2. Right-click solution > Restore packages
3. Expand Dependencies node

**ACTUAL**
Only the first-level of dependencies are shown
![image](https://cloud.githubusercontent.com/assets/8246794/19244930/6f83e4e2-8ed3-11e6-8cbc-778c160637e4.png)

**EXPECTED**
Able to view the full tree of dependencies

**Comment by davkean** [comment]
Dup of https://github.com/dotnet/roslyn-project-system/issues/500.
