### ISSUE TITLE
"ResolvePackageDependenciesDesignTime" does not exist in the project

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn-project-system#581]
Opening a project I occasionally get:

Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB4057	The target "ResolvePackageDependenciesDesignTime" does not exist in the project.	ConsoleApplication2	C:\Users\davkean\AppData\Local\Temp\Folder\SharedProject1\ConsoleApplication2\ConsoleApplication2.msbuildproj	1

**Comment by adrianvmsft** [comment]
This issue causes these problems in CPS Barebones project:
- references are listed with the warning icon
- the Add References Dialog does not check the references that are already added to the project

Workaround: add an empty target to the project
```xml
<Target Name="ResolvePackageDependenciesDesignTime" />
```

**Comment by adrianvmsft** [comment]
These issues also happen in a .Net Core project

**Comment by basoundr** [comment]
Fixed in #664
