### ISSUE TITLE
New Console Application (.NET Core) and open property pages, Target framework dropdown in Application tab is empty

### ISSUE THREAD

**Issue by balachir** [dotnet/roslyn-project-system#582]
**INSTALL STEPS**
WPT.25810.00
Add private MyGet feeds to Package Manager Settings

**REPRO STEPS**
1. New Console Application (.NET Core)
2. Right-click solution > Restore packages
3. Open Property Pages > Application tab

**ACTUAL**
Target framework dropdown is empty

**EXPECTED**
Target framework dropdown should show something like: ".NET Core 1.0"? What does this dropdown mean in the new csproj world when a project can target multiple frameworks ?

**Comment by jinujoseph** [comment]
Resolved via #744
