### ISSUE TITLE
Need a perf marker for first "package restore complete" when opening a .sln 

### ISSUE THREAD

**Issue by raquelsa** [dotnet/roslyn-project-system#590]
Web Tools perf tests for ASP.NET used to rely on code markers that would fire when first package restore is complete on solution open. Now that web tools team no longer controls package restore, we need a new code marker to listen to and update our tests.

**Comment by davkean** [comment]
@natidea Can you work with NuGet to figure out who's responsible for raising package restore perf marker?

In particular it's called: KnownCodeMarkers.perfPackageRestoreEnd (there's probably a start as well). ASP.NET team's perf tests are blocked on this.
