### ISSUE TITLE
Need to close and reopen project after restore to get source files out of Misc project

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn-project-system#591]
1. File -> New .NET Core project
2. Restore project
3. Open Program.cs

Notice in Misc proj. Closing project and reopening causes it to fix itself.

**Comment by srivatsn** [comment]
This doesn't happen anymore.

**Comment by jinujoseph** [comment]
linking nuget bug :https://github.com/NuGet/Home/issues/3807

**Comment by mavasani** [comment]
@jinujoseph This bug is closed. Are you still seeing this?

**Comment by mavasani** [comment]
Also this seems unrelated to NuGet/Home#3807

**Comment by jinujoseph** [comment]
No i am not seeing Misc project issue , but there is a issue with stale errors not clearing up from VS unless we close and reopen the project , which seems related to #3807
