### ISSUE TITLE
C#/VB graph providers do not work

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn-project-system#592]
The [C#](https://github.com/dotnet/roslyn/blob/614299ff83da9959fa07131c6d0ffbc58873b6ae/src/VisualStudio/CSharp/Impl/Progression/CSharpGraphProvider.cs) and [VB](https://github.com/dotnet/roslyn/blob/614299ff83da9959fa07131c6d0ffbc58873b6ae/src/VisualStudio/VisualBasic/Impl/Progression/VisualBasicGraphProvider.vb) graph providers need to be updated to use capabilities instead of intellisense GUID. They should probably use "CSharp + LanguageService" and "VB + LanguageService"

Make sure that Shared Project's also work.

**Comment by RaulPerez1** [comment]
Fixed via https://github.com/dotnet/roslyn/issues/16572
