### ISSUE TITLE
Large performance regression to load Picasso in AbstractSpecialFolderProjectTreePropertiesProvider

### ISSUE THREAD

**Issue by lifengl** [dotnet/roslyn-project-system#618]
We saw a large perf regression in the CPS perf test to load Piscasso into CPS.  The AstractSpecialFolderProjectTreePropertiesProvider.CalculatePropertyValues contributes 1.4s to the CPU time during the solution load.

This is to track this part of the regression (as a part of VS bug 277029)
Trace can be found:
\\[Internal file share]\Public\cps-perf\Dev15\Picasso-cps\25810.00(wpt)\CpsPicassoEndToEnd-10-12-2016-063623\DataBackup-2016-10-12-18-36

Name                                                                                                                     	Inc %	     Inc	Inc Ct	Exc %	Exc
 microsoft.visualstudio.projectsystem.implementation!PhysicalProjectTreeProvider.ApplyPropertiesProviderExtensions       	 10.2	   1,431	 1,431	  0.0	  6
+ microsoft.visualstudio.projectsystem.managed!AbstractSpecialFolderProjectTreePropertiesProvider.CalculatePropertyValues	  9.8	   1,368	 1,368	  0.0	  1
|+ microsoft.visualstudio.projectsystem.managed!AppDesignerFolderProjectTreePropertiesProvider.get_IsSupported           	  9.6	   1,340	 1,340	  0.0	  0
||+ microsoft.visualstudio.projectsystem.managed.vs!ProjectDesignerService.get_SupportsProjectDesigner                   	  9.5	   1,331	 1,331	  0.0	  0

**Comment by lifengl** [comment]
The trace was take from WPT 25810.00.  The trace doesn't match code I saw from the index.  Please do not call into VSHierarchy property in the project tree properties provider.  A project tree properties provider should be a pure calculation based on its input.  Calling VsHierarchy might be a point which can cause dead locks.

**Comment by lifengl** [comment]
The appDesigner check is also only necessary for a folder when the parent node is the project root

**Comment by mavasani** [comment]
@lifengl What is the right way to check if appdesigner is supported, without accessing `VsHierarchyPropID.SupportsProjectDesigner` property from the hierarchy? Is this data somewhere in the input?
