### ISSUE TITLE
Class view not populated for a .NET Core project until a non-.NET Core project uses it

### ISSUE THREAD

**Issue by mlorbetske** [dotnet/roslyn-project-system#621]
Create a Core Web Application (no auth)
Open Class View window
    --- Issue --- window is empty
Create an emtpy WAP
Note that Class View is populated
Switch back to Core project
Class View is now populated.

You must use Class View in a non-Core pojrect for it to populate.

**Comment by 333fred** [comment]
@mlorbetske, this isn't reproing for me on d15rel 25906.00. If you see it again, please reopen.
