### ISSUE TITLE
Failed to create new project platforms on Console App (.NET Core) project

### ISSUE THREAD

**Issue by Incyuna2z** [dotnet/roslyn-project-system#631]
Repro Steps:

1. Create a Console App (.NET Core) project
2. Build ------------------An error in Error List window
![issue](https://cloud.githubusercontent.com/assets/12093193/19547107/cf0cf038-96c7-11e6-87dd-306a44a871ac.jpg)

3. Select 'Configuration Manager…' in Solution Platforms
4. In Configuration Manager window, click '<New…>' in Active solution platform drop down list
5. Click 'OK' in New Solution Platform window------------Failed to create new project platforms
![step5](https://cloud.githubusercontent.com/assets/12093193/19547119/e783051c-96c7-11e6-9ae1-a55a398d551f.jpg)

**Comment by Incyuna2z** [comment]
I faced this issue on **bcb1**.25818.01 and 25819.00

**Comment by srivatsn** [comment]
#527 has more discussion on this issue. Using that issue to track instead.,
