### ISSUE TITLE
[Suggestion] Getting rid of PropertyGroup/ItemGroup 

### ISSUE THREAD

**Issue by MaximRouiller** [dotnet/roslyn-project-system#632]
By @filipw:

> How about a csproj without `<PropertyGroup>`, `<ItemGroup>`, the 2 default imports and an implicit  `<Compile Include="**\*.cs" />`

> ```
<Project>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp1.0</TargetFramework>

>    <PackageReference Include="Microsoft.NETCore.App" Version="1.0.0" />
>    <PackageReference Include="Microsoft.NET.SDK" Version="1.0.0" />
</Project>
> ```

**Comment by Mike-EEE** [comment]
![](http://i.imgur.com/0mKXcg1.gif)

**Comment by luisrudge** [comment]
next step: simple json to xml conversion :trollface:

**Comment by gulbanana** [comment]
without groups, how would the build system tell whether something was a property or an item if it was not repeated?

**Comment by srivatsn** [comment]
This would need to be a msbuild feature. Please file the issue over at https://github.com/microsoft/msbuild

**Comment by MaximRouiller** [comment]
@srivatsn Done. /cc @filipw

**Comment by 333fred** [comment]
Closing as this has been ported to the appropriate repo.

**Comment by forki** [comment]
Does the same thing work for fsproj? Cc @kevinransom
