### ISSUE TITLE
legacy csproj project system - editing csproj file squiggles <PackageReference />

### ISSUE THREAD

**Issue by rrelyea** [dotnet/roslyn-project-system#638]
1. see repro steps from https://github.com/NuGet/Home/issues/3723
   (need some nuget bits that aren't in d15prerel yet)

expected: 
intellisense (xsd?) of .csproj understands <PackageReference />

actual:
red squiggle

**Comment by 333fred** [comment]
Related to #220.

**Comment by srivatsn** [comment]
This is now fixed.
