### ISSUE TITLE
VS 2015 should warn about not being to handle netcore projects

### ISSUE THREAD

**Issue by srivatsn** [dotnet/roslyn-project-system#640]
NetCore projects depend on a bunch of new features in the new project system in VS "15" and in the new msbuild. However, since these are just csproj files, if opened in VS 2015, it will open but will probably mess up the project and function incorrectly. We should figure out a way to block opening of these projects in 2015. It would be ideal if we can do it without some artifact in the project file like ToolsVersion or something that'll add cruft to the file.

**Comment by NickCraver** [comment]
Initial crazy thoughts: how about a lack of the XML namespace? More generally: instead of triggering on an artifact that *adds* cruft, we could do detection based on the *lack of* cruft.

**Comment by srivatsn** [comment]
Since we now have new syntax for the SDK attribute on a project and items with metadata as attributes, these projects won't load correctly in VS 2015.
