### ISSUE TITLE
Two sets of CSharp.xaml, CSharp.BrowseObject.Xaml, CSharp.ProjectItemsSchema.xaml deployed

### ISSUE THREAD

**Issue by lifengl** [dotnet/roslyn-project-system#642]
One sets is under MSBuild\15.0\bin\en-US, and another sets are under MSbuild\Microsoft\VisualStudio\Managed\

They are not exactly the same, 

The first set is referenced inside Microsoft.CSharp.CurrentVersion.targets, the second set is referenced indirectly through Microsoft.CSharp.DesignTime.targets.

Do we need a duplicated but slightly different sets of those files?  They are all loaded into VS,

**Comment by srivatsn** [comment]
This should be fixed now. The msbuild imports were setup in a way that both were getting imported but ours would override. Now it's been changed such that just the copy from the msbuild\Microsoft\visualstudio\managed should get loaded.
