### ISSUE TITLE
Project System: We need a compat mode to let a project be opened in csproj/msvbproj when features are not supported

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn-project-system#65]
_From @davkean on April 12, 2016 0:54_

I'm thinking that we implement a pre-req handler via IVsRetargetProject that does a check to see if the project contains a list of unsupported features, and then offers to reload via csproj/msvbproj.  

As we bring up features we simply remove them from this list so that we open more and more projects via CPS.

_Copied from original issue: dotnet/roslyn#10493_

**Comment by srivatsn** [comment]
Need to file a bug against CPS for new projects.

**Comment by jinujoseph** [comment]
@srivatsn  I am going to file a new bug regarding having the ability to dogfood..
Let me know if some thing needs to be done here.
