### ISSUE TITLE
Build should be blocked if a restore operation is underway

### ISSUE THREAD

**Issue by srivatsn** [dotnet/roslyn-project-system#654]
With auto-restore, the restore operation could be underway when a build gets kicked off. We should make the build wait for the restore to complete to be in a consistent state.

**Comment by natidea** [comment]
NuGet tracking issue: https://github.com/NuGet/Home/issues/3780

**Comment by rrelyea** [comment]
Eta for this fix to block build during restore? Anything you need from us?
