### ISSUE TITLE
In most cases DesignTime build returns empty ResolvedProjectReferences data

### ISSUE THREAD

**Issue by abpiskunov** [dotnet/roslyn-project-system#663]
Very rarely i saw receiving expected data in snapshots for ResolvedProjectReferences , in most cases when your projecA references project B we receive empty snapshots for ResolvedProjectRefernces. Could be something with ResolveProjectReferencesDesignTime  target or some weird timing in CPS, if they have any specific logic for ResolvedProjectReference rules.

**Comment by abpiskunov** [comment]
This results in project reference nodes to appear yellow (unresolved) most of the time.

**Comment by abpiskunov** [comment]
I figured what is going on, it appears that some timing changed and unresolved projects are sent first without resolved ones and Dependencies code was confused . This is a bug in Dependencies nodes provider. I am grabbing it. Fix is available, will checkin along with other Dependencies bug fixes on monday.

**Comment by srivatsn** [comment]
Did a F2F review and added some comments but looks good for the most part.
