### ISSUE TITLE
Nominate project api is not called for multi-target frameworks

### ISSUE THREAD

**Issue by jainaashish** [dotnet/roslyn-project-system#672]
CPS projects with multi-targeting frameworks are not being nominated after add/ remove package references. Which creates further issues for nuget ui.

Check nuget issue to get exact repro steps: https://github.com/NuGet/Home/issues/3803

**Comment by jainaashish** [comment]
This is @rrelyea -- This will break AutoRestore for multitargetting in VS for RC. Is this on path to fix? (i don't understand what preview 5 is...)

**Comment by srivatsn** [comment]
Yes @natidea or @basoundr whoever gets done with their current issue first will look into this next.

**Comment by natidea** [comment]
I have a fix that appears to be working consistently. (Prior to this, I saw it work sometimes.) Doing more validation and setting up a PR.
