### ISSUE TITLE
GUID shows-up in new csproj format

### ISSUE THREAD

**Issue by morrisjoe** [dotnet/roslyn-project-system#676]
**Repro:**
Install latest RC bits from d15prerel ( I used \\cpvsbuild\drops\VS\d15prerel\products\25830.00)
File->NewPorject->Console(Core)
Open the csproj file

**Expected:**
Shouldn't see any GUIDs

**Actual:**
See a GUID (see image)
![guidincsproj](https://cloud.githubusercontent.com/assets/12700391/19866656/3a276eea-9f5e-11e6-8fed-89bf0aed907f.jpg)

**Comment by 333fred** [comment]
It appears that our ImplicitProjectPropertiesProvider isn't being called for this property, so it's delegating to the default provider, which of course saves the property.

**Comment by srivatsn** [comment]
The issue is understood and @basoundr is preparing a PR for this issue.
