### ISSUE TITLE
Migrated project from command-line migration again prompts migration when opened from VS

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn-project-system#690]
Refer https://github.com/dotnet/cli/issues/4561 for repro steps

**Comment by 333fred** [comment]
@srivatsn, I think the way we should handle this is by checking to see if there's a csproj in the directory already, and if so, just loading it. What timeframe do we want this for?

**Comment by 333fred** [comment]
@piotrpMSFT, if we don't want the dialog to pop up in VS, there's no way around it; migration will have to modify the solution file.

**Comment by 333fred** [comment]
This was fixed in the CLI when running migrate on a solution file.
