### ISSUE TITLE
Configuration management

### ISSUE THREAD

**Issue by nguerrera** [dotnet/roslyn-project-system#694]
VS side of https://github.com/dotnet/sdk/issues/350

We need to stop inferring configurations from usage and support a different scheme for managing them. See the SDK issue for the proposed scheme.

We also need to make 'Copy settings from ___' work when creating new configurations. Today, it creates a new property group using the old inference pattern but does not transfer any settings.

**Comment by mavasani** [comment]
Isn't this going to be a very risky change at this stage? Note that we made changes to CPS [ImplicitProjectConfigurationsService](http://index/?query=ImplicitP&rightProject=Microsoft.VisualStudio.ProjectSystem.Implementation&file=ImplicitProjectConfigurationsService.cs&line=77) to export a collection of 3rd party Project [DimensionProviders](http://index/?leftProject=Microsoft.VisualStudio.ProjectSystem.Implementation&leftSymbol=yi9zsn3yhvqu&file=ImplicitProjectConfigurationsService.cs&rightSymbol=c6izohgy7c0m), which allow us to add `TargetFramework` as a project configuration dimension using [TargetFrameworkProjectConfigurationDimensionProvider](http://index/?leftProject=Microsoft.VisualStudio.ProjectSystem.Managed&leftSymbol=mmzgb6nr8w6w). I don't think any other CPS project configurations service have this extensibility point, so I am unsure how we are attempting to tackle this without a significant refactoring/functionality add in CPS.

**Comment by RaulPerez1** [comment]
I'm experimenting with the same approach for Config/Platform but as you mentioned it doesn't looks like CPS is picking those up. I'm trying to build CPS now to debug the scenario and get a better idea on what we need. I agree that if it's not something we can change on our side easily we need to look for other options (or move this to post RTW)

**Comment by mavasani** [comment]
Also tagging @lifengl for confirmation, but as far as I know, only [ImplicitProjectConfigurationsService](http://index/?leftProject=Microsoft.VisualStudio.ProjectSystem.Implementation&leftSymbol=c6izohgy7c0m&file=ImplicitProjectConfigurationsService.cs) supports extensible dimension providers, since it was needed for our specific requirement.

**Comment by srivatsn** [comment]
When fixing this make sure that removing\renaming an existing configuration works and also that copying from an existing configuration works.

**Comment by davidmatson** [comment]
Is the following behavior also part of this bug?

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net452</TargetFramework>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <DisableImplicitFrameworkReferences>true</DisableImplicitFrameworkReferences>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
  </PropertyGroup>
</Project>
```

Then, in project properties for all configurations, change Build -> Platform target to x86.

Expected:
RuntimeIdentifier changes to win-x86

Actual:
RuntimeIdentifier is unchanged, and conflicting platform target properties are added. Updated csproj is:
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net452</TargetFramework>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <DisableImplicitFrameworkReferences>true</DisableImplicitFrameworkReferences>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <PlatformTarget>x86</PlatformTarget>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <PlatformTarget>x86</PlatformTarget>
  </PropertyGroup>
</Project>
```

Having the full plethora of x64, AnyCPU and x86 added here is delightful :)

**Comment by RaulPerez1** [comment]
@davidmatson - No but it could be partially related to #1300

**Comment by davidmatson** [comment]
OK, I'll file a separate bug then. Was trying to avoid spamming with bugs that get dup'd to this one; I'm 0 for 4 guessing which way to go :)

#1820
