### ISSUE TITLE
Namespace not added to created first file created in the class library project   

### ISSUE THREAD

**Issue by bzhu94** [dotnet/roslyn-project-system#697]
REPRO STEPS:

1. Create a new Console App (.NET Core) project.
2. In the same solution, create a new Class Library (.NET Standard) project.
3. Add a new C# class into the Class Library.

Expected: The namespace of the file is set.

Actual: The namespace of the file is not set to anything.

**Comment by 333fred** [comment]
Dupe of  https://github.com/dotnet/sdk/issues/271
