### ISSUE TITLE
Flaky Test: TaskDelaySchedulerTests.Dispose_ClearsPendingTasks

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn-project-system#699]
Failed here: https://ci.dot.net/job/dotnet_roslyn-project-system/job/master/job/windows_release_prtest/601/

@BillHiebert, anything you've seen before?

**Comment by BillHiebert** [comment]
@333fred  - are you still seeing this? The link in the issue is no longer available

**Comment by BillHiebert** [comment]
@333fred  - I see what the problem is. The test code assumes the task will never run, but due to scheduling it could execute.
