### ISSUE TITLE
Project migration failed from IDE 

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn-project-system#703]
**Repro steps** 
- unzip \\scratch2\scratch\jinuj\TestSceanrio\VSMigrationDemo.zip to your local machine 
- open the solution 

**Expected** 
Project migrated successfully 

**Actual**
![image](https://cloud.githubusercontent.com/assets/12449387/19985343/7fd97de8-a1cf-11e6-8d56-24bfca0793e1.png)

Pls note that migration works from cli 
![image](https://cloud.githubusercontent.com/assets/12449387/19985730/381b385a-a1d1-11e6-91c8-8f169d6ef200.png)

**Build Info** 
d15rel/15.0.25902.2
1.0.0-preview3-004040

**Comment by 333fred** [comment]
@jinujoseph, I can't repro this on the same build. The error message indicates that it couldn't find the relevant project.json. Could you make sure that you didn't accidentally move or delete a file? @piotrpMSFT, anything you've seen before?

**Comment by jinujoseph** [comment]
Did you try from the same project i provided.
Before migration 
![image](https://cloud.githubusercontent.com/assets/12449387/19989078/4a7d5220-a1e1-11e6-930b-0ef79fe015fa.png)

After migration 
![image](https://cloud.githubusercontent.com/assets/12449387/19989097/6ce29280-a1e1-11e6-9dd7-b66028c157de.png)

**Comment by piotrpMSFT** [comment]
We added backup functionality to cli. If it successfully migrates it moves all pj artifacts to backup folder. I understand this is affecting VS migration. VS can disable by passing --no-backup to `dotnet migrate`

**Comment by 333fred** [comment]
Closed by #706.
