### ISSUE TITLE
Edit csproj to add a package and then close the file , prompts for wrong filename

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn-project-system#704]
![image](https://cloud.githubusercontent.com/assets/12449387/19986960/f9f4cda2-a1d5-11e6-8440-a887ec96563a.png)

Environment data

d15rel/15.0.25902.2
1.0.0-preview3-004040

**Comment by 333fred** [comment]
That is the correct file name, unfortunately. I'm not sure that there's really anything we can do about this with the current implementation, It is actually editing a temp file. I'm just changing the displayed name in the tab title.

**Comment by srivatsn** [comment]
How about we make the temp file's name be just the right csproj file but in a temp directory- will that work?

**Comment by 333fred** [comment]
If you have multiple VS instances open, they'll clobber each other.

**Comment by 333fred** [comment]
We're going to have each VS create a temp directory, and put the real named project file in there.
