### ISSUE TITLE
 No Intellisense on TargetFramework and PackageReference

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn-project-system#715]
![image](https://cloud.githubusercontent.com/assets/12449387/20051249/ed8edb84-a482-11e6-8b65-116a37a75026.png)

**Envioronment**
build: d15rel/25904.2
cli: 1.0.0-preview3-004056

**Comment by srivatsn** [comment]
@RaulPerez1 can you update the schema to include these?

**Comment by RaulPerez1** [comment]
The schema is global so modifying that will make these tags show up in member list for any project regardless of if it's supported or not. Is that what we want?

Note that with the changes to the xml editor those 2 squiggles won't show up.

**Comment by srivatsn** [comment]
Both these can be applied to regular projects as well and so it's fine to put them in the schema. The editing scenario is more important for CPS-based projects.

**Comment by RaulPerez1** [comment]
For PackageReference, do we want to expose all of the properties defined in src\Microsoft.VisualStudio.ProjectSystem.Managed\ProjectSystem\Rules\PackageReference.xaml?

**Comment by RaulPerez1** [comment]
Change for this needs to happen on the VS side. Opening a bug there.

**Comment by davkean** [comment]
@RaulPerez1 this isn't VS side, it should be msbuild http://github.com/microsoft/msbuild.

**Comment by RaulPerez1** [comment]
Thanks for pointing that out, here's the PR on the MsBuild repo https://github.com/Microsoft/msbuild/pull/1347#pullrequestreview-8693522
