### ISSUE TITLE
Project edit:  Error needs a reload ?

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn-project-system#716]
Edit a project and introduce an error (missed the closing tag) 
![image](https://cloud.githubusercontent.com/assets/12449387/20069658/4f5c2ef8-a4d2-11e6-9add-c59af55cb22f.png)

The project is forced to reload 
![image](https://cloud.githubusercontent.com/assets/12449387/20069604/1b57e5c0-a4d2-11e6-943b-e79c7ea22c93.png)

The project fails to load and on reload you will get right error message.
![image](https://cloud.githubusercontent.com/assets/12449387/20069626/2bd8d0f8-a4d2-11e6-9b77-f6e1694ce612.png)

Is it possible to inform the error without reload?

**Comment by 333fred** [comment]
@jinujoseph, there is a red squiggle that appears before the file is saved, showing the error. Once the file is saved, it has overwritten the project file on disk. so there's not a heck of lot we can do there. The only way we could make this work is there was an MSBuild api to evaluate a given file and return whether or not it's a valid project.

**Comment by davkean** [comment]
Dup'ing this against: https://github.com/dotnet/roslyn-project-system/issues/1570 which is tracking this.
