### ISSUE TITLE
Remove References functionality missing.

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn-project-system#717]
**Repro Steps** 

- Create a console application (.Net Core)
- Create a Class Library (.Net Standard) 
- Reference class library from console by 
Dependencies -> Add references 
- Now try to get rid of it.

**Actual**
you need to click 'add references' and uncheck the reference 

**Expected** 
This menu should have a remove option.
![image](https://cloud.githubusercontent.com/assets/12449387/20070810/b49b3e4a-a4d6-11e6-8b6f-021e1f9e2798.png)

**Comment by abpiskunov** [comment]
dupe: https://github.com/dotnet/roslyn-project-system/issues/708
