### ISSUE TITLE
P2P reference from .Net Core Console -> .Net Framework Class Library

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn-project-system#718]
**Repro Steps** 

- Create a .Net Core Console Application
- Create a .Net Framework Class Library 
- Add reference from Console to Class Library 
- Add a method in Class Library and call the same via console
- Build 

**Expected**
Build Succeeded 

**Actual** 
Build Failed
![image](https://cloud.githubusercontent.com/assets/12449387/20071025/aa0592a4-a4d7-11e6-9e18-b9ae67bb3078.png)

**Enviornment Info** 

build: d15rel/25904.2
cli: 1.0.0-preview3-004056

**Comment by srivatsn** [comment]
This is an incompatible configuration. The issue here is that we are not issuing an error saying it's incompatible. https://github.com/dotnet/sdk/issues/264 tracks that bug,
