### ISSUE TITLE
Nuget dependencies only displayed for .Net Core projects 

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn-project-system#719]
**Repro steps** 

- Create a .Net Core Console Application
- Create a .Net Framework Class Library ( add Newtonsoft.json package ) 
- Create a .Net Standard Class Library ( add Newtonsoft.json package )
- Add reference from Console to both Class Libraries 

**Expected**
Display nuget dependencies for both projects 

**Actual**
![image](https://cloud.githubusercontent.com/assets/12449387/20071351/06963ad6-a4d9-11e6-8c83-04de30878858.png)

**Enviornment Info**
build: d15rel/25904.2
cli: 1.0.0-preview3-004056

**Comment by abpiskunov** [comment]
Here FrameworkCL is a old csproj or also is a new managed core app, but targeting full TFM?

**Comment by abpiskunov** [comment]
From Jinu: "Added as new .NetFramework Class Library ( so this is old csproj) 
I am assuming this is expected but just wanted to track it as this might be confusing for users."

**Comment by abpiskunov** [comment]
In this case it is expected for now, since there no designtime build and packages hierarchy from assets file  for old csproj files. So this is a feature size change probably.

**Comment by srivatsn** [comment]
I don't think we'll fix this for old csproj. Rather spend our energies on moving those projects to the new project system sooner.
