### ISSUE TITLE
Project System: Add item build action defaults

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn-project-system#72]
_From @davkean on March 23, 2016 17:30_

Represents what happens when you add an item to a project, either by dragging it into the tree, including it, rename it or adding via Add Item dialog.

We need to set defaults, such as Build Action and Generator.

Make note that the WPF flavor has different and additional code to handle this above and beyond csproj.dll/msvbproj.dll.

_Copied from original issue: dotnet/roslyn#10011_

**Comment by mavasani** [comment]
@davkean I tried the scenarios you mention for a resource file and a bitmap file (add item, drag and drop) and we already seem to be adding the correct values in the project file, and it shows up fine in the properties window too.

```
  <ItemGroup>
    <EmbeddedResource Include="Resource1.resx">
      <Generator>ResXFileCodeGenerator</Generator>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <Content Include="Bitmap1.bmp" />
  </ItemGroup>
```

The only thing missing seems to be that don't invoke the Generator for the resx file, and hence have the following difference from csproj.dll generated project file: 

1. Missing Resource1.Designer.cs item entry 
2. Missing `<LastGenOutput>` metadata for resx file

```
  <ItemGroup>
    <Compile Include="Resource1.Designer.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>Resource1.resx</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <Content Include="Bitmap1.bmp" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resource1.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resource1.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
```

**Comment by mavasani** [comment]
![bitmap_properties](https://cloud.githubusercontent.com/assets/10605811/16464768/9d5c8272-3df0-11e6-8ab2-35ac84d59921.png)
![resxfile_properties](https://cloud.githubusercontent.com/assets/10605811/16464766/9d5b74fe-3df0-11e6-811e-5f3ddf2eff2e.png)

**Comment by mavasani** [comment]
As per the above comments and screenshots, this is done. Please open bugs if something is broken/unimplemented here.

**Comment by srivatsn** [comment]
It looks like build actions like AdditionalFiles don't work.

![image](https://cloud.githubusercontent.com/assets/20570/20152696/219aec9a-a674-11e6-992b-ea19a2cdadcb.png)

This is blocking dependency validation from working for netcore projects.

**Comment by mavasani** [comment]
Should be a simple fix to targets- will fix after lunch
