### ISSUE TITLE
Assembly references aren't removed from intellisense when deleted from the project

### ISSUE THREAD

**Issue by BillHiebert** [dotnet/roslyn-project-system#725]
VS build D15Rel 25907.1
- Create a new asp.net core web application on full framework. Choose the web application template and change the authentication to individual auth.
- Note project doesn't build.
- Add references to system.Data and System.ComponentModel.Data.Annotations
- Everything builds, intellisense is correct
- Remove (via the ui) the two assembly references
- Build. Get a bunch of failures as expected. Double click one of the files with errors. like models\accountviewmodels\forgotpasswordviewmodel.cs

Notice that intellisense shows the [Required] and [EmailAddress} as being valid when they shouldn't be since the types come from the assemblies removed.

Close and reopen project. The types are correctly shown in error

**Comment by mavasani** [comment]
I am unable to repro this on Dev15 RC build with latest ProjectSystem VSIX installed on top of it.
