### ISSUE TITLE
howto debug vbcscompiler.exe

### ISSUE THREAD

**Issue by BartNetJS** [dotnet/roslyn-project-system#737]
vbcscompiler.exe is consuming a lot of cpu on a specific solution at the moment the unittest projects are build.
It is not Always at the same unittest project

For that I like to debug the vbcscompiler

I can start the vbcscompiler project via vs2015, but when building my solution the vbcscompiler.exe from the C:\Program Files (x86)\MSBuild\14.0\Bin folder is started.

How can I debug vbcscompiler?

tx

**Comment by srivatsn** [comment]
vbcscompiler is built out of the https://github.com/dotnet/roslyn repo. Please move this issue to that repo.

**Comment by BartNetJS** [comment]
tx, see https://github.com/dotnet/roslyn/issues/15164
