### ISSUE TITLE
Line endings inconsistent when editing .csproj files

### ISSUE THREAD

**Issue by seancpeters** [dotnet/roslyn-project-system#742]
When editing a .csproj file via right clicking on the project and choosing edit, the displayed copy of the .csproj file has modified line endings inside of xml block comments. Specifically, CRLF are replaced with LF within the comments. Because of this, Visual Studio complains about the inconsistency and offers to fix it.

The change can be seen by opening the .csproj file in a different editor - one which will display line endings, I used Notepad++. There, the line endings will all be CRLF. 

From within VS, after opening the .csproj for editing, do a "save as" on it, saving it somewhere else. Open that copy in Notepad++ and you'll see the LF line endings.

**Comment by 333fred** [comment]
Fixed in https://github.com/Microsoft/msbuild/issues/1340.
