### ISSUE TITLE
The comment codes/whitespace in csproj file are missing after editing the csproj file and reopening it.

### ISSUE THREAD

**Issue by MiaomiaoHuangfu** [dotnet/roslyn-project-system#743]
Test the scenario on the build d15rel\25909.02;
Repro steps:
1>Edit csproj and change some codes to comment;
2>Save and close the csproj file;
3>Reopen the csproj and find the comment codes missing.
![edited_comment_codes_missing_after_reopen_the_csproj_file](https://cloud.githubusercontent.com/assets/22901391/20250804/d5741aac-aa4d-11e6-8346-5a29422884a0.png)

Expected result:
Reopen the edited csproj file and the comment codes still exist in the file;
Actual result:
Reopen the edited csproj file and find the comment codes missing.

**Comment by srivatsn** [comment]
@333fred - could be a msbuild issue similar to #742?

**Comment by 333fred** [comment]
I think it's probably related, but I'm not sure it's exactly the same.

**Comment by 333fred** [comment]
Adding whitespace to this bug as well, as they're the same issue. A CPS change is needed to fix this.

**Comment by 333fred** [comment]
For RC3, the comment part of this issue should be resolved. Whitespace is still being stripped, that will be fixed post-RC3.

**Comment by 333fred** [comment]
Fixed with #1266.
