### ISSUE TITLE
Edit .csproj is not re-using the already open document

### ISSUE THREAD

**Issue by jeremymeng** [dotnet/roslyn-project-system#746]
1. Create a C# Console App project
2. Right click the project node, select "Edit ConsoleApp1.csproj"
3. Again, right click the project node, select "Edit ConsoleApp1.csproj"

**Expected:**
One single tab in editor.  The second invocation should open the existing tab

**Actual:**
two tabs opened, both for ConsoleApp1.csproj

**Comment by srivatsn** [comment]
Fixed by #835
