### ISSUE TITLE
LaunchSettingsProvider imports ISourceCodeControlIntegration components as a singleton

### ISSUE THREAD

**Issue by lifengl** [dotnet/roslyn-project-system#748]
The ISourceCodeControlIntegration was marked as an interface can be implemented by 3rd parties, so the code must use ImportMany.  Otherwise, it might cause MEF composition error, when another component implements the interface, and blocks the entire project system to load.

It has attribute like:
[ProjectSystemContract(ProjectSystemContractScope.ProjectService, ProjectSystemContractProvider.Extension)]

It is important to use ImportMany for all Extension MEF components.  CPS has a unit test to use Reflection to check that, maybe Roslyn can do something similar, (or even better, if it can create a validator.)

**Comment by BillHiebert** [comment]
Closed with: https://github.com/dotnet/roslyn-project-system/pull/910
