### ISSUE TITLE
Auto-restore not kicked in after replacing TargetFramework with TargetFrameworks

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn-project-system#750]
**Repro Steps**

- Create a console (net core ) application 
- Make sure restore completes and build 
- Right click and edit the project to the below
```
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" />
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RuntimeIdentifier>win7-x86</RuntimeIdentifier>
    <TargetFrameworks>netcoreapp1.0;net461</TargetFrameworks>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="**\*.cs" />
    <EmbeddedResource Include="**\*.resx" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NETCore.App" Condition="'$(TargetFramework)' == 'netcoreapp1.0'">
      <Version>1.0.1</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.NET.Sdk">
      <Version>1.0.0-alpha-20161104-2</Version>
      <PrivateAssets>All</PrivateAssets>
    </PackageReference>
  </ItemGroup>
  <Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />
</Project>
```
**Expected** 

Auto restore is kicked in and it builds successfully 

**Actual**
Restore is not kicked in and build fails with missing assembly reference

**WorkAround**
Go to the project directory 
run "dotnet restore "
run "dotnet build"
now come back and build from IDE and it will build fine.

**Comment by jinujoseph** [comment]
2017-RC 
d15rel/15.0.25913.0

**Comment by natidea** [comment]
This is a known issue. The problem is that this scenario changes from using `TargetFramework` to `TargetFrameworks` and this results in `TargetFramework` returning an empty string. If you open an unrestored project with `TargetFrameworks`, auto restore should work correctly. I'll change the title accordingly.
