### ISSUE TITLE
Targets and props files should be associated with xml schema

### ISSUE THREAD

**Issue by srivatsn** [dotnet/roslyn-project-system#759]
We've associated csproj with the msbuild schema in VS so that xmlns is not needed for project files. We should do the same for targets and props as well.

**Comment by davkean** [comment]
We should do ".props, .targets, .proj, and .msbuildproj"

**Comment by RaulPerez1** [comment]
Schema that controls this is on the VS side, opening a bug for this there

**Comment by srivatsn** [comment]
This is done.
