### ISSUE TITLE
"Edit project" command has different icon when the project is loaded vs unloaded

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn-project-system#761]
Loaded:

![image](https://cloud.githubusercontent.com/assets/1103906/20375969/e7197762-acd6-11e6-8994-9d7dcbdcc6d7.png)

Unloaded:

![image](https://cloud.githubusercontent.com/assets/1103906/20376020/4e44d4f4-acd7-11e6-8e64-fe811ef6e0e1.png)

Are we using the same command?

**Comment by 333fred** [comment]
No, we are not.

**Comment by davkean** [comment]
Why didn't we use the same command?

**Comment by 333fred** [comment]
By default, the unloaded edit csproj command doesn't exist on the project node.

**Comment by davkean** [comment]
We can change the context menu to change that.

**Comment by 333fred** [comment]
Fixed via 0062e1.
