### ISSUE TITLE
Changing the target framework for an ASP.NET Core app on .NET Framework causes builds to fail

### ISSUE THREAD

**Issue by davidfowl** [dotnet/roslyn-project-system#764]
Repro
- Make a new ASP.NET Core project (.NET Framework)
- Build it (it'll be targeting .NET Framework 4.5.2)
- Change the target framework in the properties to .NET Framework 4.6
- Build again

Expected
- It builds

Actual
![image](https://cloud.githubusercontent.com/assets/95136/20396539/658e33a8-ac9b-11e6-9862-cca4efdb0307.png)

**Comment by natidea** [comment]
Doing a quick investigation, it looks like this is happening because the Properties Page is not updating `TargetFramework`, resulting in the following properties:
```XML
    <TargetFramework>net452</TargetFramework>
    <TargetFrameworkIdentifier>.NETFramework</TargetFrameworkIdentifier>
    <TargetFrameworkVersion>v4.6</TargetFrameworkVersion>
```
Changing `TargetFramework` to net46 fixes the build

**Comment by srivatsn** [comment]
@jinujoseph is working on making the TF dropdown set the property correctly.

**Comment by srivatsn** [comment]
This should be fixed now?

**Comment by jinujoseph** [comment]
yes.
