### ISSUE TITLE
Localize Xaml rules and move them to locale specific folders

### ISSUE THREAD

**Issue by srivatsn** [dotnet/roslyn-project-system#776]
The XAML rules that we have today [here](https://github.com/dotnet/roslyn-project-system/tree/master/src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules) need to be localized as well. The rules need to go into local-specific folders like the ones in C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin

**Comment by nguerrera** [comment]
Have there been significant changes since the last time they were loc'ed?

**Comment by srivatsn** [comment]
We've added a significant number of strings to one or two of these files. For many of them though they are the same.
