### ISSUE TITLE
ASP.NET Core Web Application (.NET Framework) fails to build

### ISSUE THREAD

**Issue by twsouthwick** [dotnet/roslyn-project-system#778]
If you use the template "ASP.NET Core Web Application (.NET Framework)" to create a new, empty project, it fails to build. The errors are:

|Severity	| Description| Project	|File	|Line	|
|--|--|--|--|--|
|Error		|The OutputPath property is not set for project 'WebApplication2.csproj'.  Please check to make sure that you have specified a valid combination of Configuration and Platform for this project.  Configuration='Debug'  Platform='AnyCPU'.  This error may also appear if some other project is trying to follow a project-to-project reference to this project, this project has been unloaded or is not included in the solution, and the referencing project does not build using the same or an equivalent Configuration or Platform.	|WebApplication2	|C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets|	733	|
|Warning		|Your project is not referencing the ".NETFramework,Version=v4.0" framework. Add a reference to ".NETFramework,Version=v4.0" in the "frameworks" section of your project.json, and then re-run NuGet restore.	|WebApplication2	|C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\NuGet\15.0\Microsoft.NuGet.targets	|162	|
|Warning		|Your project is not referencing the ".NETFramework,Version=v4.0" framework. Add a reference to ".NETFramework,Version=v4.0" in the "frameworks" section of your project.json, and then re-run NuGet restore.	|WebApplication2	|C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\NuGet\15.0\Microsoft.NuGet.targets	|162	|
|Warning		|Your project is not referencing the ".NETFramework,Version=v4.0" framework. Add a reference to ".NETFramework,Version=v4.0" in the "frameworks" section of your project.json, and then re-run NuGet restore.	|WebApplication2	|C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\NuGet\15.0\Microsoft.NuGet.targets	|162	|
|Error		| <div>Value cannot be null. <BR>Parameter name: source<br>   at System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector)<br>   at Microsoft.NuGet.Build.Tasks.ResolveNuGetPackageAssets.GetReferencedPackages(JObject lockFile)<br>   at Microsoft.NuGet.Build.Tasks.ResolveNuGetPackageAssets.ExecuteCore()<br>   at Microsoft.NuGet.Build.Tasks.ResolveNuGetPackageAssets.Execute() </div> |	WebApplication2|	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\NuGet\15.0\Microsoft.NuGet.targets	 | 162	|
|Warning		|Your project is not referencing the ".NETFramework,Version=v4.0" framework. Add a reference to ".NETFramework,Version=v4.0" in the "frameworks" section of your project.json, and then re-run NuGet restore.|	WebApplication2	|C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\NuGet\15.0\Microsoft.NuGet.targets	|216	|
|Warning	|	Your project is not referencing the ".NETFramework,Version=v4.0" framework. Add a reference to ".NETFramework,Version=v4.0" in the "frameworks" section of your project.json, and then re-run NuGet restore.	|WebApplication2|	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\NuGet\15.0\Microsoft.NuGet.targets|	216	
|Warning	|	Your project is not referencing the ".NETFramework,Version=v4.0" framework. Add a reference to ".NETFramework,Version=v4.0" in the "frameworks" section of your project.json, and then re-run NuGet restore.	|WebApplication2|	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\NuGet\15.0\Microsoft.NuGet.targets	|216	|
|Error	|	Value cannot be null. Parameter name: source   at System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector)   at Microsoft.NuGet.Build.Tasks.ResolveNuGetPackageAssets.GetReferencedPackages(JObject lockFile)   at Microsoft.NuGet.Build.Tasks.ResolveNuGetPackageAssets.ExecuteCore()   at Microsoft.NuGet.Build.Tasks.ResolveNuGetPackageAssets.Execute()|	WebApplication2|C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\NuGet\15.0\Microsoft.NuGet.targets	 | 216	

Here is the default csproj:

```xml
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" />
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net452</TargetFramework>
    <PreserveCompilationContext>true</PreserveCompilationContext>
    <RuntimeIdentifier>win7-x86</RuntimeIdentifier>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="**\*.cs" Exclude="$(GlobalExclude)" />
    <EmbeddedResource Include="**\*.resx" Exclude="$(GlobalExclude)" />
    <Folder Include="wwwroot\" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Sdk.Web">
      <Version>1.0.0-alpha-20161104-2-112</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics">
      <Version>1.0.0</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.AspNetCore.Server.IISIntegration">
      <Version>1.0.0</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.AspNetCore.Server.Kestrel">
      <Version>1.0.1</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Logging.Console">
      <Version>1.0.0</Version>
    </PackageReference>
  </ItemGroup>
  <Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />
</Project>
```

**Comment by srivatsn** [comment]
This is the error you get when restore fails. Can you check your output window to see if restore failed?

**Comment by twsouthwick** [comment]
Restore appears to succeed. There isn't a "Package Manager" output window like in the past, but I see the text `All packages are already installed and there is nothing to restore.`  when I tell the solution to restore packages.

**Comment by srivatsn** [comment]
With the latest RC there is no pre-restore state any more for the SDK. so this should be fixed.
