### ISSUE TITLE
Intellisense not working up after adding a package after a TFM change

### ISSUE THREAD

**Issue by davidfowl** [dotnet/roslyn-project-system#784]
- Make a new netstandard class library
- Change the TFM from netstandard1.4 to netstandar1.6
- Add JSON.NET 
    ````xml
    <PackageReference Include="Newtonsoft.Json">
      <Version>9.0.1</Version>
    </PackageReference>
    ````
- Add this code to a constructor in Class1.cs:
    ```C#
    using System;

        namespace ClassLibrary9
        {
            public class Class1
            {
                public Class1()
                {
                    Newtonsoft.Json.JsonConvert.SerializeObject(null);
                }
            }
        }
    ```

## Expected

Intellisense is happy

## Actual

Intellisense is not happy

![image](https://cloud.githubusercontent.com/assets/95136/20475074/a783ef60-af7e-11e6-89c4-07bb6619b73b.png)

**Comment by davkean** [comment]
Here's my repro that doesn't work:

1. File -> New Class Library ( .NET Standard)
2. Right-click project and choose Edit ClassLibrary.csproj
3. Change .netstandard1.4 -> .netstandard1.6
4. Save
5. Quickly after that, add:

``` XML
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json">
      <Version>9.0.1</Version>
    </PackageReference>
  </ItemGroup>
```

6. Save

![image](https://cloud.githubusercontent.com/assets/1103906/21926222/e84780fe-d9d4-11e6-997c-6155d9be96ab.png)


Note that the assets file that NuGet generated looks correct.

**Comment by davkean** [comment]
This looks similar to: https://github.com/dotnet/roslyn-project-system/issues/1159

**Comment by srivatsn** [comment]
I assume this is the same as https://github.com/dotnet/roslyn-project-system/issues/1445

**Comment by mavasani** [comment]
No repro on 26205.0.d15rel. I tried both the repros above and the NuGet package reference is correctly resolved and intellisense works fine.
