### ISSUE TITLE
No IntelliSense for a COM reference assembly

### ISSUE THREAD

**Issue by pzgulyas** [dotnet/roslyn-project-system#786]
There is no intellisense for a COM assembly in VS 2017 .NET Core based project, but interestingly despite of that, it compiles and runs correctly. Also, adding a COM reference using VS 2017 UI adds a wrong line `<COMReference Include="pfcls.dll">` into the following (corrected) block in csproj:
```xml
  <ItemGroup>
    <COMReference Include="pfcls">
      <Guid>{176453F2-6934-4304-8C9D-126D98C1700E}</Guid>
      <VersionMajor>1</VersionMajor>
      <VersionMinor>0</VersionMinor>
      <Lcid>0</Lcid>
      <WrapperTool>tlbimp</WrapperTool>
      <Isolated>False</Isolated>
      <EmbedInteropTypes>True</EmbedInteropTypes>
    </COMReference>
  </ItemGroup>
```
The final dll name becomes `Interop.pfcls.dll` after build, so the added name is wrong anyway.

(Just for info: The example above shows a PTC Creo-Pro/Engineer CAD software VB.API interop reference)

**Comment by pzgulyas** [comment]
A workaround is to add the generated `Interop.pfcls.dll` from the bin folder as an assembly reference beside the COM reference in csproj. Although VS drops two additional warnings (MSB3061 Unable to delete file, and MSB3245 Could not resolve this reference) at build time, the project eventually builds, and there is also intellisense available.

**Comment by davkean** [comment]
I can reproduce this.

**Comment by davkean** [comment]
@srivatsn Walked through this - design-time build looks fine, and we're passing the reference onto Roslyn. This is beyond my expertise, can @mavasani have a look?

**Comment by davkean** [comment]
Here's one that is registered on all VS boxes:
```
    <COMReference Include="Accessibility">
      <Guid>{1EA4DBF0-3C3B-11CF-810C-00AA00389B71}</Guid>
      <VersionMajor>1</VersionMajor>
      <VersionMinor>1</VersionMinor>
      <Lcid>0</Lcid>
      <WrapperTool>tlbimp</WrapperTool>
      <Isolated>False</Isolated>
      <EmbedInteropTypes>True</EmbedInteropTypes>
    </COMReference>
``

**Comment by davkean** [comment]
Another thing, if I double-click it, Object Browser doesn't see it *unless* I've already opened it using via  legacy project system, no idea if this related or another bug.

**Comment by mavasani** [comment]
The issue here is that COM references get passed as link references with _relative_ path to the command line parser, unlike the other assembly references which are passed down as full path. Subsequently, our Language service attempts to add these as MetadataReferences with a relative path, which ends up resolving to incorrect full path. Fix is to make sure that we invoke `UnconfiguredProject.MakeRooted` in MetadataReferenceFilesLanguageServiceItemHandler. I'll prepare a PR to fix this.
