### ISSUE TITLE
Edited csproj in vs cannot be saved or closed.

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn-project-system#787]
Edit csproj to add a package and then close the file (or alt-f4). The prompt to save shows the right file name shown 

![image](https://cloud.githubusercontent.com/assets/12449387/20493065/399514fe-afcc-11e6-8486-18bdab64ace9.png)

Click yes and prompt a window to save the file in temp location.
3.Click the save but prompt a warning and say the default saved location does not exist shown below:
![image](https://cloud.githubusercontent.com/assets/12449387/20493205/b8e41764-afcc-11e6-98b9-82f5ad5451ee.png)

**Expected result:** 
The edited .csproj file in vs can be saved with the right name in an exist location. build the solution succeeded.

**Actual result:**
The edited .csproj file in vs cannot be saved; the csproj file cannot be closed as well if the file is edited.  Building the solution has no respond.

**Comment by jinujoseph** [comment]
Build:d15prerel/25919.1

**Comment by 333fred** [comment]
The issue here is that I'm listening to `IVsWindowFrameNotify2.OnClose` to clean up the project file, which apparently gets fired before the Unsaved Dialog is shown. Looking into events we can listen to for later cleanup.

**Comment by srivatsn** [comment]
Fixed by #835
