### ISSUE TITLE
Show dependency graph through project references

### ISSUE THREAD

**Issue by davidfowl** [dotnet/roslyn-project-system#791]
Unlike the xproj tooling, the new csproj tooling don't show the full dependency graph through the solution explorer. This makes it hard to determine what dependencies come from which projects by looking at a single project:

![image](https://cloud.githubusercontent.com/assets/95136/20513502/153447a0-b03b-11e6-908e-7972cb50deab.png)

This is super valuable when debugging to see where things are coming from without looking in the assets file.

**Comment by davidfowl** [comment]
Also, this information is available in the assets file.

**Comment by davkean** [comment]
Haven't got the latest build to check this - but I'm pretty confident we had already done, or were going to do this. @abpiskunov?

**Comment by srivatsn** [comment]
Do you have a specific repro @davidfowl. This is what I see when I add a library as a p2p ref to a console app:
![image](https://cloud.githubusercontent.com/assets/20570/20534854/9b644c10-b097-11e6-844f-d8a6ce283e49.png)

**Comment by davidfowl** [comment]
Hmm, let me check again.

**Comment by davidfowl** [comment]
We can close this. It doesn't work for packages.config but that's by design. Was testing new proj -> old csproj + packages.config
