### ISSUE TITLE
A project containing no imports shouldn't fail to load unintelligibly in VS

### ISSUE THREAD

**Issue by srivatsn** [dotnet/roslyn-project-system#793]
If a project has no imports, then the XAML rules needed by the project are not brought in and we fail to load the project and show an error about a missing the "BrowseObject" catalog. This may require a CPS fix? We should either just load successfully (like the old project system) or fail with a more intelligible error about missing critical targets or something. Since csproj is editable now, it's more likely for someone to get into this state.

**Comment by srivatsn** [comment]
Tagging @jviau and @lifengl. Per #1012 we now crash VS in this case. Can we pursue some fix for this for RTM?

**Comment by jviau** [comment]
@srivatsn this is a CPS issue. We won't be able to load the project, as without the XAML rules CPS has no idea how to interpret the project file. The best we could do is a descriptive error. Maybe we can load the .csproj file but have an empty tree with a message saying that no xaml rules were loaded.

I opened a bug in our database to track this.

**Comment by srivatsn** [comment]
Thanks i'll keep this issue open as a tracking item.

**Comment by jviau** [comment]
@srivatsn is there an issue tracking the 2nd point @adrianvmsft pointed out? `ProjectLockFileWatcher.GetProjectLockFilePathAsync` crashes VS if `BaseIntermediateOutputPath` is not defined in the project or set to an empty string. For example, shared projects do not have that property set, so trying to load one right now crashes VS due to this.

**Comment by adrianvmsft** [comment]
I think that was #1012 but got duped against this one. So I guess we could either reactivate it or have this bug (but in that case we should remove the Tracking tag).

**Comment by adrianvmsft** [comment]
@srivatsn @davkean Just a reminder that the crash reported above (Issue 2) needs to be fixed on the roslyn project system side (the CPS side of the fixes are in, but they won't prevent the crash)

**Comment by davkean** [comment]
@adrianvmsft Tracking via: https://github.com/dotnet/roslyn-project-system/issues/1129
