### ISSUE TITLE
csproj File Automatically Reformatted

### ISSUE THREAD

**Issue by wjk** [dotnet/roslyn-project-system#805]
I have just added an MSBuild-based .NET Core project to a brand-new solution in VS 2017 RC. When I right-click the project and select Edit, the solution file is automatically reformatted to match Visual Studio's (old) standards for MSBuild project formatting. Namely:

* Blank lines between tags are removed.
* The newline at the end of the file is removed.
* The UTF-8 BOM is removed.

This causes pointless commit churn when I move between IDEs. In addition, I am not very pleased about the removal of the blank lines between tags. Could this behavior be changed? Thanks!

**Comment by davkean** [comment]
Thanks - all this is known, except the BOM. I'll make sure we check the BOM when we fix this: https://github.com/dotnet/roslyn-project-system/issues/512.

Keep these bugs coming!

**Comment by wjk** [comment]
@davkean I'm afraid this behavior is still occurring, albeit in slightly different circumstances than before. As far as I can tell, Visual Studio no longer reformats my csproj files when I edit them by hand. However, Visual Studio (2017 RC 3, build 26127.0) still reformats my csproj files (in the same way as described above) when it makes changes to it by itself.

For example, when I add an empty folder to a project, Visual Studio adds a `<Folder>` item to my project, as well as an `<ItemGroup>` to contain it. However, when I then add a source file into that folder (obviating the need for the explicit `Folder` item), Visual Studio removes the tag as it should -- but it also removes all newlines (between tags as well as the one at the end of the file), as well as all comments, if any are present. (I neglected to mention the comment issue in my initial post above, but it does occur.)

Could this issue please be reopened until this is fixed as well? Thanks!

**Comment by davkean** [comment]
@wjk I cannot repro this with the new project system, can you open a new bug with the exact repro?

We've still got some weird issues while editing with the editor, such as https://github.com/dotnet/roslyn-project-system/issues/1348 and https://github.com/dotnet/roslyn-project-system/issues/1347 and wondering if your issue is related. 

Can you repro it without the editor?

**Comment by wjk** [comment]
As far as I can tell, the issue only occurs when Visual Studio edits the csproj file. If I edit the csproj XML using Notepad, Visual Studio will leave it the formatting as I specified it. Is this what you were talking about? In addition, the symptom mentioned above regarding the csproj being reformatted when I open it in the editor still occurs as well. I can workaround these issues using the Command Prompt and Notepad, but it is fairly inconvenient.

It might take me a little while to provide a repro. I have not yet determined if this issue affects all Core csproj files, or is caused by a quirk specific to my project. Thanks!

**Comment by 333fred** [comment]
@davkean, I can reproduce. Opened an issue on msbuild: https://github.com/Microsoft/msbuild/issues/1627.
