### ISSUE TITLE
Add "Edit project" command to Project menu

### ISSUE THREAD

**Issue by wjk** [dotnet/roslyn-project-system#806]
Currently (in VS 2017 RC), the Edit Project command is only available in a project's right-click menu. Could this possibly be added to the Project menu in the menu bar as well? This will make it easier for me to access this command using only the keyboard. Thanks!

**Comment by davkean** [comment]
Yep, definitely. 

@333fred I think we should reuse the existing edit project command, and add it to both Project and Project context menus. The vsct is located /src/appid/inc/SharedCmdPlace.vsct in the VS tree, see my commit 655368c7 for an example.

**Comment by 333fred** [comment]
This was fixed in #1065.
