### ISSUE TITLE
C# template icons look bad under new MRU templates

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn-project-system#807]
![image](https://cloud.githubusercontent.com/assets/1103906/20610836/bd73bd6e-b2f3-11e6-903f-c78fd612cf29.png)

**Comment by davkean** [comment]
Interestingly enough, they look fine under small icons in the new project dialog:

![image](https://cloud.githubusercontent.com/assets/1103906/20612340/fc46b3c0-b30c-11e6-967e-c341d4536fb1.png)

**Comment by davkean** [comment]
Weirdly this is what the Console app template looks now under my MRU, looks like there's some sort of bug in the MRU caching/display:

![image](https://cloud.githubusercontent.com/assets/1103906/20652216/194b8a3e-b549-11e6-966d-be94842d51ef.png)

**Comment by davkean** [comment]
It gets worse: 

![image](https://cloud.githubusercontent.com/assets/1103906/20871050/39a9fcf6-bae5-11e6-86a9-ce74b6418821.png)

This is a clean machine with zero project types/templates installed, and these have roamed from another high DPI machine.

**Comment by prasethu** [comment]
@davkean This needs to be filed in the VS IDE bug database.

I think the issue is when the icon is roamed from a high DPI to a non high DPI machine. Would that be accurate?

**Comment by davkean** [comment]
Closed in lieu of an internal bug.
