### ISSUE TITLE
You can no longer edit an unloaded project

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn-project-system#808]
Build: 15.0.25918.0 D14PREREL

1. Create a new C# Console App (.NET Framework)
2. Unload project
3. Right-click and choose Edit

Expected: For the text editor to open 
Actual: Nothing

**Comment by davkean** [comment]
@333fred Did we regress this? Is our handler taking over this, or has something else regressed this?

**Comment by 333fred** [comment]
It shouldn't be. Our handler should only be triggering for CPS projects that are either C# or VB.

**Comment by davkean** [comment]
Opened an internal bug: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/295877
