### ISSUE TITLE
Unable to reference .NET Standard project from an UWP project

### ISSUE THREAD

**Issue by psoszynski** [dotnet/roslyn-project-system#818]
1. Visual Studio 2017RC (fresh install)

2. New Project -> Universal Windows ('App1').
    References: a) Microsoft.NETCore.UniversalWindowsPlatform, b) Universal Windows

3. Add Project -> .NET Core -> Class Library (.NET Standard) ('Class Library1').
    References: a) Microsoft.NET.Sdk (1.0.0-alpha-20161104-2, b) NETStandard.Library (1.6.0)

4. Trying to add a project reference from 'App1' to 'Class Library1'.
    Error: "Unable to add a reference to project 'Class Library1'"

Any ideas?

**Comment by davkean** [comment]
Thanks, this is a known issue. As a workaround, you should be able to reference the binary directly.

**Comment by srivatsn** [comment]
This is now fixed in the latest update to the RC.
