### ISSUE TITLE
Project System: Can rename/manipulate items outside of the project

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn-project-system#82]
_From @davkean on March 22, 2016 23:42_

You should be able to manipulate folders and files, by moving, renaming and deleting that are outside of the project, similar to csproj/msvbproj.

_Copied from original issue: dotnet/roslyn#9991_

**Comment by NoneGiven** [comment]
Dupe of https://github.com/dotnet/roslyn-project-system/issues/63 .

**Comment by davkean** [comment]
Thanks!
