### ISSUE TITLE
.NET Core xUnit tests have no SourceInformation

### ISSUE THREAD

**Issue by gulbanana** [dotnet/roslyn-project-system#826]
When using xUnit in VS2017, the relationship between unit tests and their source code is not discovered. This means that the Test Explorer toolwindow categorises them as "external", and features like rightclick -> run test and Live Unit Testing do not work. 

To reproduce: File -> New Project -> "xUnit Test Project (.NET Core)" or check out https://github.com/gulbanana/repro-netcore-diasym. Then, build the solution and observe the consequences in Test Explorer.

**Comment by gulbanana** [comment]
Potentially related fix for an older issue (this one was about discovering sourceinformation for referenced libraries in an older tooling version): https://github.com/xunit/xunit/pull/924

**Comment by srivatsn** [comment]
@codito - can you please comment on this?

**Comment by gulbanana** [comment]
I am still experiencing this problem in RC Refresh.

**Comment by codito** [comment]
@gulbanana created https://github.com/xunit/xunit/issues/1054 to track this.

**Comment by onovotny** [comment]
@srivatsn we have a fix but uncovered an issue with the TestPlatform ObjectModel lib: https://github.com/xunit/xunit/pull/1055#issuecomment-268281826. The PortableSymbolReader isn't getting data for async state machine stuff. Affects both MSTest and xUnit (and anything else that wants the data). Not sure who owns that but I'd think it should be an RC3 blocker.

**Comment by srivatsn** [comment]
Thanks Oren. @dotnet/vstest owns this code. I'll track this for RC3.

**Comment by pvlakshm** [comment]
This issue is fixed with https://github.com/dotnet/sdk/commit/e4eb65dee3fa7b4a5bf21a9b73f74171511b89f6. You can try the fix by updating Test.SDK version in csproj as shown below.

`<PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.0.0-preview-20170106-08" />`

**Comment by onovotny** [comment]
@pvlakshm before the templates are cut for RC3, can the xunit runner version be updated to the compatible version, 2.2.0-beta4-build1216, or later?

/cc @bradwilson

**Comment by bradwilson** [comment]
I'm going to run beta5 builds (these should've been renamed long ago), so give me ~ 20 minutes to get you a beta5 build# for both `xunit` and `xunit.runner.visualstudio`.

**Comment by bradwilson** [comment]
I haven't provided build #s yet, because the current Visual Studio runner package is broken. Still working on a fix.

**Comment by bradwilson** [comment]
Please use:
- `xunit` version `2.2.0-beta5-build3474`
- `xunit.runner.visualstudio` version `2.2.0-beta5-build1225`

Thanks!

**Comment by srivatsn** [comment]
Tagging @dotnet/vstest.

Can someone send a PR to update the templates here - https://github.com/dotnet/sdk/tree/master/src/Templates/ProjectTemplates/CSharp/.NETCore/CSharpXUnitTest

**Comment by bradwilson** [comment]
I'll do it.

**Comment by bradwilson** [comment]
https://github.com/dotnet/sdk/pull/615

**Comment by davkean** [comment]
This issue was moved to Microsoft/vstest#361
