### ISSUE TITLE
New project system does not discover net461 tests

### ISSUE THREAD

**Issue by gulbanana** [dotnet/roslyn-project-system#827]
Steps to reproduce:
1) Create a new "xUnit test project"
2) Change it to target net461, adding a RID and removing the netcore.app package
Or, check out https://github.com/gulbanana/repro-netcore-netfxtest

Build; observe that no tests are discovered. This may be due to an SDK issue - I see warnings about the testhost architecture - but `dotnet test` isn't working yet so I can't check.

**Comment by srivatsn** [comment]
@codito - can you comment on this?

**Comment by gulbanana** [comment]
In RC Refresh, this problem no longer applies when RID `win7-x86` is used, but still occurs for RID `win7-x64`.

**Comment by codito** [comment]
@gulbanana for test projects targeting desktop framework, the `OutputType` property need not be set (i.e. Library by default). If the `OutputType` is library, a RID is not required.

A test project that multitargets to desktop and netcore could define the `OutputType` under a conditional. E.g. `<OutputType Condition=" '$(TargetFramework)' == 'netcoreapp1.0' ">Exe</OutputType>`

**Comment by gulbanana** [comment]
In that case the only remaining work will be the document this or add templates/gui settings for it (since i don't think anyone is going to guess that solution :)).

**Comment by codito** [comment]
Agree, we should document this or possibly get rid of this requirement.

**Comment by codito** [comment]
Update: we will fix the Microsoft.NET.Test.Sdk package to take care of conditional OutputType.

Thanks @gulbanana for reporting this. Please keep the feedback coming :)

**Comment by gulbanana** [comment]
no problem, thanks for looking into it

**Comment by codito** [comment]
As of https://github.com/dotnet/sdk/commit/e4eb65dee3fa7b4a5bf21a9b73f74171511b89f6, `Microsoft.Net.Test.Sdk` can handle `OutputType` mismatch between net4x and netcoreapp targets. `OutputType` tag need not be specified in the test project.

This fix should be available in next VS update.

**Comment by gulbanana** [comment]
cool, i'll try it out when available

**Comment by davkean** [comment]
This issue was moved to Microsoft/vstest#362
