### ISSUE TITLE
What files are included in .NET Core projects?

### ISSUE THREAD

**Issue by djanosik** [dotnet/roslyn-project-system#828]
I have a new `.csproj` ASP.NET Core project. I am trying to figure out what files are included in the project and how. The following items are defined in my `.csproj`:

```xml
<Compile Include="**\*.cs" />
<EmbeddedResource Include="**\*.resx" />
<Content Include="appsettings.json">
  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
</Content>
```

This is the result:

- all `**\*.cs` files are included ✓
- all `**\*.resx` files are included ✓
- `appsettings.json` is included ✓
- `compilersettings.json` is included, but not defined in project file
- `wwwroot\**\*` is included, but not defined in project file
- `web.config` is included, but not defined in project file
- `.bowerrc` is included, but it does not even exist
- all `Styles\**\*.less` files are included, but `Styles\**\*.otf` are not

It's a bit strange and inconsistent. Are some well-known files included by default? Who decides what files are well-know and what files are not?

**Comment by davidfowl** [comment]
The ASP.NET globs are a bit of a mess. Can you move this issue to https://github.com/aspnet/Tooling/issues

**Comment by djanosik** [comment]
Yeap, moved to https://github.com/aspnet/Tooling/issues/884.
