### ISSUE TITLE
Sometimes create new project doesn't ever complete from the UI

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn-project-system#829]
**Repro steps** 

- Create a new console application.

**Expected**
project created 

**Actual** 
It keep showing this UI 
![image](https://cloud.githubusercontent.com/assets/12449387/20679853/6e702fee-b551-11e6-9c8a-982027f2b659.png)

Note: The files are created. Kill the instance and open the .csproj and it loads fine.

**Build**
d15prerel/15.0.25927.3

This is flaky and doesn't repro all the time.

**Comment by mavasani** [comment]
Can you take a dump next time this happens for you?

**Comment by jinujoseph** [comment]
\\mlangfs1\public\Jinuj\dmp\projectCreate.dmp

**Comment by davkean** [comment]
I can't get any stacks out of the dump for some reason, but this looks like a dup of https://github.com/dotnet/roslyn-project-system/issues/777, which is be fixed by a NuGet insertion today.

**Comment by davkean** [comment]
@jinujoseph Can you verify if you can run into this in today's build? I'm pretty confident this is the NuGet bug.

**Comment by jinujoseph** [comment]
yes , i verified this on d15prerel/15.0.25929.0
