### ISSUE TITLE
Can't disable AppDesigner for the project by removing the capability

### ISSUE THREAD

**Issue by adrianvmsft** [dotnet/roslyn-project-system#833]
Create new .Net Core project
Edit the project file and include the following at the end of the project (after Import Microsoft.CSharp.targets):
```xml
  <ItemGroup>
    <ProjectCapability Remove="AppDesigner" />
  </ItemGroup>
```
Reload the project
In solution explorer, select the project node, right click properties
Expected: the CPS properties designer to be displayed
Actual: App designer still gets displayed

Note: Other capabilities seem to be fine. For example, if you use 
```xml
<ProjectCapability Remove="OpenProjectFile" />
```
The Edit project menu item will be properly removed.

**Comment by davkean** [comment]
Pulling this back in - it's the same fix as Shared Projects fix.
