### ISSUE TITLE
CPS needs to support returning IVsDesignTimeAssemblyResolution from IVsProject.GetItemContext

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn-project-system#843]
Currently CPS implements IVsDesignTimeAssemblyResolution on the hierarchy node. However, most code that uses IVsDesignTimeAssemblyResolution, uses it via IVsProject.GetItemContext both with ROOT and specific items.

We need to add support for this.

**Comment by srivatsn** [comment]
Fixed
