### ISSUE TITLE
Framework assemblies from NuGet packages aren't being found via IVsDesignTimeAssemblyResolution.ResolveAssemblyPathInTargetFx 

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn-project-system#844]
Framework assemblies from NuGet packages aren't being found via IVsDesignTimeAssemblyResolution.ResolveAssemblyPathInTargetFx.

This method basically directly calls ResolveAssemblyReference outside of a build with evaluated properties from an MSBuild instance, thereby skipping NuGet build target that raises NuGet packages as References.

**Comment by davkean** [comment]
My mistake, it does do a design-time build by calling GetFrameworkPaths to populate ResolveAssemblyReference, however it's cached for the lifetime of a project.

**Comment by davkean** [comment]
Wondering aloud if we just provide our own instance of IVsDesignTimeAssemblyResolution that just remembers results from the last design-time build. It might be calling ResolveAssemblyReference so that it gets framework unification, what if we just simplified it and did it ourselves?

**Comment by davkean** [comment]
Looking through the old project system - this is effectively what it does, it remembers the results from the last Rebuild, Build, Compile or ResolveReferences and then uses those results.

**Comment by srivatsn** [comment]
This is now done.
