### ISSUE TITLE
P2P Reference fails to build 

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn-project-system#848]
**Repro Steps**

- Create a Core Console Applciation 
- Create a Core ClassLibrary 
- Reference ClassLibrary from Console.
- Restore will fail saying the CL is not compatible with .14 
- Edit the Class Library project and set to .NetStandard 1.5 or 
- Build 

**Expected** 
It builds fine

**Actual**
![image](https://cloud.githubusercontent.com/assets/12449387/20768869/728c275a-b6f4-11e6-82b1-3d6dd3f74d79.png)

Rebuilding sometimes gives me this  
![image](https://cloud.githubusercontent.com/assets/12449387/20768932/ab40d9f6-b6f4-11e6-858b-4bc4c4e02ec6.png)

**Comment by jinujoseph** [comment]
This is on d15prerel/25929.3

**Comment by jinujoseph** [comment]
If you got this to build successfully, close the solution and reopen and try again

**Comment by srivatsn** [comment]
Looks like that warning is issued by the SDK?

**Comment by nguerrera** [comment]
This did not repro in d15rel/15.0.26005.1. This could have happened if the assets were incorrect at some point due to another bug.

**Comment by jinujoseph** [comment]
I retried this and not seeing the repro on d15rel/15.0.26005.1
