### ISSUE TITLE
F5 does not work for a newly create netcore console app

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn-project-system#851]
1. Enlist into SDK repo and build latest sources
2. Install the built C# and VB templates VSIX
3. Create a C#/VB netcore console app, say "TestProj"
4. F5

**Expected:** Application launches

**Got:**

```
---------------------------
Microsoft Visual Studio
---------------------------
Unable to start program 'TestProj.exe'.

The system cannot find the file specified.

---------------------------
OK   
---------------------------
```

If I close and re-open the solution and then attempt to F5, it works fine.

**Comment by mavasani** [comment]
@srivatsn Do you know if this broke recently? I thought this used to work fine...

**Comment by srivatsn** [comment]
@mavasani do you see this for c# projects as well? VB has some issues that requires a new compiler and some adjustment to the SDK but C# should work fine.

**Comment by mavasani** [comment]
Yes, I do for new C# and VB projects both.

**Comment by srivatsn** [comment]
Can you try the latest RC2 build? Some other folks mentioned that this is working fine in RC2 builds.

**Comment by mavasani** [comment]
Ok, will do.

**Comment by davkean** [comment]
Is it a timing thing? F5'ing before restore?

**Comment by mavasani** [comment]
No the assembly was built as .dll instead of .exe

**Comment by davkean** [comment]
Could this be the result of the output type broken thing?

**Comment by srivatsn** [comment]
The last time I saw this issue it was a race - the component that launches the debugger computes the executable to launch and in a pre-restore state the TFI is .NETFramework so it think it needs to run foo.exe. However post-restore the TFI changes to .NETCoreApp and the build produces foo.dll which is correct. Now with SDKs since we don't have a pre-restore state at all there's no chance for the debugger to think that the TFI is .NETFramework and compute the executablepath as foo.exe. Hence my belief that this will not repro in recent builds.

**Comment by jinujoseph** [comment]
Seems to work fine in the latest build
![image](https://cloud.githubusercontent.com/assets/12449387/20981429/99147010-bc69-11e6-9e09-e582f4eea1e8.png)

**Comment by srivatsn** [comment]
Closing since this seems to work and shouldn't have races in the SDK world. Please reopen if you still see this on latest builds.

**Comment by davkean** [comment]
Two people have reported this - I don't think this is a fluke. I suspect it's a broken configuration as I'm seeing active configs changes during startup,

**Comment by davkean** [comment]
Sorry, wrong bug, but I still think it's related to this: https://github.com/dotnet/roslyn-project-system/issues/921
