### ISSUE TITLE
Changes to Pre/Post Build events are not saved

### ISSUE THREAD

**Issue by RaulPerez1** [dotnet/roslyn-project-system#857]
ValueChanged isn't firing on the function below so it falls on the "user cancelled" code path. Most likely an issue with Descriptor.SetValue for these two properties.

Microsoft.VisualStudio.AppDesigner\PropPages\PropertyControlData.vb

Public Sub SetValue(Descriptor As PropertyDescriptor, Component As Object, Value As Object)
                'Hook up to detect if ValueChanged is fired
                Descriptor.AddValueChanged(Component, AddressOf ValueChanged)

                _valueChangedWasFired = False
                Try
                    'Go ahead and do the SetValue.  It will throw if there's an exception
                    '  (other than cancel/checkout exceptions).
                    Descriptor.SetValue(Component, Value)

                    'If we made it here, either the value was successfully changed, or
                    '  the set was canceled by the user in a checkout dialog, etc.
                    If _valueChangedWasFired Then
                        'The set was successful
                        Return
                    Else
                        'Must have been canceled by the user.  There will already have been
                        '  a UI indication of the cancelation.  But we need to throw so that the
                        '  current transaction gets cancelled (otherwise the property page may
                        '  show a changed value, and the user may get prompted for additional
                        '  checkouts as we try to process more property changes).
                        Common.Switches.TracePDProperties(TraceLevel.Warning, "*** SetValue() did not return failure, but also did not fire OnValueChanged.  Assuming a checkout or other cancel occurred.")
                        Throw CheckoutException.Canceled
                    End If

                Finally
                    Descriptor.RemoveValueChanged(Component, AddressOf ValueChanged)
                    _valueChangedWasFired = False
                End Try
            End Sub

**Comment by davkean** [comment]
Yeah as you suspected this is a dup of https://github.com/dotnet/roslyn-project-system/issues/841
