### ISSUE TITLE
Broken assembly references don't show as broken in the solution explorer

### ISSUE THREAD

**Issue by davidfowl** [dotnet/roslyn-project-system#865]
It should show up in the usual broken reference way.

![image](https://cloud.githubusercontent.com/assets/95136/20861325/ebf4dcf0-b941-11e6-86df-d8782558f8e5.png)

**Comment by abpiskunov** [comment]
This is a bug in dependency nodes - DT build sends us updates unresolved reference in this case, which we don't process correctly in  DependenciesSubTreeProviderBase.ProcessDependenciesChanges. I would need to fix that after i am back.
