### ISSUE TITLE
Add file as link does not work in VS2017 RC.2

### ISSUE THREAD

**Issue by mjcheetham** [dotnet/roslyn-project-system#867]
#### Build info
d15prerel/15.0.26002.0
#### Repro steps
1. File > New > Project... > Visual C# > Class Library (.NET Standard)
1. Add a simple text file on the file system either
a. outside of the previously created project tree directory (e.g., ../file1.txt, ../../dir/file2.txt),
b. underneath the previously created project tree directory (e.g., ./file3.txt)
1. Right-click ClassLibrary1 in the Solution Explorer > Add > Existing Item...
![image](https://cloud.githubusercontent.com/assets/5658207/20886683/278d6936-baef-11e6-9f21-d4c4f8a53d3d.png)
1. Select the file (any) created in the step 2
![image](https://cloud.githubusercontent.com/assets/5658207/20886699/3144aaca-baef-11e6-9121-10afb8712077.png)
1. Add as Link

##### Expected
File is added as a link.

##### Actual
Error message is displayed and link is not added.

![image](https://cloud.githubusercontent.com/assets/5658207/20886729/51a2d152-baef-11e6-9c8a-9e96167dc6bc.png)

**Comment by srivatsn** [comment]
Just tried this on d15rel/15.0.26002.2 and this works fine for me. @RaulPerez1 since you have a prerel build installed, can you see if this repros for you?

**Comment by RaulPerez1** [comment]
Not reproing on prerel 26013.2

**Comment by davkean** [comment]
@mjcheetham Can you repro this? I would expect this error to occur if you attempted to add a file to a folder that had been deleted from disk, but never for a linked file.

**Comment by mjcheetham** [comment]
@davkean, I was definitely able to repro this on d15prerel/15.0.26002.0.
I have since tried a later build from d15prerel and this seems to be OK now.
