### ISSUE TITLE
P2P UWP App -> .Net Standard Class Library 

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn-project-system#902]
**Repro Steps**

- Create a new Windows Universal -> Blank App (Universal Windows) 
- Select the default 
![image](https://cloud.githubusercontent.com/assets/12449387/20991185/e9ce82b6-bc91-11e6-8927-1e71dc2c36e3.png)
- To the solution add new -> New Project -> .Net Core -> Class Library (.NET Standard) 
- Add reference from App - > Class Library 
- Build 

**Expected**
Successful Build with no warning 

**Actual**
![image](https://cloud.githubusercontent.com/assets/12449387/20991260/5940b588-bc92-11e6-8141-ee19744c5b73.png)

**Comment by davkean** [comment]
These warning don't appear without the reference?

**Comment by jinujoseph** [comment]
you are right , it should this warning for just UWP app alone.

Closing this.
