### ISSUE TITLE
No AutoComplete/Suggestion on PackageReference

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/roslyn-project-system#903]
**Repro Steps**

Create a console application 
right click Edit Project 
Type <Package 

**Expected** 
you should get AutoComplete 

**Actual**
![image](https://cloud.githubusercontent.com/assets/12449387/20992338/55543a02-bc98-11e6-8f04-c0f9cba07879.png)

**Comment by RaulPerez1** [comment]
This is on MsBuild. I'll ping them again to see why the schemas that VS ships are not getting pulled from the MsBuild insertions.

**Comment by RaulPerez1** [comment]
https://github.com/Microsoft/msbuild/issues/1488
