### ISSUE TITLE
Projects migrated previous to RC2 should be disallowed from loading

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn-project-system#904]
We should disallow projects that have been migrated previous to RC2 from loading. They can get into a bad state when you have projects migrated before and projects migrated after, they can conflict and get into a bad state. /cc @davkean @piotrpMSFT @livarcocc.

**Comment by srivatsn** [comment]
At this point, given the backlog of issues, I don't think this is worth the cost.
