### ISSUE TITLE
Guard against $(ManagedXamlResourcesDirectory) not ending with \

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/roslyn-project-system#906]
Currently there's an assumption that ManagedXamlResourcesDirectory always ends in a backslash.

However it is violated here:
https://github.com/dotnet/roslyn-project-system/blob/master/src/Targets/Microsoft.Managed.DesignTime.targets#L22

and in all places where ManagedXamlResourcesDirectory is used, e.g.:
https://github.com/dotnet/roslyn-project-system/blob/master/src/Targets/Microsoft.Managed.DesignTime.targets#L66

**Comment by davkean** [comment]
The number of times I've fixed those bloody back slashes...

**Comment by KirillOsenkov** [comment]
Correction: $(MSBuildThisFileDirectory) is guaranteed to end in a backslash, so that is correct. However if you specify a custom one (like I did), I don't know what's the best way to do it, either use $([System.IO.Path]::Combine($(Path1),$(Path2))) or mutate the property by appending a backslash if missing.
