### ISSUE TITLE
Removing the xmlns from within VS and saving causes VS to re-add it 

### ISSUE THREAD

**Issue by onovotny** [dotnet/roslyn-project-system#919]
When editing a csproj that has the following in it (using the latest RC from today):

`<Project ToolsVersion="15.0" Sdk="Microsoft.NET.Sdk.Web" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">`

If I remove the xmlns, as soon as I hit save, it gets added back.

If I unload the project, hit edit, it doesn't appear. Then when I reload the project, it seems to stay gone.

**Comment by srivatsn** [comment]
Sounds like an artifact of how we get the xml to display in the editor?

**Comment by 333fred** [comment]
Fixed by https://github.com/dotnet/roslyn-project-system/pull/1238.
