### ISSUE TITLE
Build of ProjectSystem vsix is disabled 

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn-project-system#93]
_From @genlu on February 17, 2016 21:43_

The vsix project for ProjectSystem (in future branch) is removed from the solution, since the content of the vsix is not getting signed and causes build failure as a result. We need to figure out how to sign the binaries in it and enable the build.

Here's the PR that disabled it:
https://github.com/dotnet/roslyn-internal/pull/585

_Copied from original issue: dotnet/roslyn#8838_

**Comment by srivatsn** [comment]
Not relevant after moving the code out of the roslyn repo.
