### ISSUE TITLE
Commenting out csproj elements moves them to top on save

### ISSUE THREAD

**Issue by onovotny** [dotnet/roslyn-project-system#932]
When I have a CSproj open for editing, if I comment-out a property group, when I hit save, it moves the commented area to the top of the file, right under project. That's startling and wrong as it moves items from where I want. Further, if it can change the meaning if they're uncommented and not restored to the correct location (which someone may not know where it belongs).

**Comment by davkean** [comment]
Yeah, not by design.

**Comment by 333fred** [comment]
I opened https://github.com/Microsoft/msbuild/issues/1472. Leaving this open to track.

**Comment by anurse** [comment]
I'm seeing slightly different behavior. If I comment out items in the csproj, they disappear completely.

**Comment by davkean** [comment]
@333fred Does your later check-in work around @anurse's issue? Basically MSBuild doesn't represent comments or whitespace in their model, we're getting this fixed.

**Comment by 333fred** [comment]
I don't believe so. CPS will be consuming the new msbuild APIs soon though, so updating the ReloadableProject to use them is in my plate as soon as CPS does.

**Comment by 333fred** [comment]
This should be fixed by https://github.com/dotnet/roslyn-project-system/pull/1140. @onovotny, please open a new issue if you see it again after the next release.
