### ISSUE TITLE
Can projects that haven’t migrated to .NET Core yet use the simplified csproj?

### ISSUE THREAD

**Issue by eyalsk** [dotnet/roslyn-project-system#933]
Can projects that haven’t migrated to .NET Core yet use the simplified csproj? also, as far as I can see I still need to unload the project in order to edit it whereas it isn’t the case with .NET Core projects, any plans to bring _legacy_ projects more closer to the way .NET Core projects work?

**Comment by eyalsk** [comment]
This was answered by Matt Gertz at the .NET blog:

> Right now, the legacy projects and new .NET Core projects are distinct things. Although I can’t give a timetable, we’d certainly prefer for them to become the same thing in the future (that would be both better for you and better for us :-))

**Comment by srivatsn** [comment]
You can make a project with the SDK attribute and target the desktop framework and that will work and be "simplified". It will open with the new project system. However, we haven't implemented all the features that the old project system had and there are lots of compat gaps. So there's a bunch of work to be done before we can switch all projects to use the new project system but as Matt says we want to get there.

**Comment by eyalsk** [comment]
@srivatsn Thanks. :)

**Comment by eyalsk** [comment]
@srivatsn It's been a long time but are you guys track this internally or something?

**Comment by khellang** [comment]
What is the issue? I've been using SDK-based projects for all my full framework apps and libraries for over a year. Even for WPF apps (with SDK Extras).

**Comment by eyalsk** [comment]
Well, the issue is that it isn't the default yet.

**Comment by davkean** [comment]
We are still tracking this - that list that @srivatsn pointed to is correct. You'll also see WPF/WinForms designer bring up as part of .NET Core 3.0.

**Comment by eyalsk** [comment]
@srivatsn, @davkean Thank you.

**Comment by steji113** [comment]
@davkean @Pilchie just a further clarification on this, is it expected that an existing WPF app targeting .NET Framework can be updated to use the new SDK style .csproj format and still target .NET Framework and also be worked on using the designers in the upcoming VS 2019 16.0 release? Also, is this still targeted for Q2 2019 per this page: https://docs.microsoft.com/en-us/visualstudio/productinfo/vs-roadmap?

**Comment by davkean** [comment]
It will be in the 16.x timeframe, around the same time as .NET Core 3.0 (of which I do not have dates). It will not be supported in the 16.0 release: https://github.com/dotnet/project-system/blob/master/docs/feature-comparison.md.
