### ISSUE TITLE
OAProject isn't MarshalByRefObject

### ISSUE THREAD

**Issue by bricelam** [dotnet/roslyn-project-system#934]
When trying to use the Entity Framework 6 PMC commands (e.g. `Add-Migration`) on a ASP.NET Core project targeting .NET Framework, you get the following error.

> Type 'Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.Automation.OAProject' in assembly 'Microsoft.VisualStudio.ProjectSystem.VS.Implementation, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' is not marked as serializable.

Is there any way to make that a `MarshalByRefObject` like it is on the other project types?

cc @divega

**Comment by srivatsn** [comment]
@jviau thoughts?

**Comment by davkean** [comment]
The other project types aren't MarshalByRef - they're native components and hence span AppDomains. :)

But I suspect as we bring up desktop compat we're going to see more and more like this, such as this: https://github.com/dotnet/roslyn-project-system/issues/924

**Comment by bricelam** [comment]
@davkean I knew you were going to say that as I filed it. 😄 I should know not to over-simplify on a Managed Languages repo.

**Comment by davkean** [comment]
:)

**Comment by jviau** [comment]
We moved CPS IVsHierarchy to COM Aggregation, but not the DTE layer. Are we wanting to start implementation MarshalByRefObject on the CPS DTE layer? That means ensuring all the objects we return are MarshalByRef, and I am not sure how deep that rabbit hole goes.

COM Aggregation / wrapping in a COM layer for the DTE feels unnecessary right now as we have no request to aggregate with anything yet.

**Comment by davkean** [comment]
There's no current need to aggregate it, but we may need to implement the DTE layer as marshal by ref, if we want to be a drop in replacement for the existing project system.

I've seen two different consumers so far who use us in a separate AppDomain. ([TestDriven.NET](https://github.com/dotnet/roslyn-project-system/issues/924) and above.

**Comment by jviau** [comment]
Okay, we will work with the EF team to find out what we all need to marshal by ref.

**Comment by srivatsn** [comment]
@jviau can you close this if you're tracking this issue in your database?

**Comment by jviau** [comment]
@srivatsn I don't have permissions to close issues. But yes, we are tracking this in our database.

**Comment by weitzhandler** [comment]
Are we going to see any solution this any time soon?
What's the best practice of enabling migrations in the following situation without hassle?

- VS 15.2
- Solution consisting of (csproj): 
-- ASP.NET Web API
-- Xamarin.Forms PCL (+Droid, iOS, UWP)

When trying to enable migrations I get the [this](https://github.com/aspnet/EntityFramework6/issues/317#issue-242885263) error.
