### ISSUE TITLE
P2P ref from UWP picks the win8 version instead of uap10.0 ver of cross-compiled lib

### ISSUE THREAD

**Issue by onovotny** [dotnet/roslyn-project-system#937]
A UWP project isn't getting the correct output of a cross-compiled project. Instead it's getting the win8 version.

Check out 
https://github.com/onovotny/Zeroconf/tree/847ef218c7f94a1dc0b0dfa35a4c11d954c97f98

The ZeroconfTest.UWP project has a P2P ref to Zeroconf. Zeroconf has lots of targets. The product in the dll shows what TFM it was built for. When looking at what's in the UWP\bin\x86\Debug directory, I see the win8 version not the uap10.0 version and things break.

**Comment by nguerrera** [comment]
I believe this is because we're passing TargetFrameworkMoniker instead of NugetTargetMoniker in GetTargetFrameworkProperties. The fix would go in msbuild if so. 

@onovotny Can you try the following patch to https://github.com/Microsoft/msbuild/blob/xplat/src/XMakeTasks/Microsoft.Common.CurrentVersion.targets#L1511 in 
C:\Program Files (x86)\Microsoft Visual Studio\2017\[sku]\MSBuild\15.0\Bin or C:\Program Files [(x86)]\dotnet\sdk\1.0.0-[version] (depending if you're building with VS/desktop msbuild or dotnet.]


``` diff
 <Target Name="_GetProjectReferenceTargetFrameworkProperties"
          Outputs="%(_MSBuildProjectReferenceExistent.Identity)">

+  <PropertyGroup>
+    <_ReferringTargetFramework Condition='$(NugetTargetMoniker)' != ''>$(NugetTargetMoniker)</_ReferringTargetFramework>
+    <_ReferringTargetFramework Condition='$(NugetTargetMonker)' == ''>$(TargetFrameworkMoniker)</_ReferringTargetFramework>
+  </PropertyGroup>

    <!-- As a mitigation for https://github.com/Microsoft/msbuild/issues/1276
       .vcxproj is treated specially to avoid the cost of double-evaluating
       for easily-identifiable-as-not-cross-targeting C++ projects. -->
    <MSBuild
        Projects="%(_MSBuildProjectReferenceExistent.Identity)"
        Targets="GetTargetFrameworkProperties"
        BuildInParallel="$(BuildInParallel)"
-        Properties="%(_MSBuildProjectReferenceExistent.SetConfiguration); %(_MSBuildProjectReferenceExistent.SetPlatform); ReferringTargetFramework=$(TargetFrameworkMoniker)"
+        Properties="%(_MSBuildProjectReferenceExistent.SetConfiguration); %(_MSBuildProjectReferenceExistent.SetPlatform); ReferringTargetFramework=$(_ReferringTargetFramework)"
        ContinueOnError="!$(BuildingProject)"
        RemoveProperties="%(_MSBuildProjectReferenceExistent.GlobalPropertiesToRemove);TargetFramework"
        Condition="'%(_MSBuildProjectReferenceExistent.Extension)' != '.vcxproj'">

      <Output TaskParameter="TargetOutputs" PropertyName="_ProjectReferenceTargetFrameworkProperties" />
    </MSBuild>
```

If that works, then we should move this bug to the msbuild repo and that would be my starting point for a proposed fix.

**Comment by nguerrera** [comment]
And for a workaround that is less invasive while waiting for a new build,  you can override _GetProjectReferenceTargetFrameworkProperties somewhere else than editing Microsoft.Common.CurrentVersion.targets. ;)

**Comment by onovotny** [comment]
Just tested and it didn't change the result. The win8 ver is in the output directory of the UWP app. Keep in mind that the UWP project is a "regular" UWP project and does not use the SDK to build.

**Comment by nguerrera** [comment]
> Keep in mind that the UWP project is a "regular" UWP project and does not use the SDK to build

I understand that, this target is for the referring side which can be any project that uses common targets.

I'll go ahead and repro this myself. I still suspect it's something along the lines above.

**Comment by onovotny** [comment]
Gotcha, yeah you should be able to repro with the commit above (should be the head of branch currently)

**Comment by nguerrera** [comment]
My fix worked for me:

![image](https://cloud.githubusercontent.com/assets/75470/21163208/9338713c-c146-11e6-865f-7c563fa580c9.png)

**Comment by nguerrera** [comment]
I fixed some minor typos in the patch if you want to try again. Make sure to edit the same copy that is used by msbuild. Try kill msbuild.exe instances and closing VS too.

Look for the following in a diag log if the fix is correctly applied (sorry for the French, search for GetTargetFrameworkProperties and GetNearestTargetFramework):

Referring side passing UAP 10 instead of .NETCore 5:
```
Tâche "MSBuild" (IDTâche:8)
  Paramètre de tâche :Projects=..\Zeroconf\Zeroconf.csproj (IDTâche:8)
  Paramètre de tâche :Targets=GetTargetFrameworkProperties (IDTâche:8)
  Paramètre de tâche :BuildInParallel=True (IDTâche:8)
  Paramètre de tâche :Properties=ReferringTargetFramework=UAP,Version=v10.0.10240 (IDTâche:8)
  Paramètre de tâche :RemoveProperties=;TargetFramework (IDTâche:8)
```

Receiving side picking uap10.0 instead of win8:
```
Tâche "GetNearestTargetFramework" (IDTâche:9)
  Paramètre de tâche :ReferringTargetFramework=UAP,Version=v10.0.10240 (IDTâche:9)
  Paramètre de tâche :
      PossibleTargetFrameworks=
          netstandard1.0
          netstandard1.3
          net45
          uap10.0
          portable-win81+wpa81
          win8
          wpa81 (IDTâche:9)
  Paramètre de tâche :ProjectFilePath=D:\Src\Zeroconf\Zeroconf\Zeroconf.csproj (IDTâche:9)
  Propriété en sortie : NearestTargetFramework=uap10.0 (IDTâche:9)
```

**Comment by nguerrera** [comment]
Moved to Microsoft/msbuild#1474

**Comment by nguerrera** [comment]
Here's an easier workaround:

Add this to the bottom of Zeroconf/Zeroconf.csproj:

```
 <!-- Workaround for https://github.com/Microsoft/msbuild/issues/1474 -->
  <Target Name="AdjustReferringTargetFrameworkForUAP" BeforeTargets="GetTargetFrameworkProperties">
    <PropertyGroup Condition="'$(ReferringTargetFramework)' == '.NETCore,Version=v5.0'">
      <ReferringTargetFramework>UAP,Version=v10.0</ReferringTargetFramework>
    </PropertyGroup>
  </Target>
```

This will intercept when the x-targeting project is deciding which dll to give back to the referring project and swap out the input given to nuget for the selection from .NET Core 5 to UAP 10.

**Comment by onovotny** [comment]
Thanks, that workaround did the trick

**Comment by onovotny** [comment]
I'm seeing this now in a .NET 4.5 test project referencing a project that multi-targets to the following:
`netstandard1.2;netstandard1.3;net45;win81;wpa81;MonoAndroid70;Xamarin.iOS10`

It's using the `netstandard1.2` version (the first in the list?) instead of the `net45` ver.
