### ISSUE TITLE
Visual Studio hangs when project file is edited outside VS to be invalid

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/roslyn-project-system#941]
- Create a new .NET Core Console App
- Open up the project file in an external editor and add the following:

```xml
  <ItemGroup Condition="'$(DesignTimeBuild)' != 'true''">
    <Compile Remove="Platforms\**\*.cs" />
  </ItemGroup>
```

(Note that there is an extra single quote at the end of the Condition attribute.)

- Save

EXPECTED: Some sort of semi-graceful failure.  Perhaps the project should be unloaded and the error message could be shown in the Solution output (this is what happens when you try to open a project with this error).
ACTUAL: Visual studio hangs

**Comment by BillHiebert** [comment]
I confirmed this is fixed with PR https://github.com/dotnet/roslyn-project-system/pull/859. You now see the following message:
```
---------------------------
Microsoft Visual Studio
---------------------------
The project 'ConsoleApp2' has encountered an error.  You may need reload the project after fixing the problem.

Expected a closing quote after position 31 in condition "'$(DesignTimeBuild)' != 'true''".  C:\Users\billhie\documents\visual studio 2017\Projects\ConsoleApp2\ConsoleApp2\ConsoleApp2.csproj
---------------------------
OK   
---------------------------

```
