### ISSUE TITLE
Add PackageReference to the end of the Itemgroup instead of adding it to the top of the itemgroup

### ISSUE THREAD

**Issue by basoundr** [dotnet/roslyn-project-system#951]

**Comment by jviau** [comment]
@basoundr is the code that adds the item to msbuild in CPS or in your project system? If it is in CPS we have a helper that this should be using. It tries to find the best place for an item to be added at (groups with similar items and then goes alphabetically).

**Comment by basoundr** [comment]
This code is in CPS. Could you point me to the helper?

**Comment by abpiskunov** [comment]
we might want to check if ItemGroup packages were sorted before we add: if yes, we need to insert to corresponding place, if not - at the end. Thats what we did in *.xproj in Dev14

**Comment by jviau** [comment]
Looks like the item is being added with a simple msbuild `Project.AddItem()` call in the base class. We can override this to use our more explicit logic. 

@abpiskunov CPS doesn't do exactly that and I think it falls out of scope of this release. If it is unsorted CPS won't try to sort it, it will place it in front of the first item it finds that comes after it alphabetically. Is this acceptable for now?

**Comment by davkean** [comment]
@jviau I think that's fine for now - let's get a bug on it though. I'm a little worried by other bugs on your plate at the moment. :)

**Comment by abpiskunov** [comment]
yep, tracking it with other issue should be fine

**Comment by jviau** [comment]
I opened an internal bug for this and assigned it to myself. The fix should be easy, so no need to worry @davkean haha.

**Comment by basoundr** [comment]
@jviau fixed it [here](https://mseng.visualstudio.com/VSIDEProj/_git/VSIDEProj.CPS/pullrequest/170000?_a=overview)

Thank you @jviau
