### ISSUE TITLE
Red squiggles after migrate and successful build

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn-project-system#956]
With RC2. Repo is here: https://github.com/balaTest/ProjectKTestProjects, 
Migrate Dev14_K101/Tooling202/AspNetCoreWeb_IndAuth_WithAI_1, open HomeController.cs. Red squiggles in the editor, even though the project builds successfully.

![image](https://cloud.githubusercontent.com/assets/2371880/21208871/cfc2f688-c225-11e6-945d-6ae50d3dd080.png)

@davkean, seen this before?

**Comment by 333fred** [comment]
This is still repro'ing for me on d15prerel/26102.03. Looking at the solution explorer, it seems like the design-time build isn't getting the NuGet packages for some reason:
![image](https://cloud.githubusercontent.com/assets/2371880/21620090/87fcf4d4-d1a7-11e6-9b52-ab129fc5d130.png)

**Comment by srivatsn** [comment]
Can you take a look? Could it be related to #785?

**Comment by 333fred** [comment]
Alright, so this no longer repros on the latest build of master, and appears to have been fixed by https://github.com/dotnet/roslyn-project-system/pull/1073. Still looking into why that fixed the issue. My current working theory is that when the old project file is there, something caches that the project file was the xproj, and we attempt to get intellisense from building the xproj instead of the csproj. When the project is reloaded, there's no more cached xproj, and intellisense starts working again. With the change, though, there's no xproj left, and whatever cached copy was retaining the xproj info is updated.
