### ISSUE TITLE
Documentation provided in the "More information" link of the "One-Way Upgrade" dialog is inaccurate in the context of .NET Core and ASP.NET Core projects

### ISSUE THREAD

**Issue by balachir** [dotnet/roslyn-project-system#967]
When migrating a project from Dev14, we get this dialog

![image](https://cloud.githubusercontent.com/assets/8246794/21246184/ff42961e-c2db-11e6-9ff9-f31d14a99e5a.png)

**ACTUAL**

Documentation provided in the "[More information](https://docs.microsoft.com/en-us/visualstudio/porting/port-migrate-and-upgrade-visual-studio-projects)" link of the "One-Way Upgrade" dialog is inaccurate in the context of .NET Core and ASP.NET Core projects

It mentions that the behavior is same between VS 2015 and VS 2017. And also says, you can open the projects using VS 2013 and VS 2012

**Comment by davkean** [comment]
Hmm, doesn't this belong over on https://github.com/Microsoft/visualstudio-docs/issues?

**Comment by morrisjoe** [comment]
Let me ask the Gordon and team who the right contact is that we should be working with

**Comment by morrisjoe** [comment]
I discussed this issue with Fred. No code changes needed. Decision is to change the content in the landing page https://docs.microsoft.com/en-us/visualstudio/porting/port-migrate-and-upgrade-visual-studio-projects  to include a .NET Core migration section.

**Comment by davkean** [comment]
@morrisjoe Are you planning on submit a PR to change the doc?

**Comment by morrisjoe** [comment]
Update - Partially fixed. Now it lands in the new microsoft.docs. page - https://docs.microsoft.com/en-us/visualstudio/porting/port-migrate-and-upgrade-visual-studio-projects  , which is good. But more work is needed to add a .NET Core related para to it. Will fix in the coming days. until then let's keep it open.

**Comment by morrisjoe** [comment]
Discussed with doc team and they asked to close this one and move over the issue to docs. Moved to 
https://github.com/dotnet/docs/issues/1482
