### ISSUE TITLE
Investigate UI blocks on project load

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn-project-system#971]
It appears that there are some UI blocks on project load - much more than desktop and it runs design-time builds on the UI thread.

We should investigate - it's much more obvious under the debugger where it can block for 10 or 20 seconds at a time.

**Comment by mavasani** [comment]
Now tracked by VSO [366684](https://devdiv.visualstudio.com/DevDiv/_workitems?id=366684&fullScreen=false&_a=edit)
