### ISSUE TITLE
System.IO.File in .NET Standard library fails when run in unit test

### ISSUE THREAD

**Issue by gulbanana** [dotnet/roslyn-project-system#975]
Possibly this issue should be in a vstest repository but I can't find one.
Repro: https://github.com/gulbanana/repro-netstandard-systemio

When using System.IO in a .NET Standard 1.4 class library, unit tests referencing the library fail. The error is
`Message: System.IO.FileLoadException : Could not load file or assembly 'System.IO.FileSystem, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)`

**Comment by srivatsn** [comment]
@codito

**Comment by srivatsn** [comment]
@dotnet/vstest

**Comment by codito** [comment]
We're investigating this issue. As a workaround, please use `<PackageReference Include="NETStandard.Library" Version="1.6.0" />` instead of `1.6.1` in netstdlib.csproj.

**Comment by gulbanana** [comment]
The workaround works on my system (until I want to use a nuget package which references 1.6.1 :))

**Comment by davkean** [comment]
This issue was moved to Microsoft/vstest#363
