### ISSUE TITLE
No tests are discovered when multi-targetting

### ISSUE THREAD

**Issue by gulbanana** [dotnet/roslyn-project-system#976]
This is a project file created from the default template and then edited to add a second TFM.
```
<Project Sdk="Microsoft.NET.Sdk" ToolsVersion="15.0">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>netcoreapp1.0;net461</TargetFrameworks>
    <RuntimeIdentifier Condition="'$(TargetFramework)' == 'net461'">win7-x86</RuntimeIdentifier>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="**\*.cs" />
    <EmbeddedResource Include="**\*.resx" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Condition=" '$(TargetFramework)' == 'netcoreapp1.0' " Include="Microsoft.NETCore.App" Version="1.0.1" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.0.0-preview-20161123-03" />
    <PackageReference Include="xunit" Version="2.2.0-beta4-build3444" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.2.0-beta4-build1194" />
  </ItemGroup>
</Project>
```

No tests are discovered for either TFM, although each works separately (e.g. if the TargetFrameworks is changed to TargetFramework). Here is the build log with /v:diag, which includes a warning about irreconcilable dependencies and some issues finding test adapters: https://gist.github.com/gulbanana/add7c9bbc4eecfdd7c4bd5b4af7fea5f

**Comment by srivatsn** [comment]
@codito

**Comment by srivatsn** [comment]
@dotnet/vstest

**Comment by codito** [comment]
(sorry for delay in response)

@gulbanana can you try with conditional `<OutputType Condition='$(TargetFramework)' == 'netcoreapp1.0'>Exe</OutputType>` and remove the RID from csproj?

**Comment by gulbanana** [comment]
OK, I've tried that and it doesn't fully work. Here is a repro: https://github.com/gulbanana/repro-testdiscovery-multitarget

With this setup, `dotnet test` runs tests for both tfms. However, Visual Studio does not discover any tests at all. If you change the order of target frameworks to `netcoreapp1.0;net461` then Visual Studio is able to discover only the netcoreapp tests, but still not the net461 ones. Unfortunately keeping the existing full-framework tests working is my priority in the real code!

**Comment by codito** [comment]
@gulbanana thanks for reporting this. We're tracking this issue for an upcoming release.

**Comment by davkean** [comment]
This issue was moved to Microsoft/vstest#364
