### ISSUE TITLE
Hide AssemblyInformation button on ApplicationPage for dotnet core projects

### ISSUE THREAD

**Issue by mavasani** [dotnet/roslyn-project-system#977]
We have moved these properties to Package page as part of https://github.com/dotnet/roslyn-project-system/pull/950

**Comment by RaulPerez1** [comment]
@mavasani I have changes in flight to condition other stuff on .Net Core. I can add this check in there as well.

**Comment by mavasani** [comment]
Thanks Raul.

**Comment by mavasani** [comment]
@RaulPerez1 I have a fix for this, sending a PR soon.

**Comment by mavasani** [comment]
https://github.com/dotnet/roslyn-project-system/pull/1023
