### ISSUE TITLE
VS2017 RC2 error list shows netstandard library project compiles all files twice

### ISSUE THREAD

**Issue by AArnott** [dotnet/roslyn-project-system#986]
Using d15rel 26014.00.

```
git clone -b vs2017MT https://github.com/AArnott/Validation.git
cd Validation
git checkout 6045abdc
src\Validation.sln
```

The error list in VS2017 RC2 shows many errors around ambiguous calls because the language service is compiling each file twice. Yet when I build the project, the output window clearly shows that problem is not in the build itself. (A few errors are there, but they are unrelated).

Error	CS0121	The call is ambiguous between the following methods or properties: ...

![image](https://cloud.githubusercontent.com/assets/3548/21284282/51fb0a1c-c3cc-11e6-9dc0-d3971bd5712a.png)

**Comment by davkean** [comment]
I suspect we're passing the sources files twice.
