### ISSUE TITLE
Targeting net20 results in broken reference warnings

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn-project-system#987]
(I'm multitargeting `net20` and `netstandard1.3` but this happens also when just targeting `net20`.)

Under Dependencies > Assemblies I have `System`, `System.Core`, `System.Data`, `System.Drawing`, `System.Runtime.Serialization`, `System.Xml` and `System.Xml.Linq`. Of these I only actually need `System`, so ordinarily I'd delete the rest. However deleting is impossible since they are defined outside my .csproj.

Not being able to delete doesn't bother me too much, except that I get build warnings for `System.Core`, `System.Runtime.Serialization` and `System.Xml.Linq` due to targeting `net20`.

If you are going to require mandatory assembly references if one of the targets is .NET Framework, I'd expect you to detect which references make sense to add given the framework version. (Personally I'd be even more happy with no mandatory references and having to list them in the .csproj so I can delete all of them except `System`.)

**Comment by jnm2** [comment]
Correction: the build warnings always show up when compiling at the command line.

**Comment by davkean** [comment]
This issue was moved to dotnet/sdk#532
