### ISSUE TITLE
Single-targeting net20 results in MSB4086

### ISSUE THREAD

**Issue by jnm2** [dotnet/roslyn-project-system#989]
With `<TargetFramework>net20</TargetFramework>`, you get MSB4086:

> A numeric comparison was attempted on "$(_TargetFrameworkVersionWithoutV)" that evaluates to "" instead of a number, in condition " '$(_TargetFrameworkVersionWithoutV)' >= '4.5' ".
>
> _(C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.Sdk.BeforeCommon.targets, line 86)_

With `<TargetFrameworks>net20</TargetFrameworks>` all is well.

Build 15.0.26014.0

**Comment by davkean** [comment]
This issue was moved to dotnet/sdk#533
