### ISSUE TITLE
Unexpected message when starting project execution

### ISSUE THREAD

**Issue by Yves57** [dotnet/roslyn-project-system#995]
I cloned the ASP.NET Razor sources.
When I start the RazorPageGenerator project (to debug or just run, even with a Release compilation), I have the message "Object reference not set to an instance of an object". I just have to validate it to continue, but it is strange.
![image](https://cloud.githubusercontent.com/assets/11701094/21316645/04eab366-c602-11e6-932b-3fe4c64e7a28.png)

Please note that creating a new ".NET Core Console App" from scratch is OK.
I use the most recent Visual Studio 2017RC.

**Comment by davkean** [comment]
Can you attach the project that is causing the issue?

**Comment by Yves57** [comment]
Sorry, I have probably not clear: there is no secret project to use, I just play with the [ASP.NET Razor](https://github.com/aspnet/Razor) sources.
Additional information:
- I tried to create a ".NET Core Web Application" from scratch, and I have not the same problem.
- My computer is quite old, so there is maybe a kind of timeout problem?
- I have tried to restart Visual Studio, but the message is still there for this project.

**Comment by basoundr** [comment]
@Yves57 I tried to repro this issue but I am having some trouble getting the test solution ready.

I cloned the repo and ran build.cmd. It gave the following error(pasted just the erroring portion)

---------------------------------------------------------------------
info: Run target: test
info: Run target: package-prepare
info: Run target: nuget-verify
info: Exec
info:   program: dotnet
info:   commandline: ".build\nugetpackageverifier\1.0.2-rc2-15144\NuGetPackageVerifier.dll" "C:\repos\razor\Razor\artifacts\build" "C:\repos\razor\Razor\NuGetPackageVerifier.json"
info:   workingdir: C:\repos\razor\Razor
NORMAL: Read 2 package set(s) from C:\repos\razor\Razor\NuGetPackageVerifier.json
NORMAL: Found 5 packages in C:\repos\razor\Razor\artifacts\build
NORMAL: Found 3 unlisted packages. Every package in the repo should be listed in exactly one package set. Running default or all rules on unlisted packages.
ERROR: 2 error(s) and 0 warning(s) found with package Microsoft.AspNetCore.Razor (1.2.0-preview1-t003b7c531)
ERROR: ASSEMBLY_COPYRIGHT @ lib/net451/Microsoft.AspNetCore.Razor.dll: The managed assembly 'lib/net451/Microsoft.AspNetCore.Razor.dll' in this package is missing the 'AssemblyCopyright' attribute.
ERROR: NEUTRAL_RESOURCES_LANGUAGE @ lib/net451/Microsoft.AspNetCore.Razor.dll: The managed assembly 'lib/net451/Microsoft.AspNetCore.Razor.dll' in this package is missing the '[assembly: NeutralResourcesLanguage("en-us")]' attribute.

ERROR: 2 error(s) and 0 warning(s) found with package Microsoft.AspNetCore.Razor.Evolution (1.2.0-preview1-t003b7c531)
ERROR: ASSEMBLY_COPYRIGHT @ lib/net451/Microsoft.AspNetCore.Razor.Evolution.dll: The managed assembly 'lib/net451/Microsoft.AspNetCore.Razor.Evolution.dll' in this package is missing the 'AssemblyCopyright' attribute.
ERROR: NEUTRAL_RESOURCES_LANGUAGE @ lib/net451/Microsoft.AspNetCore.Razor.Evolution.dll: The managed assembly 'lib/net451/Microsoft.AspNetCore.Razor.Evolution.dll' in this package is missing the '[assembly: NeutralResourcesLanguage("en-us")]' attribute.

ERROR: 2 error(s) and 0 warning(s) found with package Microsoft.AspNetCore.Razor.Runtime (1.2.0-preview1-t003b7c531)
ERROR: ASSEMBLY_COPYRIGHT @ lib/net451/Microsoft.AspNetCore.Razor.Runtime.dll: The managed assembly 'lib/net451/Microsoft.AspNetCore.Razor.Runtime.dll' in this package is missing the 'AssemblyCopyright' attribute.
ERROR: NEUTRAL_RESOURCES_LANGUAGE @ lib/net451/Microsoft.AspNetCore.Razor.Runtime.dll: The managed assembly 'lib/net451/Microsoft.AspNetCore.Razor.Runtime.dll' in this package is missing the '[assembly: NeutralResourcesLanguage("en-us")]' attribute.

ERROR: SUMMARY: 6 error(s) and 0 warning(s) found
NORMAL: Total took 1618ms
fail: Exit code 2 from dotnet
fail: Stack trace:
   at View7f9e810b823d4557b8af508e1e6534a6.Dotnet(String command) in c:\Users\basoundr\AppData\Local\Temp\3c10ee7d9cec416d8f14593e0f3261c3-1.cs:line 1069
   at View7f9e810b823d4557b8af508e1e6534a6.<>c__DisplayClassf1.<RenderViewLevel0>b__b7() in c:\Users\basoundr\AppData\Local\Temp\3c10ee7d9cec416d8f14593e0f3261c3-1.cs:line 9985
   at Sake.Engine.Builder.BuilderBase`1.CallTarget(String name)
   at Sake.Engine.Builder.BuilderBase`1.StartingTarget(String name)
   at View7f9e810b823d4557b8af508e1e6534a6.StartingTarget(String name) in c:\Users\basoundr\AppData\Local\Temp\3c10ee7d9cec416d8f14593e0f3261c3-1.cs:line 3637
   at View7f9e810b823d4557b8af508e1e6534a6.<RenderViewLevel0>b__6e() in c:\Users\basoundr\AppData\Local\Temp\3c10ee7d9cec416d8f14593e0f3261c3-1.cs:line 4267
   at Sake.Engine.Builder.BuilderBase`1.CallTarget(String name)
   at View7f9e810b823d4557b8af508e1e6534a6.<RenderViewLevel0>b__64() in c:\Users\basoundr\AppData\Local\Temp\3c10ee7d9cec416d8f14593e0f3261c3-1.cs:line 4090
   at Sake.Engine.Builder.BuilderBase`1.CallTarget(String name)
   at Sake.Engine.SakeEngine.Execute(Options options)
   at Sake.Engine.SakeEngine.Execute(String[] args)
   at Sake.Program.Main(String[] args)
--------------------------------------------------------------------------------

Is this supposed to happen? How do I fix it?

With the broken state, I don't see the error dialog that you have described in the issue

**Comment by Yves57** [comment]
@basoundr 
I use directly Visual Studio to compile the sources, not "build.cmd". And I had some problems to build it (see aspnet/KoreBuild#152), but clearly not this kind of problem. And I finally succeeded to build the sources.
The error dialog is displayed after, only when debugging the "RazorPageGenerator" application.

**Comment by basoundr** [comment]
@Yves57 I am currently working on a newer build of Visual Studio and I don't see the Null Reference Exception. Could you please verify this repro-es? Also, from the screenshot, is the Exception thrown at the line `if (args == null || args.Length != 1)`?

**Comment by Yves57** [comment]
I'm not a Microsoft developer, so I can't test "new builds". And the problem is visible in debug mode or not. It is not about the breakpoint or the line under the breakpoint.

**Comment by 333fred** [comment]
@Yves57, I'm not able to repro this on the latest builds, so I'm going to close this as no repro. If you do see this issue again on the next public builds, please feel free to reopen.
